# Generated by Django 5.0.2 on 2025-04-12 07:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_company", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Başlık")),
                ("description", models.TextField(verbose_name="Açıklama")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FINANS", "Finans"),
                            ("MUHASEBE", "Muhasebe"),
                            ("EKONOMI", "Ekonomi"),
                            ("YATIRIM", "Yatırım"),
                            ("TEKNOLOJI", "Teknoloji"),
                            ("DIGER", "Diğer"),
                        ],
                        max_length=20,
                        verbose_name="Kategori",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[("KOLAY", "Kolay"), ("ORTA", "Orta"), ("ZOR", "Zor")],
                        max_length=10,
                        verbose_name="Zorluk",
                    ),
                ),
                ("xp_reward", models.PositiveIntegerField(verbose_name="XP Ödülü")),
                (
                    "money_reward",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Para Ödülü",
                    ),
                ),
                (
                    "knowledge_reward",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Bilgi Ödülü"
                    ),
                ),
                ("steps", models.JSONField(default=list, verbose_name="Adımlar")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Günlük Görev",
                "verbose_name_plural": "Günlük Görevler",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Ürün Adı")),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Ürün Kodu"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Birim Fiyat"
                    ),
                ),
                (
                    "stock_quantity",
                    models.IntegerField(default=0, verbose_name="Stok Miktarı"),
                ),
                (
                    "min_stock_level",
                    models.IntegerField(
                        default=10, verbose_name="Minimum Stok Seviyesi"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ürün",
                "verbose_name_plural": "Ürünler",
            },
        ),
        migrations.AlterModelOptions(
            name="virtualcompany",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Sanal Şirket",
                "verbose_name_plural": "Sanal Şirketler",
            },
        ),
        migrations.RemoveField(
            model_name="virtualcompany",
            name="capital",
        ),
        migrations.RemoveField(
            model_name="virtualcompany",
            name="company_name",
        ),
        migrations.RemoveField(
            model_name="virtualcompany",
            name="user",
        ),
        migrations.AddField(
            model_name="virtualcompany",
            name="address",
            field=models.TextField(default="Varsayılan Adres", verbose_name="Adres"),
        ),
        migrations.AddField(
            model_name="virtualcompany",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_companies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="virtualcompany",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Açıklama"),
        ),
        migrations.AddField(
            model_name="virtualcompany",
            name="email",
            field=models.EmailField(
                default="info@finasis.com", max_length=254, verbose_name="E-posta"
            ),
        ),
        migrations.AddField(
            model_name="virtualcompany",
            name="founded_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Kuruluş Tarihi"
            ),
        ),
        migrations.AddField(
            model_name="virtualcompany",
            name="industry",
            field=models.CharField(
                default="Teknoloji", max_length=100, verbose_name="Sektör"
            ),
        ),
        migrations.AddField(
            model_name="virtualcompany",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Aktif"),
        ),
        migrations.AddField(
            model_name="virtualcompany",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="virtual_companies/logos/",
                verbose_name="Logo",
            ),
        ),
        migrations.AddField(
            model_name="virtualcompany",
            name="name",
            field=models.CharField(
                default="Yeni Şirket", max_length=255, verbose_name="Şirket Adı"
            ),
        ),
        migrations.AddField(
            model_name="virtualcompany",
            name="phone",
            field=models.CharField(
                default="5555555555", max_length=20, verbose_name="Telefon"
            ),
        ),
        migrations.AddField(
            model_name="virtualcompany",
            name="tax_number",
            field=models.CharField(
                default="1234567890", max_length=20, verbose_name="Vergi Numarası"
            ),
        ),
        migrations.AddField(
            model_name="virtualcompany",
            name="tax_office",
            field=models.CharField(
                default="Merkez", max_length=100, verbose_name="Vergi Dairesi"
            ),
        ),
        migrations.AddField(
            model_name="virtualcompany",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Güncellenme Tarihi"
            ),
        ),
        migrations.AddField(
            model_name="virtualcompany",
            name="website",
            field=models.URLField(blank=True, default="", verbose_name="Website"),
        ),
        migrations.AlterField(
            model_name="virtualcompany",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Oluşturulma Tarihi"
            ),
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Departman Adı"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "budget",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="Bütçe"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="virtual_departments",
                        to="virtual_company.virtualcompany",
                        verbose_name="Şirket",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="virtual_managed_departments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yönetici",
                    ),
                ),
            ],
            options={
                "verbose_name": "Departman",
                "verbose_name_plural": "Departmanlar",
                "ordering": ["company", "name"],
            },
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("income", "Gelir"), ("expense", "Gider")],
                        max_length=20,
                        verbose_name="Tür",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Miktar"
                    ),
                ),
                ("description", models.TextField(verbose_name="Açıklama")),
                ("date", models.DateField(verbose_name="Tarih")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to="virtual_company.virtualcompany",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_budgets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to="virtual_company.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bütçe",
                "verbose_name_plural": "Bütçeler",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("manager", "Yönetici"),
                            ("employee", "Çalışan"),
                            ("intern", "Stajyer"),
                        ],
                        max_length=20,
                        verbose_name="Rol",
                    ),
                ),
                ("position", models.CharField(max_length=100, verbose_name="Pozisyon")),
                (
                    "salary",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Maaş"
                    ),
                ),
                ("hire_date", models.DateField(verbose_name="İşe Başlama Tarihi")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="virtual_company.virtualcompany",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="virtual_company.department",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Çalışan",
                "verbose_name_plural": "Çalışanlar",
                "ordering": ["user__username"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Başlık")),
                ("content", models.TextField(verbose_name="İçerik")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("finance", "Finans"),
                            ("accounting", "Muhasebe"),
                            ("management", "Yönetim"),
                            ("operations", "Operasyonlar"),
                            ("hr", "İnsan Kaynakları"),
                            ("other", "Diğer"),
                        ],
                        max_length=20,
                        verbose_name="Kategori",
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Etiketler"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="virtual_companies/knowledge_base/",
                        verbose_name="Dosya",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_knowledge",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bilgi Bankası",
                "verbose_name_plural": "Bilgi Bankası",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeBaseRelatedItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Başlık")),
                ("url", models.URLField(blank=True, verbose_name="URL")),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "knowledge_base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_items",
                        to="virtual_company.knowledgebase",
                    ),
                ),
            ],
            options={
                "verbose_name": "İlişkili Öğe",
                "verbose_name_plural": "İlişkili Öğeler",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="ProductionOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Üretim Emri No"
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="Üretim Miktarı")),
                (
                    "planned_start_date",
                    models.DateField(verbose_name="Planlanan Başlangıç"),
                ),
                ("planned_end_date", models.DateField(verbose_name="Planlanan Bitiş")),
                (
                    "actual_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Gerçek Başlangıç"
                    ),
                ),
                (
                    "actual_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Gerçek Bitiş"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planlandı"),
                            ("in_progress", "Üretimde"),
                            ("completed", "Tamamlandı"),
                            ("cancelled", "İptal Edildi"),
                        ],
                        default="planned",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notlar")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="production_orders",
                        to="virtual_company.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Üretim Emri",
                "verbose_name_plural": "Üretim Emirleri",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Proje Adı")),
                ("description", models.TextField(verbose_name="Açıklama")),
                ("start_date", models.DateField(verbose_name="Başlangıç Tarihi")),
                ("end_date", models.DateField(verbose_name="Bitiş Tarihi")),
                (
                    "budget",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Bütçe"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planlandı"),
                            ("in_progress", "Devam Ediyor"),
                            ("completed", "Tamamlandı"),
                            ("cancelled", "İptal Edildi"),
                        ],
                        default="planned",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "progress",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="İlerleme",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="virtual_company.virtualcompany",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="virtual_company.department",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_projects",
                        to="virtual_company.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proje",
                "verbose_name_plural": "Projeler",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QualityControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inspection_date",
                    models.DateTimeField(verbose_name="Kontrol Tarihi"),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("passed", "Geçti"),
                            ("failed", "Başarısız"),
                            ("conditional", "Şartlı Kabul"),
                        ],
                        max_length=20,
                        verbose_name="Sonuç",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notlar")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "inspector",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "production_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_controls",
                        to="virtual_company.productionorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kalite Kontrol",
                "verbose_name_plural": "Kalite Kontroller",
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Başlık")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("financial", "Finansal"),
                            ("operational", "Operasyonel"),
                            ("project", "Proje"),
                            ("performance", "Performans"),
                        ],
                        max_length=20,
                        verbose_name="Tür",
                    ),
                ),
                ("content", models.TextField(verbose_name="İçerik")),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="virtual_companies/reports/",
                        verbose_name="Dosya",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="virtual_company.virtualcompany",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Rapor",
                "verbose_name_plural": "Raporlar",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("in", "Giriş"),
                            ("out", "Çıkış"),
                            ("transfer", "Transfer"),
                            ("adjustment", "Düzeltme"),
                        ],
                        max_length=20,
                        verbose_name="Hareket Tipi",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="Miktar")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Birim Fiyat"
                    ),
                ),
                (
                    "reference",
                    models.CharField(max_length=100, verbose_name="Referans"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notlar")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to="virtual_company.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stok Hareketi",
                "verbose_name_plural": "Stok Hareketleri",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Başlık")),
                ("description", models.TextField(verbose_name="Açıklama")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Düşük"),
                            ("medium", "Orta"),
                            ("high", "Yüksek"),
                            ("urgent", "Acil"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Öncelik",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "Yapılacak"),
                            ("in_progress", "Devam Ediyor"),
                            ("review", "İncelemede"),
                            ("completed", "Tamamlandı"),
                        ],
                        default="todo",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Başlangıç Tarihi")),
                ("due_date", models.DateField(verbose_name="Bitiş Tarihi")),
                (
                    "completed_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Tamamlanma Tarihi"
                    ),
                ),
                (
                    "progress",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="İlerleme",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tasks",
                        to="virtual_company.employee",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="virtual_company.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Görev",
                "verbose_name_plural": "Görevler",
                "ordering": ["priority", "due_date"],
            },
        ),
        migrations.CreateModel(
            name="ModuleSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module", models.CharField(max_length=100, verbose_name="Modül")),
                ("key", models.CharField(max_length=100, verbose_name="Anahtar")),
                ("value", models.TextField(verbose_name="Değer")),
                (
                    "is_global",
                    models.BooleanField(
                        default=False,
                        help_text="Global ayarlar tüm şirketler için geçerlidir.",
                        verbose_name="Global",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_settings",
                        to="virtual_company.virtualcompany",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modül Ayarı",
                "verbose_name_plural": "Modül Ayarları",
                "ordering": ["module", "key"],
                "unique_together": {("module", "company", "key")},
            },
        ),
        migrations.CreateModel(
            name="BillOfMaterials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="Miktar"
                    ),
                ),
                ("unit", models.CharField(max_length=20, verbose_name="Birim")),
                ("notes", models.TextField(blank=True, verbose_name="Notlar")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bom_components",
                        to="virtual_company.product",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bom_masters",
                        to="virtual_company.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ürün Ağacı",
                "verbose_name_plural": "Ürün Ağaçları",
                "unique_together": {("product", "component")},
            },
        ),
        migrations.CreateModel(
            name="UserDailyTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("BASLAMADI", "Başlamadı"),
                            ("DEVAM_EDIYOR", "Devam Ediyor"),
                            ("TAMAMLANDI", "Tamamlandı"),
                        ],
                        default="BASLAMADI",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "completed_steps",
                    models.JSONField(default=list, verbose_name="Tamamlanan Adımlar"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notlar"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Başlama Tarihi"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tamamlanma Tarihi"
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="virtual_user_tasks",
                        to="virtual_company.dailytask",
                        verbose_name="Görev",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="virtual_daily_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kullanıcı Günlük Görevi",
                "verbose_name_plural": "Kullanıcı Günlük Görevleri",
                "unique_together": {("user", "task")},
            },
        ),
    ]
