# Generated by Django 5.0.2 on 2025-04-09 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0002_bank_cashbox_chartofaccounts_stock_stocktransaction'),
        ('virtual_company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='crm.Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('company_name', models.CharField(max_length=100, verbose_name='Firma Adı')),
                ('tax_office', models.CharField(max_length=100, verbose_name='Vergi Dairesi')),
                ('tax_number', models.CharField(max_length=20, verbose_name='Vergi Numarası')),
                ('address', models.TextField(blank=True, verbose_name='Adres')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-posta')),
                ('website', models.URLField(blank=True, verbose_name='Web Sitesi')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounting.account', verbose_name='Cari Hesap')),
                ('virtual_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='virtual_company.virtualcompany')),
            ],
            options={
                'verbose_name': 'Müşteri',
                'verbose_name_plural': 'Müşteriler',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=50, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=50, verbose_name='Soyad')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Pozisyon')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Departman')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='Cep Telefonu')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-posta')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Birincil İletişim')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('virtual_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='virtual_company.virtualcompany')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.customer', verbose_name='Müşteri')),
            ],
            options={
                'verbose_name': 'İletişim Kişisi',
                'verbose_name_plural': 'İletişim Kişileri',
                'ordering': ['customer', 'last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200, verbose_name='Fırsat Adı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('status', models.CharField(choices=[('new', 'Yeni'), ('contacted', 'İletişime Geçildi'), ('qualified', 'Nitelikli'), ('proposal', 'Teklif'), ('negotiation', 'Pazarlık'), ('closed_won', 'Kazanıldı'), ('closed_lost', 'Kaybedildi')], default='new', max_length=20, verbose_name='Durum')),
                ('priority', models.CharField(choices=[('low', 'Düşük'), ('medium', 'Orta'), ('high', 'Yüksek'), ('urgent', 'Acil')], default='medium', max_length=20, verbose_name='Öncelik')),
                ('expected_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Beklenen Tutar')),
                ('probability', models.IntegerField(default=0, verbose_name='Olasılık (%)')),
                ('expected_close_date', models.DateField(blank=True, null=True, verbose_name='Beklenen Kapanış Tarihi')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_opportunities', to=settings.AUTH_USER_MODEL, verbose_name='Atanan Kişi')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='crm.customer', verbose_name='Müşteri')),
                ('virtual_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='virtual_company.virtualcompany')),
            ],
            options={
                'verbose_name': 'Satış Fırsatı',
                'verbose_name_plural': 'Satış Fırsatları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('file', models.FileField(upload_to='crm/documents/%Y/%m/', verbose_name='Dosya')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='crm.customer', verbose_name='Müşteri')),
                ('virtual_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='virtual_company.virtualcompany')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='crm.opportunity', verbose_name='Satış Fırsatı')),
            ],
            options={
                'verbose_name': 'Belge',
                'verbose_name_plural': 'Belgeler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('activity_type', models.CharField(choices=[('call', 'Telefon Görüşmesi'), ('meeting', 'Toplantı'), ('email', 'E-posta'), ('task', 'Görev'), ('note', 'Not')], max_length=20, verbose_name='Aktivite Tipi')),
                ('subject', models.CharField(max_length=200, verbose_name='Konu')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('completed', models.BooleanField(default=False, verbose_name='Tamamlandı')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma Tarihi')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_activities', to=settings.AUTH_USER_MODEL, verbose_name='Atanan Kişi')),
                ('virtual_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='virtual_company.virtualcompany')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.customer', verbose_name='Müşteri')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.opportunity', verbose_name='Satış Fırsatı')),
            ],
            options={
                'verbose_name': 'Aktivite',
                'verbose_name_plural': 'Aktiviteler',
                'ordering': ['-created_at'],
            },
        ),
    ]
