# Generated by Django 4.2.23 on 2025-08-30 17:17

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("finance", "0004_integratedbankaccount"),
        ("accounting", "0006_invoice_e_archive"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                ("code", models.CharField(max_length=10, verbose_name="Banka Kodu")),
                ("name", models.CharField(max_length=100, verbose_name="Banka Adı")),
                (
                    "swift_code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="SWIFT Kodu"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="banks/", verbose_name="Logo"
                    ),
                ),
            ],
            options={
                "verbose_name": "Banka",
                "verbose_name_plural": "Bankalar",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "account_number",
                    models.CharField(max_length=50, verbose_name="Hesap Numarası"),
                ),
                ("iban", models.CharField(max_length=50, verbose_name="IBAN")),
                (
                    "branch_code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Şube Kodu"
                    ),
                ),
                (
                    "branch_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Şube Adı"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="TRY", max_length=3, verbose_name="Para Birimi"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "accounting_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bank_accounts",
                        to="finance.account",
                        verbose_name="Muhasebe Hesabı",
                    ),
                ),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accounts",
                        to="finance_banking.bank",
                        verbose_name="Banka",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="banking_bank_accounts",
                        to="accounting.company",
                        verbose_name="Şirket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Banka Hesabı",
                "verbose_name_plural": "Banka Hesapları",
                "ordering": ["company", "bank", "currency"],
                "unique_together": {("company", "iban")},
            },
        ),
        migrations.CreateModel(
            name="BankTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("transaction_date", models.DateField(verbose_name="İşlem Tarihi")),
                (
                    "reference_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Referans No"
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Açıklama"),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("deposit", "Yatırma"),
                            ("withdrawal", "Çekme"),
                            ("transfer", "Havale/EFT"),
                            ("payment", "Ödeme"),
                            ("interest", "Faiz"),
                            ("fee", "Komisyon/Masraf"),
                            ("other", "Diğer"),
                        ],
                        max_length=20,
                        verbose_name="İşlem Tipi",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Tutar",
                    ),
                ),
                (
                    "is_reconciled",
                    models.BooleanField(default=False, verbose_name="Mutabakatlı"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_transactions",
                        to="accounting.company",
                        verbose_name="Şirket",
                    ),
                ),
                (
                    "destination_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_transactions",
                        to="finance_banking.bankaccount",
                        verbose_name="Hedef Hesap",
                    ),
                ),
                (
                    "source_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outgoing_transactions",
                        to="finance_banking.bankaccount",
                        verbose_name="Kaynak Hesap",
                    ),
                ),
                (
                    "voucher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bank_transactions",
                        to="finance.voucher",
                        verbose_name="Muhasebe Fişi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Banka İşlemi",
                "verbose_name_plural": "Banka İşlemleri",
                "ordering": ["-transaction_date", "-created_at"],
            },
        ),
    ]
