# Generated by Django 5.2.6 on 2025-09-17 16:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance_banking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banktransaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Tutar",
            ),
        ),
        migrations.AlterField(
            model_name="banktransaction",
            name="destination_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="incoming_transactions_related",
                to="finance_banking.bankaccount",
                verbose_name="Hedef Hesap",
            ),
        ),
        migrations.AlterField(
            model_name="banktransaction",
            name="source_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="outgoing_transactions_related",
                to="finance_banking.bankaccount",
                verbose_name="Kaynak Hesap",
            ),
        ),
    ]
