# Generated by Django 5.2.1 on 2025-10-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0012_edefter_company_zip_updated_nullable_files"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="edefter",
            options={"ordering": ["-year", "-month"], "verbose_name": "e-Defter", "verbose_name_plural": "e-Defterler"},
        ),
        migrations.AlterField(
            model_name="edefter",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma Tarihi"),
        ),
        migrations.AlterField(
            model_name="edefter",
            name="month",
            field=models.PositiveIntegerField(verbose_name="Ay"),
        ),
        migrations.AlterField(
            model_name="edefter",
            name="status",
            field=models.CharField(default="taslak", max_length=20, verbose_name="Durum"),
        ),
        migrations.AlterField(
            model_name="edefter",
            name="type",
            field=models.CharField(
                choices=[("yevmiye", "Yevmiye"), ("kebir", "Kebir")], max_length=10, verbose_name="Defter Türü"
            ),
        ),
        migrations.AlterField(
            model_name="edefter",
            name="year",
            field=models.PositiveIntegerField(verbose_name="Yıl"),
        ),
        migrations.AlterUniqueTogether(
            name="edefter",
            unique_together={("company", "year", "month", "type")},
        ),
    ]
