# Generated by Django 5.1.8 on 2025-04-15 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnomalyDetection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "detection_type",
                    models.CharField(
                        choices=[
                            ("transaction", "İşlem Anomalisi"),
                            ("pattern", "Örüntü Anomalisi"),
                            ("trend", "Trend Anomalisi"),
                        ],
                        max_length=20,
                        verbose_name="Tespit Tipi",
                    ),
                ),
                ("source_data", models.JSONField(verbose_name="Kaynak Veri")),
                ("anomaly_score", models.FloatField(verbose_name="Anomali Skoru")),
                ("description", models.TextField(verbose_name="Açıklama")),
                (
                    "is_resolved",
                    models.BooleanField(default=False, verbose_name="Çözüldü mü?"),
                ),
                (
                    "resolution_notes",
                    models.TextField(blank=True, verbose_name="Çözüm Notları"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "detected_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ai_assistant.aimodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anomali Tespiti",
                "verbose_name_plural": "Anomali Tespitleri",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FinancialReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Rapor Başlığı"),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("balance_sheet", "Bilanço"),
                            ("income_statement", "Gelir Tablosu"),
                            ("cash_flow", "Nakit Akışı"),
                            ("budget", "Bütçe"),
                            ("custom", "Özel Rapor"),
                        ],
                        max_length=20,
                        verbose_name="Rapor Tipi",
                    ),
                ),
                ("content", models.JSONField(verbose_name="Rapor İçeriği")),
                (
                    "parameters",
                    models.JSONField(default=dict, verbose_name="Rapor Parametreleri"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ai_assistant.aimodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Finansal Rapor",
                "verbose_name_plural": "Finansal Raporlar",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrendAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[
                            ("revenue", "Gelir Trendi"),
                            ("expense", "Gider Trendi"),
                            ("profit", "Kâr Trendi"),
                            ("cash_flow", "Nakit Akış Trendi"),
                        ],
                        max_length=20,
                        verbose_name="Analiz Tipi",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Başlangıç Tarihi")),
                ("end_date", models.DateField(verbose_name="Bitiş Tarihi")),
                ("trend_data", models.JSONField(verbose_name="Trend Verisi")),
                ("prediction", models.JSONField(verbose_name="Tahmin Verisi")),
                ("confidence_score", models.FloatField(verbose_name="Güven Skoru")),
                ("insights", models.TextField(verbose_name="İçgörüler")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "analyzed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ai_assistant.aimodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trend Analizi",
                "verbose_name_plural": "Trend Analizleri",
                "ordering": ["-created_at"],
            },
        ),
    ]
