# Generated by Django 5.2.8 on 2025-12-16 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinQuestEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("economic", "Ekonomik"),
                            ("weather", "Hava Durumu"),
                            ("social", "Sosyal"),
                            ("quest", "Görev"),
                        ],
                        max_length=20,
                    ),
                ),
                ("effects", models.JSONField(default=dict)),
                ("duration_minutes", models.IntegerField(default=10)),
                ("trigger_conditions", models.JSONField(default=dict)),
                ("probability", models.FloatField(default=0.1, help_text="0.0 - 1.0")),
            ],
            options={
                "verbose_name": "Olay",
                "verbose_name_plural": "Olaylar",
            },
        ),
        migrations.CreateModel(
            name="FinQuestItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("equipment", "Ekipman"),
                            ("consumable", "Sarf Malzeme"),
                            ("quest", "Görev Eşyası"),
                            ("cosmetic", "Kozmetik"),
                        ],
                        max_length=20,
                    ),
                ),
                ("buy_price", models.IntegerField(default=100)),
                ("sell_price", models.IntegerField(default=50)),
                ("health_bonus", models.IntegerField(default=0)),
                ("energy_bonus", models.IntegerField(default=0)),
                ("skill_bonuses", models.JSONField(default=dict)),
                ("model_path", models.CharField(blank=True, max_length=200)),
                ("icon", models.CharField(default="📦", max_length=50)),
                ("is_tradeable", models.BooleanField(default=True)),
                ("is_stackable", models.BooleanField(default=True)),
                ("max_stack", models.IntegerField(default=99)),
            ],
            options={
                "verbose_name": "FinQuest Eşya",
                "verbose_name_plural": "FinQuest Eşyalar",
            },
        ),
        migrations.CreateModel(
            name="FinQuestNPC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "npc_type",
                    models.CharField(
                        choices=[
                            ("merchant", "Tüccar"),
                            ("banker", "Bankacı"),
                            ("teacher", "Öğretmen"),
                            ("quest_giver", "Görev Veren"),
                            ("rival", "Rakip"),
                        ],
                        max_length=20,
                    ),
                ),
                ("city", models.CharField(max_length=50)),
                (
                    "ai_intelligence",
                    models.FloatField(default=0.5, help_text="0.0 - 1.0"),
                ),
                ("personality", models.CharField(default="neutral", max_length=50)),
                ("model_path", models.CharField(blank=True, max_length=200)),
                ("dialogue", models.JSONField(default=list)),
                ("inventory", models.JSONField(default=dict)),
                ("price_multiplier", models.FloatField(default=1.0)),
            ],
            options={
                "verbose_name": "NPC",
                "verbose_name_plural": "NPC'ler",
            },
        ),
        migrations.CreateModel(
            name="FinQuestQuest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quest_type",
                    models.CharField(
                        choices=[
                            ("tutorial", "Öğretici"),
                            ("main", "Ana Hikaye"),
                            ("side", "Yan Görev"),
                            ("daily", "Günlük"),
                            ("challenge", "Meydan Okuma"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("required_level", models.IntegerField(default=1)),
                ("required_city", models.CharField(blank=True, max_length=50)),
                ("prerequisites", models.JSONField(default=list)),
                ("objectives", models.JSONField(default=list)),
                ("reward_xp", models.IntegerField(default=100)),
                ("reward_money", models.IntegerField(default=500)),
                ("reward_items", models.JSONField(default=list)),
                ("difficulty_level", models.IntegerField(default=1)),
                (
                    "time_limit_minutes",
                    models.IntegerField(default=0, help_text="0 = sınırsız"),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "FinQuest Görev",
                "verbose_name_plural": "FinQuest Görevler",
                "ordering": ["quest_type", "required_level"],
            },
        ),
        migrations.CreateModel(
            name="FinQuestWorld",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("map_data", models.JSONField(default=dict)),
                ("biomes", models.JSONField(default=list)),
                ("economic_level", models.IntegerField(default=1, help_text="1-10")),
                ("tax_rate", models.FloatField(default=0.1)),
                ("market_prices", models.JSONField(default=dict)),
                ("weather", models.CharField(default="sunny", max_length=20)),
                ("time_of_day", models.CharField(default="day", max_length=20)),
                ("is_unlocked", models.BooleanField(default=True)),
                ("unlock_requirement", models.JSONField(default=dict)),
            ],
            options={
                "verbose_name": "Dünya/Şehir",
                "verbose_name_plural": "Dünyalar/Şehirler",
            },
        ),
        migrations.CreateModel(
            name="FinQuestCharacter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Maceraperest", max_length=100)),
                ("current_city", models.CharField(default="Mardin", max_length=50)),
                ("position_x", models.FloatField(default=0.0)),
                ("position_y", models.FloatField(default=1.0)),
                ("position_z", models.FloatField(default=0.0)),
                ("level", models.IntegerField(default=1)),
                ("xp", models.IntegerField(default=0)),
                ("health", models.IntegerField(default=100)),
                ("energy", models.IntegerField(default=100)),
                ("money", models.IntegerField(default=10000)),
                ("skill_trading", models.IntegerField(default=10)),
                ("skill_negotiation", models.IntegerField(default=10)),
                ("skill_accounting", models.IntegerField(default=10)),
                ("skill_investing", models.IntegerField(default=10)),
                ("skill_management", models.IntegerField(default=10)),
                ("quests_completed", models.IntegerField(default=0)),
                ("cities_explored", models.JSONField(default=list)),
                ("achievements_unlocked", models.JSONField(default=list)),
                (
                    "difficulty",
                    models.IntegerField(
                        choices=[
                            (1, "Acemi"),
                            (2, "Normal"),
                            (3, "Zor"),
                            (4, "Uzman"),
                            (5, "Efsane"),
                        ],
                        default=2,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_played", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="finquest_characters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "FinQuest Karakter",
                "verbose_name_plural": "FinQuest Karakterler",
                "ordering": ["-level", "-xp"],
            },
        ),
        migrations.CreateModel(
            name="FinQuestSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.IntegerField(default=0)),
                ("xp_earned", models.IntegerField(default=0)),
                ("money_earned", models.IntegerField(default=0)),
                ("quests_completed", models.IntegerField(default=0)),
                ("cities_visited", models.IntegerField(default=0)),
                ("session_data", models.JSONField(default=dict)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="finquest.finquestcharacter",
                    ),
                ),
            ],
            options={
                "verbose_name": "FinQuest Oyun Oturumu",
                "verbose_name_plural": "FinQuest Oyun Oturumları",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="FinQuestInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                ("is_equipped", models.BooleanField(default=False)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to="finquest.finquestcharacter",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finquest.finquestitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "FinQuest Envanteri",
                "verbose_name_plural": "FinQuest Envanterleri",
                "unique_together": {("character", "item")},
            },
        ),
        migrations.CreateModel(
            name="FinQuestPlayerQuest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("progress", models.JSONField(default=dict)),
                ("is_completed", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="active_quests",
                        to="finquest.finquestcharacter",
                    ),
                ),
                (
                    "quest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finquest.finquestquest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Karakter Görevi",
                "verbose_name_plural": "Karakter Görevleri",
                "unique_together": {("character", "quest")},
            },
        ),
    ]
