# Generated by Django 4.2.25 on 2025-10-30 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_plan_audience_enterpriseinquiry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="audience",
            field=models.CharField(
                choices=[("sme", "KOBİ"), ("edu", "Eğitim"), ("games", "Oyuncu")], default="sme", max_length=10
            ),
        ),
    ]
