# Generated by Django 4.2.25 on 2025-11-02 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("billing", "0004_alter_plan_audience"),
    ]

    operations = [
        migrations.CreateModel(
            name="Discount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=50, unique=True, verbose_name="İndirim Kodu")),
                ("name", models.CharField(max_length=200, verbose_name="İndirim Adı")),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("PERCENTAGE", "Yüzde"), ("FIXED", "Sabit Tutar"), ("FREE_TRIAL", "Ücretsiz Deneme")],
                        max_length=20,
                        verbose_name="İndirim Tipi",
                    ),
                ),
                ("discount_value", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="İndirim Değeri")),
                ("valid_from", models.DateTimeField(verbose_name="Geçerlilik Başlangıcı")),
                ("valid_until", models.DateTimeField(verbose_name="Geçerlilik Bitişi")),
                ("max_uses", models.IntegerField(blank=True, null=True, verbose_name="Maksimum Kullanım")),
                ("max_uses_per_user", models.IntegerField(default=1, verbose_name="Kullanıcı Başına Maks. Kullanım")),
                ("times_used", models.IntegerField(default=0, verbose_name="Kullanım Sayısı")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "applicable_plans",
                    models.ManyToManyField(
                        blank=True, related_name="discounts", to="billing.plan", verbose_name="Geçerli Planlar"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan",
                    ),
                ),
            ],
            options={
                "verbose_name": "İndirim Kuponu",
                "verbose_name_plural": "İndirim Kuponları",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentGateway",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Gateway Adı")),
                (
                    "gateway_type",
                    models.CharField(
                        choices=[
                            ("PAYTR", "PayTR"),
                            ("IYZICO", "Iyzico"),
                            ("STRIPE", "Stripe"),
                            ("PAYPAL", "PayPal"),
                            ("BANK", "Banka"),
                        ],
                        max_length=20,
                        verbose_name="Gateway Tipi",
                    ),
                ),
                ("api_key", models.CharField(max_length=200, verbose_name="API Key")),
                ("api_secret", models.CharField(max_length=200, verbose_name="API Secret")),
                ("merchant_id", models.CharField(blank=True, max_length=100, verbose_name="Merchant ID")),
                ("base_url", models.URLField(verbose_name="Base URL")),
                ("webhook_url", models.URLField(blank=True, verbose_name="Webhook URL")),
                ("is_test_mode", models.BooleanField(default=True, verbose_name="Test Modu")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("total_transactions", models.IntegerField(default=0, verbose_name="Toplam İşlem")),
                ("successful_transactions", models.IntegerField(default=0, verbose_name="Başarılı İşlem")),
                ("failed_transactions", models.IntegerField(default=0, verbose_name="Başarısız İşlem")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Ödeme Gateway",
                "verbose_name_plural": "Ödeme Gatewayleri",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PaymentAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("attempt_number", models.IntegerField(default=1, verbose_name="Deneme Numarası")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INITIATED", "Başlatıldı"),
                            ("PROCESSING", "İşleniyor"),
                            ("SUCCESS", "Başarılı"),
                            ("FAILED", "Başarısız"),
                            ("CANCELLED", "İptal Edildi"),
                        ],
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                ("request_data", models.JSONField(default=dict, verbose_name="İstek Verisi")),
                ("response_data", models.JSONField(default=dict, verbose_name="Yanıt Verisi")),
                ("response_code", models.CharField(blank=True, max_length=50, verbose_name="Yanıt Kodu")),
                ("error_message", models.TextField(blank=True, verbose_name="Hata Mesajı")),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True, verbose_name="IP Adresi")),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                ("attempted_at", models.DateTimeField(auto_now_add=True, verbose_name="Deneme Zamanı")),
                (
                    "gateway",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="billing.paymentgateway",
                        verbose_name="Gateway",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="billing.transaction",
                        verbose_name="İşlem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ödeme Denemesi",
                "verbose_name_plural": "Ödeme Denemeleri",
                "ordering": ["-attempted_at"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("invoice_number", models.CharField(max_length=50, unique=True, verbose_name="Fatura No")),
                ("invoice_date", models.DateField(verbose_name="Fatura Tarihi")),
                ("due_date", models.DateField(verbose_name="Vade Tarihi")),
                ("billing_period_start", models.DateField(verbose_name="Dönem Başlangıç")),
                ("billing_period_end", models.DateField(verbose_name="Dönem Bitiş")),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Ara Toplam")),
                ("tax_amount", models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Vergi")),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="İndirim"),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Toplam")),
                ("line_items", models.JSONField(default=list, verbose_name="Fatura Kalemleri")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Taslak"),
                            ("SENT", "Gönderildi"),
                            ("PAID", "Ödendi"),
                            ("OVERDUE", "Vadesi Geçti"),
                            ("CANCELLED", "İptal Edildi"),
                            ("REFUNDED", "İade Edildi"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True, verbose_name="Ödeme Tarihi")),
                ("payment_method", models.CharField(blank=True, max_length=50, verbose_name="Ödeme Yöntemi")),
                ("notes", models.TextField(blank=True, verbose_name="Notlar")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="billing.subscriptionprofile",
                        verbose_name="Abonelik",
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="billing.transaction",
                        verbose_name="İşlem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fatura",
                "verbose_name_plural": "Faturalar",
                "ordering": ["-invoice_date"],
            },
        ),
        migrations.CreateModel(
            name="DiscountUsage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "original_amount",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Orijinal Tutar"),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="İndirim Tutarı"),
                ),
                ("final_amount", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Final Tutar")),
                ("used_at", models.DateTimeField(auto_now_add=True, verbose_name="Kullanım Zamanı")),
                (
                    "discount",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usages",
                        to="billing.discount",
                        verbose_name="İndirim",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="billing.subscriptionprofile",
                        verbose_name="Abonelik",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "İndirim Kullanımı",
                "verbose_name_plural": "İndirim Kullanımları",
                "ordering": ["-used_at"],
            },
        ),
    ]
