# Generated by Django 5.2.8 on 2025-12-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_discount_paymentgateway_paymentattempt_invoice_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoice",
            options={
                "ordering": ["-invoice_date"],
                "verbose_name": "Abonelik Faturası",
                "verbose_name_plural": "Abonelik Faturaları",
            },
        ),
        migrations.AlterModelOptions(
            name="plan",
            options={
                "ordering": ["order", "name"],
                "verbose_name": "Plan",
                "verbose_name_plural": "Planlar",
            },
        ),
        migrations.AddField(
            model_name="plan",
            name="beta_discount_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Beta döneminde uygulanacak indirim yüzdesi",
                max_digits=5,
                verbose_name="Beta İndirimi (%)",
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="is_beta_plan",
            field=models.BooleanField(
                default=False,
                help_text="Bu plan beta dönemine özel mi?",
                verbose_name="Beta Planı",
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="is_popular",
            field=models.BooleanField(
                default=False,
                help_text="Popüler plan olarak işaretle",
                verbose_name="Popüler",
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="order",
            field=models.IntegerField(
                default=0, help_text="Görüntüleme sırası", verbose_name="Sıra"
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="trial_days",
            field=models.IntegerField(
                default=14,
                help_text="Ücretsiz deneme süresi (gün)",
                verbose_name="Deneme Süresi (Gün)",
            ),
        ),
    ]
