# Generated by Django 4.2.25 on 2025-11-02 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("management", "0003_helpcontent"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatabaseSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snapshot_date", models.DateField(verbose_name="Snapshot Tarihi")),
                (
                    "total_size_mb",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Toplam Boyut (MB)",
                    ),
                ),
                (
                    "data_size_mb",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Veri Boyutu (MB)"
                    ),
                ),
                (
                    "index_size_mb",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="İndeks Boyutu (MB)",
                    ),
                ),
                ("table_count", models.IntegerField(verbose_name="Tablo Sayısı")),
                ("total_rows", models.BigIntegerField(verbose_name="Toplam Satır")),
                (
                    "model_statistics",
                    models.JSONField(
                        default=dict,
                        help_text="{'User': 1500, 'Invoice': 35000, ...}",
                        verbose_name="Model İstatistikleri",
                    ),
                ),
                (
                    "avg_query_time_ms",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Ortalama Sorgu Süresi (ms)",
                    ),
                ),
                (
                    "slow_queries_count",
                    models.IntegerField(default=0, verbose_name="Yavaş Sorgu Sayısı"),
                ),
                (
                    "fragmentation_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Fragmentation (%)",
                    ),
                ),
                (
                    "optimization_needed",
                    models.BooleanField(
                        default=False, verbose_name="Optimizasyon Gerekli"
                    ),
                ),
                (
                    "recommendations",
                    models.TextField(blank=True, verbose_name="Öneriler"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Veritabanı Snapshot",
                "verbose_name_plural": "Veritabanı Snapshotları",
                "ordering": ["-snapshot_date"],
            },
        ),
        migrations.CreateModel(
            name="UsageStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_date", models.DateField(verbose_name="Dönem Tarihi")),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("DAILY", "Günlük"),
                            ("WEEKLY", "Haftalık"),
                            ("MONTHLY", "Aylık"),
                        ],
                        default="DAILY",
                        max_length=20,
                        verbose_name="Dönem Tipi",
                    ),
                ),
                (
                    "total_users",
                    models.IntegerField(default=0, verbose_name="Toplam Kullanıcı"),
                ),
                (
                    "active_users",
                    models.IntegerField(default=0, verbose_name="Aktif Kullanıcı"),
                ),
                (
                    "new_users",
                    models.IntegerField(default=0, verbose_name="Yeni Kullanıcı"),
                ),
                (
                    "total_sessions",
                    models.IntegerField(default=0, verbose_name="Toplam Oturum"),
                ),
                (
                    "average_session_duration",
                    models.IntegerField(
                        default=0, verbose_name="Ortalama Oturum Süresi (dk)"
                    ),
                ),
                (
                    "total_transactions",
                    models.IntegerField(default=0, verbose_name="Toplam İşlem"),
                ),
                (
                    "total_invoices",
                    models.IntegerField(default=0, verbose_name="Toplam Fatura"),
                ),
                (
                    "total_reports",
                    models.IntegerField(default=0, verbose_name="Toplam Rapor"),
                ),
                (
                    "module_usage",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="{'accounting': 150, 'finance': 200, ...}",
                        verbose_name="Modül Kullanımı",
                    ),
                ),
                (
                    "feature_usage",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Özellik Kullanımı"
                    ),
                ),
                (
                    "api_calls",
                    models.IntegerField(default=0, verbose_name="API Çağrısı"),
                ),
                (
                    "api_errors",
                    models.IntegerField(default=0, verbose_name="API Hataları"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Kullanım İstatistiği",
                "verbose_name_plural": "Kullanım İstatistikleri",
                "ordering": ["-period_date"],
                "unique_together": {("period_date", "period_type")},
            },
        ),
        migrations.CreateModel(
            name="SystemHealth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cpu_usage",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="CPU Kullanımı (%)"
                    ),
                ),
                (
                    "memory_usage",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="RAM Kullanımı (%)"
                    ),
                ),
                (
                    "disk_usage",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Disk Kullanımı (%)",
                    ),
                ),
                (
                    "db_connections",
                    models.IntegerField(verbose_name="Aktif DB Bağlantı"),
                ),
                (
                    "db_response_time_ms",
                    models.IntegerField(verbose_name="DB Yanıt Süresi (ms)"),
                ),
                ("active_users", models.IntegerField(verbose_name="Aktif Kullanıcı")),
                (
                    "requests_per_minute",
                    models.IntegerField(verbose_name="Dakika Başı İstek"),
                ),
                (
                    "error_count",
                    models.IntegerField(default=0, verbose_name="Hata Sayısı"),
                ),
                (
                    "overall_status",
                    models.CharField(
                        choices=[
                            ("HEALTHY", "Sağlıklı"),
                            ("WARNING", "Uyarı"),
                            ("CRITICAL", "Kritik"),
                            ("DOWN", "Çalışmıyor"),
                        ],
                        default="HEALTHY",
                        max_length=20,
                        verbose_name="Genel Durum",
                    ),
                ),
                (
                    "status_message",
                    models.TextField(blank=True, verbose_name="Durum Mesajı"),
                ),
                (
                    "checked_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Kontrol Zamanı"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sistem Sağlığı",
                "verbose_name_plural": "Sistem Sağlık Kayıtları",
                "ordering": ["-checked_at"],
                "indexes": [
                    models.Index(
                        fields=["-checked_at"], name="management__checked_79b1b7_idx"
                    ),
                    models.Index(
                        fields=["overall_status", "-checked_at"],
                        name="management__overall_74c329_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SystemAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audit_name",
                    models.CharField(max_length=200, verbose_name="Denetim Adı"),
                ),
                (
                    "audit_type",
                    models.CharField(
                        choices=[
                            ("SECURITY", "Güvenlik Denetimi"),
                            ("COMPLIANCE", "Uyumluluk Denetimi"),
                            ("PERFORMANCE", "Performans Denetimi"),
                            ("DATA", "Veri Denetimi"),
                            ("ACCESS", "Erişim Denetimi"),
                        ],
                        max_length=30,
                        verbose_name="Denetim Tipi",
                    ),
                ),
                ("description", models.TextField(verbose_name="Açıklama")),
                (
                    "audit_criteria",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Denetim Kriterleri"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PASSED", "Geçti"),
                            ("FAILED", "Başarısız"),
                            ("WARNING", "Uyarı"),
                            ("PENDING", "Beklemede"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "findings",
                    models.JSONField(blank=True, default=list, verbose_name="Bulgular"),
                ),
                (
                    "issues_found",
                    models.IntegerField(default=0, verbose_name="Bulunan Sorun Sayısı"),
                ),
                (
                    "compliance_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Uyumluluk Skoru (%)",
                    ),
                ),
                (
                    "recommendations",
                    models.TextField(blank=True, verbose_name="Öneriler"),
                ),
                (
                    "action_items",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Aksiyon Maddeleri"
                    ),
                ),
                ("audit_date", models.DateField(verbose_name="Denetim Tarihi")),
                (
                    "next_audit_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Sonraki Denetim"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "audited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Denetleyen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sistem Denetimi",
                "verbose_name_plural": "Sistem Denetimleri",
                "ordering": ["-audit_date"],
            },
        ),
        migrations.CreateModel(
            name="PerformanceMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("RESPONSE_TIME", "Yanıt Süresi"),
                            ("THROUGHPUT", "İşlem Hacmi"),
                            ("ERROR_RATE", "Hata Oranı"),
                            ("UPTIME", "Çalışma Süresi"),
                            ("API_LATENCY", "API Gecikmesi"),
                        ],
                        max_length=30,
                        verbose_name="Metrik Tipi",
                    ),
                ),
                (
                    "metric_name",
                    models.CharField(max_length=100, verbose_name="Metrik Adı"),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Değer"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        help_text="ms, %, requests/sec, vs.",
                        max_length=20,
                        verbose_name="Birim",
                    ),
                ),
                (
                    "target_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Hedef Değer",
                    ),
                ),
                (
                    "is_healthy",
                    models.BooleanField(default=True, verbose_name="Sağlıklı"),
                ),
                (
                    "endpoint",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Endpoint"
                    ),
                ),
                (
                    "module",
                    models.CharField(blank=True, max_length=50, verbose_name="Modül"),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Kayıt Zamanı"
                    ),
                ),
            ],
            options={
                "verbose_name": "Performans Metriği",
                "verbose_name_plural": "Performans Metrikleri",
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["metric_type", "-recorded_at"],
                        name="management__metric__b45718_idx",
                    ),
                    models.Index(
                        fields=["module", "-recorded_at"],
                        name="management__module_900097_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceWindow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Bakım Başlığı"),
                ),
                ("description", models.TextField(verbose_name="Açıklama")),
                ("start_time", models.DateTimeField(verbose_name="Başlangıç Zamanı")),
                ("end_time", models.DateTimeField(verbose_name="Bitiş Zamanı")),
                (
                    "estimated_duration_minutes",
                    models.IntegerField(verbose_name="Tahmini Süre (dakika)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Planlandı"),
                            ("IN_PROGRESS", "Devam Ediyor"),
                            ("COMPLETED", "Tamamlandı"),
                            ("CANCELLED", "İptal Edildi"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "actual_start_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Gerçek Başlangıç"
                    ),
                ),
                (
                    "actual_end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Gerçek Bitiş"
                    ),
                ),
                (
                    "affected_modules",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Etkilenen Modüller"
                    ),
                ),
                (
                    "notify_users",
                    models.BooleanField(
                        default=True, verbose_name="Kullanıcılara Bildir"
                    ),
                ),
                (
                    "notification_sent",
                    models.BooleanField(
                        default=False, verbose_name="Bildirim Gönderildi"
                    ),
                ),
                (
                    "completion_notes",
                    models.TextField(blank=True, verbose_name="Tamamlanma Notları"),
                ),
                (
                    "issues_encountered",
                    models.TextField(blank=True, verbose_name="Karşılaşılan Sorunlar"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performed_maintenances",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Gerçekleştiren",
                    ),
                ),
                (
                    "scheduled_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_maintenances",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Planlayan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bakım Penceresi",
                "verbose_name_plural": "Bakım Pencereleri",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Özellik Adı"
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        max_length=100, unique=True, verbose_name="Anahtar"
                    ),
                ),
                ("description", models.TextField(verbose_name="Açıklama")),
                (
                    "is_enabled",
                    models.BooleanField(default=False, verbose_name="Aktif"),
                ),
                (
                    "enabled_for_all",
                    models.BooleanField(default=False, verbose_name="Herkes İçin"),
                ),
                (
                    "enabled_for_roles",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Aktif Roller"
                    ),
                ),
                (
                    "rollout_percentage",
                    models.IntegerField(
                        default=0,
                        help_text="0-100",
                        verbose_name="Kullanıma Sunma Yüzdesi",
                    ),
                ),
                (
                    "module",
                    models.CharField(blank=True, max_length=50, verbose_name="Modül"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan",
                    ),
                ),
                (
                    "enabled_for_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="enabled_features",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aktif Kullanıcılar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Özellik Bayrağı",
                "verbose_name_plural": "Özellik Bayrakları",
                "ordering": ["module", "name"],
            },
        ),
        migrations.CreateModel(
            name="BackupLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "backup_name",
                    models.CharField(max_length=200, verbose_name="Yedekleme Adı"),
                ),
                (
                    "backup_type",
                    models.CharField(
                        choices=[
                            ("FULL", "Tam Yedekleme"),
                            ("INCREMENTAL", "Artırımlı"),
                            ("DIFFERENTIAL", "Farksal"),
                            ("DATABASE", "Veritabanı"),
                            ("FILES", "Dosyalar"),
                        ],
                        max_length=20,
                        verbose_name="Yedekleme Tipi",
                    ),
                ),
                (
                    "file_path",
                    models.CharField(max_length=500, verbose_name="Dosya Yolu"),
                ),
                (
                    "file_size_mb",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Dosya Boyutu (MB)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Beklemede"),
                            ("RUNNING", "Çalışıyor"),
                            ("COMPLETED", "Tamamlandı"),
                            ("FAILED", "Başarısız"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Başlangıç"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Bitiş"),
                ),
                (
                    "duration_seconds",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Süre (saniye)"
                    ),
                ),
                (
                    "success_message",
                    models.TextField(blank=True, verbose_name="Başarı Mesajı"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Hata Mesajı"),
                ),
                (
                    "items_backed_up",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Yedeklenen Öğe Sayısı"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "initiated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Başlatan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yedekleme Logu",
                "verbose_name_plural": "Yedekleme Logları",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ErrorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("DEBUG", "Debug"),
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="ERROR",
                        max_length=20,
                        verbose_name="Ciddiyet",
                    ),
                ),
                (
                    "error_type",
                    models.CharField(max_length=100, verbose_name="Hata Tipi"),
                ),
                ("error_message", models.TextField(verbose_name="Hata Mesajı")),
                (
                    "stack_trace",
                    models.TextField(blank=True, verbose_name="Stack Trace"),
                ),
                (
                    "module",
                    models.CharField(blank=True, max_length=100, verbose_name="Modül"),
                ),
                (
                    "function",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Fonksiyon"
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Dosya Yolu"
                    ),
                ),
                (
                    "line_number",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Satır Numarası"
                    ),
                ),
                (
                    "request_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="İstek Yolu"
                    ),
                ),
                (
                    "request_method",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="HTTP Metodu"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Adresi"
                    ),
                ),
                (
                    "extra_data",
                    models.JSONField(blank=True, default=dict, verbose_name="Ek Veri"),
                ),
                (
                    "is_resolved",
                    models.BooleanField(default=False, verbose_name="Çözüldü"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Çözüm Zamanı"
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşma Zamanı"
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_errors",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Çözen",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hata Logu",
                "verbose_name_plural": "Hata Logları",
                "ordering": ["-occurred_at"],
                "indexes": [
                    models.Index(
                        fields=["severity", "-occurred_at"],
                        name="management__severit_3342e7_idx",
                    ),
                    models.Index(
                        fields=["is_resolved", "-occurred_at"],
                        name="management__is_reso_80cb82_idx",
                    ),
                    models.Index(
                        fields=["module", "-occurred_at"],
                        name="management__module_c868ea_idx",
                    ),
                ],
            },
        ),
    ]
