# Generated by Django 5.2.8 on 2025-12-15 11:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0004_databasesnapshot_usagestatistics_systemhealth_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={
                "verbose_name": "Sistem Bildirimi",
                "verbose_name_plural": "Sistem Bildirimleri",
            },
        ),
        migrations.AlterModelOptions(
            name="performancemetric",
            options={
                "ordering": ["-recorded_at"],
                "verbose_name": "Sistem Performans Metriği",
                "verbose_name_plural": "Sistem Performans Metrikleri",
            },
        ),
    ]
