# Generated by Django 5.1.8 on 2025-04-19 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "virtual_company",
            "0002_dailytask_product_alter_virtualcompany_options_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_virtual_company_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
