version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    labels:
      - "npm dependencies"
      - "security"
    commit-message:
      prefix: "npm"
      include: "scope"
    open-pull-requests-limit: 10
    reviewers:
      - "finansal-teknolojiler/frontend-team"
    assignees:
      - "finansal-teknolojiler/maintainers"
    groups:
      dev-dependencies:
        patterns:
          - "*eslint*"
          - "*prettier*"
          - "*jest*"
          - "*test*"
        update-types:
          - "minor"
          - "patch"
      production-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "*eslint*"
          - "*prettier*"
          - "*jest*"
          - "*test*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    labels:
      - "pip dependencies"
      - "security"
    commit-message:
      prefix: "pip"
      include: "scope"
    open-pull-requests-limit: 10
    reviewers:
      - "finansal-teknolojiler/backend-team"
    assignees:
      - "finansal-teknolojiler/maintainers"
    groups:
      django-dependencies:
        patterns:
          - "django*"
          - "djangorestframework*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    labels:
      - "docker"
      - "security"
    commit-message:
      prefix: "docker"
      include: "scope"
    open-pull-requests-limit: 3
    reviewers:
      - "finansal-teknolojiler/devops-team"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    labels:
      - "github-actions"
      - "security"
    commit-message:
      prefix: "github-actions"
      include: "scope"
    open-pull-requests-limit: 5
    reviewers:
      - "finansal-teknolojiler/devops-team" 