# Generated by Django 5.0.2 on 2025-04-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_is_virtual_company_user_remove_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_virtual_company_user',
            field=models.BooleanField(default=False, verbose_name='Sanal Şirket Kullanıcısı'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('business', 'İşletme'), ('student', 'Öğrenci'), ('teacher', 'Öğretmen')], default='student', max_length=10, verbose_name='Kullanıcı Rolü'),
        ),
    ]
