runtime: python310
service: default
instance_class: F2

env_variables:
  DJANGO_SETTINGS_MODULE: "config.settings.prod"
  DJANGO_ALLOWED_HOSTS: "finasis.com.tr,www.finasis.com.tr,api.finasis.com.tr"
  
  # Veritabanı Yapılandırması
  DB_ENGINE: "django.db.backends.postgresql"
  DB_NAME: "finasis_db"
  DB_HOST: "/cloudsql/your-project:region:instance-name"
  DB_PORT: ""
  
  # Redis Cache Yapılandırması
  REDIS_URL: "redis://10.0.0.1:6379/0"
  REDIS_MAX_CONNECTIONS: "20"
  REDIS_TIMEOUT: "300"
  
  # Güvenlik Ayarları
  SECURE_SSL_REDIRECT: "True"
  SESSION_COOKIE_SECURE: "True"
  CSRF_COOKIE_SECURE: "True"
  SECURE_BROWSER_XSS_FILTER: "True"
  SECURE_CONTENT_TYPE_NOSNIFF: "True"
  X_FRAME_OPTIONS: "DENY"
  SECURE_HSTS_SECONDS: "31536000"
  SECURE_HSTS_INCLUDE_SUBDOMAINS: "True"
  SECURE_HSTS_PRELOAD: "True"
  
  # CORS Yapılandırması
  CORS_ALLOWED_ORIGINS: "https://finasis.com.tr,https://www.finasis.com.tr,https://api.finasis.com.tr"
  CORS_ALLOW_METHODS: "GET,POST,PUT,PATCH,DELETE,OPTIONS"
  CORS_ALLOW_CREDENTIALS: "True"
  
  # Performans Ayarları
  CONN_MAX_AGE: "60"
  DEFAULT_TIMEOUT: "30"
  COMPRESS_ENABLED: "True"
  USE_X_FORWARDED_HOST: "True"

# Statik ve Media Dosya Yönetimi
handlers:
- url: /static
  static_dir: staticfiles/
  secure: always
  http_headers:
    X-Content-Type-Options: nosniff
    X-Frame-Options: DENY
    Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
    Content-Security-Policy: "default-src 'self'; img-src 'self' data: https:; style-src 'self' 'unsafe-inline' https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; connect-src 'self' https:;"

- url: /media
  static_dir: media/
  secure: always
  http_headers:
    X-Content-Type-Options: nosniff
    X-Frame-Options: DENY
    Strict-Transport-Security: max-age=31536000; includeSubDomains; preload

- url: /.*
  script: auto
  secure: always
  http_headers:
    Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
    X-Content-Type-Options: nosniff
    X-Frame-Options: DENY

# Uygulama Başlatma Yapılandırması
entrypoint: gunicorn -b :$PORT config.wsgi:application --timeout=120 --workers=2 --threads=4 --worker-class=gthread --worker-tmp-dir=/dev/shm --max-requests=1000 --max-requests-jitter=50

# Otomatik Ölçeklendirme
automatic_scaling:
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.6
  min_instances: 1
  max_instances: 10
  min_idle_instances: 1
  max_idle_instances: 2
  min_pending_latency: 30ms
  max_pending_latency: 200ms
  cool_down_period_sec: 180

# Sağlık Kontrolü
liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  initial_delay_sec: 300

readiness_check:
  path: "/ready"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300

# VPC Yapılandırması
vpc_access_connector:
  name: "projects/your-project/locations/region/connectors/your-connector"

# Kaynak Limitleri
resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 20

# İzleme ve Günlük Kaydı
env:
  PYTHONUNBUFFERED: "True"

inbound_services:
- warmup
- health_check 