# Generated by Django 5.2.8 on 2025-11-11 16:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("developer_portal", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="apikeyusagelog",
            new_name="developer_p_api_key_2199ed_idx",
            old_name="developer__api_key_058ed9_idx",
        ),
        migrations.RenameIndex(
            model_name="apikeyusagelog",
            new_name="developer_p_api_key_11a385_idx",
            old_name="developer__api_key_413f21_idx",
        ),
        migrations.RenameIndex(
            model_name="developerapikey",
            new_name="developer_p_prefix_f463ea_idx",
            old_name="developer__prefix_ab512f_idx",
        ),
        migrations.RenameIndex(
            model_name="developerapikey",
            new_name="developer_p_organiz_11bd54_idx",
            old_name="developer__organiza_d6fe4d_idx",
        ),
    ]
