# Generated by Django 4.2.23 on 2025-09-11 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0001_initial"),
        ("finance", "0004_integratedbankaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicerecord",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="finance_invoice_records",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="voucher",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="finance_vouchers",
                to="tenancy.tenant",
            ),
        ),
    ]
