# Generated by Django 5.2.6 on 2025-09-28 09:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0009_planningscenario"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("finance", "0005_invoicerecord_tenant_voucher_tenant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataBackup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "backup_name",
                    models.CharField(max_length=200, verbose_name="Yedek Adı"),
                ),
                (
                    "backup_type",
                    models.CharField(
                        choices=[
                            ("FULL", "Tam Yedek"),
                            ("INCREMENTAL", "Artan Yedek"),
                            ("DIFFERENTIAL", "Fark Yedek"),
                            ("SELECTIVE", "Seçici Yedek"),
                        ],
                        max_length=20,
                        verbose_name="Yedek Tipi",
                    ),
                ),
                (
                    "backup_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yedekleme Tarihi"
                    ),
                ),
                (
                    "included_tables",
                    models.JSONField(
                        default=list, verbose_name="Dahil Edilen Tablolar"
                    ),
                ),
                (
                    "excluded_tables",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Hariç Tutulan Tablolar"
                    ),
                ),
                (
                    "record_count",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Kayıt Sayısı"
                    ),
                ),
                (
                    "file_path",
                    models.CharField(max_length=500, verbose_name="Dosya Yolu"),
                ),
                (
                    "file_size_bytes",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Dosya Boyutu (Byte)"
                    ),
                ),
                (
                    "compression_used",
                    models.BooleanField(
                        default=True, verbose_name="Sıkıştırma Kullanıldı"
                    ),
                ),
                (
                    "encryption_used",
                    models.BooleanField(
                        default=True, verbose_name="Şifreleme Kullanıldı"
                    ),
                ),
                (
                    "file_hash",
                    models.CharField(max_length=128, verbose_name="Dosya Hash"),
                ),
                (
                    "checksum",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Checksum"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_PROGRESS", "Devam Ediyor"),
                            ("COMPLETED", "Tamamlandı"),
                            ("FAILED", "Başarısız"),
                            ("CORRUPTED", "Bozuk"),
                            ("VERIFIED", "Doğrulandı"),
                        ],
                        default="IN_PROGRESS",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="Başlangıç Zamanı")),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Bitiş Zamanı"
                    ),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Süre (Saniye)"
                    ),
                ),
                (
                    "retention_period_days",
                    models.PositiveIntegerField(
                        default=365, verbose_name="Saklama Süresi (Gün)"
                    ),
                ),
                (
                    "scheduled_deletion_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Planlanan Silme Tarihi"
                    ),
                ),
                (
                    "last_verification_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Son Doğrulama Tarihi"
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("NOT_VERIFIED", "Doğrulanmadı"),
                            ("VERIFIED", "Doğrulandı"),
                            ("VERIFICATION_FAILED", "Doğrulama Başarısız"),
                        ],
                        default="NOT_VERIFIED",
                        max_length=20,
                        verbose_name="Doğrulama Durumu",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Hata Mesajı"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_backups",
                        to="accounting.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Veri Yedek",
                "verbose_name_plural": "Veri Yedekleri",
                "ordering": ["-backup_date"],
            },
        ),
        migrations.CreateModel(
            name="DataSubjectRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_id",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="Talep ID"
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("ACCESS", "Erişim Hakkı"),
                            ("RECTIFICATION", "Düzeltme Hakkı"),
                            ("ERASURE", "Silme Hakkı"),
                            ("OBJECTION", "İtiraz Hakkı"),
                            ("PORTABILITY", "Taşınabilirlik Hakkı"),
                            ("RESTRICTION", "İşleme Kısıtlama Hakkı"),
                            ("COMPLAINT", "Şikayet"),
                        ],
                        max_length=20,
                        verbose_name="Talep Tipi",
                    ),
                ),
                (
                    "request_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Talep Tarihi"
                    ),
                ),
                (
                    "data_subject_name",
                    models.CharField(max_length=200, verbose_name="Ad Soyad"),
                ),
                (
                    "data_subject_email",
                    models.EmailField(max_length=254, verbose_name="E-posta"),
                ),
                (
                    "data_subject_phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Telefon"),
                ),
                (
                    "identity_verified",
                    models.BooleanField(
                        default=False, verbose_name="Kimlik Doğrulandı"
                    ),
                ),
                (
                    "verification_method",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Doğrulama Yöntemi"
                    ),
                ),
                (
                    "request_description",
                    models.TextField(verbose_name="Talep Açıklaması"),
                ),
                (
                    "specific_data_requested",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="Talep Edilen Belirli Veriler",
                    ),
                ),
                (
                    "preferred_response_method",
                    models.CharField(
                        choices=[
                            ("EMAIL", "E-posta"),
                            ("POST", "Posta"),
                            ("PHONE", "Telefon"),
                            ("IN_PERSON", "Şahsen"),
                        ],
                        default="EMAIL",
                        max_length=50,
                        verbose_name="Tercih Edilen Yanıt Yöntemi",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Alındı"),
                            ("UNDER_REVIEW", "İnceleniyor"),
                            ("ADDITIONAL_INFO_REQUIRED", "Ek Bilgi Gerekli"),
                            ("APPROVED", "Onaylandı"),
                            ("PARTIALLY_APPROVED", "Kısmen Onaylandı"),
                            ("REJECTED", "Reddedildi"),
                            ("COMPLETED", "Tamamlandı"),
                        ],
                        default="RECEIVED",
                        max_length=30,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "due_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Vade Tarihi"
                    ),
                ),
                (
                    "response_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Yanıt Tarihi"
                    ),
                ),
                (
                    "is_overdue",
                    models.BooleanField(default=False, verbose_name="Süresi Geçti"),
                ),
                (
                    "response_summary",
                    models.TextField(blank=True, verbose_name="Yanıt Özeti"),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Red Gerekçesi"),
                ),
                (
                    "actions_taken",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Alınan Aksiyonlar"
                    ),
                ),
                (
                    "supporting_documents",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Destekleyici Belgeler"
                    ),
                ),
                (
                    "internal_notes",
                    models.TextField(blank=True, verbose_name="İç Notlar"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atanan Kişi",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_subject_requests",
                        to="accounting.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Veri Sahibi Talebi",
                "verbose_name_plural": "Veri Sahibi Talepleri",
                "ordering": ["-request_date"],
            },
        ),
        migrations.CreateModel(
            name="EncryptionKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key_name",
                    models.CharField(max_length=100, verbose_name="Anahtar Adı"),
                ),
                (
                    "key_type",
                    models.CharField(
                        choices=[
                            ("AES", "AES Şifreleme"),
                            ("FERNET", "Fernet Şifreleme"),
                            ("RSA", "RSA Şifreleme"),
                            ("HASH", "Hash Fonksiyonu"),
                        ],
                        max_length=20,
                        verbose_name="Anahtar Tipi",
                    ),
                ),
                (
                    "key_purpose",
                    models.CharField(
                        help_text="personal_data, financial_data, backups vb.",
                        max_length=100,
                        verbose_name="Kullanım Amacı",
                    ),
                ),
                (
                    "algorithm",
                    models.CharField(max_length=50, verbose_name="Algoritma"),
                ),
                (
                    "key_length",
                    models.PositiveIntegerField(verbose_name="Anahtar Uzunluğu (bit)"),
                ),
                (
                    "encrypted_key_value",
                    models.BinaryField(verbose_name="Şifrelenmiş Anahtar Değeri"),
                ),
                (
                    "key_hash",
                    models.CharField(
                        max_length=128, unique=True, verbose_name="Anahtar Hash"
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "activation_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Aktivasyon Tarihi",
                    ),
                ),
                (
                    "expiration_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Son Kullanma Tarihi"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "is_compromised",
                    models.BooleanField(
                        default=False, verbose_name="Güvenliği İhlal Edildi"
                    ),
                ),
                (
                    "rotation_required",
                    models.BooleanField(default=False, verbose_name="Rotasyon Gerekli"),
                ),
                (
                    "usage_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Kullanım Sayısı"
                    ),
                ),
                (
                    "last_used_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Son Kullanım Tarihi"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encryption_keys",
                        to="accounting.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Şifreleme Anahtarı",
                "verbose_name_plural": "Şifreleme Anahtarları",
                "ordering": ["-created_date"],
            },
        ),
        migrations.CreateModel(
            name="PersonalDataCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Kategori Adı")),
                ("description", models.TextField(verbose_name="Açıklama")),
                (
                    "sensitivity_level",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Genel"),
                            ("INTERNAL", "Dahili"),
                            ("CONFIDENTIAL", "Gizli"),
                            ("RESTRICTED", "Çok Gizli"),
                            ("SENSITIVE", "Hassas Kişisel Veri"),
                        ],
                        max_length=20,
                        verbose_name="Hassasiyet Seviyesi",
                    ),
                ),
                (
                    "processing_purpose",
                    models.CharField(
                        choices=[
                            ("CONTRACTUAL", "Sözleşme Gereği"),
                            ("LEGAL_OBLIGATION", "Yasal Yükümlülük"),
                            ("LEGITIMATE_INTEREST", "Meşru Menfaat"),
                            ("CONSENT", "Açık Rıza"),
                            ("PUBLIC_INTEREST", "Kamu Yararı"),
                            ("VITAL_INTEREST", "Yaşamsal Çıkar"),
                        ],
                        max_length=20,
                        verbose_name="İşleme Amacı",
                    ),
                ),
                (
                    "legal_basis",
                    models.TextField(
                        help_text="KVKK'nın hangi maddesi veya başka yasal düzenleme",
                        verbose_name="Hukuki Dayanak",
                    ),
                ),
                (
                    "retention_period_months",
                    models.PositiveIntegerField(
                        help_text="0 = Süresiz", verbose_name="Saklama Süresi (Ay)"
                    ),
                ),
                (
                    "deletion_required",
                    models.BooleanField(
                        default=True, verbose_name="Otomatik Silme Gerekli"
                    ),
                ),
                (
                    "data_subjects_informed",
                    models.BooleanField(
                        default=False, verbose_name="Veri Sahipleri Bilgilendirildi"
                    ),
                ),
                (
                    "information_method",
                    models.CharField(
                        blank=True,
                        help_text="E-posta, SMS, Web sitesi aydınlatma metni vb.",
                        max_length=100,
                        verbose_name="Bilgilendirme Yöntemi",
                    ),
                ),
                (
                    "encryption_required",
                    models.BooleanField(
                        default=False, verbose_name="Şifreleme Gerekli"
                    ),
                ),
                (
                    "access_restrictions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Hangi roller/departmanlar erişebilir",
                        verbose_name="Erişim Kısıtları",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_categories",
                        to="accounting.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kişisel Veri Kategorisi",
                "verbose_name_plural": "Kişisel Veri Kategorileri",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SecurityIncident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "incident_id",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="Olay ID"
                    ),
                ),
                (
                    "incident_type",
                    models.CharField(
                        choices=[
                            ("DATA_BREACH", "Veri İhlali"),
                            ("UNAUTHORIZED_ACCESS", "Yetkisiz Erişim"),
                            ("MALWARE", "Zararlı Yazılım"),
                            ("PHISHING", "Kimlik Avı"),
                            ("SYSTEM_COMPROMISE", "Sistem Güvenliği İhlali"),
                            ("PHYSICAL_BREACH", "Fiziksel Güvenlik İhlali"),
                            ("INSIDER_THREAT", "İç Tehdit"),
                            ("DDoS", "Hizmet Dışı Bırakma Saldırısı"),
                            ("OTHER", "Diğer"),
                        ],
                        max_length=30,
                        verbose_name="Olay Tipi",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Başlık")),
                ("description", models.TextField(verbose_name="Açıklama")),
                ("detected_date", models.DateTimeField(verbose_name="Tespit Tarihi")),
                (
                    "occurred_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Gerçekleşme Tarihi"
                    ),
                ),
                (
                    "reported_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Raporlama Tarihi"
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Düşük"),
                            ("MEDIUM", "Orta"),
                            ("HIGH", "Yüksek"),
                            ("CRITICAL", "Kritik"),
                        ],
                        max_length=20,
                        verbose_name="Şiddet",
                    ),
                ),
                (
                    "affected_systems",
                    models.JSONField(default=list, verbose_name="Etkilenen Sistemler"),
                ),
                (
                    "affected_data_types",
                    models.JSONField(
                        default=list, verbose_name="Etkilenen Veri Tipleri"
                    ),
                ),
                (
                    "estimated_records_affected",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Etkilenen Kayıt Sayısı (Tahmini)",
                    ),
                ),
                (
                    "is_personal_data_involved",
                    models.BooleanField(
                        default=False, verbose_name="Kişisel Veri İçeriyor"
                    ),
                ),
                (
                    "personal_data_categories",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="Etkilenen Kişisel Veri Kategorileri",
                    ),
                ),
                (
                    "data_subjects_affected",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Etkilenen Veri Sahibi Sayısı",
                    ),
                ),
                (
                    "kvkk_notification_required",
                    models.BooleanField(
                        default=False, verbose_name="KVKK Bildirimi Gerekli"
                    ),
                ),
                (
                    "kvkk_notification_sent",
                    models.BooleanField(
                        default=False, verbose_name="KVKK Bildirimi Gönderildi"
                    ),
                ),
                (
                    "kvkk_notification_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="KVKK Bildirim Tarihi"
                    ),
                ),
                (
                    "data_subjects_notification_required",
                    models.BooleanField(
                        default=False, verbose_name="Veri Sahipleri Bildirimi Gerekli"
                    ),
                ),
                (
                    "data_subjects_notification_sent",
                    models.BooleanField(
                        default=False,
                        verbose_name="Veri Sahipleri Bildirimi Gönderildi",
                    ),
                ),
                (
                    "data_subjects_notification_date",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Veri Sahipleri Bildirim Tarihi",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Açık"),
                            ("INVESTIGATING", "Araştırılıyor"),
                            ("CONTAINED", "Kontrol Altına Alındı"),
                            ("RESOLVED", "Çözümlendi"),
                            ("CLOSED", "Kapatıldı"),
                        ],
                        default="OPEN",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                ("root_cause", models.TextField(blank=True, verbose_name="Kök Neden")),
                (
                    "resolution_summary",
                    models.TextField(blank=True, verbose_name="Çözüm Özeti"),
                ),
                (
                    "lessons_learned",
                    models.TextField(blank=True, verbose_name="Alınan Dersler"),
                ),
                (
                    "response_time_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Müdahale Süresi (Saat)",
                    ),
                ),
                (
                    "resolution_time_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Çözüm Süresi (Saat)",
                    ),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Tahmini Maliyet",
                    ),
                ),
                (
                    "actual_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Gerçek Maliyet",
                    ),
                ),
                (
                    "external_authorities_notified",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="Bilgilendirilen Dış Otoriteler",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atanan Kişi",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_incidents",
                        to="accounting.company",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_incidents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Raporlayan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Güvenlik Olayı",
                "verbose_name_plural": "Güvenlik Olayları",
                "ordering": ["-detected_date"],
            },
        ),
        migrations.CreateModel(
            name="DataEncryption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_identifier",
                    models.CharField(
                        help_text="Tablo adı, alan adı, kayıt ID'si vb.",
                        max_length=255,
                        verbose_name="Veri Tanımlayıcısı",
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        help_text="personal_data, financial_record, document vb.",
                        max_length=100,
                        verbose_name="Veri Tipi",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "encryption_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Şifreleme Tarihi"
                    ),
                ),
                (
                    "data_hash",
                    models.CharField(max_length=128, verbose_name="Veri Hash"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "decryption_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Şifre Çözme Tarihi"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_encryptions",
                        to="accounting.company",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "encrypted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Şifreleyen",
                    ),
                ),
                (
                    "encryption_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="encrypted_data",
                        to="finance.encryptionkey",
                        verbose_name="Şifreleme Anahtarı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Veri Şifreleme Kaydı",
                "verbose_name_plural": "Veri Şifreleme Kayıtları",
                "ordering": ["-encryption_date"],
                "indexes": [
                    models.Index(
                        fields=["data_identifier", "data_type"],
                        name="finance_dat_data_id_b493c7_idx",
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="finance_dat_content_892ec1_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PersonalDataRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_subject_id",
                    models.CharField(
                        help_text="Müşteri ID, çalışan ID vb. (hashlenmiş)",
                        max_length=100,
                        verbose_name="Veri Sahibi ID",
                    ),
                ),
                (
                    "data_subject_type",
                    models.CharField(
                        help_text="customer, employee, vendor vb.",
                        max_length=50,
                        verbose_name="Veri Sahibi Tipi",
                    ),
                ),
                (
                    "processing_activity",
                    models.CharField(
                        choices=[
                            ("COLLECTION", "Toplama"),
                            ("STORAGE", "Saklama"),
                            ("UPDATE", "Güncelleme"),
                            ("SHARING", "Paylaşma"),
                            ("TRANSFER", "Aktarma"),
                            ("ANONYMIZATION", "Anonimleştirme"),
                            ("DELETION", "Silme"),
                            ("ACCESS", "Erişim"),
                        ],
                        max_length=20,
                        verbose_name="İşleme Faaliyeti",
                    ),
                ),
                (
                    "processing_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="İşleme Tarihi"
                    ),
                ),
                (
                    "data_fields_processed",
                    models.JSONField(
                        default=list,
                        help_text="Hangi alanlar işlendi: name, email, phone vb.",
                        verbose_name="İşlenen Veri Alanları",
                    ),
                ),
                ("processing_purpose", models.TextField(verbose_name="İşleme Amacı")),
                (
                    "consent_obtained",
                    models.BooleanField(default=False, verbose_name="Rıza Alındı"),
                ),
                (
                    "consent_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Rıza Tarihi"
                    ),
                ),
                (
                    "consent_method",
                    models.CharField(
                        blank=True,
                        help_text="Online form, yazılı belge vb.",
                        max_length=100,
                        verbose_name="Rıza Yöntemi",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Adresi"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, verbose_name="Kullanıcı Aracısı"),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "scheduled_deletion_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Planlanan Silme Tarihi"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silindi"),
                ),
                (
                    "deletion_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Silme Tarihi"
                    ),
                ),
                (
                    "deletion_method",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Silme Yöntemi"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_data_records",
                        to="accounting.company",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "data_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="data_records",
                        to="finance.personaldatacategory",
                        verbose_name="Veri Kategorisi",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="İşleyen Kişi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kişisel Veri Kaydı",
                "verbose_name_plural": "Kişisel Veri Kayıtları",
                "ordering": ["-processing_date"],
                "indexes": [
                    models.Index(
                        fields=["data_subject_id", "data_subject_type"],
                        name="finance_per_data_su_bba202_idx",
                    ),
                    models.Index(
                        fields=["processing_activity", "processing_date"],
                        name="finance_per_process_befc2a_idx",
                    ),
                    models.Index(
                        fields=["scheduled_deletion_date"],
                        name="finance_per_schedul_6450f9_idx",
                    ),
                ],
            },
        ),
    ]
