# Generated by Django 5.2.1 on 2025-10-08 09:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0010_exchangerate_glaccount_gljournalentry_gljournalline"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("finance", "0008_trialbalancesnapshot"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Drop indexes that reference fields we are about to remove to avoid
        # sqlite3 table remake errors like "NewJournalEntry has no field named 'account'".
        migrations.RemoveIndex(
            model_name="journalentry",
            name="finance_jou_account_d972a3_idx",
        ),
        migrations.RemoveIndex(
            model_name="journalentry",
            name="finance_jou_voucher_b9c6ea_idx",
        ),
        # JournalVoucher indexes referencing 'company' must be dropped before removing the field
        migrations.RemoveIndex(
            model_name="journalvoucher",
            name="finance_jou_company_71c28b_idx",
        ),
        migrations.RemoveIndex(
            model_name="journalvoucher",
            name="finance_jou_company_ac6fa3_idx",
        ),
        migrations.RemoveField(
            model_name="journalentry",
            name="account",
        ),
        migrations.RemoveField(
            model_name="taxrate",
            name="account",
        ),
        migrations.RemoveField(
            model_name="fixedasset",
            name="cost_account",
        ),
        migrations.RemoveField(
            model_name="fixedasset",
            name="accumulated_depreciation_account",
        ),
        migrations.RemoveField(
            model_name="inventoryitem",
            name="cost_of_sales_account",
        ),
        migrations.RemoveField(
            model_name="costcenter",
            name="budget_account",
        ),
        migrations.RemoveField(
            model_name="inventoryitem",
            name="inventory_account",
        ),
        migrations.AlterUniqueTogether(
            name="costcenter",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="costcenter",
            name="company",
        ),
        migrations.RemoveField(
            model_name="costcenter",
            name="parent",
        ),
        migrations.AlterUniqueTogether(
            name="depreciationentry",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="depreciationentry",
            name="fiscal_period",
        ),
        migrations.RemoveField(
            model_name="depreciationentry",
            name="fixed_asset",
        ),
        migrations.RemoveField(
            model_name="depreciationentry",
            name="voucher",
        ),
        migrations.RemoveField(
            model_name="depreciationmethod",
            name="company",
        ),
        migrations.RemoveField(
            model_name="fixedasset",
            name="depreciation_method",
        ),
        migrations.AlterUniqueTogether(
            name="fiscalperiod",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="fiscalperiod",
            name="closed_by",
        ),
        migrations.RemoveField(
            model_name="fiscalperiod",
            name="company",
        ),
        migrations.RemoveField(
            model_name="journalvoucher",
            name="fiscal_period",
        ),
        migrations.RemoveField(
            model_name="fixedasset",
            name="company",
        ),
        migrations.AlterUniqueTogether(
            name="inventoryitem",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="inventoryitem",
            name="company",
        ),
        migrations.RemoveField(
            model_name="stockmovement",
            name="inventory_item",
        ),
        migrations.AlterUniqueTogether(
            name="journalentry",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="journalentry",
            name="voucher",
        ),
        migrations.AlterUniqueTogether(
            name="journalvoucher",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="journalvoucher",
            name="company",
        ),
        migrations.RemoveField(
            model_name="journalvoucher",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="journalvoucher",
            name="posted_by",
        ),
        migrations.RemoveField(
            model_name="stockmovement",
            name="voucher",
        ),
        migrations.RemoveField(
            model_name="stockmovement",
            name="company",
        ),
        migrations.RemoveField(
            model_name="stockmovement",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="taxrate",
            name="company",
        ),
        migrations.CreateModel(
            name="ApprovalWorkflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="İş Akışı Adı")),
                (
                    "workflow_type",
                    models.CharField(
                        choices=[
                            ("VOUCHER_APPROVAL", "Fiş Onayı"),
                            ("PAYMENT_APPROVAL", "Ödeme Onayı"),
                            ("PURCHASE_APPROVAL", "Satın Alma Onayı"),
                            ("BUDGET_APPROVAL", "Bütçe Onayı"),
                            ("USER_ACCESS", "Kullanıcı Erişimi"),
                            ("REPORT_ACCESS", "Rapor Erişimi"),
                        ],
                        max_length=30,
                        verbose_name="İş Akışı Tipi",
                    ),
                ),
                (
                    "min_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Minimum Tutar",
                    ),
                ),
                (
                    "max_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Maksimum Tutar",
                    ),
                ),
                (
                    "applicable_modules",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Geçerli Modüller"
                    ),
                ),
                (
                    "is_sequential",
                    models.BooleanField(
                        default=True,
                        help_text="True: Sırayla onay, False: Paralel onay",
                        verbose_name="Sıralı Onay",
                    ),
                ),
                (
                    "require_all_approvers",
                    models.BooleanField(
                        default=True, verbose_name="Tüm Onaylayanlar Gerekli"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_workflows",
                        to="accounting.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Onay İş Akışı",
                "verbose_name_plural": "Onay İş Akışları",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_id",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="Talep ID"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Başlık")),
                ("description", models.TextField(verbose_name="Açıklama")),
                ("object_id", models.PositiveIntegerField()),
                (
                    "requested_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Talep Zamanı"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Beklemede"),
                            ("IN_PROGRESS", "İşlemde"),
                            ("APPROVED", "Onaylandı"),
                            ("REJECTED", "Reddedildi"),
                            ("CANCELLED", "İptal Edildi"),
                            ("TIMEOUT", "Zaman Aşımı"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "current_step",
                    models.PositiveIntegerField(default=0, verbose_name="Mevcut Adım"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Tutar",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tamamlanma Zamanı"
                    ),
                ),
                (
                    "final_decision",
                    models.TextField(blank=True, verbose_name="Nihai Karar"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_requests",
                        to="accounting.company",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="finance_approval_requests",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Talep Eden",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval_requests",
                        to="finance.approvalworkflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "Onay Talebi",
                "verbose_name_plural": "Onay Talepleri",
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalWorkflowStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_order", models.PositiveIntegerField(verbose_name="Adım Sırası")),
                (
                    "step_name",
                    models.CharField(max_length=100, verbose_name="Adım Adı"),
                ),
                (
                    "approver_role",
                    models.CharField(
                        blank=True,
                        help_text="Belirli bir role sahip herhangi bir kullanıcı",
                        max_length=100,
                        verbose_name="Onaylayıcı Rolü",
                    ),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(default=True, verbose_name="Zorunlu"),
                ),
                (
                    "timeout_hours",
                    models.PositiveIntegerField(
                        default=24, verbose_name="Zaman Aşımı (Saat)"
                    ),
                ),
                (
                    "auto_approve_after_timeout",
                    models.BooleanField(
                        default=False, verbose_name="Zaman Aşımında Otomatik Onay"
                    ),
                ),
                (
                    "condition_expression",
                    models.TextField(
                        blank=True,
                        help_text="Python ifadesi: amount > 10000, user.department == 'finance'",
                        verbose_name="Koşul İfadesi",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "approver_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Onaylayıcı Kullanıcı",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_steps",
                        to="finance.approvalworkflow",
                        verbose_name="İş Akışı",
                    ),
                ),
            ],
            options={
                "verbose_name": "İş Akışı Adımı",
                "verbose_name_plural": "İş Akışı Adımları",
                "ordering": ["step_order"],
                "unique_together": {("workflow", "step_order")},
            },
        ),
        migrations.CreateModel(
            name="ApprovalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Beklemede"),
                            ("APPROVED", "Onaylandı"),
                            ("REJECTED", "Reddedildi"),
                            ("TIMEOUT", "Zaman Aşımı"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                ("due_date", models.DateTimeField(verbose_name="Vade Tarihi")),
                (
                    "decision_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Karar Tarihi"
                    ),
                ),
                ("comments", models.TextField(blank=True, verbose_name="Yorumlar")),
                (
                    "notification_sent",
                    models.BooleanField(
                        default=False, verbose_name="Bildirim Gönderildi"
                    ),
                ),
                (
                    "reminder_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Hatırlatma Sayısı"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Onaylayıcı",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_records",
                        to="finance.approvalrequest",
                        verbose_name="Onay Talebi",
                    ),
                ),
                (
                    "workflow_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="finance.approvalworkflowstep",
                        verbose_name="İş Akışı Adımı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Onay Kaydı",
                "verbose_name_plural": "Onay Kayıtları",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditTrail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Oturum ID"
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("CREATE", "Oluştur"),
                            ("UPDATE", "Güncelle"),
                            ("DELETE", "Sil"),
                            ("VIEW", "Görüntüle"),
                            ("EXPORT", "Dışa Aktar"),
                            ("PRINT", "Yazdır"),
                            ("LOGIN", "Giriş"),
                            ("LOGOUT", "Çıkış"),
                            ("APPROVE", "Onayla"),
                            ("REJECT", "Reddet"),
                            ("CANCEL", "İptal Et"),
                            ("POST", "Kaydet"),
                            ("UNPOST", "Kaydı Geri Al"),
                        ],
                        max_length=20,
                        verbose_name="İşlem Tipi",
                    ),
                ),
                (
                    "table_name",
                    models.CharField(max_length=100, verbose_name="Tablo Adı"),
                ),
                (
                    "record_id",
                    models.CharField(max_length=100, verbose_name="Kayıt ID"),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "old_values",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Eski Değerler"
                    ),
                ),
                (
                    "new_values",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Yeni Değerler"
                    ),
                ),
                (
                    "changed_fields",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Değişen Alanlar"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Adresi"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, verbose_name="Tarayıcı Bilgisi"),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Düşük"),
                            ("MEDIUM", "Orta"),
                            ("HIGH", "Yüksek"),
                            ("CRITICAL", "Kritik"),
                        ],
                        default="LOW",
                        max_length=20,
                        verbose_name="Risk Seviyesi",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "module_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Modül Adı"
                    ),
                ),
                (
                    "function_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Fonksiyon Adı"
                    ),
                ),
                ("success", models.BooleanField(default=True, verbose_name="Başarılı")),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Hata Mesajı"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Zaman"),
                ),
                (
                    "duration_ms",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Süre (ms)"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_trails",
                        to="accounting.company",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Denetim İzi",
                "verbose_name_plural": "Denetim İzleri",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ControlActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "control_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Kontrol ID"
                    ),
                ),
                (
                    "control_name",
                    models.CharField(max_length=200, verbose_name="Kontrol Adı"),
                ),
                (
                    "control_description",
                    models.TextField(verbose_name="Kontrol Açıklaması"),
                ),
                ("control_objective", models.TextField(verbose_name="Kontrol Amacı")),
                (
                    "control_type",
                    models.CharField(
                        choices=[
                            ("PREVENTIVE", "Önleyici"),
                            ("DETECTIVE", "Tespit Edici"),
                            ("CORRECTIVE", "Düzeltici"),
                            ("COMPENSATING", "Telafi Edici"),
                        ],
                        max_length=20,
                        verbose_name="Kontrol Tipi",
                    ),
                ),
                (
                    "control_nature",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manuel"),
                            ("AUTOMATIC", "Otomatik"),
                            ("IT_DEPENDENT", "BT Bağımlı"),
                            ("IT_GENERAL", "BT Genel"),
                        ],
                        max_length=20,
                        verbose_name="Kontrol Doğası",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("REAL_TIME", "Gerçek Zamanlı"),
                            ("DAILY", "Günlük"),
                            ("WEEKLY", "Haftalık"),
                            ("MONTHLY", "Aylık"),
                            ("QUARTERLY", "Üç Aylık"),
                            ("ANNUALLY", "Yıllık"),
                            ("ON_DEMAND", "Talep Üzerine"),
                        ],
                        max_length=20,
                        verbose_name="Sıklık",
                    ),
                ),
                (
                    "control_procedure",
                    models.TextField(verbose_name="Kontrol Prosedürü"),
                ),
                (
                    "evidence_required",
                    models.TextField(blank=True, verbose_name="Gerekli Kanıt"),
                ),
                (
                    "design_effectiveness",
                    models.CharField(
                        choices=[
                            ("EFFECTIVE", "Etkili"),
                            ("INEFFECTIVE", "Etkisiz"),
                            ("NOT_EVALUATED", "Değerlendirilmedi"),
                        ],
                        default="NOT_EVALUATED",
                        max_length=20,
                        verbose_name="Tasarım Etkinliği",
                    ),
                ),
                (
                    "operating_effectiveness",
                    models.CharField(
                        choices=[
                            ("EFFECTIVE", "Etkili"),
                            ("INEFFECTIVE", "Etkisiz"),
                            ("NOT_EVALUATED", "Değerlendirilmedi"),
                        ],
                        default="NOT_EVALUATED",
                        max_length=20,
                        verbose_name="İşleyiş Etkinliği",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "last_performed_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Son Uygulama Tarihi"
                    ),
                ),
                (
                    "next_due_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Sonraki Vade Tarihi"
                    ),
                ),
                (
                    "improvement_recommendations",
                    models.TextField(blank=True, verbose_name="İyileştirme Önerileri"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="control_activities",
                        to="accounting.company",
                    ),
                ),
                (
                    "control_owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_controls",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kontrol Sahibi",
                    ),
                ),
                (
                    "control_performer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performed_controls",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kontrol Uygulayıcısı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kontrol Faaliyeti",
                "verbose_name_plural": "Kontrol Faaliyetleri",
                "ordering": ["control_id"],
            },
        ),
        migrations.CreateModel(
            name="ControlExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("execution_date", models.DateField(verbose_name="Uygulama Tarihi")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PASSED", "Başarılı"),
                            ("FAILED", "Başarısız"),
                            ("NOT_APPLICABLE", "Uygulanamaz"),
                            ("DEFERRED", "Ertelendi"),
                        ],
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "results_description",
                    models.TextField(verbose_name="Sonuç Açıklaması"),
                ),
                (
                    "exceptions_noted",
                    models.TextField(
                        blank=True, verbose_name="Tespit Edilen İstisnalar"
                    ),
                ),
                (
                    "evidence_attached",
                    models.BooleanField(default=False, verbose_name="Kanıt Ekli"),
                ),
                (
                    "management_response",
                    models.TextField(blank=True, verbose_name="Yönetim Yanıtı"),
                ),
                (
                    "corrective_actions",
                    models.TextField(blank=True, verbose_name="Düzeltici Aksiyonlar"),
                ),
                (
                    "follow_up_required",
                    models.BooleanField(default=False, verbose_name="Takip Gerekli"),
                ),
                (
                    "follow_up_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Takip Tarihi"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "control_activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="finance.controlactivity",
                        verbose_name="Kontrol Faaliyeti",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Uygulayan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kontrol Uygulama Kaydı",
                "verbose_name_plural": "Kontrol Uygulama Kayıtları",
                "ordering": ["-execution_date"],
            },
        ),
        migrations.CreateModel(
            name="RiskAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assessment_date",
                    models.DateField(verbose_name="Değerlendirme Tarihi"),
                ),
                (
                    "risk_title",
                    models.CharField(max_length=200, verbose_name="Risk Başlığı"),
                ),
                ("risk_description", models.TextField(verbose_name="Risk Açıklaması")),
                (
                    "risk_category",
                    models.CharField(
                        choices=[
                            ("FINANCIAL", "Mali Risk"),
                            ("OPERATIONAL", "Operasyonel Risk"),
                            ("COMPLIANCE", "Uyum Riski"),
                            ("STRATEGIC", "Stratejik Risk"),
                            ("TECHNOLOGY", "Teknoloji Riski"),
                            ("REPUTATION", "İtibar Riski"),
                        ],
                        max_length=20,
                        verbose_name="Risk Kategorisi",
                    ),
                ),
                (
                    "likelihood",
                    models.CharField(
                        choices=[
                            ("VERY_LOW", "Çok Düşük"),
                            ("LOW", "Düşük"),
                            ("MEDIUM", "Orta"),
                            ("HIGH", "Yüksek"),
                            ("VERY_HIGH", "Çok Yüksek"),
                        ],
                        help_text="Riskin gerçekleşme olasılığı",
                        max_length=20,
                        verbose_name="Olasılık",
                    ),
                ),
                (
                    "impact",
                    models.CharField(
                        choices=[
                            ("VERY_LOW", "Çok Düşük"),
                            ("LOW", "Düşük"),
                            ("MEDIUM", "Orta"),
                            ("HIGH", "Yüksek"),
                            ("VERY_HIGH", "Çok Yüksek"),
                        ],
                        help_text="Gerçekleştiğinde yaratacağı etki",
                        max_length=20,
                        verbose_name="Etki",
                    ),
                ),
                (
                    "risk_score",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Risk Skoru"
                    ),
                ),
                (
                    "overall_risk_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("VERY_LOW", "Çok Düşük"),
                            ("LOW", "Düşük"),
                            ("MEDIUM", "Orta"),
                            ("HIGH", "Yüksek"),
                            ("VERY_HIGH", "Çok Yüksek"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Genel Risk Seviyesi",
                    ),
                ),
                (
                    "potential_financial_impact",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Potansiyel Mali Etki",
                    ),
                ),
                (
                    "existing_controls",
                    models.TextField(blank=True, verbose_name="Mevcut Kontroller"),
                ),
                (
                    "control_effectiveness",
                    models.CharField(
                        choices=[
                            ("VERY_LOW", "Çok Düşük"),
                            ("LOW", "Düşük"),
                            ("MEDIUM", "Orta"),
                            ("HIGH", "Yüksek"),
                            ("VERY_HIGH", "Çok Yüksek"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                        verbose_name="Kontrol Etkinliği",
                    ),
                ),
                (
                    "recommended_actions",
                    models.TextField(blank=True, verbose_name="Önerilen Aksiyonlar"),
                ),
                (
                    "action_priority",
                    models.CharField(
                        choices=[
                            ("VERY_LOW", "Çok Düşük"),
                            ("LOW", "Düşük"),
                            ("MEDIUM", "Orta"),
                            ("HIGH", "Yüksek"),
                            ("VERY_HIGH", "Çok Yüksek"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                        verbose_name="Aksiyon Önceliği",
                    ),
                ),
                (
                    "target_completion_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Hedef Tamamlanma Tarihi"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IDENTIFIED", "Tespit Edildi"),
                            ("UNDER_REVIEW", "İncelemede"),
                            ("ACTION_PLANNED", "Aksiyon Planlandı"),
                            ("IN_PROGRESS", "Devam Ediyor"),
                            ("MITIGATED", "Azaltıldı"),
                            ("ACCEPTED", "Kabul Edildi"),
                            ("CLOSED", "Kapatıldı"),
                        ],
                        default="IDENTIFIED",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "next_review_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Sonraki İnceleme Tarihi"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Değerlendiren",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_assessments",
                        to="accounting.company",
                    ),
                ),
                (
                    "responsible_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_risks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Sorumlu Kişi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Risk Değerlendirmesi",
                "verbose_name_plural": "Risk Değerlendirmeleri",
                "ordering": ["-assessment_date"],
            },
        ),
        migrations.AddField(
            model_name="controlactivity",
            name="risk_assessment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="control_activities",
                to="finance.riskassessment",
                verbose_name="İlgili Risk",
            ),
        ),
        migrations.CreateModel(
            name="UserPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "module_name",
                    models.CharField(
                        help_text="accounting, finance, inventory vb.",
                        max_length=100,
                        verbose_name="Modül Adı",
                    ),
                ),
                (
                    "permission_type",
                    models.CharField(
                        choices=[
                            ("READ", "Okuma"),
                            ("CREATE", "Oluşturma"),
                            ("UPDATE", "Güncelleme"),
                            ("DELETE", "Silme"),
                            ("APPROVE", "Onaylama"),
                            ("EXPORT", "Dışa Aktarma"),
                            ("REPORT", "Raporlama"),
                            ("ADMIN", "Yönetici"),
                        ],
                        max_length=20,
                        verbose_name="İzin Tipi",
                    ),
                ),
                (
                    "amount_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Bu tutarın üstündeki işlemlerde izin yok",
                        max_digits=15,
                        null=True,
                        verbose_name="Tutar Limiti",
                    ),
                ),
                (
                    "date_restriction",
                    models.CharField(
                        blank=True,
                        help_text="current_month, last_3_months, current_year vb.",
                        max_length=50,
                        verbose_name="Tarih Kısıtı",
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Geçerlilik Başlangıcı",
                    ),
                ),
                (
                    "valid_to",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Geçerlilik Bitişi"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "granted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="İzin Verme Zamanı"
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="Gerekçe")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_permissions",
                        to="accounting.company",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_permissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="İzin Veren",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Kullanıcı İzni",
                "verbose_name_plural": "Kullanıcı İzinleri",
            },
        ),
        migrations.DeleteModel(
            name="ChartOfAccounts",
        ),
        # Ensure dependent model is removed before deleting FiscalPeriod it references
        migrations.DeleteModel(
            name="TrialBalanceSnapshot",
        ),
        migrations.DeleteModel(
            name="CostCenter",
        ),
        migrations.DeleteModel(
            name="DepreciationEntry",
        ),
        migrations.DeleteModel(
            name="DepreciationMethod",
        ),
        migrations.DeleteModel(
            name="FiscalPeriod",
        ),
        migrations.DeleteModel(
            name="FixedAsset",
        ),
        migrations.DeleteModel(
            name="InventoryItem",
        ),
        migrations.DeleteModel(
            name="JournalEntry",
        ),
        migrations.DeleteModel(
            name="JournalVoucher",
        ),
        migrations.DeleteModel(
            name="StockMovement",
        ),
        migrations.DeleteModel(
            name="TaxRate",
        ),
        migrations.AddIndex(
            model_name="audittrail",
            index=models.Index(
                fields=["company", "timestamp"], name="finance_aud_company_caa4a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="audittrail",
            index=models.Index(
                fields=["user", "timestamp"], name="finance_aud_user_id_fc822e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="audittrail",
            index=models.Index(
                fields=["table_name", "record_id"],
                name="finance_aud_table_n_27c0f1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="audittrail",
            index=models.Index(
                fields=["action_type", "timestamp"],
                name="finance_aud_action__3dec66_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="audittrail",
            index=models.Index(
                fields=["risk_level", "timestamp"],
                name="finance_aud_risk_le_6adac6_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userpermission",
            unique_together={("user", "company", "module_name", "permission_type")},
        ),
    ]
