# Generated by Django 5.2.1 on 2025-10-08 17:32

from django.db import migrations


def noop_forward(apps, schema_editor):
    # TrialBalanceSnapshot may already be removed in 0009; nothing to do.
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0009_remove_journalentry_account_remove_taxrate_account_and_more"),
    ]

    operations = [
        migrations.RunPython(noop_forward, migrations.RunPython.noop),
    ]
