# Generated by Django 4.2.25 on 2025-11-02 10:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("accounting", "0013_alter_edefter_options_alter_edefter_created_at_and_more"),
        ("finance", "0011_chartofaccounts_depreciationmethod_fiscalperiod_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userpermission",
            unique_together={("user", "company", "module_name", "permission_type")},
        ),
    ]
