# Generated by Django 5.2.7 on 2025-11-02 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0012_add_internal_control_models"),
    ]

    operations = []
