# Generated by Django 4.2.25 on 2025-11-02 13:46

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("finance", "0015_fix_trialbalancesnapshot_user_reference"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("name", models.CharField(max_length=100, verbose_name="Metrik Adı")),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("LIQUIDITY", "Likidite"),
                            ("PROFITABILITY", "Karlılık"),
                            ("EFFICIENCY", "Verimlilik"),
                            ("LEVERAGE", "Kaldıraç"),
                            ("MARKET", "Piyasa"),
                        ],
                        max_length=20,
                        verbose_name="Metrik Tipi",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=4, max_digits=15, verbose_name="Değer"
                    ),
                ),
                (
                    "benchmark_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=15,
                        null=True,
                        verbose_name="Referans Değer",
                    ),
                ),
                ("period_start", models.DateField(verbose_name="Dönem Başlangıç")),
                ("period_end", models.DateField(verbose_name="Dönem Bitiş")),
                ("formula", models.TextField(blank=True, verbose_name="Formül")),
                (
                    "calculation_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Hesaplama Verisi"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notlar")),
            ],
            options={
                "verbose_name": "Finansal Metrik",
                "verbose_name_plural": "Finansal Metrikler",
                "ordering": ["-period_end", "metric_type"],
            },
        ),
        migrations.CreateModel(
            name="PaymentTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("name", models.CharField(max_length=100, verbose_name="Vade Adı")),
                (
                    "term_type",
                    models.CharField(
                        choices=[
                            ("NET", "Net"),
                            ("EOM", "Ay Sonu"),
                            ("COD", "Teslimatta Ödeme"),
                            ("CBD", "Nakit İndirimli"),
                            ("INSTALLMENT", "Taksitli"),
                        ],
                        max_length=20,
                        verbose_name="Vade Tipi",
                    ),
                ),
                ("days", models.IntegerField(default=0, verbose_name="Gün")),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="İndirim Oranı",
                    ),
                ),
                (
                    "discount_days",
                    models.IntegerField(default=0, verbose_name="İndirim Günü"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
            ],
            options={
                "verbose_name": "Ödeme Vadesi",
                "verbose_name_plural": "Ödeme Vadeleri",
                "ordering": ["days"],
            },
        ),
        migrations.CreateModel(
            name="RecurringTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("name", models.CharField(max_length=200, verbose_name="İşlem Adı")),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("INCOME", "Gelir"),
                            ("EXPENSE", "Gider"),
                            ("TRANSFER", "Transfer"),
                        ],
                        max_length=20,
                        verbose_name="İşlem Tipi",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Tutar"
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Günlük"),
                            ("weekly", "Haftalık"),
                            ("biweekly", "2 Haftada Bir"),
                            ("monthly", "Aylık"),
                            ("quarterly", "3 Aylık"),
                            ("semiannually", "6 Aylık"),
                            ("annually", "Yıllık"),
                        ],
                        max_length=20,
                        verbose_name="Sıklık",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Başlangıç Tarihi")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Bitiş Tarihi"
                    ),
                ),
                ("next_occurrence", models.DateField(verbose_name="Sonraki Oluşum")),
                (
                    "is_paused",
                    models.BooleanField(default=False, verbose_name="Duraklatıldı"),
                ),
                (
                    "last_executed",
                    models.DateField(
                        blank=True, null=True, verbose_name="Son Çalıştırma"
                    ),
                ),
                (
                    "execution_count",
                    models.IntegerField(default=0, verbose_name="Çalıştırma Sayısı"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="finance.account",
                        verbose_name="Hesap",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="finance.transactioncategory",
                        verbose_name="Kategori",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tekrarlayan İşlem",
                "verbose_name_plural": "Tekrarlayan İşlemler",
                "ordering": ["next_occurrence"],
            },
        ),
        migrations.CreateModel(
            name="Reconciliation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "reconciliation_type",
                    models.CharField(
                        choices=[
                            ("BANK", "Banka Mutabakatı"),
                            ("SUPPLIER", "Tedarikçi Mutabakatı"),
                            ("CUSTOMER", "Müşteri Mutabakatı"),
                            ("INVENTORY", "Stok Mutabakatı"),
                            ("ACCOUNT", "Hesap Mutabakatı"),
                        ],
                        max_length=20,
                        verbose_name="Mutabakat Tipi",
                    ),
                ),
                ("period_start", models.DateField(verbose_name="Dönem Başlangıç")),
                ("period_end", models.DateField(verbose_name="Dönem Bitiş")),
                (
                    "system_balance",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Sistem Bakiyesi"
                    ),
                ),
                (
                    "statement_balance",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Ekstre Bakiyesi"
                    ),
                ),
                (
                    "difference",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Fark"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Beklemede"),
                            ("IN_PROGRESS", "Devam Ediyor"),
                            ("COMPLETED", "Tamamlandı"),
                            ("DISCREPANCY", "Uyuşmazlık"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "reconciliation_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Mutabakat Verisi"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notlar")),
                (
                    "reconciled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Mutabakat Tarihi"
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="finance.account",
                        verbose_name="Hesap",
                    ),
                ),
                (
                    "reconciled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Mutabakat Yapan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mutabakat",
                "verbose_name_plural": "Mutabakatlar",
                "ordering": ["-period_end"],
            },
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "loan_name",
                    models.CharField(max_length=200, verbose_name="Kredi Adı"),
                ),
                (
                    "loan_type",
                    models.CharField(
                        choices=[
                            ("BUSINESS", "İşletme Kredisi"),
                            ("INVESTMENT", "Yatırım Kredisi"),
                            ("MORTGAGE", "İpotek"),
                            ("PERSONAL", "Tüketici Kredisi"),
                            ("CREDIT_LINE", "Kredi Limiti"),
                            ("OTHER", "Diğer"),
                        ],
                        max_length=20,
                        verbose_name="Kredi Tipi",
                    ),
                ),
                ("lender", models.CharField(max_length=200, verbose_name="Borç Veren")),
                (
                    "principal_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Ana Para"
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Faiz Oranı (%)"
                    ),
                ),
                ("loan_date", models.DateField(verbose_name="Kredi Tarihi")),
                ("maturity_date", models.DateField(verbose_name="Vade Tarihi")),
                (
                    "payment_frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Günlük"),
                            ("weekly", "Haftalık"),
                            ("biweekly", "2 Haftada Bir"),
                            ("monthly", "Aylık"),
                            ("quarterly", "3 Aylık"),
                            ("semiannually", "6 Aylık"),
                            ("annually", "Yıllık"),
                        ],
                        max_length=20,
                        verbose_name="Ödeme Sıklığı",
                    ),
                ),
                (
                    "installment_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Taksit Tutarı"
                    ),
                ),
                (
                    "outstanding_balance",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Kalan Bakiye"
                    ),
                ),
                (
                    "total_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Toplam Ödenen",
                    ),
                ),
                (
                    "total_interest_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Ödenen Faiz",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Aktif"),
                            ("PAID", "Ödendi"),
                            ("DEFAULTED", "Temerrüt"),
                            ("RESTRUCTURED", "Yeniden Yapılandırıldı"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notlar")),
                (
                    "liability_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="finance.account",
                        verbose_name="Borç Hesabı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kredi",
                "verbose_name_plural": "Krediler",
                "ordering": ["-loan_date"],
            },
        ),
        migrations.CreateModel(
            name="Investment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "investment_name",
                    models.CharField(max_length=200, verbose_name="Yatırım Adı"),
                ),
                (
                    "investment_type",
                    models.CharField(
                        choices=[
                            ("STOCK", "Hisse Senedi"),
                            ("BOND", "Tahvil"),
                            ("MUTUAL_FUND", "Yatırım Fonu"),
                            ("REAL_ESTATE", "Gayrimenkul"),
                            ("COMMODITY", "Emtia"),
                            ("CRYPTO", "Kripto Para"),
                            ("DEPOSIT", "Mevduat"),
                            ("OTHER", "Diğer"),
                        ],
                        max_length=20,
                        verbose_name="Yatırım Tipi",
                    ),
                ),
                ("purchase_date", models.DateField(verbose_name="Alım Tarihi")),
                (
                    "purchase_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Alım Fiyatı"
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("1.00"),
                        max_digits=15,
                        verbose_name="Miktar",
                    ),
                ),
                (
                    "current_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Güncel Fiyat"
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Toplam Maliyet"
                    ),
                ),
                (
                    "current_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Güncel Değer"
                    ),
                ),
                (
                    "unrealized_gain_loss",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Gerçekleşmemiş Kar/Zarar",
                    ),
                ),
                (
                    "return_percentage",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Getiri (%)"
                    ),
                ),
                (
                    "sale_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Satış Tarihi"
                    ),
                ),
                (
                    "sale_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Satış Fiyatı",
                    ),
                ),
                (
                    "realized_gain_loss",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Gerçekleşen Kar/Zarar",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notlar")),
                (
                    "investment_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="finance.account",
                        verbose_name="Yatırım Hesabı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yatırım",
                "verbose_name_plural": "Yatırımlar",
                "ordering": ["-purchase_date"],
            },
        ),
        migrations.CreateModel(
            name="AssetDepreciation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "asset_name",
                    models.CharField(max_length=200, verbose_name="Varlık Adı"),
                ),
                ("purchase_date", models.DateField(verbose_name="Satın Alma Tarihi")),
                (
                    "purchase_cost",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Satın Alma Maliyeti",
                    ),
                ),
                (
                    "salvage_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Hurda Değeri",
                    ),
                ),
                (
                    "useful_life_years",
                    models.IntegerField(verbose_name="Faydalı Ömür (Yıl)"),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("STRAIGHT_LINE", "Doğrusal Amortisman"),
                            ("DECLINING_BALANCE", "Azalan Bakiyeler"),
                            ("SUM_OF_YEARS", "Yıllar Toplamı"),
                            ("UNITS_OF_PRODUCTION", "Üretim Miktarı"),
                        ],
                        default="STRAIGHT_LINE",
                        max_length=30,
                        verbose_name="Amortisman Yöntemi",
                    ),
                ),
                (
                    "annual_depreciation",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Yıllık Amortisman",
                    ),
                ),
                (
                    "accumulated_depreciation",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Birikmiş Amortisman",
                    ),
                ),
                (
                    "book_value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Net Defter Değeri",
                    ),
                ),
                (
                    "is_fully_depreciated",
                    models.BooleanField(
                        default=False, verbose_name="Tamamen Amortismana Tabi Tutuldu"
                    ),
                ),
                (
                    "last_depreciation_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Son Amortisman Tarihi"
                    ),
                ),
                (
                    "accumulated_depreciation_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accumulated_depreciation",
                        to="finance.account",
                        verbose_name="Birikmiş Amortisman Hesabı",
                    ),
                ),
                (
                    "asset_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asset_depreciation",
                        to="finance.account",
                        verbose_name="Varlık Hesabı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Amortisman",
                "verbose_name_plural": "Amortismanlar",
                "ordering": ["purchase_date"],
            },
        ),
    ]
