# Generated by Django 5.2.8 on 2025-12-15 11:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0016_financialmetric_paymentterm_recurringtransaction_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={
                "ordering": ["code"],
                "verbose_name": "Finans Hesabı",
                "verbose_name_plural": "Finans Hesapları",
            },
        ),
        migrations.AlterModelOptions(
            name="invoice",
            options={
                "ordering": ["-issue_date"],
                "verbose_name": "Finans Faturası",
                "verbose_name_plural": "Finans Faturaları",
            },
        ),
        migrations.AlterModelOptions(
            name="securityincident",
            options={
                "ordering": ["-detected_date"],
                "verbose_name": "Finans Güvenlik Olayı",
                "verbose_name_plural": "Finans Güvenlik Olayları",
            },
        ),
    ]
