# Generated by Django 4.2.23 on 2025-09-01 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounting", "0006_invoice_e_archive"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankStatement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("period_start", models.DateField(verbose_name="Dönem Başlangıç")),
                ("period_end", models.DateField(verbose_name="Dönem Bitiş")),
                (
                    "opening_balance",
                    models.DecimalField(decimal_places=2, max_digits=15, verbose_name="Açılış Bakiyesi"),
                ),
                (
                    "closing_balance",
                    models.DecimalField(decimal_places=2, max_digits=15, verbose_name="Kapanış Bakiyesi"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statements",
                        to="accounting.bankaccount",
                        verbose_name="Banka Hesabı",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_statements",
                        to="accounting.company",
                        verbose_name="Şirket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Banka Ekstresi",
                "verbose_name_plural": "Banka Ekstreleri",
                "ordering": ["-period_start"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseInvoice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("invoice_number", models.CharField(max_length=50, unique=True, verbose_name="Fatura Numarası")),
                ("issue_date", models.DateField(verbose_name="Fatura Tarihi")),
                ("due_date", models.DateField(blank=True, null=True, verbose_name="Vade Tarihi")),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Toplam Tutar")),
                ("currency", models.CharField(default="TRY", max_length=10, verbose_name="Para Birimi")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Açıklama")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Taslak"),
                            ("APPROVED", "Onaylandı"),
                            ("PAID", "Ödendi"),
                            ("CANCELED", "İptal Edildi"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif mi?")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Güncellenme")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_invoices",
                        to="accounting.company",
                        verbose_name="Şirket",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_purchase_invoices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan Kullanıcı",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_purchase_invoices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Güncelleyen Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alış Faturası",
                "verbose_name_plural": "Alış Faturaları",
                "ordering": ["-issue_date"],
            },
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Tedarikçi Adı")),
                ("tax_number", models.CharField(blank=True, max_length=20, null=True, verbose_name="Vergi Numarası")),
                ("email", models.EmailField(blank=True, max_length=254, null=True, verbose_name="E-posta")),
                ("phone", models.CharField(blank=True, max_length=20, null=True, verbose_name="Telefon")),
                ("address", models.TextField(blank=True, null=True, verbose_name="Adres")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif mi?")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Güncellenme")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendors",
                        to="accounting.company",
                        verbose_name="Şirket",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_vendors",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan Kullanıcı",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_vendors",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Güncelleyen Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tedarikçi",
                "verbose_name_plural": "Tedarikçiler",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="payment",
            name="approved",
            field=models.BooleanField(default=False, verbose_name="Onaylandı mı?"),
        ),
        migrations.AddField(
            model_name="payment",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Onay Zamanı"),
        ),
        migrations.AddField(
            model_name="payment",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_payments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Onaylayan",
            ),
        ),
        migrations.CreateModel(
            name="VendorPayment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Ödeme Tutarı")),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("NAKIT", "Nakit"),
                            ("KREDIKARTI", "Kredi Kartı"),
                            ("BANKA", "Banka Transferi"),
                            ("CEK", "Çek"),
                            ("DIGER", "Diğer"),
                        ],
                        max_length=20,
                        verbose_name="Ödeme Yöntemi",
                    ),
                ),
                ("payment_date", models.DateField(auto_now_add=True, verbose_name="Ödeme Tarihi")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Açıklama")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif mi?")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_payments",
                        to="accounting.company",
                        verbose_name="Şirket",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_vendor_payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan Kullanıcı",
                    ),
                ),
                (
                    "related_invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="accounting.purchaseinvoice",
                        verbose_name="İlgili Fatura",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_vendor_payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Güncelleyen Kullanıcı",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="accounting.vendor",
                        verbose_name="Tedarikçi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tedarikçi Ödemesi",
                "verbose_name_plural": "Tedarikçi Ödemeleri",
                "ordering": ["-payment_date"],
            },
        ),
        migrations.AddField(
            model_name="purchaseinvoice",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_invoices",
                to="accounting.vendor",
                verbose_name="Tedarikçi",
            ),
        ),
        migrations.CreateModel(
            name="BankStatementLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(verbose_name="Tarih")),
                ("description", models.CharField(blank=True, max_length=255, null=True, verbose_name="Açıklama")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15, verbose_name="Tutar")),
                (
                    "matched_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matched_statement_lines",
                        to="accounting.banktransaction",
                        verbose_name="Eşleşen Hareket",
                    ),
                ),
                (
                    "statement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="accounting.bankstatement",
                        verbose_name="Ekstre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Banka Ekstresi Satırı",
                "verbose_name_plural": "Banka Ekstresi Satırları",
                "ordering": ["date", "id"],
            },
        ),
    ]
