# Generated by Django 4.2.25 on 2025-11-03 16:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_errorlog"),
        ("common", "0003_webhook_systemsetting_emailtemplate_apikey_and_more"),
    ]

    operations = []
