# Generated by Django 4.2.25 on 2025-11-03 17:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0004_merge_20251103_1945"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="errorlog",
            new_name="common_erro_last_se_f451b4_idx",
            old_name="common_erro_last_se_idx",
        ),
        migrations.RenameIndex(
            model_name="errorlog",
            new_name="common_erro_severit_152af9_idx",
            old_name="common_erro_severit_idx",
        ),
        migrations.RenameIndex(
            model_name="errorlog",
            new_name="common_erro_error_t_2a8549_idx",
            old_name="common_erro_error_t_idx",
        ),
    ]
