# Generated by Django 5.2.7 on 2025-11-06 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "common",
            "0005_rename_common_erro_last_se_idx_common_erro_last_se_f451b4_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="Konu")),
                ("message", models.TextField(verbose_name="Mesaj")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Düşük"),
                            ("normal", "Normal"),
                            ("high", "Yüksek"),
                            ("urgent", "Acil"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="Öncelik",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Açık"),
                            ("in_progress", "İşleniyor"),
                            ("waiting_user", "Kullanıcı Yanıtı Bekleniyor"),
                            ("resolved", "Çözüldü"),
                            ("closed", "Kapatıldı"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                ("resolution", models.TextField(blank=True, verbose_name="Çözüm")),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Çözüm Tarihi"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Adresi"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Güncellenme"),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tickets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atanan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_tickets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Destek Talebi",
                "verbose_name_plural": "Destek Talepleri",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="common_supp_status_9c5431_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="common_supp_user_id_576097_idx",
                    ),
                    models.Index(
                        fields=["priority", "status"],
                        name="common_supp_priorit_16bf9b_idx",
                    ),
                ],
            },
        ),
    ]
