# Generated by Django 5.2.8 on 2025-12-15 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0006_supportticket"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BetaCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Kampanya Adı")),
                (
                    "slug",
                    models.SlugField(max_length=200, unique=True, verbose_name="Slug"),
                ),
                ("description", models.TextField(verbose_name="Açıklama")),
                (
                    "title",
                    models.CharField(
                        help_text="Örn: Beta Kullanıcısı Olun, Şirket Ortağı Olun!",
                        max_length=200,
                        verbose_name="Başlık",
                    ),
                ),
                (
                    "short_description",
                    models.CharField(
                        help_text="Örn: 2 ay ücretsiz Pro paket + 1 şirket hissesi + Beta Pioneer rozeti + %20 kalıcı indirim",
                        max_length=500,
                        verbose_name="Kısa Açıklama",
                    ),
                ),
                (
                    "discount_percent",
                    models.IntegerField(
                        default=20,
                        help_text="Kalıcı indirim yüzdesi (örn: 20 = %20)",
                        verbose_name="İndirim Yüzdesi",
                    ),
                ),
                (
                    "free_months",
                    models.IntegerField(
                        default=2,
                        help_text="Kaç ay ücretsiz erişim verilecek",
                        verbose_name="Ücretsiz Ay Sayısı",
                    ),
                ),
                (
                    "company_shares",
                    models.IntegerField(
                        default=1,
                        help_text="Verilecek şirket hissesi sayısı",
                        verbose_name="Şirket Hissesi Sayısı",
                    ),
                ),
                (
                    "includes_badge",
                    models.BooleanField(
                        default=True,
                        help_text="Beta Pioneer rozeti verilecek mi?",
                        verbose_name="Beta Rozeti Dahil",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Taslak"),
                            ("scheduled", "Zamanlanmış"),
                            ("active", "Aktif"),
                            ("paused", "Duraklatıldı"),
                            ("ended", "Sonlandı"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Kampanyanın başlayacağı tarih (boş bırakılırsa hemen başlar)",
                        null=True,
                        verbose_name="Başlangıç Tarihi",
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Kampanyanın biteceği tarih (boş bırakılırsa süresiz)",
                        null=True,
                        verbose_name="Bitiş Tarihi",
                    ),
                ),
                (
                    "publish_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Kampanyanın yayınlanacağı tarih (zamanlanmış yayınlama)",
                        null=True,
                        verbose_name="Yayınlanma Tarihi",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Kampanya aktif mi?",
                        verbose_name="Aktif",
                    ),
                ),
                (
                    "show_on_homepage",
                    models.BooleanField(
                        default=True,
                        help_text="Ana sayfada kampanya banner'ı gösterilsin mi?",
                        verbose_name="Ana Sayfada Göster",
                    ),
                ),
                (
                    "show_on_plans",
                    models.BooleanField(
                        default=True,
                        help_text="Planlar sayfasında kampanya gösterilsin mi?",
                        verbose_name="Planlar Sayfasında Göster",
                    ),
                ),
                (
                    "show_on_registration",
                    models.BooleanField(
                        default=True,
                        help_text="Kayıt sayfasında kampanya gösterilsin mi?",
                        verbose_name="Kayıt Sayfasında Göster",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Güncellenme"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_campaigns",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_campaigns",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Güncelleyen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Beta Kampanyası",
                "verbose_name_plural": "Beta Kampanyaları",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "is_active"],
                        name="common_beta_status_2fd714_idx",
                    ),
                    models.Index(
                        fields=["start_date", "end_date"],
                        name="common_beta_start_d_a2895f_idx",
                    ),
                    models.Index(
                        fields=["publish_at"], name="common_beta_publish_9088f2_idx"
                    ),
                ],
            },
        ),
    ]
