# Generated by Django 4.2.25 on 2025-11-02 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blockchain", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "locked_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Varlık Bakiyesi",
                "verbose_name_plural": "Varlık Bakiyeleri",
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("create", "Oluşturma"),
                            ("update", "Güncelleme"),
                            ("delete", "Silme"),
                            ("verify", "Doğrulama"),
                            ("transfer", "Transfer"),
                            ("execute", "Sözleşme Çalıştırma"),
                        ],
                        max_length=20,
                    ),
                ),
                ("target_model", models.CharField(max_length=50)),
                ("target_id", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("metadata", models.JSONField(default=dict)),
            ],
            options={
                "verbose_name": "Denetim Logu",
                "verbose_name_plural": "Denetim Logları",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("block_number", models.IntegerField(db_index=True, unique=True)),
                ("previous_hash", models.CharField(db_index=True, max_length=64)),
                (
                    "block_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("nonce", models.IntegerField(default=0)),
                ("merkle_root", models.CharField(blank=True, max_length=64)),
                ("transactions_count", models.IntegerField(default=0)),
                ("is_valid", models.BooleanField(default=True)),
                ("difficulty", models.IntegerField(default=4)),
                ("data", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Blok",
                "verbose_name_plural": "Bloklar",
                "ordering": ["-block_number"],
            },
        ),
        migrations.CreateModel(
            name="DigitalAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("asset_name", models.CharField(max_length=100)),
                ("asset_symbol", models.CharField(max_length=10)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("utility", "Utility Token"),
                            ("security", "Security Token"),
                            ("nft", "NFT"),
                            ("currency", "Currency Token"),
                            ("governance", "Governance Token"),
                        ],
                        max_length=20,
                    ),
                ),
                ("total_supply", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "circulating_supply",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("metadata", models.JSONField(default=dict)),
            ],
            options={
                "verbose_name": "Dijital Varlık",
                "verbose_name_plural": "Dijital Varlıklar",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SmartContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_address",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("contract_name", models.CharField(max_length=100)),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("invoice_auto", "Otomatik Faturalama"),
                            ("payment_schedule", "Ödeme Planı"),
                            ("multi_signature", "Çoklu İmza"),
                            ("escrow", "Emanet"),
                            ("subscription", "Abonelik"),
                            ("custom", "Özel"),
                        ],
                        max_length=30,
                    ),
                ),
                ("code", models.TextField(help_text="Sözleşme kodu (JSON/Python)")),
                (
                    "abi",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Application Binary Interface",
                    ),
                ),
                (
                    "deployed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("execution_count", models.IntegerField(default=0)),
                ("last_executed", models.DateTimeField(blank=True, null=True)),
                ("parameters", models.JSONField(default=dict)),
            ],
            options={
                "verbose_name": "Akıllı Sözleşme",
                "verbose_name_plural": "Akıllı Sözleşmeler",
                "ordering": ["-deployed_at"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("invoice", "Fatura"),
                            ("payment", "Ödeme"),
                            ("expense", "Gider"),
                            ("voucher", "Fiş"),
                            ("contract", "Akıllı Sözleşme"),
                            ("asset_transfer", "Varlık Transferi"),
                            ("audit", "Denetim Kaydı"),
                            ("edefter", "E-Defter"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("from_address", models.CharField(max_length=255)),
                ("to_address", models.CharField(max_length=255)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("payload", models.JSONField(default=dict)),
                ("payload_hash", models.CharField(db_index=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Beklemede"),
                            ("confirmed", "Onaylandı"),
                            ("failed", "Başarısız"),
                            ("cancelled", "İptal Edildi"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "gas_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("signature", models.TextField(blank=True)),
                ("reference_model", models.CharField(blank=True, max_length=50)),
                ("reference_id", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AlterModelOptions(
            name="chainrecord",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Zincir Kaydı",
                "verbose_name_plural": "Zincir Kayıtları",
            },
        ),
        migrations.AddField(
            model_name="chainrecord",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chainrecord",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_chain_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="chainrecord",
            name="reference",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name="chainrecord",
            index=models.Index(
                fields=["reference", "hash_hex"], name="blockchain__referen_a69878_idx"
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="block",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="blockchain.block",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="smartcontract",
            name="deployed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="digitalasset",
            name="contract",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="blockchain.smartcontract",
            ),
        ),
        migrations.AddField(
            model_name="digitalasset",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_assets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="block",
            name="mined_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mined_blocks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="blockchain.transaction",
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blockchain_audit_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="assetbalance",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="blockchain.digitalasset",
            ),
        ),
        migrations.AddField(
            model_name="assetbalance",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asset_balances",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chainrecord",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chain_records",
                to="blockchain.transaction",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["transaction_type", "status"],
                name="blockchain__transac_978433_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["timestamp"], name="blockchain__timesta_8ceb09_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="assetbalance",
            unique_together={("user", "asset")},
        ),
    ]
