# Generated by Django 5.2.6 on 2025-09-27 05:04

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounting", "0009_planningscenario"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SMEBenchmark",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("industry_code", models.CharField(max_length=20, verbose_name="Sektör Kodu")),
                ("industry_name", models.CharField(max_length=200, verbose_name="Sektör Adı")),
                ("company_size_category", models.CharField(max_length=50, verbose_name="Şirket Büyüklük Kategorisi")),
                (
                    "benchmark_current_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="Benchmark Cari Oran"
                    ),
                ),
                (
                    "benchmark_quick_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="Benchmark Asit Test"
                    ),
                ),
                (
                    "benchmark_debt_to_equity",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="Benchmark Borç/Özkaynak"
                    ),
                ),
                (
                    "benchmark_profit_margin",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="Benchmark Kar Marjı"
                    ),
                ),
                (
                    "benchmark_roa",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="Benchmark ROA"
                    ),
                ),
                (
                    "benchmark_roe",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="Benchmark ROE"
                    ),
                ),
                ("sample_size", models.IntegerField(verbose_name="Örneklem Büyüklüğü")),
                ("data_year", models.IntegerField(verbose_name="Veri Yılı")),
                ("last_updated", models.DateTimeField(auto_now=True, verbose_name="Son Güncelleme")),
            ],
            options={
                "verbose_name": "KOBİ Benchmark Verisi",
                "verbose_name_plural": "KOBİ Benchmark Verileri",
                "ordering": ["industry_name", "company_size_category"],
                "unique_together": {("industry_code", "company_size_category", "data_year")},
            },
        ),
        migrations.CreateModel(
            name="BudgetPlan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("budget_name", models.CharField(max_length=200, verbose_name="Bütçe Adı")),
                (
                    "budget_type",
                    models.CharField(
                        choices=[
                            ("OPERATIONAL", "Operasyonel Bütçe"),
                            ("INVESTMENT", "Yatırım Bütçesi"),
                            ("CASH_FLOW", "Nakit Akış Bütçesi"),
                            ("MASTER", "Ana Bütçe"),
                        ],
                        max_length=20,
                        verbose_name="Bütçe Türü",
                    ),
                ),
                ("fiscal_year", models.IntegerField(verbose_name="Mali Yıl")),
                ("period_start", models.DateField(verbose_name="Dönem Başlangıcı")),
                ("period_end", models.DateField(verbose_name="Dönem Sonu")),
                (
                    "planned_revenue",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15, verbose_name="Planlanan Gelir"
                    ),
                ),
                (
                    "planned_expenses",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15, verbose_name="Planlanan Gider"
                    ),
                ),
                (
                    "planned_profit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15, verbose_name="Planlanan Kar"
                    ),
                ),
                (
                    "actual_revenue",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15, verbose_name="Gerçekleşen Gelir"
                    ),
                ),
                (
                    "actual_expenses",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15, verbose_name="Gerçekleşen Gider"
                    ),
                ),
                (
                    "actual_profit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15, verbose_name="Gerçekleşen Kar"
                    ),
                ),
                (
                    "revenue_variance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15, verbose_name="Gelir Varyansı"
                    ),
                ),
                (
                    "expense_variance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15, verbose_name="Gider Varyansı"
                    ),
                ),
                (
                    "profit_variance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15, verbose_name="Kar Varyansı"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Taslak"),
                            ("APPROVED", "Onaylandı"),
                            ("ACTIVE", "Aktif"),
                            ("COMPLETED", "Tamamlandı"),
                            ("CANCELLED", "İptal Edildi"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="Notlar")),
                ("approved_at", models.DateTimeField(blank=True, null=True, verbose_name="Onay Tarihi")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma Tarihi")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Güncellenme Tarihi")),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_budgets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Onaylayan",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounting.company", verbose_name="Şirket"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bütçe Planı",
                "verbose_name_plural": "Bütçe Planları",
                "ordering": ["-fiscal_year", "-created_at"],
                "unique_together": {("company", "budget_name", "fiscal_year")},
            },
        ),
        migrations.CreateModel(
            name="CashFlowForecast",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("forecast_name", models.CharField(max_length=200, verbose_name="Tahmin Adı")),
                (
                    "forecast_type",
                    models.CharField(
                        choices=[
                            ("WEEKLY", "Haftalık"),
                            ("MONTHLY", "Aylık"),
                            ("QUARTERLY", "Çeyreklik"),
                            ("ANNUAL", "Yıllık"),
                        ],
                        max_length=20,
                        verbose_name="Tahmin Türü",
                    ),
                ),
                ("forecast_date", models.DateField(verbose_name="Tahmin Tarihi")),
                (
                    "cash_from_sales",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15, verbose_name="Satışlardan Nakit"
                    ),
                ),
                (
                    "cash_from_receivables",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15, verbose_name="Alacaklardan Nakit"
                    ),
                ),
                (
                    "cash_from_investments",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15, verbose_name="Yatırımlardan Nakit"
                    ),
                ),
                (
                    "cash_from_loans",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15, verbose_name="Kredilerden Nakit"
                    ),
                ),
                (
                    "other_cash_inflows",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15, verbose_name="Diğer Nakit Girişleri"
                    ),
                ),
                (
                    "cash_for_operations",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15, verbose_name="Operasyonel Giderler"
                    ),
                ),
                (
                    "cash_for_payroll",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15, verbose_name="Bordro Ödemeleri"
                    ),
                ),
                (
                    "cash_for_suppliers",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15, verbose_name="Tedarikçi Ödemeleri"
                    ),
                ),
                (
                    "cash_for_taxes",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15, verbose_name="Vergi Ödemeleri"
                    ),
                ),
                (
                    "cash_for_investments",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15, verbose_name="Yatırım Harcamaları"
                    ),
                ),
                (
                    "cash_for_loan_payments",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15, verbose_name="Kredi Ödemeleri"
                    ),
                ),
                (
                    "other_cash_outflows",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15, verbose_name="Diğer Nakit Çıkışları"
                    ),
                ),
                (
                    "total_cash_inflows",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15, verbose_name="Toplam Nakit Girişi"
                    ),
                ),
                (
                    "total_cash_outflows",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15, verbose_name="Toplam Nakit Çıkışı"
                    ),
                ),
                (
                    "net_cash_flow",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15, verbose_name="Net Nakit Akışı"
                    ),
                ),
                (
                    "opening_cash_balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15, verbose_name="Açılış Nakit Bakiyesi"
                    ),
                ),
                (
                    "closing_cash_balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15, verbose_name="Kapanış Nakit Bakiyesi"
                    ),
                ),
                ("cash_shortage_risk", models.BooleanField(default=False, verbose_name="Nakit Sıkışıklığı Riski")),
                (
                    "minimum_cash_threshold",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("10000.00"), max_digits=15, verbose_name="Minimum Nakit Eşiği"
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="Notlar")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma Tarihi")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Güncellenme Tarihi")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounting.company", verbose_name="Şirket"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nakit Akış Tahmini",
                "verbose_name_plural": "Nakit Akış Tahminleri",
                "ordering": ["-forecast_date", "-created_at"],
                "unique_together": {("company", "forecast_date", "forecast_type")},
            },
        ),
        migrations.CreateModel(
            name="FinancialRatio",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "ratio_category",
                    models.CharField(
                        choices=[
                            ("LIQUIDITY", "Likidite Oranları"),
                            ("ACTIVITY", "Faaliyet Oranları"),
                            ("LEVERAGE", "Kaldıraç Oranları"),
                            ("PROFITABILITY", "Karlılık Oranları"),
                            ("MARKET", "Piyasa Oranları"),
                        ],
                        max_length=20,
                        verbose_name="Oran Kategorisi",
                    ),
                ),
                ("calculation_date", models.DateField(verbose_name="Hesaplama Tarihi")),
                (
                    "current_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="Cari Oran"
                    ),
                ),
                (
                    "quick_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="Asit Test Oranı"
                    ),
                ),
                (
                    "cash_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="Nakit Oranı"
                    ),
                ),
                (
                    "inventory_turnover",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="Stok Devir Hızı"
                    ),
                ),
                (
                    "receivables_turnover",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="Alacak Devir Hızı"
                    ),
                ),
                (
                    "asset_turnover",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="Aktif Devir Hızı"
                    ),
                ),
                (
                    "debt_to_equity",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="Borç/Özkaynak"
                    ),
                ),
                (
                    "debt_to_assets",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="Borç/Aktif"
                    ),
                ),
                (
                    "equity_multiplier",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="Özkaynak Çarpanı"
                    ),
                ),
                (
                    "gross_margin",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="Brüt Kar Marjı"
                    ),
                ),
                (
                    "operating_margin",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="Faaliyet Kar Marjı"
                    ),
                ),
                (
                    "net_margin",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="Net Kar Marjı"
                    ),
                ),
                (
                    "roa",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="Aktif Karlılığı"
                    ),
                ),
                (
                    "roe",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="Özkaynak Karlılığı"
                    ),
                ),
                ("industry_benchmark", models.JSONField(blank=True, null=True, verbose_name="Sektör Benchmarkı")),
                ("peer_comparison", models.JSONField(blank=True, null=True, verbose_name="Rakip Karşılaştırması")),
                ("analysis_notes", models.TextField(blank=True, null=True, verbose_name="Analiz Notları")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma Tarihi")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Güncellenme Tarihi")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounting.company", verbose_name="Şirket"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Finansal Oran",
                "verbose_name_plural": "Finansal Oranlar",
                "ordering": ["-calculation_date", "-created_at"],
                "unique_together": {("company", "ratio_category", "calculation_date")},
            },
        ),
        migrations.CreateModel(
            name="KOBIFinancialAnalysis",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[
                            ("MONTHLY", "Aylık Analiz"),
                            ("QUARTERLY", "Çeyreklik Analiz"),
                            ("ANNUAL", "Yıllık Analiz"),
                            ("CUSTOM", "Özel Dönem"),
                        ],
                        default="MONTHLY",
                        max_length=20,
                        verbose_name="Analiz Türü",
                    ),
                ),
                ("analysis_period_start", models.DateField(verbose_name="Analiz Başlangıç Tarihi")),
                ("analysis_period_end", models.DateField(verbose_name="Analiz Bitiş Tarihi")),
                (
                    "total_revenue",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15, verbose_name="Toplam Gelir"
                    ),
                ),
                (
                    "total_expenses",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15, verbose_name="Toplam Gider"
                    ),
                ),
                (
                    "net_profit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15, verbose_name="Net Kar"
                    ),
                ),
                (
                    "total_assets",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15, verbose_name="Toplam Varlık"
                    ),
                ),
                (
                    "total_liabilities",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15, verbose_name="Toplam Borç"
                    ),
                ),
                (
                    "current_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="Cari Oran"
                    ),
                ),
                (
                    "quick_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="Asit Test Oranı"
                    ),
                ),
                (
                    "debt_to_equity_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="Borç/Özkaynak Oranı"
                    ),
                ),
                (
                    "profit_margin",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="Kar Marjı"
                    ),
                ),
                (
                    "roa",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="Aktif Karlılığı (ROA)"
                    ),
                ),
                (
                    "roe",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="Özkaynak Karlılığı (ROE)"
                    ),
                ),
                (
                    "financial_health_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True, verbose_name="Finansal Sağlık Skoru"
                    ),
                ),
                (
                    "health_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EXCELLENT", "Mükemmel"),
                            ("GOOD", "İyi"),
                            ("FAIR", "Orta"),
                            ("POOR", "Zayıf"),
                            ("CRITICAL", "Kritik"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Sağlık Durumu",
                    ),
                ),
                ("recommendations", models.TextField(blank=True, null=True, verbose_name="Öneriler")),
                ("analysis_notes", models.TextField(blank=True, null=True, verbose_name="Analiz Notları")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma Tarihi")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Güncellenme Tarihi")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounting.company", verbose_name="Şirket"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan",
                    ),
                ),
            ],
            options={
                "verbose_name": "KOBİ Finansal Analizi",
                "verbose_name_plural": "KOBİ Finansal Analizleri",
                "ordering": ["-created_at"],
                "unique_together": {("company", "analysis_period_start", "analysis_period_end")},
            },
        ),
        migrations.CreateModel(
            name="ProfitabilityAnalysis",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("analysis_name", models.CharField(max_length=200, verbose_name="Analiz Adı")),
                (
                    "analysis_dimension",
                    models.CharField(
                        choices=[
                            ("PRODUCT", "Ürün Bazlı"),
                            ("SERVICE", "Hizmet Bazlı"),
                            ("CUSTOMER", "Müşteri Bazlı"),
                            ("REGION", "Bölge Bazlı"),
                            ("CHANNEL", "Kanal Bazlı"),
                        ],
                        max_length=20,
                        verbose_name="Analiz Boyutu",
                    ),
                ),
                ("dimension_value", models.CharField(max_length=200, verbose_name="Boyut Değeri")),
                ("analysis_period_start", models.DateField(verbose_name="Analiz Başlangıç Tarihi")),
                ("analysis_period_end", models.DateField(verbose_name="Analiz Bitiş Tarihi")),
                (
                    "gross_revenue",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15, verbose_name="Brüt Gelir"
                    ),
                ),
                (
                    "discounts",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15, verbose_name="İndirimler"
                    ),
                ),
                (
                    "returns",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15, verbose_name="İadeler"
                    ),
                ),
                (
                    "net_revenue",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15, verbose_name="Net Gelir"
                    ),
                ),
                (
                    "direct_costs",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15, verbose_name="Direkt Maliyetler"
                    ),
                ),
                (
                    "indirect_costs",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15, verbose_name="Endirekt Maliyetler"
                    ),
                ),
                (
                    "total_costs",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15, verbose_name="Toplam Maliyetler"
                    ),
                ),
                (
                    "gross_profit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15, verbose_name="Brüt Kar"
                    ),
                ),
                (
                    "net_profit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15, verbose_name="Net Kar"
                    ),
                ),
                (
                    "gross_profit_margin",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="Brüt Kar Marjı %"
                    ),
                ),
                (
                    "net_profit_margin",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="Net Kar Marjı %"
                    ),
                ),
                ("units_sold", models.IntegerField(default=0, verbose_name="Satılan Birim")),
                (
                    "revenue_per_unit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15, verbose_name="Birim Başına Gelir"
                    ),
                ),
                (
                    "cost_per_unit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15, verbose_name="Birim Başına Maliyet"
                    ),
                ),
                (
                    "profit_per_unit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15, verbose_name="Birim Başına Kar"
                    ),
                ),
                ("analysis_notes", models.TextField(blank=True, null=True, verbose_name="Analiz Notları")),
                (
                    "improvement_recommendations",
                    models.TextField(blank=True, null=True, verbose_name="İyileştirme Önerileri"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma Tarihi")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Güncellenme Tarihi")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounting.company", verbose_name="Şirket"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Karlılık Analizi",
                "verbose_name_plural": "Karlılık Analizleri",
                "ordering": ["-created_at"],
                "unique_together": {
                    ("company", "analysis_dimension", "dimension_value", "analysis_period_start", "analysis_period_end")
                },
            },
        ),
    ]
