# Generated by Django 4.2.25 on 2025-10-30 19:58

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0015_remove_banktransaction_acc_banktxn_date_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("kobi_analysis", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialGoal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("goal_name", models.CharField(max_length=200, verbose_name="Hedef Adı")),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("REVENUE", "Gelir Hedefi"),
                            ("PROFIT", "Kar Hedefi"),
                            ("COST_REDUCTION", "Maliyet Azaltma"),
                            ("GROWTH", "Büyüme Hedefi"),
                            ("EFFICIENCY", "Verimlilik Hedefi"),
                        ],
                        max_length=20,
                        verbose_name="Hedef Türü",
                    ),
                ),
                ("target_amount", models.DecimalField(decimal_places=2, max_digits=15, verbose_name="Hedef Tutar")),
                (
                    "current_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15, verbose_name="Mevcut Tutar"
                    ),
                ),
                (
                    "achievement_percentage",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5, verbose_name="Başarım %"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Başlangıç Tarihi")),
                ("deadline", models.DateField(verbose_name="Termin")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Başlanmadı"),
                            ("IN_PROGRESS", "Devam Ediyor"),
                            ("COMPLETED", "Tamamlandı"),
                            ("FAILED", "Başarısız"),
                            ("CANCELLED", "İptal Edildi"),
                        ],
                        default="NOT_STARTED",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("LOW", "Düşük"), ("MEDIUM", "Orta"), ("HIGH", "Yüksek"), ("CRITICAL", "Kritik")],
                        default="MEDIUM",
                        max_length=10,
                        verbose_name="Öncelik",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True, verbose_name="Açıklama")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma Tarihi")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Güncellenme Tarihi")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounting.company", verbose_name="Şirket"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Finansal Hedef",
                "verbose_name_plural": "Finansal Hedefler",
                "ordering": ["-priority", "deadline"],
            },
        ),
        migrations.CreateModel(
            name="RiskAssessment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("risk_name", models.CharField(max_length=200, verbose_name="Risk Adı")),
                (
                    "risk_category",
                    models.CharField(
                        choices=[
                            ("FINANCIAL", "Finansal"),
                            ("OPERATIONAL", "Operasyonel"),
                            ("STRATEGIC", "Stratejik"),
                            ("COMPLIANCE", "Uyumluluk"),
                            ("REPUTATION", "İtibar"),
                            ("TECHNOLOGY", "Teknoloji"),
                        ],
                        max_length=20,
                        verbose_name="Risk Kategorisi",
                    ),
                ),
                ("description", models.TextField(verbose_name="Açıklama")),
                (
                    "likelihood",
                    models.CharField(
                        choices=[
                            ("RARE", "Çok Nadir"),
                            ("UNLIKELY", "Olası Değil"),
                            ("POSSIBLE", "Mümkün"),
                            ("LIKELY", "Muhtemel"),
                            ("ALMOST_CERTAIN", "Neredeyse Kesin"),
                        ],
                        max_length=20,
                        verbose_name="Olasılık",
                    ),
                ),
                (
                    "impact",
                    models.CharField(
                        choices=[
                            ("NEGLIGIBLE", "İhmal Edilebilir"),
                            ("MINOR", "Küçük"),
                            ("MODERATE", "Orta"),
                            ("MAJOR", "Büyük"),
                            ("CATASTROPHIC", "Felaket"),
                        ],
                        max_length=20,
                        verbose_name="Etki",
                    ),
                ),
                ("risk_score", models.IntegerField(default=0, verbose_name="Risk Skoru")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IDENTIFIED", "Tespit Edildi"),
                            ("ASSESSING", "Değerlendiriliyor"),
                            ("MITIGATING", "Önlem Alınıyor"),
                            ("MONITORING", "İzleniyor"),
                            ("CLOSED", "Kapatıldı"),
                        ],
                        default="IDENTIFIED",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                ("identified_date", models.DateField(verbose_name="Tespit Tarihi")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounting.company", verbose_name="Şirket"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kobi_risk_assessments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Risk Değerlendirmesi",
                "verbose_name_plural": "Risk Değerlendirmeleri",
            },
        ),
        migrations.AddField(
            model_name="cashflowforecast",
            name="confidence_level",
            field=models.CharField(
                choices=[("LOW", "Düşük"), ("MEDIUM", "Orta"), ("HIGH", "Yüksek")],
                default="MEDIUM",
                max_length=10,
                verbose_name="Güven Seviyesi",
            ),
        ),
        migrations.AddField(
            model_name="cashflowforecast",
            name="forecast_period_end",
            field=models.DateField(blank=True, null=True, verbose_name="Tahmin Dönemi Bitiş"),
        ),
        migrations.AddField(
            model_name="cashflowforecast",
            name="forecast_period_start",
            field=models.DateField(blank=True, null=True, verbose_name="Tahmin Dönemi Başlangıç"),
        ),
        migrations.CreateModel(
            name="SWOTAnalysis",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("analysis_date", models.DateField(verbose_name="Analiz Tarihi")),
                ("strengths", models.TextField(verbose_name="Güçlü Yönler")),
                ("weaknesses", models.TextField(verbose_name="Zayıf Yönler")),
                ("opportunities", models.TextField(verbose_name="Fırsatlar")),
                ("threats", models.TextField(verbose_name="Tehditler")),
                (
                    "strategic_recommendations",
                    models.TextField(blank=True, null=True, verbose_name="Stratejik Öneriler"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounting.company", verbose_name="Şirket"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan",
                    ),
                ),
            ],
            options={
                "verbose_name": "SWOT Analizi",
                "verbose_name_plural": "SWOT Analizleri",
            },
        ),
        migrations.CreateModel(
            name="RiskMitigation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("mitigation_action", models.CharField(max_length=200, verbose_name="Önlem Aksiyonu")),
                ("description", models.TextField(verbose_name="Açıklama")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planlandı"),
                            ("IN_PROGRESS", "Devam Ediyor"),
                            ("COMPLETED", "Tamamlandı"),
                            ("DEFERRED", "Ertelendi"),
                        ],
                        default="PLANNED",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "effectiveness",
                    models.CharField(
                        blank=True,
                        choices=[("LOW", "Düşük"), ("MEDIUM", "Orta"), ("HIGH", "Yüksek")],
                        max_length=10,
                        null=True,
                        verbose_name="Etkinlik",
                    ),
                ),
                ("deadline", models.DateField(blank=True, null=True, verbose_name="Termin")),
                (
                    "cost_estimate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True, verbose_name="Tahmini Maliyet"
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Sorumlu",
                    ),
                ),
                (
                    "risk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mitigation_plans",
                        to="kobi_analysis.riskassessment",
                        verbose_name="Risk",
                    ),
                ),
            ],
            options={
                "verbose_name": "Risk Önlemi",
                "verbose_name_plural": "Risk Önlemleri",
            },
        ),
        migrations.CreateModel(
            name="PerformanceMetric",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("metric_name", models.CharField(max_length=100, verbose_name="Metrik Adı")),
                (
                    "metric_category",
                    models.CharField(
                        choices=[
                            ("FINANCIAL", "Finansal"),
                            ("OPERATIONAL", "Operasyonel"),
                            ("CUSTOMER", "Müşteri"),
                            ("PROCESS", "Süreç"),
                            ("EMPLOYEE", "Çalışan"),
                        ],
                        max_length=20,
                        verbose_name="Kategori",
                    ),
                ),
                ("current_value", models.DecimalField(decimal_places=2, max_digits=15, verbose_name="Mevcut Değer")),
                (
                    "target_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True, verbose_name="Hedef Değer"
                    ),
                ),
                (
                    "trend",
                    models.CharField(
                        blank=True,
                        choices=[("UP", "Yükseliş"), ("DOWN", "Düşüş"), ("STABLE", "Sabit")],
                        max_length=10,
                        null=True,
                        verbose_name="Trend",
                    ),
                ),
                ("last_updated", models.DateField(verbose_name="Son Güncelleme")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounting.company", verbose_name="Şirket"
                    ),
                ),
            ],
            options={
                "verbose_name": "Performans Metriği",
                "verbose_name_plural": "Performans Metrikleri",
            },
        ),
        migrations.CreateModel(
            name="MetricTarget",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("target_period", models.DateField(verbose_name="Hedef Dönemi")),
                ("target_value", models.DecimalField(decimal_places=2, max_digits=15, verbose_name="Hedef Değer")),
                ("is_achieved", models.BooleanField(default=False, verbose_name="Başarıldı mı?")),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targets",
                        to="kobi_analysis.performancemetric",
                        verbose_name="Metrik",
                    ),
                ),
            ],
            options={
                "verbose_name": "Metrik Hedefi",
                "verbose_name_plural": "Metrik Hedefleri",
            },
        ),
        migrations.CreateModel(
            name="IndustryBenchmark",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("industry_sector", models.CharField(max_length=100, verbose_name="Sektör")),
                ("benchmark_year", models.IntegerField(verbose_name="Benchmark Yılı")),
                ("metric_name", models.CharField(max_length=100, verbose_name="Metrik Adı")),
                ("average_value", models.DecimalField(decimal_places=2, max_digits=15, verbose_name="Ortalama Değer")),
                ("top_quartile_value", models.DecimalField(decimal_places=2, max_digits=15, verbose_name="En İyi %25")),
            ],
            options={
                "verbose_name": "Sektör Benchmarkı",
                "verbose_name_plural": "Sektör Benchmarkları",
                "unique_together": {("industry_sector", "benchmark_year", "metric_name")},
            },
        ),
        migrations.CreateModel(
            name="GoalProgress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("progress_date", models.DateField(verbose_name="İlerleme Tarihi")),
                ("current_amount", models.DecimalField(decimal_places=2, max_digits=15, verbose_name="Mevcut Tutar")),
                (
                    "achievement_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5, verbose_name="Başarım %"),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="Notlar")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Kayıt Tarihi")),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_records",
                        to="kobi_analysis.financialgoal",
                        verbose_name="Hedef",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hedef İlerlemesi",
                "verbose_name_plural": "Hedef İlerlemeleri",
                "ordering": ["-progress_date"],
            },
        ),
        migrations.CreateModel(
            name="ForecastScenario",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("scenario_name", models.CharField(max_length=100, verbose_name="Senaryo Adı")),
                (
                    "scenario_type",
                    models.CharField(
                        choices=[("OPTIMISTIC", "İyimser"), ("PESSIMISTIC", "Kötümser"), ("REALISTIC", "Gerçekçi")],
                        max_length=20,
                        verbose_name="Senaryo Türü",
                    ),
                ),
                ("probability", models.DecimalField(decimal_places=2, max_digits=5, verbose_name="Olasılık %")),
                (
                    "projected_revenue",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15, verbose_name="Tahmini Gelir"
                    ),
                ),
                (
                    "projected_expenses",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15, verbose_name="Tahmini Gider"
                    ),
                ),
                (
                    "projected_profit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15, verbose_name="Tahmini Kar"
                    ),
                ),
                ("assumptions", models.TextField(blank=True, null=True, verbose_name="Varsayımlar")),
                (
                    "forecast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scenarios",
                        to="kobi_analysis.cashflowforecast",
                        verbose_name="Tahmin",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tahmin Senaryosu",
                "verbose_name_plural": "Tahmin Senaryoları",
            },
        ),
        migrations.CreateModel(
            name="FinancialHealthSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("snapshot_date", models.DateField(verbose_name="Snapshot Tarihi")),
                ("overall_score", models.DecimalField(decimal_places=2, max_digits=5, verbose_name="Genel Skor")),
                ("liquidity_score", models.DecimalField(decimal_places=2, max_digits=5, verbose_name="Likidite Skoru")),
                (
                    "profitability_score",
                    models.DecimalField(decimal_places=2, max_digits=5, verbose_name="Karlılık Skoru"),
                ),
                (
                    "solvency_score",
                    models.DecimalField(decimal_places=2, max_digits=5, verbose_name="Ödeme Gücü Skoru"),
                ),
                (
                    "efficiency_score",
                    models.DecimalField(decimal_places=2, max_digits=5, verbose_name="Verimlilik Skoru"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounting.company", verbose_name="Şirket"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sağlık Snapshot",
                "verbose_name_plural": "Sağlık Snapshots",
                "ordering": ["-snapshot_date"],
            },
        ),
        migrations.CreateModel(
            name="FinancialAlert",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("CASH_LOW", "Düşük Nakit"),
                            ("PROFIT_DECLINE", "Kar Düşüşü"),
                            ("DEBT_HIGH", "Yüksek Borç"),
                            ("EXPENSE_SPIKE", "Gider Artışı"),
                            ("REVENUE_DROP", "Gelir Düşüşü"),
                        ],
                        max_length=20,
                        verbose_name="Uyarı Türü",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[("LOW", "Düşük"), ("MEDIUM", "Orta"), ("HIGH", "Yüksek"), ("CRITICAL", "Kritik")],
                        max_length=10,
                        verbose_name="Ciddiyet",
                    ),
                ),
                ("alert_message", models.TextField(verbose_name="Uyarı Mesajı")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif mi?")),
                ("triggered_at", models.DateTimeField(auto_now_add=True, verbose_name="Tetiklenme Zamanı")),
                ("resolved_at", models.DateTimeField(blank=True, null=True, verbose_name="Çözüm Zamanı")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounting.company", verbose_name="Şirket"
                    ),
                ),
            ],
            options={
                "verbose_name": "Finansal Uyarı",
                "verbose_name_plural": "Finansal Uyarılar",
                "ordering": ["-triggered_at"],
            },
        ),
        migrations.CreateModel(
            name="CompetitorAnalysis",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("competitor_name", models.CharField(max_length=200, verbose_name="Rakip Adı")),
                ("analysis_date", models.DateField(verbose_name="Analiz Tarihi")),
                (
                    "revenue",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name="Gelir"),
                ),
                (
                    "market_share",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True, verbose_name="Pazar Payı %"
                    ),
                ),
                ("strengths", models.TextField(blank=True, null=True, verbose_name="Güçlü Yönler")),
                ("weaknesses", models.TextField(blank=True, null=True, verbose_name="Zayıf Yönler")),
                ("overall_rating", models.IntegerField(default=5, verbose_name="Genel Rating")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounting.company", verbose_name="Şirket"
                    ),
                ),
            ],
            options={
                "verbose_name": "Rakip Analizi",
                "verbose_name_plural": "Rakip Analizleri",
            },
        ),
        migrations.CreateModel(
            name="BudgetLineItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("line_item_name", models.CharField(max_length=200, verbose_name="Kalem Adı")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("REVENUE", "Gelir"),
                            ("EXPENSE", "Gider"),
                            ("ASSET", "Varlık"),
                            ("LIABILITY", "Borç"),
                        ],
                        max_length=20,
                        verbose_name="Kategori",
                    ),
                ),
                (
                    "planned_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15, verbose_name="Planlanan Tutar"
                    ),
                ),
                (
                    "actual_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15, verbose_name="Gerçekleşen Tutar"
                    ),
                ),
                (
                    "variance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15, verbose_name="Varyans"
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="Notlar")),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="kobi_analysis.budgetplan",
                        verbose_name="Bütçe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bütçe Kalemi",
                "verbose_name_plural": "Bütçe Kalemleri",
                "ordering": ["category", "line_item_name"],
            },
        ),
        migrations.CreateModel(
            name="AdvisoryReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("report_title", models.CharField(max_length=200, verbose_name="Rapor Başlığı")),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("MONTHLY", "Aylık Rapor"),
                            ("QUARTERLY", "Çeyreklik Rapor"),
                            ("ANNUAL", "Yıllık Rapor"),
                            ("CUSTOM", "Özel Rapor"),
                        ],
                        max_length=20,
                        verbose_name="Rapor Türü",
                    ),
                ),
                ("report_date", models.DateField(verbose_name="Rapor Tarihi")),
                ("content", models.TextField(verbose_name="Rapor İçeriği")),
                ("summary", models.TextField(blank=True, null=True, verbose_name="Özet")),
                ("recommendations", models.TextField(blank=True, null=True, verbose_name="Öneriler")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounting.company", verbose_name="Şirket"
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Danışmanlık Raporu",
                "verbose_name_plural": "Danışmanlık Raporları",
                "ordering": ["-report_date"],
            },
        ),
    ]
