# Generated by Django 5.2.8 on 2025-12-15 11:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kobi_analysis", "0003_workingcapitalanalysis_sensitivityanalysis_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="performancemetric",
            options={
                "verbose_name": "KOBİ Performans Metriği",
                "verbose_name_plural": "KOBİ Performans Metrikleri",
            },
        ),
    ]
