# Generated by Django 5.2.8 on 2025-11-12 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="partnerapplication",
            new_name="partners_pa_status_575fef_idx",
            old_name="partners_pa_status_0ee13f_idx",
        ),
        migrations.RenameIndex(
            model_name="partnerapplication",
            new_name="partners_pa_partner_2b0024_idx",
            old_name="partners_pa_partner_37f9d3_idx",
        ),
    ]
