global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'alerts@finasis.com'
  smtp_auth_username: 'alerts@finasis.com'
  smtp_auth_password: '${SMTP_PASSWORD}'

route:
  group_by: ['alertname', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'team-financial'

  routes:
  - match:
      severity: critical
    receiver: 'team-critical'
    group_wait: 10s
    repeat_interval: 1h

receivers:
- name: 'team-financial'
  email_configs:
  - to: 'financial-team@finasis.com'
  slack_configs:
  - api_url: '${SLACK_WEBHOOK_URL}'
    channel: '#financial-alerts'
    send_resolved: true

- name: 'team-critical'
  email_configs:
  - to: 'critical-alerts@finasis.com'
  slack_configs:
  - api_url: '${SLACK_WEBHOOK_URL}'
    channel: '#critical-alerts'
    send_resolved: true
  pagerduty_configs:
  - routing_key: '${PAGERDUTY_ROUTING_KEY}'
    send_resolved: true 