# Generated by Django 5.2.6 on 2025-09-22 20:05

import django.db.models.deletion
import src.apps.education.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0002_meeting"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingInvitation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="E-posta")),
                (
                    "token",
                    models.CharField(
                        default=src.apps.education.models.generate_invitation_token, max_length=64, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Beklemede"),
                            ("accepted", "Kabul"),
                            ("declined", "Reddet"),
                            ("canceled", "İptal"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True, verbose_name="Gönderim Tarihi")),
                ("responded_at", models.DateTimeField(blank=True, null=True, verbose_name="Yanıt Tarihi")),
                (
                    "invited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_meeting_invitations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Davet Eden",
                    ),
                ),
                (
                    "invitee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meeting_invitations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Davetli",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="education.meeting",
                        verbose_name="Toplantı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Toplantı Daveti",
                "verbose_name_plural": "Toplantı Davetleri",
                "indexes": [models.Index(fields=["token"], name="education_m_token_a3995e_idx")],
            },
        ),
    ]
