# Generated by Django 5.2.7 on 2025-10-21 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0006_meetingpresence"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="meetingpresence",
            new_name="education_m_meeting_1fbcdd_idx",
            old_name="education_meetingpresence_idx",
        ),
    ]
