# Generated by Django 5.2.6 on 2025-09-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InvestorDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("file_url", models.URLField()),
                (
                    "kind",
                    models.CharField(
                        choices=[("deck", "Sunum"), ("report", "Rapor")], max_length=50
                    ),
                ),
                ("published_at", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Yatırımcı Belgesi",
                "verbose_name_plural": "Yatırımcı Belgeleri",
                "ordering": ["-published_at", "name"],
            },
        ),
        migrations.CreateModel(
            name="PressRelease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("date", models.DateField()),
                ("summary", models.TextField(blank=True)),
                ("url", models.URLField(blank=True)),
            ],
            options={
                "verbose_name": "Basın Bülteni",
                "verbose_name_plural": "Basın Bültenleri",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("role", models.CharField(max_length=120)),
                ("department", models.CharField(blank=True, max_length=120)),
            ],
            options={
                "verbose_name": "Ekip Üyesi",
                "verbose_name_plural": "Ekip Üyeleri",
                "ordering": ["name"],
            },
        ),
    ]
