# Generated by Django 5.2.8 on 2025-12-12 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corporate", "0002_partner_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Ad Soyad")),
                ("email", models.EmailField(max_length=254, verbose_name="E-posta")),
                (
                    "company",
                    models.CharField(blank=True, max_length=200, verbose_name="Şirket"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=50, verbose_name="Telefon"),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("demo", "Demo Talebi"),
                            ("sales", "Satış Bilgisi"),
                            ("support", "Teknik Destek"),
                            ("compliance", "Uyumluluk Danışmanlığı"),
                            ("partnership", "Partnerlik"),
                            ("other", "Diğer"),
                        ],
                        default="other",
                        max_length=32,
                        verbose_name="Konu",
                    ),
                ),
                ("message", models.TextField(verbose_name="Mesaj")),
                (
                    "consent_gdpr",
                    models.BooleanField(default=False, verbose_name="KVKK onayı"),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Formun gönderildiği sayfa veya kampanya kodu.",
                        max_length=100,
                        verbose_name="Kaynak",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma"),
                ),
                (
                    "handled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="İlgilenme zamanı"
                    ),
                ),
                (
                    "is_resolved",
                    models.BooleanField(default=False, verbose_name="Tamamlandı"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="İç notlar")),
                (
                    "handled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handled_contact_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="İlgilenen kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "İletişim Mesajı",
                "verbose_name_plural": "İletişim Mesajları",
                "ordering": ("-created_at",),
            },
        ),
    ]
