# Generated by Django 5.2.8 on 2025-12-15 11:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("corporate", "0003_contactmessage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="partnerapplication",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Kurumsal Partner Başvurusu",
                "verbose_name_plural": "Kurumsal Partner Başvuruları",
            },
        ),
        migrations.AlterModelOptions(
            name="partnercategory",
            options={
                "ordering": ("priority", "name"),
                "verbose_name": "Kurumsal Partner Kategorisi",
                "verbose_name_plural": "Kurumsal Partner Kategorileri",
            },
        ),
    ]
