# Generated by Django 5.2.1 on 2025-09-11 21:00

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EducationModule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100, verbose_name="Görev Başlığı")),
                ("description", models.TextField(verbose_name="Görev Açıklaması")),
                ("points", models.PositiveIntegerField(default=10, verbose_name="Puan")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif mi?")),
            ],
            options={
                "verbose_name": "Eğitim Modülü",
                "verbose_name_plural": "Eğitim Modülleri",
            },
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "completed_modules",
                    models.ManyToManyField(
                        blank=True, to="virtual_company.educationmodule", verbose_name="Tamamlanan Görevler"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Öğrenci Profili",
                "verbose_name_plural": "Öğrenci Profilleri",
            },
        ),
        migrations.CreateModel(
            name="TeacherProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "managed_students",
                    models.ManyToManyField(
                        blank=True, to="virtual_company.studentprofile", verbose_name="Takip Ettiği Öğrenciler"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Öğretmen Profili",
                "verbose_name_plural": "Öğretmen Profilleri",
            },
        ),
        migrations.CreateModel(
            name="VirtualCompany",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Şirket Adı")),
                ("description", models.TextField(verbose_name="Şirket Açıklaması")),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12, verbose_name="Bakiye (₺)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma Tarihi")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Son Güncelleme")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_virtual_companies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Şirket Sahibi (Kullanıcı)",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="virtual_companies",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sanal Şirket",
                "verbose_name_plural": "Sanal Şirketler",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("INCOME", "Gelir"), ("EXPENSE", "Gider")], max_length=7, verbose_name="İşlem Türü"
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Tutar (₺)")),
                ("description", models.TextField(verbose_name="Açıklama")),
                ("date", models.DateField(auto_now_add=True, verbose_name="Tarih")),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="virtual_transactions",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="virtual_company.virtualcompany",
                        verbose_name="Şirket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Finansal İşlem",
                "verbose_name_plural": "Finansal İşlemler",
                "ordering": ["-date"],
            },
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="virtual_company",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="virtual_company.virtualcompany", verbose_name="Şirket"
            ),
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Ürün Adı")),
                ("description", models.TextField(verbose_name="Ürün Açıklaması")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Birim Fiyat (₺)")),
                ("stock", models.PositiveIntegerField(default=0, verbose_name="Stok Miktarı")),
                ("marker_id", models.CharField(default="hiro", max_length=50, verbose_name="Marker ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Eklenme Tarihi")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Son Güncelleme")),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="virtual_products",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="virtual_company.virtualcompany",
                        verbose_name="Bağlı Olduğu Şirket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ürün",
                "verbose_name_plural": "Ürünler",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("invoice_number", models.CharField(max_length=20, verbose_name="Fatura No")),
                ("customer_name", models.CharField(max_length=100, verbose_name="Müşteri Adı")),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Toplam Tutar (₺)")),
                ("issue_date", models.DateField(verbose_name="Fatura Tarihi")),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="virtual_invoices",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="virtual_company.virtualcompany",
                        verbose_name="Şirket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fatura",
                "verbose_name_plural": "Faturalar",
                "ordering": ["-issue_date"],
            },
        ),
        migrations.CreateModel(
            name="FinanceReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100, verbose_name="Rapor Başlığı")),
                ("content", models.TextField(verbose_name="Rapor İçeriği")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma Tarihi")),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="virtual_reports",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="virtual_company.virtualcompany",
                        verbose_name="Şirket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Finansal Rapor",
                "verbose_name_plural": "Finansal Raporlar",
            },
        ),
        migrations.CreateModel(
            name="AIAccountingRecommendation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("suggestion", models.TextField(verbose_name="Öneri Açıklaması")),
                ("confidence_score", models.FloatField(verbose_name="Tahmin Güveni (%)")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Öğrenci",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="virtual_company.virtualcompany",
                        verbose_name="Şirket",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Muhasebe Önerisi",
                "verbose_name_plural": "AI Muhasebe Önerileri",
            },
        ),
        migrations.CreateModel(
            name="AccountingEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(auto_now_add=True, verbose_name="Kayıt Tarihi")),
                ("description", models.CharField(max_length=255, verbose_name="İşlem Açıklaması")),
                ("debit_account", models.CharField(max_length=100, verbose_name="Borç Hesabı")),
                ("credit_account", models.CharField(max_length=100, verbose_name="Alacak Hesabı")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Tutar (₺)")),
                (
                    "effect_on_balance",
                    models.CharField(
                        choices=[("POSITIVE", "Pozitif"), ("NEGATIVE", "Negatif"), ("NEUTRAL", "Nötr")],
                        max_length=50,
                        verbose_name="Şirket Bakiyesine Etki",
                    ),
                ),
                ("ai_recommendation", models.TextField(blank=True, null=True, verbose_name="Yapay Zeka Önerisi")),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Öğrenci",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="virtual_entries",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="virtual_company.virtualcompany",
                        verbose_name="Şirket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Muhasebe Kaydı",
                "verbose_name_plural": "Muhasebe Kayıtları",
                "ordering": ["-date"],
            },
        ),
    ]
