# Generated by Django 4.2.25 on 2025-11-02 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_company", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyLeaderboard",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("total_revenue", models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ("total_profit", models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ("successful_transactions", models.IntegerField(default=0)),
                ("achievements_earned", models.IntegerField(default=0)),
                ("level", models.IntegerField(default=1)),
                ("experience_points", models.IntegerField(default=0)),
                ("rank", models.IntegerField(default=999)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaderboard_stats",
                        to="virtual_company.virtualcompany",
                    ),
                ),
            ],
            options={
                "verbose_name": "Liderlik Tablosu",
                "verbose_name_plural": "Liderlik Tabloları",
                "ordering": ["-total_profit", "-total_revenue"],
            },
        ),
        migrations.CreateModel(
            name="CompanyAchievement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "achievement_type",
                    models.CharField(
                        choices=[
                            ("first_sale", "İlk Satış"),
                            ("profitable", "Kârlı Şirket"),
                            ("millionaire", "Milyoner"),
                            ("top_seller", "En İyi Satıcı"),
                            ("efficient", "Verimli Yönetim"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("icon", models.CharField(default="bi-trophy", max_length=50)),
                ("points", models.IntegerField(default=100)),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to="virtual_company.virtualcompany",
                    ),
                ),
            ],
            options={
                "verbose_name": "Başarı",
                "verbose_name_plural": "Başarılar",
                "ordering": ["-earned_at"],
            },
        ),
    ]
