# Generated by Django 5.2.8 on 2025-12-15 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_company", "0002_companyleaderboard_companyachievement"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="financereport",
            options={
                "verbose_name": "Sanal Şirket Finansal Raporu",
                "verbose_name_plural": "Sanal Şirket Finansal Raporları",
            },
        ),
        migrations.AlterModelOptions(
            name="invoice",
            options={
                "ordering": ["-issue_date"],
                "verbose_name": "Sanal Şirket Faturası",
                "verbose_name_plural": "Sanal Şirket Faturaları",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Sanal Şirket Ürünü",
                "verbose_name_plural": "Sanal Şirket Ürünleri",
            },
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={
                "ordering": ["-date"],
                "verbose_name": "Sanal Şirket Finansal İşlemi",
                "verbose_name_plural": "Sanal Şirket Finansal İşlemleri",
            },
        ),
    ]
