# Generated by Django 5.2.8 on 2025-12-15 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trade_sim", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tournament",
            options={
                "verbose_name": "TradeSim Turnuvası",
                "verbose_name_plural": "TradeSim Turnuvaları",
            },
        ),
    ]
