global:
  scrape_interval: 10s
  evaluation_interval: 10s
  scrape_timeout: 5s

  external_labels:
    monitor: 'finasis-monitor'
    environment: 'production'
    region: 'europe-istanbul'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 'alertmanager:9093'
    - scheme: https
      tls_config:
        ca_file: /etc/ssl/certs/ca-certificates.crt
      basic_auth:
        username: 'prometheus'
        password: '${ALERTMANAGER_PASSWORD}'

rule_files:
  - "/etc/prometheus/rules/*.yml"

scrape_configs:
  - job_name: 'prometheus'
    honor_labels: true
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: '/metrics'
    scheme: https
    tls_config:
      cert_file: /etc/ssl/certs/prometheus.crt
      key_file: /etc/ssl/private/prometheus.key

  - job_name: 'web'
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 3s
    static_configs:
      - targets: ['web:8000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'finasis-web'
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: pod
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'http_requests_total'
        action: keep

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    params:
      format: ['prometheus']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'finasis-redis'

  - job_name: 'postgres'
    static_configs:
      - targets: ['db:5432']
    metrics_path: '/metrics'
    params:
      format: ['prometheus']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'finasis-postgres'
    tls_config:
      insecure_skip_verify: false

  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']
    metrics_path: '/metrics'
    scheme: https
    tls_config:
      cert_file: /etc/ssl/certs/traefik.crt
      key_file: /etc/ssl/private/traefik.key

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 5s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'finasis-node'

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    metrics_path: '/metrics'
    scheme: https
    tls_config:
      cert_file: /etc/ssl/certs/cadvisor.crt
      key_file: /etc/ssl/private/cadvisor.key

storage:
  tsdb:
    path: /prometheus
    retention: 15d
    wal_compression: true
    max_block_chunk_segment_size: 512MB

remote_write:
  - url: "https://thanos-receive:10908/api/v1/receive"
    queue_config:
      capacity: 2500
      max_shards: 200
      min_shards: 1
      max_samples_per_send: 500
      batch_send_deadline: 5s
    write_relabel_configs:
      - source_labels: [__name__]
        regex: expensive_metric.*
        action: drop 