apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: "5s"
      queryTimeout: "60s"
      httpMethod: "POST"

  - name: PostgreSQL
    type: postgres
    access: proxy
    url: localhost:5432
    database: finasis
    user: postgres
    jsonData:
      sslmode: "disable"
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400
      postgresVersion: 14
      timescaledb: true

  - name: Redis
    type: redis-datasource
    access: proxy
    url: localhost:6379
    jsonData:
      poolSize: 10
      timeout: 10
      pingInterval: 60

  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    jsonData:
      esVersion: 8.0.0
      timeField: "@timestamp"
      interval: Daily
      timeInterval: "1m"
      maxConcurrentShardRequests: 256
      logMessageField: "message"
      logLevelField: "level" 