# Generated by Django 5.2.1 on 2025-08-30 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_transaction_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegratedBankAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
        ),
    ]
