# Generated by Django 5.2.8 on 2025-11-11 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="İsim")),
                ("codename", models.CharField(max_length=100, verbose_name="Kod adı")),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="Açıklama"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme tarihi"
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_permissions",
                        to="contenttypes.contenttype",
                        verbose_name="İçerik tipi",
                    ),
                ),
                (
                    "django_permission",
                    models.OneToOneField(
                        blank=True,
                        help_text="Django native permission ile eşleşir.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="auth.permission",
                        verbose_name="Django Yetkisi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yetki",
                "verbose_name_plural": "Yetkiler",
                "ordering": [
                    "content_type__app_label",
                    "content_type__model",
                    "codename",
                ],
                "unique_together": {("content_type", "codename")},
            },
        ),
        migrations.CreateModel(
            name="PermissionGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Grup Adı"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "is_system",
                    models.BooleanField(default=False, verbose_name="Sistem Grubu"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="groups",
                        to="permissions.permission",
                        verbose_name="Yetkiler",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yetki Grubu",
                "verbose_name_plural": "Yetki Grupları",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="İsim")),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="Açıklama"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("SYSTEM", "Sistem"),
                            ("GAME", "Oyun"),
                            ("CUSTOM", "Özel"),
                        ],
                        default="CUSTOM",
                        max_length=10,
                        verbose_name="Rol Tipi",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme tarihi"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="permissions.role",
                        verbose_name="Üst Rol",
                    ),
                ),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True, to="permissions.permission", verbose_name="Yetkiler"
                    ),
                ),
            ],
            options={
                "verbose_name": "Rol",
                "verbose_name_plural": "Roller",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TemporaryPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(verbose_name="Geçerlilik Başlangıcı"),
                ),
                ("valid_until", models.DateTimeField(verbose_name="Geçerlilik Bitişi")),
                ("reason", models.TextField(verbose_name="Sebep")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "is_revoked",
                    models.BooleanField(default=False, verbose_name="İptal Edildi"),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="İptal Tarihi"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_temp_permissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Onaylayan",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="permissions.permission",
                        verbose_name="Yetki",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temporary_permissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Geçici Yetki",
                "verbose_name_plural": "Geçici Yetkiler",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PermissionAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("GRANTED", "Verildi"),
                            ("REVOKED", "İptal Edildi"),
                            ("MODIFIED", "Değiştirildi"),
                            ("CHECKED", "Kontrol Edildi"),
                            ("DENIED", "Reddedildi"),
                        ],
                        max_length=20,
                        verbose_name="Aksiyon",
                    ),
                ),
                (
                    "resource",
                    models.CharField(blank=True, max_length=200, verbose_name="Kaynak"),
                ),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[("ALLOWED", "İzin Verildi"), ("DENIED", "Reddedildi")],
                        max_length=20,
                        verbose_name="Sonuç",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Adresi"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performed_permission_audits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Gerçekleştiren",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="permissions.permission",
                        verbose_name="Yetki",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_audits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yetki Denetim Logu",
                "verbose_name_plural": "Yetki Denetim Logları",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="permissions_user_id_7214ed_idx",
                    ),
                    models.Index(
                        fields=["action", "-created_at"],
                        name="permissions_action_ea6fe4_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RoleHierarchy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inherit_permissions",
                    models.BooleanField(
                        default=True, verbose_name="Yetkileri Miras Al"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "additional_permissions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="hierarchy_additions",
                        to="permissions.permission",
                        verbose_name="Ek Yetkiler",
                    ),
                ),
                (
                    "child_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_hierarchies",
                        to="permissions.role",
                        verbose_name="Alt Rol",
                    ),
                ),
                (
                    "parent_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_hierarchies",
                        to="permissions.role",
                        verbose_name="Üst Rol",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rol Hiyerarşisi",
                "verbose_name_plural": "Rol Hiyerarşileri",
                "unique_together": {("parent_role", "child_role")},
            },
        ),
        migrations.CreateModel(
            name="UserPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme tarihi"
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_permission_permissions",
                        to="permissions.permission",
                        verbose_name="Yetki",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_user_permissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kullanıcı Yetkisi",
                "verbose_name_plural": "Kullanıcı Yetkileri",
                "ordering": ["user__username", "permission__codename"],
                "unique_together": {("user", "permission")},
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme tarihi"
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to="permissions.role",
                        verbose_name="Rol",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kullanıcı rolü",
                "verbose_name_plural": "Kullanıcı rolleri",
                "ordering": ["user__username", "role__name"],
                "unique_together": {("user", "role")},
            },
        ),
    ]
