# Generated by Django 5.2.1 on 2025-05-27 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_customuser_company_delete_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("kobi", "KOBİ"),
                    ("egitimci", "Eğitimci"),
                    ("ogrenci", "Öğrenci"),
                    ("oyuncu", "Oyuncu"),
                ],
                default="ogrenci",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subscription_type",
                    models.CharField(
                        choices=[
                            ("basic", "Temel"),
                            ("premium", "Premium"),
                            ("pro", "Pro"),
                        ],
                        default="basic",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(auto_now_add=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="accounts.customuser",
                    ),
                ),
            ],
        ),
    ]
