# Generated by Django 5.0.3 on 2024-03-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_virtual_company_user_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[
                    ('admin', 'Yönetici'), 
                    ('manager', 'Genel Müdür'), 
                    ('finance_manager', 'Finans Sorumlusu'), 
                    ('accounting', 'Muhasebe Sorumlusu'), 
                    ('stock_operator', 'Depo Yetkilisi'), 
                    ('sales', 'Satış Sorumlusu'), 
                    ('hr', 'İnsan Kaynakları'), 
                    ('business', 'İşletme'), 
                    ('student', 'Öğrenci'), 
                    ('teacher', 'Öğretmen'), 
                    ('guest', 'Misafir')
                ],
                default='student',
                max_length=20,
                verbose_name='Kullanıcı Rolü'
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefon'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='Profil Resmi'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Son Giriş IP Adresi'),
        ),
        migrations.AddField(
            model_name='user',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='Başarısız Giriş Denemeleri'),
        ),
        migrations.AddField(
            model_name='user',
            name='account_locked_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hesap Kilitleme Süresi'),
        ),
    ] 