# Generated by Django 5.2.1 on 2025-05-27 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_subscriptiontype_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "new_subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="new_logs",
                        to="accounts.subscriptiontype",
                    ),
                ),
                (
                    "old_subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="old_logs",
                        to="accounts.subscriptiontype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription_logs",
                        to="accounts.customuser",
                    ),
                ),
            ],
        ),
    ]
