# Generated by Django 5.2.6 on 2025-09-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_subscriptionlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptiontype",
            name="audience",
            field=models.CharField(
                choices=[
                    ("sme", "KOBİ"),
                    ("edu_student", "Öğrenci"),
                    ("edu_teacher", "Öğretmen"),
                    ("edu_campus", "Kampüs/Okul"),
                ],
                default="sme",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="subscriptiontype",
            name="features",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="subscriptiontype",
            name="monthly_price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="subscriptiontype",
            name="period_options",
            field=models.CharField(
                choices=[("monthly", "Aylık"), ("yearly", "Yıllık"), ("monthly_yearly", "Aylık/Yıllık")],
                default="monthly",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="subscriptiontype",
            name="user_limit",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscriptiontype",
            name="yearly_price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
