# Generated by Django 5.2.1

from django.db import migrations
from django.db import models

try:
    import accounts.models as accounts_models

    DefaultManagerClass = getattr(accounts_models, "CustomUserManager", models.Manager)
except Exception:
    # Fallback during tests or when import path is unavailable
    DefaultManagerClass = models.Manager


def set_customuser_manager(apps, schema_editor):
    # No runtime changes needed; migration only needs to record the manager path
    pass


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0007_subscriptiontype_audience_subscriptiontype_features_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[
                # Use the real CustomUserManager if importable; otherwise fall back to base Manager
                ("objects", DefaultManagerClass()),
            ],
        ),
    ]
