# Generated by Django 5.2.8 on 2025-11-12 07:29

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_userprofile_userpreference_twofactorauth_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("free", "Ücretsiz"),
                            ("basic", "Temel"),
                            ("professional", "Profesyonel"),
                            ("enterprise", "Kurumsal"),
                            ("custom", "Özel"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="Plan Adı",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(max_length=100, verbose_name="Görünen Ad"),
                ),
                ("description", models.TextField(verbose_name="Plan Açıklaması")),
                (
                    "price_monthly",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Aylık Ücret (₺)",
                    ),
                ),
                (
                    "price_yearly",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Yıllık Ücret (₺)",
                    ),
                ),
                (
                    "max_users",
                    models.IntegerField(
                        default=1,
                        help_text="Plan kapsamındaki maksimum kullanıcı sayısı",
                        verbose_name="Max Kullanıcı",
                    ),
                ),
                (
                    "max_companies",
                    models.IntegerField(default=1, verbose_name="Max Şirket"),
                ),
                (
                    "max_transactions",
                    models.IntegerField(default=100, verbose_name="Aylık Max İşlem"),
                ),
                (
                    "storage_gb",
                    models.IntegerField(default=1, verbose_name="Depolama (GB)"),
                ),
                (
                    "has_accounting",
                    models.BooleanField(default=True, verbose_name="Muhasebe Modülü"),
                ),
                (
                    "has_finance",
                    models.BooleanField(default=False, verbose_name="Finans Modülü"),
                ),
                (
                    "has_ai_assistant",
                    models.BooleanField(default=False, verbose_name="AI Asistan"),
                ),
                (
                    "has_education",
                    models.BooleanField(default=True, verbose_name="Eğitim"),
                ),
                (
                    "has_games",
                    models.BooleanField(default=True, verbose_name="Oyunlar"),
                ),
                (
                    "has_blockchain",
                    models.BooleanField(default=False, verbose_name="Blockchain"),
                ),
                (
                    "has_api_access",
                    models.BooleanField(default=False, verbose_name="API Erişimi"),
                ),
                (
                    "has_priority_support",
                    models.BooleanField(default=False, verbose_name="Öncelikli Destek"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "is_popular",
                    models.BooleanField(default=False, verbose_name="Popüler Plan"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Sıralama")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Abonelik Planı",
                "verbose_name_plural": "Abonelik Planları",
                "ordering": ["order", "price_monthly"],
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("super_admin", "Süper Yönetici"),
                            ("admin", "Sistem Yöneticisi"),
                            ("accountant", "Muhasebeci"),
                            ("financial_advisor", "Mali Müşavir"),
                            ("business_owner", "İşletme Sahibi"),
                            ("employee", "Çalışan"),
                            ("auditor", "Denetçi"),
                            ("student", "Öğrenci"),
                            ("viewer", "Görüntüleyici"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="Rol Adı",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(max_length=100, verbose_name="Görünen Ad"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "hierarchy_level",
                    models.IntegerField(
                        default=10,
                        help_text="Düşük değer = Yüksek yetki (0=Süper Admin, 10=En düşük)",
                        verbose_name="Hiyerarşi Seviyesi",
                    ),
                ),
                (
                    "can_manage_users",
                    models.BooleanField(
                        default=False, verbose_name="Kullanıcı Yönetimi"
                    ),
                ),
                (
                    "can_manage_companies",
                    models.BooleanField(default=False, verbose_name="Şirket Yönetimi"),
                ),
                (
                    "can_view_all_finances",
                    models.BooleanField(
                        default=False, verbose_name="Tüm Mali Verileri Görme"
                    ),
                ),
                (
                    "can_edit_finances",
                    models.BooleanField(default=False, verbose_name="Mali Düzenleme"),
                ),
                (
                    "can_approve_transactions",
                    models.BooleanField(default=False, verbose_name="İşlem Onaylama"),
                ),
                (
                    "can_generate_reports",
                    models.BooleanField(default=False, verbose_name="Rapor Oluşturma"),
                ),
                (
                    "can_access_ai",
                    models.BooleanField(
                        default=True, verbose_name="AI Asistan Erişimi"
                    ),
                ),
                (
                    "can_use_education",
                    models.BooleanField(default=True, verbose_name="Eğitim Modülü"),
                ),
                (
                    "can_play_games",
                    models.BooleanField(default=True, verbose_name="Oyun Modülü"),
                ),
                (
                    "can_use_blockchain",
                    models.BooleanField(
                        default=False, verbose_name="Blockchain Modülü"
                    ),
                ),
                (
                    "max_companies",
                    models.IntegerField(
                        default=1,
                        help_text="Bu role sahip kullanıcı kaç şirket yönetebilir (-1=sınırsız)",
                        verbose_name="Maksimum Şirket Sayısı",
                    ),
                ),
                (
                    "max_transactions_per_month",
                    models.IntegerField(
                        default=100,
                        help_text="Aylık maksimum işlem sayısı (-1=sınırsız)",
                        verbose_name="Aylık Max İşlem",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Kullanıcı Rolü",
                "verbose_name_plural": "Kullanıcı Rolleri",
                "ordering": ["hierarchy_level", "name"],
            },
        ),
        migrations.CreateModel(
            name="RoleBasedUserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Telefon"),
                ),
                (
                    "tc_no",
                    models.CharField(
                        blank=True, max_length=11, verbose_name="TC Kimlik No"
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Doğum Tarihi"
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Şirket Adı"
                    ),
                ),
                (
                    "job_title",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="İş Unvanı"
                    ),
                ),
                (
                    "license_number",
                    models.CharField(
                        blank=True,
                        help_text="Mali müşavir ruhsat numarası vb.",
                        max_length=50,
                        verbose_name="Ruhsat/Lisans No",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="Europe/Istanbul",
                        max_length=50,
                        verbose_name="Saat Dilimi",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("tr", "Türkçe"), ("en", "English")],
                        default="tr",
                        max_length=10,
                        verbose_name="Dil",
                    ),
                ),
                (
                    "two_factor_enabled",
                    models.BooleanField(
                        default=False, verbose_name="İki Faktörlü Doğrulama"
                    ),
                ),
                (
                    "last_password_change",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Son Şifre Değişikliği"
                    ),
                ),
                (
                    "login_attempts",
                    models.IntegerField(
                        default=0, verbose_name="Başarısız Giriş Denemeleri"
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(default=False, verbose_name="Hesap Kilitli"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.userrole",
                        verbose_name="Kullanıcı Rolü",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kullanıcı Profili",
                "verbose_name_plural": "Kullanıcı Profilleri",
            },
        ),
        migrations.CreateModel(
            name="UserSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Beklemede"),
                            ("active", "Aktif"),
                            ("cancelled", "İptal Edildi"),
                            ("expired", "Süresi Doldu"),
                            ("suspended", "Askıya Alındı"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "billing_period",
                    models.CharField(
                        choices=[
                            ("monthly", "Aylık"),
                            ("yearly", "Yıllık"),
                            ("lifetime", "Yaşam Boyu"),
                        ],
                        default="monthly",
                        max_length=20,
                        verbose_name="Faturalama Dönemi",
                    ),
                ),
                ("start_date", models.DateTimeField(verbose_name="Başlangıç Tarihi")),
                ("end_date", models.DateTimeField(verbose_name="Bitiş Tarihi")),
                (
                    "next_billing_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Sonraki Faturalama"
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Ödenen Tutar",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="TRY", max_length=3, verbose_name="Para Birimi"
                    ),
                ),
                (
                    "current_month_transactions",
                    models.IntegerField(default=0, verbose_name="Bu Ay İşlem Sayısı"),
                ),
                (
                    "total_transactions",
                    models.IntegerField(default=0, verbose_name="Toplam İşlem"),
                ),
                (
                    "storage_used_mb",
                    models.IntegerField(
                        default=0, verbose_name="Kullanılan Depolama (MB)"
                    ),
                ),
                (
                    "auto_renew",
                    models.BooleanField(default=True, verbose_name="Otomatik Yenileme"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notlar")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.subscriptionplan",
                        verbose_name="Abonelik Planı",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_subscription",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kullanıcı Aboneliği",
                "verbose_name_plural": "Kullanıcı Abonelikleri",
                "ordering": ["-created_at"],
            },
        ),
    ]
