# Generated by Django 5.2.8 on 2025-11-12 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_update_role_codes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userrole",
            name="name",
            field=models.CharField(
                choices=[
                    ("super_admin", "Süper Yönetici"),
                    ("admin", "Sistem Yöneticisi"),
                    ("finance_manager", "Finans Müdürü"),
                    ("kobi_owner", "KOBİ Sahibi"),
                    ("kobi_employee", "KOBİ Çalışanı"),
                    ("accountant", "Muhasebeci"),
                    ("financial_advisor", "Mali Müşavir"),
                    ("auditor", "Denetçi"),
                    ("teacher", "Eğitimci"),
                    ("student", "Öğrenci"),
                    ("player", "Oyuncu"),
                    ("viewer", "Görüntüleyici"),
                ],
                max_length=50,
                unique=True,
                verbose_name="Rol Adı",
            ),
        ),
    ]
