# Generated by Django 5.2.8 on 2025-12-15 11:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_add_new_user_types"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rolebaseduserprofile",
            options={
                "verbose_name": "Rol Tabanlı Kullanıcı Profili",
                "verbose_name_plural": "Rol Tabanlı Kullanıcı Profilleri",
            },
        ),
    ]
