# Generated by Django 4.2.25 on 2025-11-02 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("education", "0011_alter_meetingrecording_id"),
        ("teacher_dashboard", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("student_number", models.CharField(max_length=20, unique=True, verbose_name="Öğrenci Numarası")),
                (
                    "department",
                    models.CharField(help_text="Öğrencinin okuduğu bölüm", max_length=100, verbose_name="Bölüm"),
                ),
                ("grade", models.CharField(help_text="Öğrencinin sınıfı", max_length=10, verbose_name="Sınıf")),
                ("enrollment_date", models.DateField(auto_now_add=True, verbose_name="Kayıt Tarihi")),
                ("graduation_date", models.DateField(blank=True, null=True, verbose_name="Mezuniyet Tarihi")),
                (
                    "gpa",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=3, verbose_name="Genel Not Ortalaması"
                    ),
                ),
                ("completed_credits", models.IntegerField(default=0, verbose_name="Tamamlanan Krediler")),
                ("total_credits", models.IntegerField(default=240, verbose_name="Toplam Krediler")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Öğrenci Profili",
                "verbose_name_plural": "Öğrenci Profilleri",
            },
        ),
        migrations.CreateModel(
            name="StudentProgress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "attendance",
                    models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name="Devam Durumu"),
                ),
                (
                    "midterm_grade",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True, verbose_name="Vize Notu"
                    ),
                ),
                (
                    "final_grade",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True, verbose_name="Final Notu"
                    ),
                ),
                (
                    "average_grade",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True, verbose_name="Ortalama Not"
                    ),
                ),
                ("letter_grade", models.CharField(blank=True, max_length=2, null=True, verbose_name="Harf Notu")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Aktif"),
                            ("passed", "Geçti"),
                            ("failed", "Kaldı"),
                            ("incomplete", "Eksik"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_progress",
                        to="education.course",
                        verbose_name="Ders",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Öğrenci",
                    ),
                ),
            ],
            options={
                "verbose_name": "Öğrenci İlerlemesi",
                "verbose_name_plural": "Öğrenci İlerlemeleri",
                "unique_together": {("student", "course")},
            },
        ),
        migrations.CreateModel(
            name="StudentAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Başlanmadı"),
                            ("in_progress", "Devam Ediyor"),
                            ("completed", "Tamamlandı"),
                            ("submitted", "Teslim Edildi"),
                            ("graded", "Notlandırıldı"),
                        ],
                        default="not_started",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                ("submission_date", models.DateTimeField(blank=True, null=True, verbose_name="Teslim Tarihi")),
                ("last_activity", models.DateTimeField(auto_now=True, verbose_name="Son Aktivite")),
                (
                    "completion_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name="Tamamlanma Yüzdesi"),
                ),
                (
                    "grade",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name="Not"),
                ),
                ("feedback", models.TextField(blank=True, verbose_name="Geri Bildirim")),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_assignments",
                        to="teacher_dashboard.assignment",
                        verbose_name="Ödev",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Öğrenci",
                    ),
                ),
            ],
            options={
                "verbose_name": "Öğrenci Ödevi",
                "verbose_name_plural": "Öğrenci Ödevleri",
                "unique_together": {("student", "assignment")},
            },
        ),
    ]
