# Generated by Django 4.2.25 on 2025-11-02 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("logo", models.ImageField(blank=True, null=True, upload_to="tenant_logos/", verbose_name="Logo")),
                ("primary_color", models.CharField(default="#007bff", max_length=7, verbose_name="Ana Renk")),
                ("secondary_color", models.CharField(default="#6c757d", max_length=7, verbose_name="İkincil Renk")),
                ("enabled_modules", models.JSONField(default=list, verbose_name="Aktif Modüller")),
                (
                    "feature_limits",
                    models.JSONField(
                        default=dict, help_text='{"users": 50, "invoices": 1000}', verbose_name="Özellik Limitleri"
                    ),
                ),
                ("max_users", models.IntegerField(default=10, verbose_name="Maksimum Kullanıcı")),
                ("max_storage_mb", models.IntegerField(default=1024, verbose_name="Maksimum Depolama (MB)")),
                (
                    "max_api_calls_per_day",
                    models.IntegerField(default=10000, verbose_name="Günlük Maksimum API Çağrısı"),
                ),
                ("contact_email", models.EmailField(blank=True, max_length=254, verbose_name="İletişim E-posta")),
                ("contact_phone", models.CharField(blank=True, max_length=20, verbose_name="İletişim Telefon")),
                ("timezone", models.CharField(default="Europe/Istanbul", max_length=50, verbose_name="Zaman Dilimi")),
                ("language", models.CharField(default="tr", max_length=10, verbose_name="Varsayılan Dil")),
                ("ip_whitelist", models.JSONField(blank=True, default=list, verbose_name="IP Beyaz Liste")),
                ("require_2fa", models.BooleanField(default=False, verbose_name="2FA Zorunlu")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="tenancy.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant Ayarları",
                "verbose_name_plural": "Tenant Ayarları",
            },
        ),
        migrations.CreateModel(
            name="TenantBilling",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("invoice_number", models.CharField(max_length=50, unique=True, verbose_name="Fatura Numarası")),
                ("billing_period_start", models.DateField(verbose_name="Fatura Dönemi Başlangıç")),
                ("billing_period_end", models.DateField(verbose_name="Fatura Dönemi Bitiş")),
                ("base_amount", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Taban Tutar")),
                (
                    "usage_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Kullanım Tutarı"),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Toplam Tutar")),
                ("billing_details", models.JSONField(default=dict, verbose_name="Fatura Detayları")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Beklemede"),
                            ("PAID", "Ödendi"),
                            ("OVERDUE", "Vadesi Geçti"),
                            ("CANCELLED", "İptal Edildi"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                ("due_date", models.DateField(verbose_name="Vade Tarihi")),
                ("paid_at", models.DateTimeField(blank=True, null=True, verbose_name="Ödeme Tarihi")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billings",
                        to="tenancy.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant Faturalandırma",
                "verbose_name_plural": "Tenant Faturalandırmalar",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TenantAudit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Oluşturuldu"),
                            ("UPDATE", "Güncellendi"),
                            ("DELETE", "Silindi"),
                            ("ACTIVATE", "Aktif Edildi"),
                            ("DEACTIVATE", "Pasif Edildi"),
                            ("SETTINGS_CHANGE", "Ayar Değiştirildi"),
                        ],
                        max_length=30,
                        verbose_name="Aksiyon",
                    ),
                ),
                ("field_name", models.CharField(blank=True, max_length=100, verbose_name="Alan Adı")),
                ("old_value", models.TextField(blank=True, verbose_name="Eski Değer")),
                ("new_value", models.TextField(blank=True, verbose_name="Yeni Değer")),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True, verbose_name="IP Adresi")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="tenancy.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant Denetim Logu",
                "verbose_name_plural": "Tenant Denetim Logları",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TenantUsage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(verbose_name="Tarih")),
                ("active_users", models.IntegerField(default=0, verbose_name="Aktif Kullanıcı")),
                ("total_users", models.IntegerField(default=0, verbose_name="Toplam Kullanıcı")),
                (
                    "storage_used_mb",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="Kullanılan Depolama (MB)"
                    ),
                ),
                ("api_calls", models.IntegerField(default=0, verbose_name="API Çağrısı")),
                ("invoices_created", models.IntegerField(default=0, verbose_name="Oluşturulan Fatura")),
                ("transactions_created", models.IntegerField(default=0, verbose_name="Oluşturulan İşlem")),
                ("reports_generated", models.IntegerField(default=0, verbose_name="Oluşturulan Rapor")),
                ("module_usage", models.JSONField(blank=True, default=dict, verbose_name="Modül Kullanımı")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_stats",
                        to="tenancy.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant Kullanımı",
                "verbose_name_plural": "Tenant Kullanımları",
                "ordering": ["-date"],
                "unique_together": {("tenant", "date")},
            },
        ),
    ]
