# Generated by Django 5.2.7 on 2025-10-21 00:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="declaration",
            new_name="submissions_code_a229ce_idx",
            old_name="decl_code_period_vkn_idx",
        ),
    ]
