# Generated by Django 4.2.25 on 2025-11-02 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "submissions",
            "0002_rename_decl_code_period_vkn_idx_submissions_code_a229ce_idx",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmissionAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="submissions/attachments/", verbose_name="Dosya"
                    ),
                ),
                (
                    "file_name",
                    models.CharField(max_length=255, verbose_name="Dosya Adı"),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("PDF", "PDF Belgesi"),
                            ("XML", "XML Dosyası"),
                            ("EXCEL", "Excel Dosyası"),
                            ("IMAGE", "Görsel"),
                            ("OTHER", "Diğer"),
                        ],
                        max_length=20,
                        verbose_name="Dosya Tipi",
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(verbose_name="Dosya Boyutu (bytes)"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="submissions.submission",
                        verbose_name="Beyan",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yükleyen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Beyan Eki",
                "verbose_name_plural": "Beyan Ekleri",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="SubmissionApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Beklemede"),
                            ("APPROVED", "Onaylandı"),
                            ("REJECTED", "Reddedildi"),
                            ("REVISION_REQUESTED", "Revizyon İstendi"),
                        ],
                        default="PENDING",
                        max_length=30,
                        verbose_name="Durum",
                    ),
                ),
                ("comments", models.TextField(blank=True, verbose_name="Yorumlar")),
                (
                    "revision_notes",
                    models.TextField(blank=True, verbose_name="Revizyon Notları"),
                ),
                (
                    "requested_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="İstek Tarihi"
                    ),
                ),
                (
                    "responded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Yanıt Tarihi"
                    ),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submission_approvals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Onaylayan",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="submissions.submission",
                        verbose_name="Beyan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Beyan Onayı",
                "verbose_name_plural": "Beyan Onayları",
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="SubmissionTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Şablon Adı")),
                (
                    "code",
                    models.CharField(
                        help_text="KDV1, BA-BS, Muhtasar, vs.",
                        max_length=50,
                        verbose_name="Beyan Kodu",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "template_structure",
                    models.JSONField(default=dict, verbose_name="Şablon Yapısı"),
                ),
                (
                    "default_values",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Varsayılan Değerler"
                    ),
                ),
                (
                    "validation_rules",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Doğrulama Kuralları"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "version",
                    models.CharField(
                        default="1.0", max_length=20, verbose_name="Versiyon"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Beyan Şablonu",
                "verbose_name_plural": "Beyan Şablonları",
                "ordering": ["code", "name"],
                "unique_together": {("code", "version")},
            },
        ),
    ]
