# Generated by Django 5.2.6 on 2025-09-21 19:45

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("teacher_dashboard", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialTermCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("term", models.CharField(max_length=100, verbose_name="Terim")),
                ("description", models.TextField(verbose_name="Açıklama")),
                ("example", models.TextField(blank=True, verbose_name="Örnek")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LearningOutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Kazanım Kodu"
                    ),
                ),
                ("description", models.TextField(verbose_name="Kazanım Açıklaması")),
            ],
            options={
                "verbose_name": "Öğrenme Kazanımı",
                "verbose_name_plural": "Öğrenme Kazanımları",
            },
        ),
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Seviye Adı")),
                ("score_required", models.IntegerField(verbose_name="Seviye Puanı")),
            ],
            options={
                "verbose_name": "Seviye",
                "verbose_name_plural": "Seviyeler",
            },
        ),
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Rozet Adı")),
                ("description", models.TextField(verbose_name="Açıklama")),
                ("icon", models.ImageField(upload_to="badges/", verbose_name="İkon")),
                (
                    "criteria",
                    models.JSONField(default=dict, verbose_name="Kazanım Kriterleri"),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="badges",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Rozeti Kazananlar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rozet",
                "verbose_name_plural": "Rozetler",
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Ders Adı")),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Ders Kodu"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "students",
                    models.ManyToManyField(
                        blank=True,
                        related_name="enrolled_courses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Öğrenciler",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teaching_courses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Öğretmen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ders",
                "verbose_name_plural": "Dersler",
            },
        ),
        migrations.CreateModel(
            name="ClassSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("starts_at", models.DateTimeField(verbose_name="Başlangıç")),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(default=45, verbose_name="Süre (dk)"),
                ),
                (
                    "topic",
                    models.CharField(blank=True, max_length=200, verbose_name="Konu"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="education.course",
                        verbose_name="Ders",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ders Oturumu",
                "verbose_name_plural": "Ders Oturumları",
            },
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Sınav Başlığı"),
                ),
                (
                    "start_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Başlangıç"
                    ),
                ),
                (
                    "end_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Bitiş"),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(default=60, verbose_name="Süre (dk)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="education.course",
                        verbose_name="Ders",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sınav",
                "verbose_name_plural": "Sınavlar",
            },
        ),
        migrations.CreateModel(
            name="ExamSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("answers", models.JSONField(default=dict, verbose_name="Cevaplar")),
                (
                    "auto_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=8,
                        verbose_name="Otomatik Puan",
                    ),
                ),
                (
                    "manual_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Manuel Puan",
                    ),
                ),
                (
                    "flags",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="İşaretler"
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="education.exam",
                        verbose_name="Sınav",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Öğrenci",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sınav Teslimi",
                "verbose_name_plural": "Sınav Teslimleri",
                "unique_together": {("exam", "student")},
            },
        ),
        migrations.CreateModel(
            name="CheatingIncident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "incident_type",
                    models.CharField(max_length=50, verbose_name="İhlal Tipi"),
                ),
                (
                    "similarity_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Benzerlik Skoru",
                    ),
                ),
                ("evidence", models.TextField(blank=True, verbose_name="Kanıt")),
                (
                    "resolved",
                    models.BooleanField(default=False, verbose_name="Çözüldü"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incidents",
                        to="education.examsubmission",
                        verbose_name="Teslim",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kopya/İş Birliği İhlali",
                "verbose_name_plural": "Kopya/İş Birliği İhlalleri",
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(verbose_name="Mesaj")),
                (
                    "page_url",
                    models.CharField(max_length=300, verbose_name="Sayfa URL"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=150, null=True, verbose_name="E-posta"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "is_answered",
                    models.BooleanField(default=False, verbose_name="Yanıtlandı mı"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Geri Bildirim",
                "verbose_name_plural": "Geri Bildirimler",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Forum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Forum Başlığı"),
                ),
                ("description", models.TextField(verbose_name="Açıklama")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_forums",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Forum",
                "verbose_name_plural": "Forumlar",
            },
        ),
        migrations.CreateModel(
            name="ForumTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Konu Başlığı"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_topics",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan",
                    ),
                ),
                (
                    "forum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="education.forum",
                        verbose_name="Forum",
                    ),
                ),
            ],
            options={
                "verbose_name": "Forum Konusu",
                "verbose_name_plural": "Forum Konuları",
            },
        ),
        migrations.CreateModel(
            name="ForumPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="İçerik")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forum_posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yazar",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="education.forumtopic",
                        verbose_name="Konu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Forum Mesajı",
                "verbose_name_plural": "Forum Mesajları",
            },
        ),
        migrations.CreateModel(
            name="GroupAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Grup Ödevi Başlığı"),
                ),
                ("description", models.TextField(verbose_name="Açıklama")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_assignments",
                        to="teacher_dashboard.assignment",
                        verbose_name="Ödev",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_group_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="group_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Üyeler",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grup Ödevi",
                "verbose_name_plural": "Grup Ödevleri",
            },
        ),
        migrations.CreateModel(
            name="LearningContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Başlık")),
                ("description", models.TextField(verbose_name="Açıklama")),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("video", "Video"),
                            ("document", "Doküman"),
                            ("image", "Görsel"),
                            ("interactive", "İnteraktif"),
                        ],
                        max_length=20,
                        verbose_name="İçerik Tipi",
                    ),
                ),
                (
                    "media_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="learning_content/",
                        verbose_name="Medya Dosyası",
                    ),
                ),
                (
                    "external_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="Harici Bağlantı"
                    ),
                ),
                (
                    "extra_note",
                    models.TextField(blank=True, verbose_name="Ek Açıklama"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_contents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Eğitim İçeriği",
                "verbose_name_plural": "Eğitim İçerikleri",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Konu Başlığı"),
                ),
                ("content", models.TextField(blank=True, verbose_name="İçerik")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Sıra")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="education.course",
                        verbose_name="Ders",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ders Konusu",
                "verbose_name_plural": "Ders Konuları",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="PortfolioItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Başlık")),
                (
                    "artifact_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="eportfolio/",
                        verbose_name="Dosya",
                    ),
                ),
                (
                    "artifact_url",
                    models.URLField(blank=True, null=True, verbose_name="Bağlantı"),
                ),
                ("reflection", models.TextField(blank=True, verbose_name="Yansıtma")),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Puan",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio_items",
                        to="education.course",
                        verbose_name="Ders",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Öğrenci",
                    ),
                ),
            ],
            options={
                "verbose_name": "E-Portfolyo Öğesi",
                "verbose_name_plural": "E-Portfolyo Öğeleri",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Soru")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("mcq", "Çoktan Seçmeli"),
                            ("text", "Açık Uçlu"),
                            ("bool", "Doğru/Yanlış"),
                        ],
                        default="mcq",
                        max_length=10,
                        verbose_name="Soru Tipi",
                    ),
                ),
                (
                    "points",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=6,
                        verbose_name="Puan",
                    ),
                ),
                (
                    "choices",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Seçenekler"
                    ),
                ),
                (
                    "correct_answer",
                    models.JSONField(
                        blank=True, default=None, null=True, verbose_name="Doğru Cevap"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="education.course",
                        verbose_name="Ders",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_questions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="questions",
                        to="education.lesson",
                        verbose_name="Ders Konusu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Soru",
                "verbose_name_plural": "Sorular",
            },
        ),
        migrations.AddField(
            model_name="exam",
            name="questions",
            field=models.ManyToManyField(
                related_name="exams", to="education.question", verbose_name="Sorular"
            ),
        ),
        migrations.CreateModel(
            name="StudentAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True, verbose_name="Tarih")),
                (
                    "completed_assignments",
                    models.IntegerField(default=0, verbose_name="Tamamlanan Ödev"),
                ),
                (
                    "completed_quizzes",
                    models.IntegerField(default=0, verbose_name="Tamamlanan Quiz"),
                ),
                (
                    "success_rate",
                    models.FloatField(default=0, verbose_name="Başarı Oranı"),
                ),
                (
                    "weak_topics",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Zayıf Konular"
                    ),
                ),
                (
                    "strong_topics",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Kuvvetli Konular"
                    ),
                ),
                (
                    "last_activity",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Son Aktivite"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Öğrenci",
                    ),
                ),
            ],
            options={
                "verbose_name": "Öğrenci Analitiği",
                "verbose_name_plural": "Öğrenci Analitikleri",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="StudentGamificationProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_score",
                    models.IntegerField(default=0, verbose_name="Toplam Puan"),
                ),
                (
                    "badges",
                    models.ManyToManyField(
                        blank=True,
                        related_name="students",
                        to="education.badge",
                        verbose_name="Kazanılan Rozetler",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="education.level",
                        verbose_name="Seviye",
                    ),
                ),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gamification",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Öğrenci",
                    ),
                ),
            ],
            options={
                "verbose_name": "Oyunlaştırma İlerlemesi",
                "verbose_name_plural": "Oyunlaştırma İlerlemeleri",
            },
        ),
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Turnuva Başlığı"),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Başlangıç"
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Bitiş"),
                ),
                ("rules", models.TextField(blank=True, verbose_name="Kurallar")),
                (
                    "standings",
                    models.JSONField(blank=True, default=list, verbose_name="Sıralama"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tournaments",
                        to="education.course",
                        verbose_name="Ders",
                    ),
                ),
            ],
            options={
                "verbose_name": "Turnuva",
                "verbose_name_plural": "Turnuvalar",
            },
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Var"),
                            ("absent", "Yok"),
                            ("excused", "İzinli"),
                            ("late", "Geç"),
                        ],
                        default="present",
                        max_length=10,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=255, verbose_name="Not"),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Öğrenci",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance",
                        to="education.classsession",
                        verbose_name="Oturum",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yoklama Kaydı",
                "verbose_name_plural": "Yoklama Kayıtları",
                "unique_together": {("session", "student")},
            },
        ),
        migrations.CreateModel(
            name="LessonOutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outcomes",
                        to="education.lesson",
                        verbose_name="Ders Konusu",
                    ),
                ),
                (
                    "outcome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="education.learningoutcome",
                        verbose_name="Kazanım",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ders-Kazanım Eşlemesi",
                "verbose_name_plural": "Ders-Kazanım Eşlemeleri",
                "unique_together": {("lesson", "outcome")},
            },
        ),
    ]
