# Generated by Django 5.2.6 on 2025-09-22 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200, verbose_name="Başlık")),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "meeting_type",
                    models.CharField(
                        choices=[("online", "Çevrimiçi"), ("in_person", "Yüz Yüze")],
                        default="online",
                        max_length=20,
                        verbose_name="Toplantı Tipi",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("scheduled", "Planlandı"), ("completed", "Tamamlandı"), ("canceled", "İptal")],
                        default="scheduled",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="Başlangıç")),
                ("end_time", models.DateTimeField(blank=True, null=True, verbose_name="Bitiş")),
                ("join_url", models.URLField(blank=True, verbose_name="Toplantı Bağlantısı (Zoom/Meet vb.)")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma Tarihi")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Güncellenme Tarihi")),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organized_meetings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Düzenleyen",
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        blank=True, related_name="meetings", to=settings.AUTH_USER_MODEL, verbose_name="Katılımcılar"
                    ),
                ),
            ],
            options={
                "verbose_name": "Toplantı",
                "verbose_name_plural": "Toplantılar",
                "ordering": ["-start_time"],
            },
        ),
    ]
