# Generated by Django 5.2.7 on 2025-10-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("education", "0010_meetingrecording_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetingrecording",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
