# Generated by Django 4.2.25 on 2025-11-02 13:25

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("education", "0011_alter_meetingrecording_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Kategori Adı"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "icon",
                    models.CharField(blank=True, max_length=50, verbose_name="İkon"),
                ),
                (
                    "color",
                    models.CharField(
                        default="#007bff", max_length=7, verbose_name="Renk"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Sıra")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="education.coursecategory",
                        verbose_name="Üst Kategori",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ders Kategorisi",
                "verbose_name_plural": "Ders Kategorileri",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="LearningPath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Yol Başlığı")),
                ("description", models.TextField(verbose_name="Açıklama")),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="learning_paths/",
                        verbose_name="Görsel",
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Başlangıç"),
                            ("intermediate", "Orta"),
                            ("advanced", "İleri"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                (
                    "estimated_weeks",
                    models.IntegerField(default=0, verbose_name="Tahmini Süre (hafta)"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Öğrenme Yolu",
                "verbose_name_plural": "Öğrenme Yolları",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudySession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(verbose_name="Başlangıç")),
                (
                    "ended_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Bitiş"),
                ),
                (
                    "duration_minutes",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Süre (dk)"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notlar")),
                (
                    "focus_score",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        null=True,
                        verbose_name="Konsantrasyon",
                    ),
                ),
                (
                    "device_type",
                    models.CharField(blank=True, max_length=50, verbose_name="Cihaz"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_sessions",
                        to="education.course",
                        verbose_name="Ders",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_sessions",
                        to="education.lesson",
                        verbose_name="Konu",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Öğrenci",
                    ),
                ),
            ],
            options={
                "verbose_name": "Çalışma Oturumu",
                "verbose_name_plural": "Çalışma Oturumları",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("course_completion", "Ders Tamamlama"),
                            ("skill_mastery", "Beceri Kazanımı"),
                            ("grade_achievement", "Not Hedefi"),
                            ("time_management", "Zaman Yönetimi"),
                            ("custom", "Özel"),
                        ],
                        default="custom",
                        max_length=30,
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Hedef Başlığı"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                ("target_date", models.DateField(verbose_name="Hedef Tarihi")),
                (
                    "target_metric",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Hedef Metrik",
                    ),
                ),
                (
                    "current_progress",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="Mevcut İlerleme",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Başlanmadı"),
                            ("in_progress", "Devam Ediyor"),
                            ("completed", "Tamamlandı"),
                            ("abandoned", "Terk Edildi"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tamamlanma Tarihi"
                    ),
                ),
                (
                    "reminder_enabled",
                    models.BooleanField(default=True, verbose_name="Hatırlatıcı Aktif"),
                ),
                (
                    "reminder_frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Günlük"),
                            ("weekly", "Haftalık"),
                            ("monthly", "Aylık"),
                        ],
                        default="weekly",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_goals",
                        to="education.course",
                        verbose_name="Ders",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_goals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Öğrenci",
                    ),
                ),
            ],
            options={
                "verbose_name": "Öğrenci Hedefi",
                "verbose_name_plural": "Öğrenci Hedefleri",
                "ordering": ["target_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PathCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Sıra")),
                (
                    "is_optional",
                    models.BooleanField(default=False, verbose_name="İsteğe Bağlı"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="path_memberships",
                        to="education.course",
                    ),
                ),
                (
                    "path",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="path_courses",
                        to="education.learningpath",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yol Dersi",
                "verbose_name_plural": "Yol Dersleri",
                "ordering": ["order"],
                "unique_together": {("path", "course")},
            },
        ),
        migrations.CreateModel(
            name="LessonResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Başlık")),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("video", "Video"),
                            ("link", "Bağlantı"),
                            ("presentation", "Sunum"),
                            ("code", "Kod Örneği"),
                            ("quiz", "Alıştırma"),
                            ("other", "Diğer"),
                        ],
                        default="pdf",
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="lesson_resources/",
                        verbose_name="Dosya",
                    ),
                ),
                (
                    "external_url",
                    models.URLField(blank=True, verbose_name="Harici Bağlantı"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                ("order", models.IntegerField(default=0, verbose_name="Sıra")),
                (
                    "is_downloadable",
                    models.BooleanField(default=True, verbose_name="İndirilebilir"),
                ),
                (
                    "requires_completion",
                    models.BooleanField(
                        default=False, verbose_name="Tamamlama Gerektirir"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="education.lesson",
                        verbose_name="Ders",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_resources",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yükleyen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ders Kaynağı",
                "verbose_name_plural": "Ders Kaynakları",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.AddField(
            model_name="learningpath",
            name="courses",
            field=models.ManyToManyField(
                related_name="learning_paths",
                through="education.PathCourse",
                to="education.course",
                verbose_name="Dersler",
            ),
        ),
        migrations.AddField(
            model_name="learningpath",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_paths",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Oluşturan",
            ),
        ),
        migrations.AddField(
            model_name="learningpath",
            name="students",
            field=models.ManyToManyField(
                blank=True,
                related_name="enrolled_paths",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Kayıtlı Öğrenciler",
            ),
        ),
        migrations.CreateModel(
            name="EnhancedCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="course_thumbnails/",
                        verbose_name="Kapak Görseli",
                    ),
                ),
                (
                    "video_intro",
                    models.URLField(blank=True, verbose_name="Tanıtım Videosu"),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Başlangıç"),
                            ("intermediate", "Orta"),
                            ("advanced", "İleri"),
                            ("expert", "Uzman"),
                        ],
                        default="beginner",
                        max_length=20,
                        verbose_name="Zorluk Seviyesi",
                    ),
                ),
                (
                    "estimated_hours",
                    models.IntegerField(default=0, verbose_name="Tahmini Süre (saat)"),
                ),
                (
                    "total_enrolled",
                    models.IntegerField(default=0, verbose_name="Toplam Kayıt"),
                ),
                (
                    "average_rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=3,
                        verbose_name="Ortalama Puan",
                    ),
                ),
                (
                    "total_reviews",
                    models.IntegerField(default=0, verbose_name="Toplam Değerlendirme"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Yayında"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Yayın Tarihi"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="courses",
                        to="education.coursecategory",
                        verbose_name="Kategori",
                    ),
                ),
                (
                    "course",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enhanced_info",
                        to="education.course",
                        verbose_name="Ders",
                    ),
                ),
                (
                    "prerequisites",
                    models.ManyToManyField(
                        blank=True,
                        related_name="required_for",
                        to="education.course",
                        verbose_name="Ön Koşul Dersler",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gelişmiş Ders Bilgisi",
                "verbose_name_plural": "Gelişmiş Ders Bilgileri",
            },
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_type",
                    models.CharField(
                        choices=[
                            ("completion", "Tamamlama"),
                            ("achievement", "Başarı"),
                            ("excellence", "Mükemmellik"),
                        ],
                        default="completion",
                        max_length=20,
                    ),
                ),
                (
                    "certificate_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Sertifika No"
                    ),
                ),
                (
                    "final_score",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Final Puanı"
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True, max_length=5, verbose_name="Harf Notu"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="certificates/",
                        verbose_name="PDF Dosyası",
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Veriliş Tarihi"
                    ),
                ),
                (
                    "verification_code",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Doğrulama Kodu"
                    ),
                ),
                (
                    "is_revoked",
                    models.BooleanField(default=False, verbose_name="İptal Edildi"),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="İptal Tarihi"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="education.course",
                        verbose_name="Ders",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_certificates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Veren",
                    ),
                ),
                (
                    "learning_path",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="education.learningpath",
                        verbose_name="Öğrenme Yolu",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Öğrenci",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sertifika",
                "verbose_name_plural": "Sertifikalar",
                "ordering": ["-issued_at"],
            },
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Başlık")),
                ("content", models.TextField(verbose_name="İçerik")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Düşük"),
                            ("normal", "Normal"),
                            ("high", "Yüksek"),
                            ("urgent", "Acil"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="Öncelik",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Yayında"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Yayın Tarihi"
                    ),
                ),
                (
                    "send_notification",
                    models.BooleanField(default=True, verbose_name="Bildirim Gönder"),
                ),
                (
                    "notification_sent",
                    models.BooleanField(
                        default=False, verbose_name="Bildirim Gönderildi"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yazar",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcements",
                        to="education.course",
                        verbose_name="Ders",
                    ),
                ),
            ],
            options={
                "verbose_name": "Duyuru",
                "verbose_name_plural": "Duyurular",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CourseReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        verbose_name="Puan",
                    ),
                ),
                (
                    "content_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        null=True,
                        verbose_name="İçerik",
                    ),
                ),
                (
                    "instructor_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        null=True,
                        verbose_name="Eğitmen",
                    ),
                ),
                (
                    "difficulty_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        null=True,
                        verbose_name="Zorluk",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Başlık")),
                ("comment", models.TextField(verbose_name="Yorum")),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="Onaylandı"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Yayında"),
                ),
                (
                    "helpful_count",
                    models.IntegerField(default=0, verbose_name="Faydalı Sayısı"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="education.course",
                        verbose_name="Ders",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Öğrenci",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ders Değerlendirmesi",
                "verbose_name_plural": "Ders Değerlendirmeleri",
                "ordering": ["-created_at"],
                "unique_together": {("course", "student")},
            },
        ),
    ]
