# Generated by Django 5.2.8 on 2025-12-15 11:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("education", "0013_studentprofile_studentassignment_studentprogress"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="badge",
            options={
                "verbose_name": "Eğitim Rozeti",
                "verbose_name_plural": "Eğitim Rozetleri",
            },
        ),
        migrations.AlterModelOptions(
            name="tournament",
            options={
                "verbose_name": "Eğitim Turnuvası",
                "verbose_name_plural": "Eğitim Turnuvaları",
            },
        ),
    ]
