# Generated by Django 4.2.25 on 2025-11-02 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityPolicy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="Politika Adı")),
                (
                    "policy_type",
                    models.CharField(
                        choices=[
                            ("PASSWORD", "Şifre Politikası"),
                            ("SESSION", "Oturum Politikası"),
                            ("ACCESS", "Erişim Politikası"),
                            ("DATA", "Veri Politikası"),
                            ("API", "API Politikası"),
                        ],
                        max_length=20,
                        verbose_name="Politika Tipi",
                    ),
                ),
                ("description", models.TextField(verbose_name="Açıklama")),
                ("rules", models.JSONField(default=dict, verbose_name="Kurallar")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("is_enforced", models.BooleanField(default=False, verbose_name="Zorunlu")),
                ("priority", models.IntegerField(default=0, verbose_name="Öncelik")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Güvenlik Politikası",
                "verbose_name_plural": "Güvenlik Politikaları",
                "ordering": ["-priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="IPWhitelist",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ip_address", models.GenericIPAddressField(unique=True, verbose_name="IP Adresi")),
                ("description", models.CharField(max_length=200, verbose_name="Açıklama")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("last_used_at", models.DateTimeField(blank=True, null=True, verbose_name="Son Kullanım")),
                ("usage_count", models.IntegerField(default=0, verbose_name="Kullanım Sayısı")),
                ("valid_until", models.DateTimeField(blank=True, null=True, verbose_name="Geçerlilik Süresi")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_whitelists",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "IP Beyaz Liste",
                "verbose_name_plural": "IP Beyaz Listeler",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IPBlacklist",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ip_address", models.GenericIPAddressField(unique=True, verbose_name="IP Adresi")),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("BRUTE_FORCE", "Brute Force"),
                            ("MALICIOUS", "Kötü Niyetli Aktivite"),
                            ("SPAM", "Spam"),
                            ("MANUAL", "Manuel Engelleme"),
                            ("AUTOMATED", "Otomatik Engelleme"),
                        ],
                        max_length=30,
                        verbose_name="Engelleme Sebebi",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                ("blocked_attempts", models.IntegerField(default=0, verbose_name="Engellenen Deneme")),
                ("first_blocked_at", models.DateTimeField(verbose_name="İlk Engelleme")),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True, verbose_name="Son Deneme")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "auto_unblock_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Otomatik Kaldırma Zamanı"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan",
                    ),
                ),
            ],
            options={
                "verbose_name": "IP Kara Liste",
                "verbose_name_plural": "IP Kara Listeler",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SecurityIncident",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "incident_type",
                    models.CharField(
                        choices=[
                            ("UNAUTHORIZED_ACCESS", "Yetkisiz Erişim"),
                            ("BRUTE_FORCE", "Brute Force Saldırısı"),
                            ("SQL_INJECTION", "SQL Injection"),
                            ("XSS", "XSS Saldırısı"),
                            ("CSRF", "CSRF Saldırısı"),
                            ("DATA_BREACH", "Veri İhlali"),
                            ("SUSPICIOUS_ACTIVITY", "Şüpheli Aktivite"),
                            ("OTHER", "Diğer"),
                        ],
                        max_length=30,
                        verbose_name="Olay Tipi",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[("LOW", "Düşük"), ("MEDIUM", "Orta"), ("HIGH", "Yüksek"), ("CRITICAL", "Kritik")],
                        max_length=20,
                        verbose_name="Ciddiyet",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Başlık")),
                ("description", models.TextField(verbose_name="Açıklama")),
                ("affected_resource", models.CharField(blank=True, max_length=200, verbose_name="Etkilenen Kaynak")),
                ("source_ip", models.GenericIPAddressField(verbose_name="Kaynak IP")),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                ("attempt_count", models.IntegerField(default=1, verbose_name="Deneme Sayısı")),
                ("is_resolved", models.BooleanField(default=False, verbose_name="Çözüldü")),
                ("resolved_at", models.DateTimeField(blank=True, null=True, verbose_name="Çözüm Zamanı")),
                ("resolution_notes", models.TextField(blank=True, verbose_name="Çözüm Notları")),
                ("action_taken", models.TextField(blank=True, verbose_name="Alınan Aksiyon")),
                ("detected_at", models.DateTimeField(auto_now_add=True, verbose_name="Tespit Tarihi")),
                (
                    "affected_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_incidents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Etkilenen Kullanıcı",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_incidents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Çözen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Güvenlik Olayı",
                "verbose_name_plural": "Güvenlik Olayları",
                "ordering": ["-detected_at"],
                "indexes": [
                    models.Index(fields=["severity", "-detected_at"], name="security_se_severit_627970_idx"),
                    models.Index(fields=["is_resolved", "-detected_at"], name="security_se_is_reso_bf1245_idx"),
                ],
            },
        ),
    ]
