# Generated by Django 5.2.8 on 2025-11-11 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0002_securityauditlog"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="securityauditlog",
            new_name="security_se_action_a3e040_idx",
            old_name="security_se_action__f34f6a_idx",
        ),
        migrations.RenameIndex(
            model_name="securityauditlog",
            new_name="security_se_actor_i_605a42_idx",
            old_name="security_se_actor__b0f690_idx",
        ),
    ]
