# Generated by Django 5.2.8 on 2025-12-15 11:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "security",
            "0003_rename_security_se_action__f34f6a_idx_security_se_action_a3e040_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="securityincident",
            options={
                "ordering": ["-detected_at"],
                "verbose_name": "Sistem Güvenlik Olayı",
                "verbose_name_plural": "Sistem Güvenlik Olayları",
            },
        ),
    ]
