"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = ["localhost", "127.0.0.1", "167.71.46.215", "finasis.com.tr", "www.finasis.com.tr"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'rest_framework',
    'crispy_forms',
    'crispy_bootstrap5',
    'channels',
    'FinAsis.apps.common.apps.CommonConfig',
    'FinAsis.apps.accounts',
    'FinAsis.apps.accounting',
    'FinAsis.apps.games',
    'FinAsis.apps.games.game_app',
    'FinAsis.apps.finance',
    'FinAsis.apps.finance.banking.apps.BankingConfig',
    'FinAsis.apps.finance.accounting.apps.AccountingConfig',
    'FinAsis.apps.blockchain',
    'FinAsis.apps.education',
    'FinAsis.apps.education.teacher_dashboard',
    'FinAsis.apps.management',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
            os.path.join(BASE_DIR, 'FinAsis', 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Use SQLite for local development unless explicitly disabled.
# Set USE_SQLITE=False in environment to use PostgreSQL settings below.
USE_SQLITE = config('USE_SQLITE', default=True, cast=bool)

if USE_SQLITE:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'finasis_db',
            'USER': 'postgres',
            'PASSWORD': 'FinAsis35',
            'HOST': 'localhost',
            'PORT': '5432',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 10}
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# AUTH_USER_MODEL = 'accounts.CustomUser'


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'tr-tr'

TIME_ZONE = 'Europe/Istanbul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'FinAsis', 'static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
ASGI_APPLICATION = "config.asgi.application"

SESSION_COOKIE_AGE = 60 * 30  # 30 dakika
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': os.path.join(BASE_DIR, 'cache'),
    }
}

# GÄ°B (e-Fatura / e-Defter) ayarlarÄ±
GIB_USERNAME = config('GIB_USERNAME', default='testuser')
GIB_PASSWORD = config('GIB_PASSWORD', default='testpass')
GIB_TEST_MODE = config('GIB_TEST_MODE', default=True, cast=bool)
GIB_EFATURA_BASE_URL = config('GIB_EFATURA_BASE_URL', default='https://efatura-test.efatura.gov.tr/api')
GIB_EDEFTER_BASE_URL = config('GIB_EDEFTER_BASE_URL', default='https://edefter-test.edefter.gov.tr/api')

# OCR/AI yerel ayarlarÄ±
USE_GOOGLE_VISION = config('USE_GOOGLE_VISION', default=False, cast=bool)
STT_ENABLED = config('STT_ENABLED', default=False, cast=bool)
VOSK_MODEL_PATH = config('VOSK_MODEL_PATH', default='')
AI_LOCAL_ONLY = config('AI_LOCAL_ONLY', default=True, cast=bool)
AI_PRIVACY_MODE = config('AI_PRIVACY_MODE', default=True, cast=bool)
