# Generated by Django 5.0.2 on 2025-04-09 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Model Adı')),
                ('model_type', models.CharField(choices=[('financial', 'Finansal Analiz'), ('recommendation', 'Öneri Sistemi'), ('chat', 'Sohbet Sistemi'), ('prediction', 'Tahmin Sistemi')], max_length=20, verbose_name='Model Tipi')),
                ('version', models.CharField(max_length=20, verbose_name='Versiyon')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('accuracy', models.FloatField(verbose_name='Doğruluk Oranı')),
                ('parameters', models.JSONField(default=dict, verbose_name='Model Parametreleri')),
                ('last_trained', models.DateTimeField(auto_now=True, verbose_name='Son Eğitim Tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'AI Model',
                'verbose_name_plural': 'AI Modeller',
                'ordering': ['-last_trained'],
            },
        ),
        migrations.CreateModel(
            name='AIFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='1-5 arası puanlama', verbose_name='Değerlendirme')),
                ('comment', models.TextField(blank=True, verbose_name='Yorum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_feedback', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='ai_assistant.aimodel', verbose_name='AI Model')),
            ],
            options={
                'verbose_name': 'AI Geri Bildirimi',
                'verbose_name_plural': 'AI Geri Bildirimleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_type', models.CharField(choices=[('market_trend', 'Piyasa Trendi'), ('stock_price', 'Hisse Fiyatı'), ('risk_analysis', 'Risk Analizi'), ('portfolio_optimization', 'Portföy Optimizasyonu')], max_length=50, verbose_name='Tahmin Tipi')),
                ('input_data', models.JSONField(verbose_name='Girdi Verileri')),
                ('prediction_result', models.TextField(verbose_name='Tahmin Sonucu')),
                ('confidence', models.FloatField(verbose_name='Güven Oranı')),
                ('is_validated', models.BooleanField(default=False, verbose_name='Doğrulandı')),
                ('validation_notes', models.TextField(blank=True, verbose_name='Doğrulama Notları')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('model_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_assistant.aimodel', verbose_name='Kullanılan Model')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_predictions', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Finansal Tahmin',
                'verbose_name_plural': 'Finansal Tahminler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('chat', 'Sohbet'), ('analysis', 'Analiz'), ('recommendation', 'Öneri')], max_length=20, verbose_name='Etkileşim Tipi')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('ai_response', models.TextField(verbose_name='AI Yanıtı')),
                ('feedback', models.IntegerField(blank=True, null=True, verbose_name='Geri Bildirim')),
                ('feedback_text', models.TextField(blank=True, verbose_name='Geri Bildirim Metni')),
                ('processing_time', models.FloatField(help_text='Saniye cinsinden', verbose_name='İşlem Süresi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_interactions', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kullanıcı Etkileşimi',
                'verbose_name_plural': 'Kullanıcı Etkileşimleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
