# Generated by Django 4.2.25 on 2025-11-02 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ai_assistant", "0002_sectorbenchmark"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentSummary",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("invoice", "Fatura"),
                            ("contract", "Sözleşme"),
                            ("report", "Rapor"),
                            ("email", "E-posta"),
                            ("meeting_notes", "Toplantı Notları"),
                            ("financial_statement", "Mali Tablo"),
                            ("legal_doc", "Hukuki Doküman"),
                            ("other", "Diğer"),
                        ],
                        max_length=30,
                        verbose_name="Doküman Tipi",
                    ),
                ),
                ("original_text", models.TextField(verbose_name="Orijinal Metin")),
                ("summary", models.TextField(verbose_name="Özet")),
                ("summary_length", models.IntegerField(verbose_name="Özet Uzunluğu (kelime)")),
                ("original_length", models.IntegerField(verbose_name="Orijinal Uzunluk (kelime)")),
                ("compression_ratio", models.FloatField(verbose_name="Sıkıştırma Oranı")),
                ("key_points", models.JSONField(blank=True, default=list, verbose_name="Ana Noktalar")),
                ("entities_mentioned", models.JSONField(blank=True, default=list, verbose_name="Bahsedilen Varlıklar")),
                ("language", models.CharField(default="tr", max_length=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("document_file", models.FileField(blank=True, null=True, upload_to="ai_summaries/")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_summaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Doküman Özeti",
                "verbose_name_plural": "Doküman Özetleri",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdvancedAnalytics",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "analytics_type",
                    models.CharField(
                        choices=[
                            ("revenue_forecast", "Gelir Tahmini"),
                            ("expense_pattern", "Gider Deseni"),
                            ("customer_segmentation", "Müşteri Segmentasyonu"),
                            ("churn_prediction", "Müşteri Kaybı Tahmini"),
                            ("profitability_analysis", "Karlılık Analizi"),
                            ("market_basket", "Market Basket Analizi"),
                            ("cohort_analysis", "Kohort Analizi"),
                            ("abc_analysis", "ABC Analizi"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("results", models.JSONField(default=dict, verbose_name="Analiz Sonuçları")),
                ("visualizations", models.JSONField(default=dict, verbose_name="Görselleştirmeler")),
                ("recommendations", models.JSONField(default=list, verbose_name="Öneriler")),
                ("accuracy_score", models.FloatField(blank=True, null=True)),
                ("confidence_level", models.FloatField(blank=True, null=True)),
                ("analysis_period_start", models.DateField(blank=True, null=True)),
                ("analysis_period_end", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advanced_analytics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Gelişmiş Analitik",
                "verbose_name_plural": "Gelişmiş Analitikler",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SentimentAnalysis",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("customer_feedback", "Müşteri Geri Bildirimi"),
                            ("invoice_note", "Fatura Notu"),
                            ("email", "E-posta"),
                            ("chat", "Sohbet"),
                            ("review", "Değerlendirme"),
                            ("social_media", "Sosyal Medya"),
                            ("document", "Doküman"),
                        ],
                        max_length=30,
                        verbose_name="Kaynak Tipi",
                    ),
                ),
                ("text_content", models.TextField(verbose_name="Analiz Edilen Metin")),
                (
                    "sentiment",
                    models.CharField(
                        choices=[("positive", "Pozitif"), ("neutral", "Nötr"), ("negative", "Negatif")],
                        max_length=20,
                        verbose_name="Duygu",
                    ),
                ),
                ("confidence_score", models.FloatField(help_text="0.0 - 1.0 arası", verbose_name="Güven Skoru")),
                ("positive_score", models.FloatField(default=0.0)),
                ("neutral_score", models.FloatField(default=0.0)),
                ("negative_score", models.FloatField(default=0.0)),
                ("keywords", models.JSONField(blank=True, default=list, verbose_name="Anahtar Kelimeler")),
                ("entities", models.JSONField(blank=True, default=list, verbose_name="Varlıklar")),
                ("language", models.CharField(default="tr", max_length=5, verbose_name="Dil")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reference_model", models.CharField(blank=True, max_length=50)),
                ("reference_id", models.IntegerField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sentiment_analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sentiment Analizi",
                "verbose_name_plural": "Sentiment Analizleri",
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["sentiment", "source_type"], name="ai_assistan_sentime_98d03f_idx")],
            },
        ),
        migrations.CreateModel(
            name="AutoGeneratedReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("daily_summary", "Günlük Özet"),
                            ("weekly_performance", "Haftalık Performans"),
                            ("monthly_financial", "Aylık Mali Rapor"),
                            ("quarterly_review", "Çeyreklik İnceleme"),
                            ("annual_report", "Yıllık Rapor"),
                            ("cash_flow", "Nakit Akışı"),
                            ("profit_loss", "Kar-Zarar"),
                            ("expense_analysis", "Gider Analizi"),
                            ("customer_insights", "Müşteri İçgörüleri"),
                            ("custom", "Özel Rapor"),
                        ],
                        max_length=30,
                        verbose_name="Rapor Tipi",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Rapor Başlığı")),
                ("content", models.TextField(blank=True, verbose_name="Rapor İçeriği")),
                ("summary", models.TextField(blank=True, verbose_name="Özet")),
                ("insights", models.JSONField(blank=True, default=list, verbose_name="İçgörüler")),
                ("metrics", models.JSONField(blank=True, default=dict, verbose_name="Metrikler")),
                ("charts_data", models.JSONField(blank=True, default=dict, verbose_name="Grafik Verileri")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generating", "Oluşturuluyor"),
                            ("completed", "Tamamlandı"),
                            ("failed", "Başarısız"),
                            ("scheduled", "Planlandı"),
                        ],
                        default="generating",
                        max_length=20,
                    ),
                ),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                ("pdf_file", models.FileField(blank=True, null=True, upload_to="ai_reports/pdf/")),
                ("excel_file", models.FileField(blank=True, null=True, upload_to="ai_reports/excel/")),
                ("is_scheduled", models.BooleanField(default=False)),
                ("schedule_frequency", models.CharField(blank=True, max_length=20)),
                ("next_generation", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Otomatik Rapor",
                "verbose_name_plural": "Otomatik Raporlar",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status", "report_type"], name="ai_assistan_status_458f6c_idx"),
                    models.Index(fields=["user", "created_at"], name="ai_assistan_user_id_1666bc_idx"),
                ],
            },
        ),
    ]
