# Generated by Django 5.2 on 2025-04-28 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0002_anomalydetection_financialreport_trendanalysis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=50)),
                ('current_price', models.FloatField()),
                ('change_percent', models.FloatField()),
                ('trend', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Piyasa Analizi',
                'verbose_name_plural': 'Piyasa Analizleri',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='aimodel',
            options={'ordering': ['-created_at'], 'verbose_name': 'AI Model', 'verbose_name_plural': 'AI Modeller'},
        ),
        migrations.RemoveField(
            model_name='aifeedback',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='financialprediction',
            name='model_version',
        ),
        migrations.AddField(
            model_name='aifeedback',
            name='feedback_text',
            field=models.TextField(blank=True, verbose_name='Geri Bildirim Metni'),
        ),
        migrations.AddField(
            model_name='financialprediction',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ai_assistant.aimodel', verbose_name='Kullanılan Model'),
        ),
        migrations.AlterField(
            model_name='aifeedback',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_assistant.aimodel', verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='aifeedback',
            name='rating',
            field=models.IntegerField(verbose_name='Değerlendirme'),
        ),
        migrations.AlterField(
            model_name='aifeedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.AlterField(
            model_name='financialprediction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.AlterField(
            model_name='userinteraction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('investment', 'Yatırım Önerisi'), ('risk', 'Risk Uyarısı'), ('opportunity', 'Fırsat Bildirimi'), ('trend', 'Trend Analizi')], max_length=50, verbose_name='İçgörü Türü')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('priority', models.CharField(choices=[('low', 'Düşük'), ('medium', 'Orta'), ('high', 'Yüksek'), ('urgent', 'Acil')], max_length=20, verbose_name='Öncelik')),
                ('action_required', models.BooleanField(default=False, verbose_name='Aksiyon Gerekli')),
                ('action_description', models.TextField(blank=True, verbose_name='Aksiyon Açıklaması')),
                ('is_read', models.BooleanField(default=False, verbose_name='Okundu')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Arşivlendi')),
                ('insight_data', models.JSONField(verbose_name='İçgörü Verisi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Geçerlilik Sonu')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_assistant.aimodel', verbose_name='Model')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'AI İçgörüsü',
                'verbose_name_plural': 'AI İçgörüleri',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('recommendations', models.JSONField()),
                ('category', models.CharField(max_length=100)),
                ('priority', models.CharField(choices=[('low', 'Düşük'), ('medium', 'Orta'), ('high', 'Yüksek')], max_length=10)),
                ('action_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='tr', max_length=10, verbose_name='Dil')),
                ('risk_tolerance', models.CharField(choices=[('low', 'Düşük'), ('medium', 'Orta'), ('high', 'Yüksek')], max_length=20, verbose_name='Risk Toleransı')),
                ('investment_horizon', models.CharField(choices=[('short', 'Kısa'), ('medium', 'Orta'), ('long', 'Uzun')], max_length=20, verbose_name='Yatırım Vadesi')),
                ('notification_preferences', models.JSONField(default=dict, verbose_name='Bildirim Tercihleri')),
                ('ai_interaction_history', models.JSONField(default=list, verbose_name='AI Etkileşim Geçmişi')),
                ('settings', models.JSONField(default=dict, verbose_name='Ayarlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('preferred_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_assistant.aimodel', verbose_name='Tercih Edilen Model')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kullanıcı Tercihi',
                'verbose_name_plural': 'Kullanıcı Tercihleri',
            },
        ),
    ]
