# Generated by Django 5.2.8 on 2025-12-15 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "ai_assistant",
            "0003_documentsummary_advancedanalytics_sentimentanalysis_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="financialreport",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "AI Finansal Rapor",
                "verbose_name_plural": "AI Finansal Raporlar",
            },
        ),
        migrations.AlterModelOptions(
            name="notification",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "AI Bildirimi",
                "verbose_name_plural": "AI Bildirimleri",
            },
        ),
        migrations.AlterModelOptions(
            name="userpreference",
            options={
                "verbose_name": "Kullanıcı Tercihi",
                "verbose_name_plural": "AI Kullanıcı Tercihleri",
            },
        ),
    ]
