# Generated by Django 5.2.1 on 2025-10-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0002_auto_20251009_2359"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditevent",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Audit Event",
                "verbose_name_plural": "Audit Events",
            },
        ),
        migrations.RenameIndex(
            model_name="auditevent",
            new_name="audit_audit_created_28d89c_idx",
            old_name="audit_audit_created_sever_idx",
        ),
        migrations.RenameIndex(
            model_name="auditevent",
            new_name="audit_audit_categor_27173c_idx",
            old_name="audit_audit_category_created_idx",
        ),
        migrations.RenameIndex(
            model_name="auditevent",
            new_name="audit_audit_actor_i_fb4253_idx",
            old_name="audit_audit_actor_created_idx",
        ),
        migrations.RenameIndex(
            model_name="auditevent",
            new_name="audit_audit_content_c1f818_idx",
            old_name="audit_audit_content_object_idx",
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="data",
            field=models.JSONField(
                blank=True, default=dict, help_text="Current state or event data"
            ),
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="diff",
            field=models.JSONField(
                blank=True, default=dict, help_text="Changes made (before/after)"
            ),
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="object_id",
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
