# Generated by Django 4.2.25 on 2025-11-02 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0015_remove_banktransaction_acc_banktxn_date_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("audit", "0003_alter_auditevent_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RiskMatrix",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("risk_name", models.CharField(max_length=200, verbose_name="Risk Adı")),
                ("risk_category", models.CharField(max_length=50, verbose_name="Risk Kategorisi")),
                (
                    "probability",
                    models.CharField(
                        choices=[
                            ("rare", "Çok Nadir (1)"),
                            ("unlikely", "Nadir (2)"),
                            ("possible", "Olası (3)"),
                            ("likely", "Muhtemel (4)"),
                            ("certain", "Kesin (5)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "impact",
                    models.CharField(
                        choices=[
                            ("negligible", "Önemsiz (1)"),
                            ("minor", "Küçük (2)"),
                            ("moderate", "Orta (3)"),
                            ("major", "Büyük (4)"),
                            ("catastrophic", "Felaket (5)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("risk_score", models.IntegerField(help_text="Olasılık x Etki (1-25)", verbose_name="Risk Skoru")),
                ("risk_level", models.CharField(max_length=20, verbose_name="Risk Seviyesi")),
                ("mitigation_plan", models.TextField(blank=True, verbose_name="Önleme Planı")),
                ("status", models.CharField(default="open", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_matrices",
                        to="accounting.company",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_risks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Risk Matrisi",
                "verbose_name_plural": "Risk Matrisleri",
                "ordering": ["-risk_score", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="RealTimeMonitoring",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("metric_name", models.CharField(max_length=100, verbose_name="Metrik Adı")),
                ("current_value", models.FloatField(verbose_name="Güncel Değer")),
                ("threshold_value", models.FloatField(verbose_name="Eşik Değer")),
                (
                    "alert_level",
                    models.CharField(
                        choices=[
                            ("info", "Bilgi"),
                            ("warning", "Uyarı"),
                            ("critical", "Kritik"),
                            ("emergency", "Acil"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                ("is_triggered", models.BooleanField(default=False)),
                ("message", models.TextField(blank=True)),
                ("resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Gerçek Zamanlı İzleme",
                "verbose_name_plural": "Gerçek Zamanlı İzlemeler",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ComplianceScore",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "compliance_area",
                    models.CharField(
                        choices=[
                            ("gdpr", "GDPR/KVKK"),
                            ("sox", "SOX Uyumluluğu"),
                            ("iso27001", "ISO 27001"),
                            ("pci_dss", "PCI DSS"),
                            ("hipaa", "HIPAA"),
                            ("financial", "Finansal Uyumluluk"),
                            ("tax", "Vergi Uyumluluğu"),
                            ("custom", "Özel Uyumluluk"),
                        ],
                        max_length=30,
                    ),
                ),
                ("score", models.IntegerField(help_text="0-100 arası", verbose_name="Uyumluluk Skoru")),
                ("max_score", models.IntegerField(default=100)),
                ("passed_checks", models.IntegerField(default=0)),
                ("failed_checks", models.IntegerField(default=0)),
                ("pending_checks", models.IntegerField(default=0)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("recommendations", models.JSONField(blank=True, default=list)),
                ("last_audit_date", models.DateField(blank=True, null=True)),
                ("next_audit_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "audited_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compliance_scores",
                        to="accounting.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Uyumluluk Skoru",
                "verbose_name_plural": "Uyumluluk Skorları",
                "ordering": ["-updated_at"],
                "unique_together": {("company", "compliance_area")},
            },
        ),
    ]
