groups:
- name: financial_alerts
  rules:
  - alert: HighTransactionErrorRate
    expr: rate(financial_transaction_errors_total[5m]) > 0.1
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Yüksek işlem hata oranı"
      description: "Son 5 dakikada işlem hata oranı %10'u aştı"

  - alert: SlowTransactionResponse
    expr: avg(financial_transaction_duration_seconds) > 2
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Yavaş işlem yanıt süresi"
      description: "Ortalama işlem süresi 2 saniyeyi aştı"

  - alert: HighSystemLoad
    expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Yüksek sistem yükü"
      description: "CPU kullanımı %80'i aştı"

  - alert: HighMemoryUsage
    expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Yüksek bellek kullanımı"
      description: "Bellek kullanımı %85'i aştı"

  - alert: HighDiskUsage
    expr: 100 - ((node_filesystem_avail_bytes * 100) / node_filesystem_size_bytes) > 85
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Yüksek disk kullanımı"
      description: "Disk kullanımı %85'i aştı" 