# Generated by Django 5.2.1

from django.db import migrations
import src.apps.accounts.models


def set_customuser_manager(apps, schema_editor):
    # No runtime changes needed; migration only needs to record the manager path
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_subscriptiontype_audience_subscriptiontype_features_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', src.apps.accounts.models.CustomUserManager()),
            ],
        ),
    ]
