# Generated by Django 5.0.2 on 2025-04-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-due_date'], 'verbose_name': 'Aktivite', 'verbose_name_plural': 'Aktiviteler'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['name'], 'verbose_name': 'İletişim Kişisi', 'verbose_name_plural': 'İletişim Kişileri'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name'], 'verbose_name': 'Müşteri', 'verbose_name_plural': 'Müşteriler'},
        ),
        migrations.AlterModelOptions(
            name='opportunity',
            options={'ordering': ['-created_at'], 'verbose_name': 'Fırsat', 'verbose_name_plural': 'Fırsatlar'},
        ),
        migrations.RemoveField(
            model_name='activity',
            name='activity_type',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='opportunity',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='department',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='is_primary',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='document',
            name='description',
        ),
        migrations.RemoveField(
            model_name='document',
            name='opportunity',
        ),
        migrations.RemoveField(
            model_name='document',
            name='title',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='description',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='expected_amount',
        ),
        migrations.AddField(
            model_name='activity',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notlar'),
        ),
        migrations.AddField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('planned', 'Planlandı'), ('in_progress', 'Devam Ediyor'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi')], default='planned', max_length=20, verbose_name='Durum'),
        ),
        migrations.AddField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('call', 'Telefon Görüşmesi'), ('meeting', 'Toplantı'), ('email', 'E-posta'), ('task', 'Görev')], default='task', max_length=20, verbose_name='Tür'),
        ),
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='İletişim Kişisi'),
        ),
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Müşteri Adı'),
        ),
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Belge Adı'),
        ),
        migrations.AddField(
            model_name='document',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notlar'),
        ),
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('contract', 'Sözleşme'), ('proposal', 'Teklif'), ('invoice', 'Fatura'), ('other', 'Diğer')], default='other', max_length=20, verbose_name='Tür'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Tutar'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='due_date',
            field=models.DateField(verbose_name='Bitiş Tarihi'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='subject',
            field=models.CharField(default='', max_length=200, verbose_name='Konu'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tax_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Vergi Numarası'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tax_office',
            field=models.CharField(blank=True, max_length=100, verbose_name='Vergi Dairesi'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/', verbose_name='Dosya'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='expected_close_date',
            field=models.DateField(verbose_name='Beklenen Kapanış Tarihi'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Fırsat Adı'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='status',
            field=models.CharField(choices=[('new', 'Yeni'), ('qualified', 'Nitelikli'), ('proposal', 'Teklif'), ('negotiation', 'Görüşme'), ('closed_won', 'Kazanıldı'), ('closed_lost', 'Kaybedildi')], default='new', max_length=20, verbose_name='Durum'),
        ),
    ]
