# Generated by Django 4.2.25 on 2025-11-02 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MockIntegration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="Entegrasyon Adı")),
                (
                    "integration_type",
                    models.CharField(
                        choices=[
                            ("GIB", "GİB (Gelir İdaresi)"),
                            ("BANK", "Banka"),
                            ("PAYMENT", "Ödeme Gateway"),
                            ("SMS", "SMS Provider"),
                            ("EMAIL", "Email Provider"),
                            ("OTHER", "Diğer"),
                        ],
                        max_length=20,
                        verbose_name="Entegrasyon Tipi",
                    ),
                ),
                ("mock_endpoint", models.URLField(verbose_name="Mock Endpoint")),
                ("default_response", models.JSONField(default=dict, verbose_name="Varsayılan Yanıt")),
                ("response_delay_ms", models.IntegerField(default=100, verbose_name="Yanıt Gecikmesi (ms)")),
                ("success_rate", models.IntegerField(default=100, help_text="0-100", verbose_name="Başarı Oranı (%)")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Mock Entegrasyon",
                "verbose_name_plural": "Mock Entegrasyonlar",
                "ordering": ["integration_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="MockScenario",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="Senaryo Adı")),
                ("description", models.TextField(verbose_name="Açıklama")),
                ("conditions", models.JSONField(default=dict, verbose_name="Koşullar")),
                ("response_data", models.JSONField(default=dict, verbose_name="Yanıt Verisi")),
                ("response_code", models.IntegerField(default=200, verbose_name="HTTP Durum Kodu")),
                ("priority", models.IntegerField(default=0, verbose_name="Öncelik")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("usage_count", models.IntegerField(default=0, verbose_name="Kullanım Sayısı")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scenarios",
                        to="integrator_mock.mockintegration",
                        verbose_name="Entegrasyon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mock Senaryo",
                "verbose_name_plural": "Mock Senaryolar",
                "ordering": ["-priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="MockRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("request_method", models.CharField(max_length=10, verbose_name="HTTP Metodu")),
                ("request_path", models.CharField(max_length=500, verbose_name="İstek Yolu")),
                ("request_headers", models.JSONField(default=dict, verbose_name="İstek Headers")),
                ("request_body", models.JSONField(default=dict, verbose_name="İstek Body")),
                ("response_status", models.IntegerField(verbose_name="HTTP Durum Kodu")),
                ("response_body", models.JSONField(default=dict, verbose_name="Yanıt Body")),
                ("response_time_ms", models.IntegerField(verbose_name="Yanıt Süresi (ms)")),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True, verbose_name="IP Adresi")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="integrator_mock.mockintegration",
                        verbose_name="Entegrasyon",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mock İstek",
                "verbose_name_plural": "Mock İstekler",
                "ordering": ["-created_at"],
            },
        ),
    ]
