# Generated by Django 5.2.1 on 2025-05-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_aiconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Taslak'), ('POSTED', 'Kaydedildi'), ('CANCELLED', 'İptal Edildi')], default='DRAFT', max_length=20, verbose_name='Durum'),
        ),
    ]
