# Generated by Django 5.2.6 on 2025-09-28 09:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0009_planningscenario"),
        ("finance", "0006_databackup_datasubjectrequest_encryptionkey_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChartOfAccounts",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(help_text="Örn: 100, 120.01", max_length=20, verbose_name="Hesap Kodu")),
                ("name", models.CharField(max_length=200, verbose_name="Hesap Adı")),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("1", "Dönen Varlıklar"),
                            ("2", "Duran Varlıklar"),
                            ("3", "Kısa Vadeli Yabancı Kaynaklar"),
                            ("4", "Uzun Vadeli Yabancı Kaynaklar"),
                            ("5", "Özkaynaklar"),
                            ("6", "Gelir Hesapları"),
                            ("7", "Maliyet Hesapları"),
                            ("8", "Gider Hesapları"),
                        ],
                        max_length=1,
                        verbose_name="Ana Grup",
                    ),
                ),
                ("level", models.PositiveIntegerField(default=1, verbose_name="Seviye")),
                (
                    "is_detail_account",
                    models.BooleanField(
                        default=False, help_text="Bu hesaba doğrudan kayıt yapılabilir mi?", verbose_name="Detay Hesap"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chart_of_accounts",
                        to="accounting.company",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_accounts",
                        to="finance.chartofaccounts",
                        verbose_name="Ana Hesap",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hesap Planı",
                "verbose_name_plural": "Hesap Planları",
                "ordering": ["code"],
                "unique_together": {("company", "code")},
            },
        ),
        migrations.CreateModel(
            name="DepreciationMethod",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Yöntem Adı")),
                (
                    "method_type",
                    models.CharField(
                        choices=[
                            ("STRAIGHT_LINE", "Doğrusal (Normal) Amortisman"),
                            ("DECLINING_BALANCE", "Azalan Bakiye"),
                            ("UNITS_OF_PRODUCTION", "Üretim Miktarı"),
                        ],
                        max_length=20,
                        verbose_name="Yöntem Tipi",
                    ),
                ),
                (
                    "rate_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Oran %",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="depreciation_methods",
                        to="accounting.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Amortisman Yöntemi",
                "verbose_name_plural": "Amortisman Yöntemleri",
            },
        ),
        migrations.CreateModel(
            name="FiscalPeriod",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Örn: 2024 Mali Yılı", max_length=100, verbose_name="Dönem Adı")),
                ("start_date", models.DateField(verbose_name="Başlangıç Tarihi")),
                ("end_date", models.DateField(verbose_name="Bitiş Tarihi")),
                ("is_closed", models.BooleanField(default=False, verbose_name="Kapalı")),
                ("closed_at", models.DateTimeField(blank=True, null=True, verbose_name="Kapanış Zamanı")),
                ("notes", models.TextField(blank=True, verbose_name="Notlar")),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kapatan Kullanıcı",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fiscal_periods",
                        to="accounting.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mali Dönem",
                "verbose_name_plural": "Mali Dönemler",
                "ordering": ["-start_date"],
                "unique_together": {("company", "start_date", "end_date")},
            },
        ),
        migrations.CreateModel(
            name="FixedAsset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("asset_code", models.CharField(max_length=50, unique=True, verbose_name="Demirbaş Kodu")),
                ("name", models.CharField(max_length=200, verbose_name="Demirbaş Adı")),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                ("purchase_date", models.DateField(verbose_name="Satın Alma Tarihi")),
                (
                    "purchase_cost",
                    models.DecimalField(decimal_places=2, max_digits=15, verbose_name="Satın Alma Maliyeti"),
                ),
                ("useful_life_years", models.PositiveIntegerField(verbose_name="Faydalı Ömür (Yıl)")),
                (
                    "salvage_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=15, verbose_name="Hurda Değeri"
                    ),
                ),
                ("depreciation_start_date", models.DateField(verbose_name="Amortisman Başlangıç Tarihi")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Aktif"),
                            ("DISPOSED", "Elden Çıkarılmış"),
                            ("UNDER_CONSTRUCTION", "Yapım Halinde"),
                            ("IDLE", "Atıl"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=100, verbose_name="Konum")),
                ("responsible_person", models.CharField(blank=True, max_length=100, verbose_name="Sorumlu Kişi")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "accumulated_depreciation_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fixed_assets_depreciation",
                        to="finance.chartofaccounts",
                        verbose_name="Birikmiş Amortisman Hesabı",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fixed_assets",
                        to="accounting.company",
                    ),
                ),
                (
                    "cost_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fixed_assets_cost",
                        to="finance.chartofaccounts",
                        verbose_name="Maliyet Hesabı",
                    ),
                ),
                (
                    "depreciation_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="finance.depreciationmethod",
                        verbose_name="Amortisman Yöntemi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sabit Kıymet",
                "verbose_name_plural": "Sabit Kıymetler",
                "ordering": ["asset_code"],
            },
        ),
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("item_code", models.CharField(max_length=50, verbose_name="Stok Kodu")),
                ("name", models.CharField(max_length=200, verbose_name="Stok Adı")),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "inventory_type",
                    models.CharField(
                        choices=[
                            ("RAW_MATERIAL", "Hammadde"),
                            ("FINISHED_GOODS", "Mamul"),
                            ("MERCHANDISE", "Ticari Mal"),
                            ("CONSUMABLES", "Sarf Malzemesi"),
                            ("PACKAGING", "Ambalaj"),
                        ],
                        max_length=20,
                        verbose_name="Stok Tipi",
                    ),
                ),
                (
                    "unit_of_measure",
                    models.CharField(
                        default="ADET", help_text="KG, LT, M2, ADET vb.", max_length=10, verbose_name="Ölçü Birimi"
                    ),
                ),
                (
                    "valuation_method",
                    models.CharField(
                        choices=[
                            ("FIFO", "İlk Giren İlk Çıkar"),
                            ("LIFO", "Son Giren İlk Çıkar"),
                            ("WEIGHTED_AVERAGE", "Ağırlıklı Ortalama"),
                        ],
                        default="WEIGHTED_AVERAGE",
                        max_length=20,
                        verbose_name="Değerleme Yöntemi",
                    ),
                ),
                (
                    "current_quantity",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=15, verbose_name="Mevcut Miktar"
                    ),
                ),
                (
                    "minimum_quantity",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=15, verbose_name="Minimum Miktar"
                    ),
                ),
                (
                    "maximum_quantity",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=15, verbose_name="Maksimum Miktar"
                    ),
                ),
                (
                    "last_purchase_price",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=15, verbose_name="Son Alış Fiyatı"
                    ),
                ),
                (
                    "average_cost",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=15, verbose_name="Ortalama Maliyet"
                    ),
                ),
                (
                    "standard_selling_price",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=15, verbose_name="Standart Satış Fiyatı"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_items",
                        to="accounting.company",
                    ),
                ),
                (
                    "cost_of_sales_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_costs",
                        to="finance.chartofaccounts",
                        verbose_name="Satılan Malın Maliyeti Hesabı",
                    ),
                ),
                (
                    "inventory_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_items",
                        to="finance.chartofaccounts",
                        verbose_name="Stok Hesabı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stok Kalemi",
                "verbose_name_plural": "Stok Kalemleri",
                "ordering": ["item_code"],
                "unique_together": {("company", "item_code")},
            },
        ),
        migrations.CreateModel(
            name="JournalVoucher",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "voucher_number",
                    models.CharField(help_text="Şirket bazında benzersiz", max_length=20, verbose_name="Fiş Numarası"),
                ),
                (
                    "voucher_type",
                    models.CharField(
                        choices=[
                            ("GENERAL", "Genel Yevmiye"),
                            ("PURCHASE", "Alış Faturası"),
                            ("SALE", "Satış Faturası"),
                            ("CASH", "Kasa"),
                            ("BANK", "Banka"),
                            ("PAYROLL", "Bordro"),
                            ("DEPRECIATION", "Amortisman"),
                            ("ADJUSTMENT", "Düzeltme"),
                            ("CLOSING", "Kapanış"),
                        ],
                        max_length=20,
                        verbose_name="Fiş Tipi",
                    ),
                ),
                ("date", models.DateField(verbose_name="Tarih")),
                ("description", models.TextField(verbose_name="Açıklama")),
                (
                    "reference_number",
                    models.CharField(
                        blank=True, help_text="Fatura no, dekont no vb.", max_length=100, verbose_name="Referans No"
                    ),
                ),
                (
                    "total_debit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=15, verbose_name="Toplam Borç"
                    ),
                ),
                (
                    "total_credit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=15, verbose_name="Toplam Alacak"
                    ),
                ),
                ("is_posted", models.BooleanField(default=False, verbose_name="Kaydedildi")),
                ("is_balanced", models.BooleanField(default=False, verbose_name="Dengeli")),
                ("posted_at", models.DateTimeField(blank=True, null=True, verbose_name="Kayıt Zamanı")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_vouchers",
                        to="accounting.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_vouchers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan",
                    ),
                ),
                (
                    "fiscal_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journal_vouchers",
                        to="finance.fiscalperiod",
                        verbose_name="Mali Dönem",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posted_vouchers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kaydeden",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yevmiye Fişi",
                "verbose_name_plural": "Yevmiye Fişleri",
                "ordering": ["-date", "-voucher_number"],
            },
        ),
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("line_number", models.PositiveIntegerField(verbose_name="Satır No")),
                ("description", models.CharField(blank=True, max_length=255, verbose_name="Açıklama")),
                (
                    "debit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Borç Tutarı",
                    ),
                ),
                (
                    "credit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Alacak Tutarı",
                    ),
                ),
                ("cost_center", models.CharField(blank=True, max_length=50, verbose_name="Masraf Merkezi")),
                ("project_code", models.CharField(blank=True, max_length=50, verbose_name="Proje Kodu")),
                ("currency_code", models.CharField(default="TRY", max_length=3, verbose_name="Para Birimi")),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("1"), max_digits=10, verbose_name="Döviz Kuru"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journal_entries",
                        to="finance.chartofaccounts",
                        verbose_name="Hesap",
                    ),
                ),
                (
                    "voucher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_entries",
                        to="finance.journalvoucher",
                        verbose_name="Fiş",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yevmiye Kaydı",
                "verbose_name_plural": "Yevmiye Kayıtları",
                "ordering": ["voucher", "line_number"],
            },
        ),
        migrations.CreateModel(
            name="DepreciationEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(verbose_name="Tarih")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15, verbose_name="Amortisman Tutarı")),
                ("notes", models.TextField(blank=True, verbose_name="Notlar")),
                (
                    "is_automatic",
                    models.BooleanField(
                        default=True, help_text="Sistem tarafından otomatik hesaplanan", verbose_name="Otomatik"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fiscal_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="depreciation_entries",
                        to="finance.fiscalperiod",
                    ),
                ),
                (
                    "fixed_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="depreciation_entries",
                        to="finance.fixedasset",
                        verbose_name="Sabit Kıymet",
                    ),
                ),
                (
                    "voucher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="finance.journalvoucher",
                        verbose_name="Yevmiye Fişi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Amortisman Kaydı",
                "verbose_name_plural": "Amortisman Kayıtları",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("PURCHASE", "Alış"),
                            ("SALE", "Satış"),
                            ("PRODUCTION", "Üretim"),
                            ("ADJUSTMENT", "Sayım Farkı"),
                            ("TRANSFER", "Transfer"),
                            ("RETURN", "İade"),
                            ("WASTE", "Fire"),
                        ],
                        max_length=20,
                        verbose_name="Hareket Tipi",
                    ),
                ),
                ("date", models.DateField(verbose_name="Tarih")),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=15, verbose_name="Miktar")),
                ("unit_cost", models.DecimalField(decimal_places=4, max_digits=15, verbose_name="Birim Maliyet")),
                ("total_cost", models.DecimalField(decimal_places=2, max_digits=15, verbose_name="Toplam Maliyet")),
                ("is_inbound", models.BooleanField(help_text="True: Giriş, False: Çıkış", verbose_name="Giriş")),
                (
                    "reference_document",
                    models.CharField(
                        blank=True,
                        help_text="Fatura no, irsaliye no vb.",
                        max_length=100,
                        verbose_name="Referans Belge",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to="accounting.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to="finance.inventoryitem",
                        verbose_name="Stok Kalemi",
                    ),
                ),
                (
                    "voucher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="finance.journalvoucher",
                        verbose_name="Muhasebe Fişi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stok Hareketi",
                "verbose_name_plural": "Stok Hareketleri",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaxRate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Vergi Adı")),
                (
                    "tax_type",
                    models.CharField(
                        choices=[
                            ("VAT", "KDV"),
                            ("SCT", "ÖTV"),
                            ("WHT", "Stopaj"),
                            ("STAMP", "Damga Vergisi"),
                            ("OTHER", "Diğer"),
                        ],
                        max_length=10,
                        verbose_name="Vergi Tipi",
                    ),
                ),
                ("rate_percentage", models.DecimalField(decimal_places=2, max_digits=5, verbose_name="Oran %")),
                ("valid_from", models.DateField(verbose_name="Geçerlilik Başlangıcı")),
                ("valid_to", models.DateField(blank=True, null=True, verbose_name="Geçerlilik Bitişi")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tax_rates",
                        to="finance.chartofaccounts",
                        verbose_name="Vergi Hesabı",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="tax_rates", to="accounting.company"
                    ),
                ),
            ],
            options={
                "verbose_name": "Vergi Oranı",
                "verbose_name_plural": "Vergi Oranları",
                "ordering": ["tax_type", "rate_percentage"],
            },
        ),
        migrations.CreateModel(
            name="CostCenter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=20, verbose_name="Masraf Merkezi Kodu")),
                ("name", models.CharField(max_length=100, verbose_name="Masraf Merkezi Adı")),
                ("manager", models.CharField(blank=True, max_length=100, verbose_name="Sorumlu")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "budget_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="finance.chartofaccounts",
                        verbose_name="Bütçe Hesabı",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_centers",
                        to="accounting.company",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_centers",
                        to="finance.costcenter",
                        verbose_name="Ana Masraf Merkezi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Masraf Merkezi",
                "verbose_name_plural": "Masraf Merkezleri",
                "ordering": ["code"],
                "unique_together": {("company", "code")},
            },
        ),
        migrations.AddIndex(
            model_name="journalvoucher",
            index=models.Index(fields=["company", "date"], name="finance_jou_company_71c28b_idx"),
        ),
        migrations.AddIndex(
            model_name="journalvoucher",
            index=models.Index(fields=["company", "voucher_type"], name="finance_jou_company_ac6fa3_idx"),
        ),
        migrations.AddIndex(
            model_name="journalvoucher",
            index=models.Index(fields=["is_posted"], name="finance_jou_is_post_42e98d_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="journalvoucher",
            unique_together={("company", "voucher_number")},
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(fields=["account"], name="finance_jou_account_d972a3_idx"),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(fields=["voucher", "account"], name="finance_jou_voucher_b9c6ea_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="journalentry",
            unique_together={("voucher", "line_number")},
        ),
        migrations.AlterUniqueTogether(
            name="depreciationentry",
            unique_together={("fixed_asset", "fiscal_period", "date")},
        ),
    ]
