# Generated by Django 4.2.25 on 2025-11-02 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NavigationMenu",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Menü Adı")),
                ("slug", models.SlugField(max_length=100, unique=True, verbose_name="Slug")),
                (
                    "menu_type",
                    models.CharField(
                        choices=[
                            ("header", "Üst Menü"),
                            ("footer", "Alt Menü"),
                            ("sidebar", "Yan Menü"),
                            ("mobile", "Mobil Menü"),
                        ],
                        max_length=20,
                        verbose_name="Menü Tipi",
                    ),
                ),
                (
                    "target_roles",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Boş bırakılırsa herkese gösterilir",
                        verbose_name="Hedef Roller",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Navigasyon Menüsü",
                "verbose_name_plural": "Navigasyon Menüleri",
                "ordering": ["menu_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="Tema Adı")),
                ("slug", models.SlugField(max_length=100, unique=True, verbose_name="Slug")),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                ("primary_color", models.CharField(default="#007bff", max_length=7, verbose_name="Ana Renk")),
                ("secondary_color", models.CharField(default="#6c757d", max_length=7, verbose_name="İkincil Renk")),
                ("success_color", models.CharField(default="#28a745", max_length=7, verbose_name="Başarı Rengi")),
                ("danger_color", models.CharField(default="#dc3545", max_length=7, verbose_name="Hata Rengi")),
                ("warning_color", models.CharField(default="#ffc107", max_length=7, verbose_name="Uyarı Rengi")),
                ("info_color", models.CharField(default="#17a2b8", max_length=7, verbose_name="Bilgi Rengi")),
                ("background_color", models.CharField(default="#ffffff", max_length=7, verbose_name="Arka Plan Rengi")),
                ("text_color", models.CharField(default="#212529", max_length=7, verbose_name="Metin Rengi")),
                (
                    "font_family",
                    models.CharField(
                        default="Inter, system-ui, sans-serif", max_length=200, verbose_name="Font Ailesi"
                    ),
                ),
                ("font_size_base", models.CharField(default="14px", max_length=10, verbose_name="Temel Font Boyutu")),
                ("border_radius", models.CharField(default="8px", max_length=10, verbose_name="Köşe Yuvarlaklığı")),
                (
                    "box_shadow",
                    models.CharField(default="0 2px 8px rgba(0,0,0,0.1)", max_length=100, verbose_name="Gölge"),
                ),
                ("custom_css", models.TextField(blank=True, verbose_name="Özel CSS")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("is_default", models.BooleanField(default=False, verbose_name="Varsayılan")),
                ("thumbnail", models.ImageField(blank=True, null=True, upload_to="themes/", verbose_name="Önizleme")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tema",
                "verbose_name_plural": "Temalar",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Widget",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200, verbose_name="Widget Başlığı")),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("html", "HTML"),
                            ("text", "Metin"),
                            ("button", "Buton"),
                            ("card", "Kart"),
                            ("stats", "İstatistik"),
                            ("chart", "Grafik"),
                            ("form", "Form"),
                            ("custom", "Özel"),
                        ],
                        max_length=20,
                        verbose_name="Widget Tipi",
                    ),
                ),
                ("content", models.TextField(verbose_name="İçerik")),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("header", "Üst Kısım"),
                            ("sidebar_left", "Sol Kenar"),
                            ("sidebar_right", "Sağ Kenar"),
                            ("footer", "Alt Kısım"),
                            ("content_top", "İçerik Üstü"),
                            ("content_bottom", "İçerik Altı"),
                        ],
                        max_length=20,
                        verbose_name="Konum",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Sıra")),
                ("css_classes", models.CharField(blank=True, max_length=200, verbose_name="CSS Sınıfları")),
                ("custom_css", models.TextField(blank=True, verbose_name="Özel CSS")),
                (
                    "target_pages",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Boş bırakılırsa tüm sayfalarda gösterilir",
                        verbose_name="Hedef Sayfalar",
                    ),
                ),
                ("target_roles", models.JSONField(blank=True, default=list, verbose_name="Hedef Roller")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_widgets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Widget",
                "verbose_name_plural": "Widgetlar",
                "ordering": ["position", "order"],
            },
        ),
        migrations.CreateModel(
            name="UserThemePreference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("dark_mode", models.BooleanField(default=False, verbose_name="Koyu Mod")),
                ("auto_dark_mode", models.BooleanField(default=True, verbose_name="Otomatik Koyu Mod")),
                ("sidebar_collapsed", models.BooleanField(default=False, verbose_name="Kenar Çubuğu Daraltılmış")),
                ("compact_mode", models.BooleanField(default=False, verbose_name="Kompakt Mod")),
                (
                    "font_size",
                    models.CharField(
                        choices=[("small", "Küçük"), ("medium", "Orta"), ("large", "Büyük")],
                        default="medium",
                        max_length=10,
                        verbose_name="Font Boyutu",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "theme",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="core_ui.theme", verbose_name="Tema"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="theme_preference",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kullanıcı Tema Tercihi",
                "verbose_name_plural": "Kullanıcı Tema Tercihleri",
            },
        ),
        migrations.CreateModel(
            name="UIComponent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="Bileşen Adı")),
                ("slug", models.SlugField(max_length=100, unique=True, verbose_name="Slug")),
                (
                    "component_type",
                    models.CharField(
                        choices=[
                            ("card", "Kart"),
                            ("modal", "Modal"),
                            ("alert", "Uyarı"),
                            ("table", "Tablo"),
                            ("list", "Liste"),
                            ("grid", "Grid"),
                            ("carousel", "Carousel"),
                            ("accordion", "Accordion"),
                            ("tabs", "Sekmeler"),
                            ("custom", "Özel"),
                        ],
                        max_length=20,
                        verbose_name="Bileşen Tipi",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                ("template_code", models.TextField(verbose_name="Template Kodu")),
                ("default_params", models.JSONField(blank=True, default=dict, verbose_name="Varsayılan Parametreler")),
                ("preview_data", models.JSONField(blank=True, default=dict, verbose_name="Önizleme Verisi")),
                (
                    "screenshot",
                    models.ImageField(blank=True, null=True, upload_to="components/", verbose_name="Ekran Görüntüsü"),
                ),
                ("version", models.CharField(default="1.0", max_length=20, verbose_name="Versiyon")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_components",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan",
                    ),
                ),
            ],
            options={
                "verbose_name": "UI Bileşeni",
                "verbose_name_plural": "UI Bileşenleri",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200, verbose_name="Sayfa Başlığı")),
                ("slug", models.SlugField(max_length=200, unique=True, verbose_name="Slug")),
                (
                    "page_type",
                    models.CharField(
                        choices=[
                            ("standard", "Standart Sayfa"),
                            ("landing", "Landing Page"),
                            ("faq", "SSS"),
                            ("terms", "Kullanım Koşulları"),
                            ("privacy", "Gizlilik Politikası"),
                            ("about", "Hakkımızda"),
                            ("contact", "İletişim"),
                        ],
                        default="standard",
                        max_length=20,
                        verbose_name="Sayfa Tipi",
                    ),
                ),
                ("content", models.TextField(verbose_name="İçerik (HTML)")),
                ("excerpt", models.TextField(blank=True, verbose_name="Özet")),
                ("meta_title", models.CharField(blank=True, max_length=200, verbose_name="Meta Başlık")),
                ("meta_description", models.TextField(blank=True, verbose_name="Meta Açıklama")),
                ("meta_keywords", models.CharField(blank=True, max_length=500, verbose_name="Meta Anahtar Kelimeler")),
                (
                    "featured_image",
                    models.ImageField(blank=True, null=True, upload_to="pages/", verbose_name="Öne Çıkan Görsel"),
                ),
                ("custom_css", models.TextField(blank=True, verbose_name="Özel CSS")),
                ("custom_js", models.TextField(blank=True, verbose_name="Özel JavaScript")),
                ("is_published", models.BooleanField(default=False, verbose_name="Yayınlandı")),
                ("published_at", models.DateTimeField(blank=True, null=True, verbose_name="Yayın Tarihi")),
                ("view_count", models.IntegerField(default=0, verbose_name="Görüntüleme")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authored_pages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yazar",
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core_ui.theme",
                        verbose_name="Özel Tema",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sayfa",
                "verbose_name_plural": "Sayfalar",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100, verbose_name="Başlık")),
                ("url", models.CharField(max_length=500, verbose_name="URL")),
                ("icon", models.CharField(blank=True, max_length=50, verbose_name="İkon (Bootstrap Icons)")),
                ("target_blank", models.BooleanField(default=False, verbose_name="Yeni Sekmede Aç")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("order", models.IntegerField(default=0, verbose_name="Sıra")),
                ("badge_text", models.CharField(blank=True, max_length=20, verbose_name="Rozet Metni")),
                (
                    "badge_color",
                    models.CharField(
                        blank=True,
                        help_text="primary, success, danger, warning, info",
                        max_length=20,
                        verbose_name="Rozet Rengi",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core_ui.navigationmenu",
                        verbose_name="Menü",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="core_ui.menuitem",
                        verbose_name="Üst Öğe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menü Öğesi",
                "verbose_name_plural": "Menü Öğeleri",
                "ordering": ["menu", "order", "title"],
            },
        ),
        migrations.CreateModel(
            name="Banner",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200, verbose_name="Başlık")),
                ("message", models.TextField(verbose_name="Mesaj")),
                (
                    "banner_type",
                    models.CharField(
                        choices=[
                            ("info", "Bilgilendirme"),
                            ("success", "Başarı"),
                            ("warning", "Uyarı"),
                            ("danger", "Hata"),
                            ("announcement", "Duyuru"),
                        ],
                        default="info",
                        max_length=20,
                        verbose_name="Tip",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[("top", "Üst"), ("bottom", "Alt"), ("floating", "Yüzer")],
                        default="top",
                        max_length=20,
                        verbose_name="Konum",
                    ),
                ),
                ("button_text", models.CharField(blank=True, max_length=50, verbose_name="Buton Metni")),
                ("button_url", models.CharField(blank=True, max_length=500, verbose_name="Buton URL")),
                ("show_to_guests", models.BooleanField(default=True, verbose_name="Misafirlere Göster")),
                ("show_to_authenticated", models.BooleanField(default=True, verbose_name="Üyelere Göster")),
                ("target_roles", models.JSONField(blank=True, default=list, verbose_name="Hedef Roller")),
                ("start_date", models.DateTimeField(blank=True, null=True, verbose_name="Başlangıç Tarihi")),
                ("end_date", models.DateTimeField(blank=True, null=True, verbose_name="Bitiş Tarihi")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("is_dismissible", models.BooleanField(default=True, verbose_name="Kapatılabilir")),
                ("view_count", models.IntegerField(default=0, verbose_name="Görüntüleme")),
                ("click_count", models.IntegerField(default=0, verbose_name="Tıklama")),
                (
                    "priority",
                    models.IntegerField(default=0, help_text="Yüksek öncelik üstte gösterilir", verbose_name="Öncelik"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_banners",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Banner",
                "verbose_name_plural": "Bannerlar",
                "ordering": ["-priority", "-created_at"],
            },
        ),
    ]
