# Generated by Django 4.2.23 on 2025-09-01 20:36

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0008_auditlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("finance_accounting", "0004_autobookingrule"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=10, unique=True, verbose_name="Kod"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Ad")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Açıklama"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
            ],
            options={
                "verbose_name": "Hesap Tipi",
                "verbose_name_plural": "Hesap Tipleri",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=3, unique=True, verbose_name="Kod"),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Ad")),
                ("symbol", models.CharField(max_length=5, verbose_name="Sembol")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Varsayılan"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
            ],
            options={
                "verbose_name": "Para Birimi",
                "verbose_name_plural": "Para Birimleri",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="FiscalYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fiscal_years",
                        to="accounting.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mali Yıl",
                "verbose_name_plural": "Mali Yıllar",
            },
        ),
        migrations.CreateModel(
            name="VoucherType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=10, unique=True, verbose_name="Kod"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Ad")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Açıklama"),
                ),
                (
                    "prefix",
                    models.CharField(
                        blank=True, max_length=5, null=True, verbose_name="Önek"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Fiş Tipi",
                "verbose_name_plural": "Fiş Tipleri",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Voucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(max_length=20, verbose_name="Fiş Numarası"),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Fiş Tarihi"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Açıklama"),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Referans"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Taslak"),
                            ("posted", "Kaydedildi"),
                            ("cancelled", "İptal Edildi"),
                        ],
                        default="draft",
                        max_length=10,
                        verbose_name="Durum",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("1.000000"),
                        max_digits=18,
                        verbose_name="Kur",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vouchers",
                        to="accounting.company",
                        verbose_name="Şirket",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vouchers",
                        to="finance_accounting.currency",
                    ),
                ),
                (
                    "fiscal_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vouchers",
                        to="finance_accounting.fiscalyear",
                        verbose_name="Mali Yıl",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vouchers",
                        to="finance_accounting.vouchertype",
                        verbose_name="Fiş Tipi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fiş",
                "verbose_name_plural": "Fişler",
                "ordering": ["company", "fiscal_year", "-date", "-number"],
                "unique_together": {("company", "fiscal_year", "type", "number")},
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Fatura Numarası"
                    ),
                ),
                ("issue_date", models.DateField(verbose_name="Düzenleme Tarihi")),
                ("due_date", models.DateField(verbose_name="Vade Tarihi")),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Toplam Tutar"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Taslak"),
                            ("APPROVED", "Onaylandı"),
                            ("PAID", "Ödendi"),
                            ("CANCELED", "İptal Edildi"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounting.customer",
                        verbose_name="Müşteri",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fatura",
                "verbose_name_plural": "Faturalar",
                "ordering": ["-issue_date"],
            },
        ),
        migrations.CreateModel(
            name="FinancialReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Rapor Adı")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("balance_sheet", "Bilanço"),
                            ("income_statement", "Gelir Tablosu"),
                            ("cash_flow", "Nakit Akışı"),
                            ("trial_balance", "Mizan"),
                            ("custom", "Özel Rapor"),
                        ],
                        max_length=20,
                        verbose_name="Rapor Tipi",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Başlangıç Tarihi")),
                ("end_date", models.DateField(verbose_name="Bitiş Tarihi")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Açıklama"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_reports",
                        to="accounting.company",
                        verbose_name="Şirket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mali Rapor",
                "verbose_name_plural": "Mali Raporlar",
            },
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, verbose_name="Hesap Kodu")),
                ("name", models.CharField(max_length=150, verbose_name="Hesap Adı")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Açıklama"),
                ),
                (
                    "is_tax_account",
                    models.BooleanField(default=False, verbose_name="Vergi Hesabı"),
                ),
                (
                    "is_bank_account",
                    models.BooleanField(default=False, verbose_name="Banka Hesabı"),
                ),
                (
                    "is_cash_account",
                    models.BooleanField(default=False, verbose_name="Kasa Hesabı"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to="accounting.company",
                        verbose_name="Şirket",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="finance_accounting.account",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accounts",
                        to="finance_accounting.accounttype",
                        verbose_name="Hesap Tipi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hesap",
                "verbose_name_plural": "Hesaplar",
                "ordering": ["company", "code"],
                "unique_together": {("company", "code")},
            },
        ),
        migrations.CreateModel(
            name="VoucherLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_no", models.PositiveSmallIntegerField(verbose_name="Satır No")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Açıklama"
                    ),
                ),
                (
                    "debit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Borç Tutarı",
                    ),
                ),
                (
                    "credit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Alacak Tutarı",
                    ),
                ),
                (
                    "foreign_debit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Döviz Borç",
                    ),
                ),
                (
                    "foreign_credit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Döviz Alacak",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="voucher_lines",
                        to="finance_accounting.account",
                        verbose_name="Hesap",
                    ),
                ),
                (
                    "voucher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="finance_accounting.voucher",
                        verbose_name="Fiş",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fiş Satırı",
                "verbose_name_plural": "Fiş Satırları",
                "ordering": ["voucher", "line_no"],
                "unique_together": {("voucher", "line_no")},
            },
        ),
        migrations.CreateModel(
            name="PostingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Kural Adı")),
                (
                    "document_type",
                    models.CharField(max_length=50, verbose_name="Belge Tipi"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "definition",
                    models.JSONField(default=dict, verbose_name="Kural Tanımı"),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(default=100, verbose_name="Öncelik"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posting_rules",
                        to="accounting.company",
                        verbose_name="Şirket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Muhasebe Kuralı",
                "verbose_name_plural": "Muhasebe Kuralları",
                "ordering": ["company", "priority", "name"],
                "unique_together": {("company", "name")},
            },
        ),
        migrations.CreateModel(
            name="GLBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="TRY", max_length=3, verbose_name="Para Birimi"
                    ),
                ),
                ("year", models.PositiveIntegerField(verbose_name="Yıl")),
                ("month", models.PositiveIntegerField(verbose_name="Ay")),
                (
                    "begin_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=18,
                        verbose_name="Açılış Bakiyesi",
                    ),
                ),
                (
                    "debit_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=18,
                        verbose_name="Borç Toplam",
                    ),
                ),
                (
                    "credit_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=18,
                        verbose_name="Alacak Toplam",
                    ),
                ),
                (
                    "end_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=18,
                        verbose_name="Kapanış Bakiyesi",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gl_balances",
                        to="finance_accounting.account",
                        verbose_name="Hesap",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gl_balances",
                        to="accounting.company",
                        verbose_name="Şirket",
                    ),
                ),
                (
                    "fiscal_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gl_balances",
                        to="finance_accounting.fiscalyear",
                        verbose_name="Mali Yıl",
                    ),
                ),
            ],
            options={
                "verbose_name": "GL Bakiye",
                "verbose_name_plural": "GL Bakiyeleri",
                "ordering": ["company", "year", "month", "account__code"],
                "unique_together": {
                    ("company", "account", "currency", "year", "month")
                },
            },
        ),
        migrations.CreateModel(
            name="AccountingPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField(verbose_name="Yıl")),
                ("month", models.PositiveIntegerField(verbose_name="Ay")),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Açık"), ("closed", "Kapalı")],
                        default="open",
                        max_length=10,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Kapanış Zamanı"
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kapatılan Kullanıcı",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounting_periods",
                        to="accounting.company",
                        verbose_name="Şirket",
                    ),
                ),
                (
                    "fiscal_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accounting_periods",
                        to="finance_accounting.fiscalyear",
                        verbose_name="Mali Yıl",
                    ),
                ),
            ],
            options={
                "verbose_name": "Muhasebe Dönemi",
                "verbose_name_plural": "Muhasebe Dönemleri",
                "ordering": ["company", "-year", "-month"],
                "unique_together": {("company", "year", "month")},
            },
        ),
    ]
