# Generated by Django 5.2.8 on 2025-12-15 11:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance_accounting", "0006_alter_accountingperiod_closed_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoice",
            options={
                "ordering": ["-issue_date"],
                "verbose_name": "Muhasebe Faturası",
                "verbose_name_plural": "Muhasebe Faturaları",
            },
        ),
    ]
