# Generated by Django 5.2.8 on 2025-12-12 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="tr, en, ar, ku, de, fr",
                        max_length=10,
                        unique=True,
                        verbose_name="Dil Kodu",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Dil Adı")),
                (
                    "native_name",
                    models.CharField(max_length=100, verbose_name="Yerel Adı"),
                ),
                (
                    "flag_emoji",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Bayrak Emoji"
                    ),
                ),
                (
                    "is_rtl",
                    models.BooleanField(default=False, verbose_name="Sağdan Sola"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Varsayılan"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Sıra")),
                (
                    "translation_completeness",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Çeviri Tamamlanma %",
                    ),
                ),
                (
                    "total_strings",
                    models.IntegerField(default=0, verbose_name="Toplam String"),
                ),
                (
                    "translated_strings",
                    models.IntegerField(default=0, verbose_name="Çevrilmiş String"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Dil",
                "verbose_name_plural": "Diller",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("translated_text", models.TextField(verbose_name="Çevrilmiş Metin")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Beklemede"),
                            ("DRAFT", "Taslak"),
                            ("REVIEW", "İncelemede"),
                            ("APPROVED", "Onaylandı"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "is_machine_translated",
                    models.BooleanField(default=False, verbose_name="Makine Çevirisi"),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Güven Skoru",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="İnceleme Tarihi"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="locale.language",
                        verbose_name="Dil",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_translations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="İnceleyen",
                    ),
                ),
                (
                    "translated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Çeviren",
                    ),
                ),
            ],
            options={
                "verbose_name": "Çeviri",
                "verbose_name_plural": "Çeviriler",
                "ordering": ["translation_string", "language"],
            },
        ),
        migrations.CreateModel(
            name="LocaleAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Oluşturuldu"),
                            ("UPDATE", "Güncellendi"),
                            ("DELETE", "Silindi"),
                            ("APPROVE", "Onaylandı"),
                            ("REJECT", "Reddedildi"),
                            ("PUBLISH", "Yayınlandı"),
                        ],
                        max_length=20,
                        verbose_name="Aksiyon",
                    ),
                ),
                ("old_value", models.TextField(blank=True, verbose_name="Eski Değer")),
                ("new_value", models.TextField(blank=True, verbose_name="Yeni Değer")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Adresi"
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Yorum")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
                (
                    "translation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="locale.translation",
                        verbose_name="Çeviri",
                    ),
                ),
            ],
            options={
                "verbose_name": "Çeviri Denetim Logu",
                "verbose_name_plural": "Çeviri Denetim Logları",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TranslationJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_name", models.CharField(max_length=200, verbose_name="İş Adı")),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "content_items",
                    models.JSONField(default=list, verbose_name="İçerik Maddeleri"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Beklemede"),
                            ("IN_PROGRESS", "Devam Ediyor"),
                            ("COMPLETED", "Tamamlandı"),
                            ("FAILED", "Başarısız"),
                            ("CANCELLED", "İptal Edildi"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "progress_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="İlerleme %",
                    ),
                ),
                (
                    "total_items",
                    models.IntegerField(default=0, verbose_name="Toplam Madde"),
                ),
                (
                    "completed_items",
                    models.IntegerField(default=0, verbose_name="Tamamlanan Madde"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Başlangıç"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Bitiş"),
                ),
                (
                    "result_summary",
                    models.TextField(blank=True, verbose_name="Sonuç Özeti"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="translation_jobs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atanan",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan",
                    ),
                ),
                (
                    "source_language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_jobs",
                        to="locale.language",
                        verbose_name="Kaynak Dil",
                    ),
                ),
                (
                    "target_languages",
                    models.ManyToManyField(
                        related_name="target_jobs",
                        to="locale.language",
                        verbose_name="Hedef Diller",
                    ),
                ),
            ],
            options={
                "verbose_name": "Çeviri İşi",
                "verbose_name_plural": "Çeviri İşleri",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TranslationMemory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_text", models.TextField(verbose_name="Kaynak Metin")),
                ("target_text", models.TextField(verbose_name="Hedef Metin")),
                (
                    "usage_count",
                    models.IntegerField(default=0, verbose_name="Kullanım Sayısı"),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Son Kullanım"
                    ),
                ),
                (
                    "quality_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Kalite Skoru",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Doğrulandı"),
                ),
                (
                    "domain",
                    models.CharField(
                        blank=True,
                        help_text="finance, accounting, legal",
                        max_length=50,
                        verbose_name="Alan",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_memories",
                        to="locale.language",
                        verbose_name="Kaynak Dil",
                    ),
                ),
                (
                    "target_language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_memories",
                        to="locale.language",
                        verbose_name="Hedef Dil",
                    ),
                ),
            ],
            options={
                "verbose_name": "Çeviri Hafızası",
                "verbose_name_plural": "Çeviri Hafızaları",
                "ordering": ["-usage_count", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TranslationString",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="common.save, auth.login",
                        max_length=200,
                        unique=True,
                        verbose_name="Çeviri Anahtarı",
                    ),
                ),
                (
                    "context",
                    models.CharField(
                        choices=[
                            ("UI", "Kullanıcı Arayüzü"),
                            ("EMAIL", "E-posta"),
                            ("SMS", "SMS"),
                            ("NOTIFICATION", "Bildirim"),
                            ("REPORT", "Rapor"),
                            ("ERROR", "Hata Mesajı"),
                            ("HELP", "Yardım"),
                        ],
                        default="UI",
                        max_length=20,
                        verbose_name="Bağlam",
                    ),
                ),
                ("source_text", models.TextField(verbose_name="Kaynak Metin (TR)")),
                (
                    "module",
                    models.CharField(blank=True, max_length=50, verbose_name="Modül"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "variables",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="['user', 'amount', ...]",
                        verbose_name="Değişkenler",
                    ),
                ),
                (
                    "is_translated",
                    models.BooleanField(default=False, verbose_name="Çevrildi"),
                ),
                (
                    "requires_review",
                    models.BooleanField(default=False, verbose_name="İnceleme Gerekli"),
                ),
                (
                    "usage_count",
                    models.IntegerField(default=0, verbose_name="Kullanım Sayısı"),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Son Kullanım"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Çeviri String",
                "verbose_name_plural": "Çeviri Stringler",
                "ordering": ["module", "key"],
            },
        ),
        migrations.AddField(
            model_name="translation",
            name="translation_string",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="locale.translationstring",
                verbose_name="Çeviri String",
            ),
        ),
        migrations.CreateModel(
            name="UserLanguagePreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fallback_languages",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Yedek Diller"
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="Europe/Istanbul",
                        max_length=100,
                        verbose_name="Zaman Dilimi",
                    ),
                ),
                (
                    "date_format",
                    models.CharField(
                        default="DD.MM.YYYY",
                        max_length=50,
                        verbose_name="Tarih Formatı",
                    ),
                ),
                (
                    "time_format",
                    models.CharField(
                        default="HH:mm", max_length=50, verbose_name="Saat Formatı"
                    ),
                ),
                (
                    "number_format",
                    models.CharField(
                        default="1.234,56", max_length=50, verbose_name="Sayı Formatı"
                    ),
                ),
                (
                    "currency_symbol",
                    models.CharField(
                        default="₺", max_length=10, verbose_name="Para Birimi Sembolü"
                    ),
                ),
                (
                    "auto_translate",
                    models.BooleanField(default=False, verbose_name="Otomatik Çeviri"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "preferred_language",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="locale.language",
                        verbose_name="Tercih Edilen Dil",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="language_preference",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kullanıcı Dil Tercihi",
                "verbose_name_plural": "Kullanıcı Dil Tercihleri",
            },
        ),
        migrations.CreateModel(
            name="LocalizedContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.CharField(max_length=64)),
                (
                    "field_name",
                    models.CharField(max_length=100, verbose_name="Alan Adı"),
                ),
                ("translated_value", models.TextField(verbose_name="Çevrilmiş Değer")),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Yayınlandı"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="locale.language",
                        verbose_name="Dil",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yerelleştirilmiş İçerik",
                "verbose_name_plural": "Yerelleştirilmiş İçerikler",
                "ordering": ["content_type", "object_id", "language"],
                "unique_together": {
                    ("content_type", "object_id", "language", "field_name")
                },
            },
        ),
        migrations.AlterUniqueTogether(
            name="translation",
            unique_together={("translation_string", "language")},
        ),
        migrations.CreateModel(
            name="MissingTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "detected_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Tespit Tarihi"
                    ),
                ),
                (
                    "detected_in",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Tespit Edilen Yer"
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Düşük"),
                            ("MEDIUM", "Orta"),
                            ("HIGH", "Yüksek"),
                            ("CRITICAL", "Kritik"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                        verbose_name="Öncelik",
                    ),
                ),
                (
                    "is_resolved",
                    models.BooleanField(default=False, verbose_name="Çözüldü"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Çözüm Tarihi"
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="locale.language",
                        verbose_name="Dil",
                    ),
                ),
                (
                    "translation_string",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="missing_translations",
                        to="locale.translationstring",
                        verbose_name="Çeviri String",
                    ),
                ),
            ],
            options={
                "verbose_name": "Eksik Çeviri",
                "verbose_name_plural": "Eksik Çeviriler",
                "ordering": ["-priority", "-detected_at"],
                "unique_together": {("translation_string", "language")},
            },
        ),
    ]
