# Generated by Django 5.2.1 on 2025-05-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0005_tournament_tournamententry"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="time_of_day",
            field=models.CharField(blank=True, default="oglen", max_length=10),
        ),
        migrations.AddField(
            model_name="city",
            name="weather",
            field=models.CharField(blank=True, default="gunesli", max_length=20),
        ),
    ]
