# Generated by Django 5.2.1 on 2025-09-23 20:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0009_product_qrreward_citymarket_userqrreward"),
    ]

    operations = [
        migrations.DeleteModel(name="Character"),
        migrations.DeleteModel(name="CharacterQuest"),
        migrations.DeleteModel(name="Quest"),
        migrations.DeleteModel(name="ChatMessage"),
        migrations.DeleteModel(name="City"),
        migrations.DeleteModel(name="CityMarket"),
        migrations.DeleteModel(name="Product"),
        migrations.DeleteModel(name="GameNotification"),
        migrations.DeleteModel(name="QrReward"),
        migrations.DeleteModel(name="Tournament"),
        migrations.DeleteModel(name="TournamentEntry"),
        migrations.DeleteModel(name="UserQrReward"),
    ]
