# Generated by Django 5.2.7 on 2025-10-26 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0011_achievement_gamestate_ursinagame_gamescore_and_more"),
    ]

    operations = [
        # Bu geçiş, eski Ursina tabanlı oyun modellerini tamamen kaldırır.
        migrations.DeleteModel(
            name="Achievement",
        ),
        migrations.DeleteModel(
            name="GameAchievement",
        ),
        migrations.DeleteModel(
            name="GameScore",
        ),
        migrations.DeleteModel(
            name="GameState",
        ),
        migrations.DeleteModel(
            name="PlayerAchievement",
        ),
        migrations.DeleteModel(
            name="PlayerWallet",
        ),
        migrations.DeleteModel(
            name="Tournament",
        ),
        migrations.DeleteModel(
            name="UrsinaGame",
        ),
        migrations.DeleteModel(
            name="UrsinaGameSession",
        ),
        migrations.DeleteModel(
            name="UrsinaPlayer",
        ),
        migrations.DeleteModel(
            name="UserGameAchievement",
        ),
    ]
