# Generated by Django 5.2.7 on 2025-10-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0013_playerprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Rozet Adı"
                    ),
                ),
                ("description", models.TextField(verbose_name="Açıklama")),
                (
                    "icon",
                    models.CharField(default="🏆", max_length=50, verbose_name="İkon"),
                ),
                (
                    "criteria",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Kazanma Kriteri"
                    ),
                ),
                (
                    "points",
                    models.PositiveIntegerField(default=10, verbose_name="Puan"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Rozet",
                "verbose_name_plural": "Rozetler",
                "ordering": ["-points", "name"],
            },
        ),
        migrations.AlterModelOptions(
            name="playerprofile",
            options={
                "ordering": ["-total_score", "-games_played"],
                "verbose_name": "Oyuncu Profili",
                "verbose_name_plural": "Oyuncu Profilleri",
            },
        ),
        migrations.AddField(
            model_name="playerprofile",
            name="total_score",
            field=models.PositiveIntegerField(default=0, verbose_name="Toplam Skor"),
        ),
        migrations.AddField(
            model_name="playerprofile",
            name="badges",
            field=models.ManyToManyField(
                blank=True,
                related_name="players",
                to="games.badge",
                verbose_name="Rozetler",
            ),
        ),
    ]
