# Generated by Django 4.2.25 on 2025-10-30 17:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("games", "0014_badge_alter_playerprofile_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyQuest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quest_type",
                    models.CharField(
                        choices=[
                            ("play_games", "Oyun Oyna"),
                            ("win_games", "Oyun Kazan"),
                            ("earn_score", "Puan Kazan"),
                            ("complete_tutorial", "Eğitim Tamamla"),
                            ("trade_items", "Takas Yap"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "target_value",
                    models.IntegerField(default=1, verbose_name="Hedef Değer"),
                ),
                ("reward_xp", models.IntegerField(default=100)),
                ("reward_coins", models.IntegerField(default=500)),
                ("reward_gems", models.IntegerField(default=0)),
                ("is_daily", models.BooleanField(default=True)),
                ("is_weekly", models.BooleanField(default=False)),
                (
                    "difficulty_level",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Günlük Görev",
                "verbose_name_plural": "Günlük Görevler",
                "ordering": ["difficulty_level", "title"],
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("skin", "Görünüm"),
                            ("boost", "Güçlendirici"),
                            ("badge", "Rozet"),
                            ("avatar", "Avatar"),
                            ("effect", "Efekt"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "rarity",
                    models.CharField(
                        choices=[
                            ("common", "Yaygın"),
                            ("rare", "Nadir"),
                            ("epic", "Epik"),
                            ("legendary", "Efsanevi"),
                        ],
                        default="common",
                        max_length=20,
                    ),
                ),
                ("price_coins", models.IntegerField(default=0)),
                ("price_gems", models.IntegerField(default=0)),
                (
                    "effect_data",
                    models.JSONField(
                        default=dict, help_text="XP boost, coin multiplier vb."
                    ),
                ),
                (
                    "duration_hours",
                    models.IntegerField(default=0, help_text="0 = kalıcı"),
                ),
                ("is_tradeable", models.BooleanField(default=True)),
                ("is_purchasable", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Eşya",
                "verbose_name_plural": "Eşyalar",
                "ordering": ["rarity", "name"],
            },
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Sezon Adı")),
                ("start_date", models.DateTimeField(verbose_name="Başlangıç Tarihi")),
                ("end_date", models.DateTimeField(verbose_name="Bitiş Tarihi")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "reward_pool",
                    models.IntegerField(
                        default=100000, verbose_name="Ödül Havuzu (Puan)"
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Sezon",
                "verbose_name_plural": "Sezonlar",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "tag",
                    models.CharField(
                        help_text="Kısa takım etiketi (örn: FIN)",
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("team_rank", models.CharField(default="bronze", max_length=20)),
                ("team_elo", models.IntegerField(default=1000)),
                ("logo_icon", models.CharField(default="🛡️", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Takım",
                "verbose_name_plural": "Takımlar",
                "ordering": ["-team_elo"],
            },
        ),
        migrations.AlterModelOptions(
            name="game",
            options={
                "ordering": ["name"],
                "verbose_name": "Oyun",
                "verbose_name_plural": "Oyunlar",
            },
        ),
        migrations.AlterModelOptions(
            name="playerprofile",
            options={
                "ordering": ["-elo_rating", "-total_score"],
                "verbose_name": "Oyuncu Profili",
                "verbose_name_plural": "Oyuncu Profilleri",
            },
        ),
        migrations.AddField(
            model_name="badge",
            name="rarity",
            field=models.CharField(
                choices=[
                    ("common", "Yaygın"),
                    ("rare", "Nadir"),
                    ("epic", "Epik"),
                    ("legendary", "Efsanevi"),
                ],
                default="common",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="badge",
            name="xp_reward",
            field=models.PositiveIntegerField(default=100, verbose_name="XP Ödülü"),
        ),
        migrations.AddField(
            model_name="game",
            name="duration_minutes",
            field=models.IntegerField(
                default=15, help_text="Ortalama oyun süresi (dakika)"
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="game_type",
            field=models.CharField(
                choices=[
                    ("competitive", "Rekabetçi"),
                    ("casual", "Günlük"),
                    ("educational", "Eğitsel"),
                    ("simulation", "Simülasyon"),
                ],
                default="casual",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="is_esport_enabled",
            field=models.BooleanField(default=False, verbose_name="E-Spor Modu"),
        ),
        migrations.AddField(
            model_name="game",
            name="max_players",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="game",
            name="min_players",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="playerprofile",
            name="coins",
            field=models.PositiveIntegerField(default=1000, verbose_name="Altın"),
        ),
        migrations.AddField(
            model_name="playerprofile",
            name="daily_streak",
            field=models.PositiveIntegerField(default=0, verbose_name="Günlük Seri"),
        ),
        migrations.AddField(
            model_name="playerprofile",
            name="elo_rating",
            field=models.IntegerField(default=1200, verbose_name="ELO Rating"),
        ),
        migrations.AddField(
            model_name="playerprofile",
            name="games_lost",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playerprofile",
            name="games_won",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playerprofile",
            name="gems",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Elmas (Premium)"
            ),
        ),
        migrations.AddField(
            model_name="playerprofile",
            name="highest_score",
            field=models.PositiveIntegerField(default=0, verbose_name="En Yüksek Skor"),
        ),
        migrations.AddField(
            model_name="playerprofile",
            name="last_played_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playerprofile",
            name="level",
            field=models.PositiveIntegerField(default=1, verbose_name="Seviye"),
        ),
        migrations.AddField(
            model_name="playerprofile",
            name="mmr",
            field=models.IntegerField(default=1000, verbose_name="Matchmaking Rating"),
        ),
        migrations.AddField(
            model_name="playerprofile",
            name="rank",
            field=models.CharField(
                choices=[
                    ("bronze", "Bronz"),
                    ("silver", "Gümüş"),
                    ("gold", "Altın"),
                    ("platinum", "Platin"),
                    ("diamond", "Elmas"),
                    ("master", "Usta"),
                    ("grandmaster", "Büyük Usta"),
                    ("challenger", "Meydan Okuyan"),
                ],
                default="bronze",
                max_length=20,
                verbose_name="Rank",
            ),
        ),
        migrations.AddField(
            model_name="playerprofile",
            name="skill_accounting",
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name="playerprofile",
            name="xp",
            field=models.PositiveIntegerField(default=0, verbose_name="Deneyim Puanı"),
        ),
        migrations.AddField(
            model_name="playerprofile",
            name="xp_to_next_level",
            field=models.PositiveIntegerField(
                default=1000, verbose_name="Sonraki Seviyeye Kalan XP"
            ),
        ),
        migrations.AlterField(
            model_name="playerprofile",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("easy", "Kolay"),
                    ("medium", "Orta"),
                    ("hard", "Zor"),
                    ("expert", "Uzman"),
                    ("adaptive", "Uyarlanır"),
                ],
                default="adaptive",
                max_length=16,
                verbose_name="Zorluk",
            ),
        ),
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Turnuva Adı")),
                ("description", models.TextField(blank=True)),
                (
                    "tournament_type",
                    models.CharField(
                        choices=[
                            ("ranked", "Dereceli"),
                            ("casual", "Günlük"),
                            ("championship", "Şampiyonluk"),
                            ("special", "Özel Etkinlik"),
                        ],
                        default="casual",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Yaklaşan"),
                            ("registration", "Kayıt Açık"),
                            ("ongoing", "Devam Ediyor"),
                            ("finished", "Bitti"),
                            ("cancelled", "İptal"),
                        ],
                        default="upcoming",
                        max_length=20,
                    ),
                ),
                ("registration_start", models.DateTimeField()),
                ("registration_end", models.DateTimeField()),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                (
                    "max_participants",
                    models.IntegerField(
                        default=128,
                        validators=[django.core.validators.MinValueValidator(2)],
                    ),
                ),
                (
                    "entry_fee_coins",
                    models.IntegerField(
                        default=0, verbose_name="Katılım Ücreti (Altın)"
                    ),
                ),
                (
                    "entry_fee_gems",
                    models.IntegerField(
                        default=0, verbose_name="Katılım Ücreti (Elmas)"
                    ),
                ),
                ("prize_pool_coins", models.IntegerField(default=10000)),
                ("prize_pool_gems", models.IntegerField(default=0)),
                (
                    "prize_distribution",
                    models.JSONField(
                        default=dict, help_text="1st: 50%, 2nd: 30%, 3rd: 20%"
                    ),
                ),
                ("rules", models.TextField(blank=True)),
                (
                    "bracket_type",
                    models.CharField(
                        choices=[
                            ("single_elimination", "Eleme"),
                            ("double_elimination", "Çift Eleme"),
                            ("round_robin", "Herkes Herkesle"),
                        ],
                        default="single_elimination",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_tournaments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournaments",
                        to="games.game",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="games.season",
                    ),
                ),
            ],
            options={
                "verbose_name": "Turnuva",
                "verbose_name_plural": "Turnuvalar",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="TeamMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Kurucu"),
                            ("captain", "Kaptan"),
                            ("member", "Üye"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="games.team"
                    ),
                ),
            ],
            options={
                "verbose_name": "Takım Üyeliği",
                "verbose_name_plural": "Takım Üyelikleri",
                "unique_together": {("team", "player")},
            },
        ),
        migrations.AddField(
            model_name="team",
            name="members",
            field=models.ManyToManyField(
                related_name="teams",
                through="games.TeamMembership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_teams",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Planlandı"),
                            ("live", "Canlı"),
                            ("finished", "Bitti"),
                            ("forfeit", "Hükmen"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("scheduled_time", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("player1_score", models.IntegerField(default=0)),
                ("player2_score", models.IntegerField(default=0)),
                ("replay_data", models.JSONField(blank=True, default=dict)),
                ("match_stats", models.JSONField(blank=True, default=dict)),
                ("elo_change_player1", models.IntegerField(default=0)),
                ("elo_change_player2", models.IntegerField(default=0)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="games.game"
                    ),
                ),
                (
                    "player1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_as_player1",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "player2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_as_player2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="games.tournament",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="won_matches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Maç",
                "verbose_name_plural": "Maçlar",
                "ordering": ["-scheduled_time"],
            },
        ),
        migrations.CreateModel(
            name="GameSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.IntegerField(default=0)),
                ("score", models.IntegerField(default=0)),
                ("is_victory", models.BooleanField(default=False)),
                ("xp_earned", models.IntegerField(default=0)),
                ("coins_earned", models.IntegerField(default=0)),
                (
                    "session_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Oyun içi events, actions vb.",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="games.game"
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="games.match",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Oyun Oturumu",
                "verbose_name_plural": "Oyun Oturumları",
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddField(
            model_name="playerprofile",
            name="current_season",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="games.season",
            ),
        ),
        migrations.CreateModel(
            name="TournamentParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "seed",
                    models.IntegerField(
                        blank=True, help_text="Turnuva kura numarası", null=True
                    ),
                ),
                ("final_rank", models.IntegerField(blank=True, null=True)),
                ("total_score", models.IntegerField(default=0)),
                ("prizes_won", models.JSONField(default=dict)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournament_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="games.tournament",
                    ),
                ),
            ],
            options={
                "verbose_name": "Turnuva Katılımcısı",
                "verbose_name_plural": "Turnuva Katılımcıları",
                "ordering": ["tournament", "seed"],
                "unique_together": {("tournament", "player")},
            },
        ),
        migrations.CreateModel(
            name="PlayerQuest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_value", models.IntegerField(default=0)),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "quest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="games.dailyquest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Oyuncu Görevi",
                "verbose_name_plural": "Oyuncu Görevleri",
                "ordering": ["-assigned_at"],
                "unique_together": {("player", "quest", "assigned_at")},
            },
        ),
        migrations.CreateModel(
            name="PlayerInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("acquired_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_equipped", models.BooleanField(default=False)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="games.item"
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Envanter",
                "verbose_name_plural": "Envanter",
                "unique_together": {("player", "item")},
            },
        ),
        migrations.CreateModel(
            name="Leaderboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leaderboard_type",
                    models.CharField(
                        choices=[
                            ("global", "Global"),
                            ("season", "Sezonluk"),
                            ("weekly", "Haftalık"),
                            ("daily", "Günlük"),
                            ("game_specific", "Oyuna Özel"),
                        ],
                        max_length=20,
                    ),
                ),
                ("rank", models.PositiveIntegerField()),
                ("score", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "game",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="games.game",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="games.season",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sıralama",
                "verbose_name_plural": "Sıralamalar",
                "ordering": ["rank"],
                "indexes": [
                    models.Index(
                        fields=["leaderboard_type", "rank"],
                        name="games_leade_leaderb_3ab7b8_idx",
                    ),
                    models.Index(
                        fields=["season", "rank"], name="games_leade_season__192009_idx"
                    ),
                ],
                "unique_together": {("leaderboard_type", "game", "season", "player")},
            },
        ),
        migrations.CreateModel(
            name="Friend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Bekliyor"),
                            ("accepted", "Kabul Edildi"),
                            ("blocked", "Engellendi"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_friend_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_friend_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Arkadaşlık",
                "verbose_name_plural": "Arkadaşlıklar",
                "unique_together": {("from_player", "to_player")},
            },
        ),
    ]
