# Generated by Django 5.2.8 on 2025-12-15 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0015_dailyquest_item_season_team_alter_game_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="badge",
            options={
                "ordering": ["-points", "name"],
                "verbose_name": "Oyun Rozeti",
                "verbose_name_plural": "Oyun Rozetleri",
            },
        ),
        migrations.AlterModelOptions(
            name="playerinventory",
            options={
                "verbose_name": "Oyuncu Envanteri",
                "verbose_name_plural": "Oyuncu Envanterleri",
            },
        ),
        migrations.AlterModelOptions(
            name="tournament",
            options={
                "ordering": ["-start_date"],
                "verbose_name": "E-Spor Turnuvası",
                "verbose_name_plural": "E-Spor Turnuvaları",
            },
        ),
    ]
