# Generated by Django 5.2.8 on 2025-12-17 14:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0016_alter_badge_options_alter_playerinventory_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Araç Adı")),
                (
                    "symbol",
                    models.CharField(max_length=20, unique=True, verbose_name="Sembol"),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("stock", "Hisse Senedi"),
                            ("bond", "Tahvil"),
                            ("gold", "Altın"),
                            ("crypto", "Kripto Para"),
                            ("forex", "Döviz"),
                            ("fund", "Yatırım Fonu"),
                            ("realestate", "Gayrimenkul Fonu"),
                            ("commodity", "Emtia"),
                        ],
                        max_length=20,
                        verbose_name="Araç Tipi",
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Düşük"),
                            ("medium", "Orta"),
                            ("high", "Yüksek"),
                            ("very_high", "Çok Yüksek"),
                        ],
                        max_length=20,
                        verbose_name="Risk Seviyesi",
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Başlangıç Fiyatı"
                    ),
                ),
                (
                    "current_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Güncel Fiyat"
                    ),
                ),
                (
                    "volatility",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.02"),
                        help_text="Fiyat değişkenliği (0.02 = %2)",
                        max_digits=5,
                        verbose_name="Volatilite",
                    ),
                ),
                (
                    "expected_return",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10.00"),
                        help_text="Yıllık beklenen getiri yüzdesi",
                        max_digits=5,
                        verbose_name="Beklenen Getiri %",
                    ),
                ),
                (
                    "trend",
                    models.CharField(
                        choices=[
                            ("bullish", "Yükseliş"),
                            ("bearish", "Düşüş"),
                            ("neutral", "Nötr"),
                        ],
                        default="neutral",
                        max_length=20,
                        verbose_name="Trend",
                    ),
                ),
                (
                    "momentum",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Fiyat momentumu (-100 ile +100 arası)",
                        max_digits=5,
                        verbose_name="Momentum",
                    ),
                ),
                (
                    "market_cap",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="Piyasa Değeri",
                    ),
                ),
                (
                    "volume_24h",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=20,
                        verbose_name="24 Saatlik Hacim",
                    ),
                ),
                (
                    "price_history",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Son 100 fiyat güncellemesi",
                        verbose_name="Fiyat Geçmişi",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "icon",
                    models.CharField(
                        default="graph-up", max_length=50, verbose_name="İkon"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Yatırım Aracı",
                "verbose_name_plural": "Yatırım Araçları",
                "ordering": ["asset_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="InvestmentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "initial_capital",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("100000.00"),
                        max_digits=15,
                        verbose_name="Başlangıç Sermayesi",
                    ),
                ),
                (
                    "cash_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("100000.00"),
                        max_digits=15,
                        verbose_name="Nakit Bakiye",
                    ),
                ),
                (
                    "total_invested",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Toplam Yatırım",
                    ),
                ),
                (
                    "total_profit_loss",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Toplam Kar/Zarar",
                    ),
                ),
                (
                    "total_return_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Toplam Getiri %",
                    ),
                ),
                (
                    "level",
                    models.PositiveIntegerField(default=1, verbose_name="Seviye"),
                ),
                (
                    "xp",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Deneyim Puanı"
                    ),
                ),
                (
                    "xp_to_next_level",
                    models.PositiveIntegerField(
                        default=1000, verbose_name="Sonraki Seviyeye XP"
                    ),
                ),
                (
                    "skill_analysis",
                    models.PositiveIntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Analiz Becerisi",
                    ),
                ),
                (
                    "skill_timing",
                    models.PositiveIntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Zamanlama Becerisi",
                    ),
                ),
                (
                    "skill_risk_management",
                    models.PositiveIntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Risk Yönetimi",
                    ),
                ),
                (
                    "skill_diversification",
                    models.PositiveIntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Çeşitlendirme",
                    ),
                ),
                (
                    "total_transactions",
                    models.PositiveIntegerField(default=0, verbose_name="Toplam İşlem"),
                ),
                (
                    "successful_trades",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Başarılı İşlem"
                    ),
                ),
                (
                    "failed_trades",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Başarısız İşlem"
                    ),
                ),
                (
                    "win_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="Kazanma Oranı %",
                    ),
                ),
                (
                    "best_daily_return",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="En İyi Günlük Getiri %",
                    ),
                ),
                (
                    "best_weekly_return",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="En İyi Haftalık Getiri %",
                    ),
                ),
                (
                    "best_monthly_return",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="En İyi Aylık Getiri %",
                    ),
                ),
                (
                    "daily_streak",
                    models.PositiveIntegerField(default=0, verbose_name="Günlük Seri"),
                ),
                (
                    "last_played_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Son Oynama Tarihi"
                    ),
                ),
                (
                    "preferences",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Tercihler"
                    ),
                ),
                (
                    "stats",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="İstatistikler"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Güncellenme"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investment_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yatırım Profili",
                "verbose_name_plural": "Yatırım Profilleri",
                "ordering": ["-total_return_percentage", "-total_profit_loss"],
            },
        ),
        migrations.CreateModel(
            name="MarketEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Başlık")),
                ("description", models.TextField(verbose_name="Açıklama")),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("news", "Haber"),
                            ("crisis", "Kriz"),
                            ("boom", "Patlama"),
                            ("regulation", "Düzenleme"),
                            ("earnings", "Kazanç Açıklaması"),
                            ("merger", "Birleşme"),
                        ],
                        max_length=20,
                        verbose_name="Olay Tipi",
                    ),
                ),
                (
                    "impact_level",
                    models.CharField(
                        choices=[
                            ("low", "Düşük"),
                            ("medium", "Orta"),
                            ("high", "Yüksek"),
                            ("critical", "Kritik"),
                        ],
                        max_length=20,
                        verbose_name="Etki Seviyesi",
                    ),
                ),
                (
                    "price_impact_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Pozitif = artış, Negatif = düşüş",
                        max_digits=5,
                        verbose_name="Fiyat Etkisi %",
                    ),
                ),
                ("event_date", models.DateTimeField(verbose_name="Olay Tarihi")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Bitiş Tarihi"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "affected_assets",
                    models.ManyToManyField(
                        blank=True,
                        related_name="market_events",
                        to="games.asset",
                        verbose_name="Etkilenen Araçlar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Piyasa Olayı",
                "verbose_name_plural": "Piyasa Olayları",
                "ordering": ["-event_date"],
            },
        ),
        migrations.CreateModel(
            name="InvestmentLeaderboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leaderboard_type",
                    models.CharField(
                        choices=[
                            ("global", "Global"),
                            ("weekly", "Haftalık"),
                            ("monthly", "Aylık"),
                            ("all_time", "Tüm Zamanlar"),
                        ],
                        max_length=20,
                        verbose_name="Liderlik Tipi",
                    ),
                ),
                ("rank", models.PositiveIntegerField(verbose_name="Sıra")),
                (
                    "total_return_percentage",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Toplam Getiri %"
                    ),
                ),
                (
                    "portfolio_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Portföy Değeri"
                    ),
                ),
                (
                    "period_start",
                    models.DateField(
                        blank=True, null=True, verbose_name="Dönem Başlangıcı"
                    ),
                ),
                (
                    "period_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="Dönem Bitişi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Güncellenme"),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaderboard_entries",
                        to="games.investmentprofile",
                        verbose_name="Profil",
                    ),
                ),
            ],
            options={
                "verbose_name": "Liderlik Tablosu",
                "verbose_name_plural": "Liderlik Tabloları",
                "ordering": ["leaderboard_type", "rank"],
                "indexes": [
                    models.Index(
                        fields=["leaderboard_type", "rank"],
                        name="games_inves_leaderb_9f3b60_idx",
                    )
                ],
                "unique_together": {
                    ("leaderboard_type", "profile", "period_start", "period_end")
                },
            },
        ),
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                        verbose_name="Miktar",
                    ),
                ),
                (
                    "average_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Birim başına ortalama alış fiyatı",
                        max_digits=15,
                        verbose_name="Ortalama Maliyet",
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Toplam Maliyet"
                    ),
                ),
                (
                    "first_purchased_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="İlk Alış"),
                ),
                (
                    "last_updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Son Güncelleme"),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolios",
                        to="games.asset",
                        verbose_name="Araç",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holdings",
                        to="games.investmentprofile",
                        verbose_name="Profil",
                    ),
                ),
            ],
            options={
                "verbose_name": "Portföy",
                "verbose_name_plural": "Portföyler",
                "ordering": ["-total_cost"],
                "unique_together": {("profile", "asset")},
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("buy", "Alış"), ("sell", "Satış")],
                        max_length=10,
                        verbose_name="İşlem Tipi",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                        verbose_name="Miktar",
                    ),
                ),
                (
                    "price_per_unit",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Birim Fiyat"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Toplam Tutar"
                    ),
                ),
                (
                    "commission",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Komisyon",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Beklemede"),
                            ("completed", "Tamamlandı"),
                            ("cancelled", "İptal Edildi"),
                        ],
                        default="completed",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "profit_loss",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Satış işlemlerinde hesaplanır",
                        max_digits=15,
                        null=True,
                        verbose_name="Kar/Zarar",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notlar")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="İşlem Tarihi"
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="games.asset",
                        verbose_name="Araç",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="games.investmentprofile",
                        verbose_name="Profil",
                    ),
                ),
            ],
            options={
                "verbose_name": "İşlem",
                "verbose_name_plural": "İşlemler",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["profile", "-created_at"],
                        name="games_trans_profile_d74592_idx",
                    ),
                    models.Index(
                        fields=["asset", "-created_at"],
                        name="games_trans_asset_i_3008af_idx",
                    ),
                ],
            },
        ),
    ]
