# Generated by Django 5.0.2 on 2025-04-12 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "virtual_company",
            "0002_dailytask_product_alter_virtualcompany_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockchainTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=255)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("invoice", "Fatura"),
                            ("payment", "Ödeme"),
                            ("account", "Cari Hesap"),
                            ("other", "Diğer"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "reference_model",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("data_hash", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "blockchain_hash",
                    models.CharField(blank=True, max_length=66, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Beklemede"),
                            ("processing", "İşleniyor"),
                            ("completed", "Tamamlandı"),
                            ("failed", "Başarısız"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "virtual_company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="virtual_company.virtualcompany",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blockchain İşlemi",
                "verbose_name_plural": "Blockchain İşlemleri",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BlockchainLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("status", models.CharField(max_length=20)),
                ("message", models.TextField()),
                ("error", models.TextField(blank=True, null=True)),
                (
                    "virtual_company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="virtual_company.virtualcompany",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="blockchain.blockchaintransaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blockchain Log",
                "verbose_name_plural": "Blockchain Logları",
                "ordering": ["-created_at"],
            },
        ),
    ]
