# Generated by Django 5.0.3 on 2024-03-28 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='İzin Adı')),
                ('codename', models.CharField(max_length=100, unique=True, verbose_name='Kod Adı')),
                ('module', models.CharField(choices=[('accounting', 'Muhasebe'), ('finance', 'Finans'), ('crm', 'Müşteri İlişkileri'), ('stock', 'Stok Yönetimi'), ('hr', 'İnsan Kaynakları'), ('reports', 'Raporlar'), ('settings', 'Ayarlar'), ('system', 'Sistem'), ('users', 'Kullanıcılar'), ('permissions', 'İzinler'), ('virtual_company', 'Sanal Şirket')], max_length=50, verbose_name='Modül')),
                ('permission_type', models.CharField(choices=[('create', 'Oluşturma'), ('view', 'Görüntüleme'), ('update', 'Güncelleme'), ('delete', 'Silme'), ('approve', 'Onaylama'), ('export', 'Dışa Aktarma'), ('import', 'İçe Aktarma'), ('report', 'Raporlama')], max_length=20, verbose_name='İzin Türü')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'İzin',
                'verbose_name_plural': 'İzinler',
                'ordering': ['module', 'permission_type'],
                'unique_together': {('module', 'permission_type')},
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Rol Adı')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Rol Kodu')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('role_type', models.CharField(choices=[('system', 'Sistem Rolü'), ('custom', 'Özel Rol')], default='custom', max_length=20, verbose_name='Rol Türü')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_roles', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='permissions.permission', verbose_name='İzinler')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roller',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Oluşturma'), ('update', 'Güncelleme'), ('delete', 'Silme'), ('assign', 'Atama'), ('revoke', 'İptal'), ('login', 'Giriş'), ('logout', 'Çıkış'), ('access', 'Erişim'), ('permission_denied', 'İzin Reddi')], max_length=20, verbose_name='İşlem')),
                ('model', models.CharField(max_length=50, verbose_name='Model')),
                ('object_id', models.CharField(max_length=100, verbose_name='Nesne ID')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Detaylar')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi')),
                ('user_agent', models.TextField(blank=True, verbose_name='Kullanıcı Ajanı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Denetim Günlüğü',
                'verbose_name_plural': 'Denetim Günlükleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, help_text="Kullanıcının birincil rolü", verbose_name='Birincil Rol')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Atanma Tarihi')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Rol geçerliliği bitiş tarihi (boş ise süresiz)', null=True, verbose_name='Bitiş Tarihi')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL, verbose_name='Atayan')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='permissions.role', verbose_name='Rol')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kullanıcı Rolü',
                'verbose_name_plural': 'Kullanıcı Rolleri',
                'ordering': ['-is_primary', 'assigned_at'],
                'unique_together': {('user', 'role')},
            },
        ),
    ]
