# -*- coding: utf-8 -*-
"""
Auto Report Generation Service
Otomatik rapor üretimi - finansal raporları AI ile oluşturma
Local AI - External API kullanmaz
"""
from datetime import datetime, timedelta
from django.utils import timezone
from django.db.models import Sum, Count
from ..models import AutoGeneratedReport


class AutoReportGenerationService:
    """
    Otomatik rapor üretim servisi
    Finansal verileri analiz edip raporlar oluşturur
    """

    @classmethod
    def generate_daily_summary(cls, user, date=None) -> AutoGeneratedReport:
        """Günlük özet raporu oluştur"""
        if date is None:
            date = timezone.now().date()

        # Veri toplama
        try:
            from accounting.models import Invoice, Expense

            invoices = Invoice.objects.filter(issue_date=date, company__users=user)

            expenses = Expense.objects.filter(date=date, company__users=user)

            invoice_total = invoices.aggregate(total=Sum("total_amount"))["total"] or 0
            expense_total = expenses.aggregate(total=Sum("amount"))["total"] or 0
            net = invoice_total - expense_total

            content = f"""
# Günlük Özet - {date.strftime('%d.%m.%Y')}

## 📊 Finansal Özet

**Gelirler:** {invoice_total:,.2f} TL ({invoices.count()} fatura)
**Giderler:** {expense_total:,.2f} TL ({expenses.count()} gider)
**Net:** {net:,.2f} TL

## 📈 Performans

{'✅ Pozitif gün - Gelir gideri aştı!' if net > 0 else '⚠️ Dikkat - Gider geliri aştı!'}

## 🎯 Öneriler

1. {'Günlük geliriniz hedefte' if invoice_total > 1000 else 'Gelir artırma stratejileri değerlendirin'}
2. {'Gider kontrolü iyi durumda' if expense_total < 1000 else 'Gider optimizasyonu önerilir'}
"""

            insights = [
                f"Toplam {invoices.count()} fatura kesildi",
                f"Ortalama fatura tutarı: {invoice_total / invoices.count() if invoices.count() > 0 else 0:,.2f} TL",
                f"Gün sonu net: {net:,.2f} TL",
            ]

            metrics = {
                "invoice_count": invoices.count(),
                "expense_count": expenses.count(),
                "invoice_total": float(invoice_total),
                "expense_total": float(expense_total),
                "net": float(net),
            }

        except Exception:
            content = "Veri alınamadı"
            insights = []
            metrics = {}

        report = AutoGeneratedReport.objects.create(
            user=user,
            report_type="daily_summary",
            title=f"Günlük Özet - {date.strftime('%d.%m.%Y')}",
            content=content,
            summary=f"Gelir: {invoice_total:,.2f} TL | Gider: {expense_total:,.2f} TL | Net: {net:,.2f} TL",
            insights=insights,
            metrics=metrics,
            period_start=date,
            period_end=date,
            status="completed",
            completed_at=timezone.now(),
        )

        return report

    @classmethod
    def generate_monthly_financial(
        cls, user, year: int = None, month: int = None
    ) -> AutoGeneratedReport:
        """Aylık mali rapor oluştur"""
        if year is None:
            year = timezone.now().year
        if month is None:
            month = timezone.now().month

        from calendar import monthrange

        period_start = datetime(year, month, 1).date()
        last_day = monthrange(year, month)[1]
        period_end = datetime(year, month, last_day).date()

        try:
            from accounting.models import Invoice, Expense

            # Aylık veriler
            invoices = Invoice.objects.filter(
                issue_date__gte=period_start,
                issue_date__lte=period_end,
                company__users=user,
            )

            expenses = Expense.objects.filter(
                date__gte=period_start, date__lte=period_end, company__users=user
            )

            invoice_total = invoices.aggregate(total=Sum("total_amount"))["total"] or 0
            expense_total = expenses.aggregate(total=Sum("amount"))["total"] or 0
            net_profit = invoice_total - expense_total

            # Müşteri analizi
            customer_count = invoices.values("customer").distinct().count()

            # Günlük ortalama
            days_in_month = (period_end - period_start).days + 1
            daily_avg_revenue = (
                invoice_total / days_in_month if days_in_month > 0 else 0
            )

            content = f"""
# Aylık Mali Rapor - {period_start.strftime('%B %Y')}

## 💰 Finansal Performans

**Toplam Gelir:** {invoice_total:,.2f} TL
**Toplam Gider:** {expense_total:,.2f} TL
**Net Kar/Zarar:** {net_profit:,.2f} TL
**Kar Marjı:** {(net_profit / invoice_total * 100) if invoice_total > 0 else 0:.1f}%

## 📊 İşlem Özeti

- **Fatura Sayısı:** {invoices.count()}
- **Gider Sayısı:** {expenses.count()}
- **Aktif Müşteri:** {customer_count}
- **Ortalama Günlük Gelir:** {daily_avg_revenue:,.2f} TL

## 🎯 İçgörüler

{'✅ Karlı ay - Hedeflerinize ulaştınız!' if net_profit > 0 else '⚠️ Zarar - Maliyet optimizasyonu gerekli'}

## 📈 Trendler

- Fatura başına ortalama: {invoice_total / invoices.count() if invoices.count() > 0 else 0:,.2f} TL
- Gün başına ortalama gider: {expense_total / days_in_month if days_in_month > 0 else 0:,.2f} TL
"""

            insights = [
                f"Ay içinde {invoices.count()} fatura kesildi",
                f"Toplam {customer_count} farklı müşteri ile iş yapıldı",
                f"Net kar marjı: {(net_profit / invoice_total * 100) if invoice_total > 0 else 0:.1f}%",
                f"Ortalama günlük gelir: {daily_avg_revenue:,.2f} TL",
            ]

            metrics = {
                "invoice_total": float(invoice_total),
                "expense_total": float(expense_total),
                "net_profit": float(net_profit),
                "invoice_count": invoices.count(),
                "expense_count": expenses.count(),
                "customer_count": customer_count,
                "profit_margin": float(
                    (net_profit / invoice_total * 100) if invoice_total > 0 else 0
                ),
            }

            # Grafik verileri
            charts_data = {
                "revenue_vs_expense": {
                    "labels": ["Gelir", "Gider"],
                    "data": [float(invoice_total), float(expense_total)],
                }
            }

        except Exception as e:
            content = f"Rapor oluşturulamadı: {str(e)}"
            insights = []
            metrics = {}
            charts_data = {}

        report = AutoGeneratedReport.objects.create(
            user=user,
            report_type="monthly_financial",
            title=f"Aylık Mali Rapor - {period_start.strftime('%B %Y')}",
            content=content,
            summary=f"Net: {net_profit:,.2f} TL | Gelir: {invoice_total:,.2f} TL | Gider: {expense_total:,.2f} TL",
            insights=insights,
            metrics=metrics,
            charts_data=charts_data,
            period_start=period_start,
            period_end=period_end,
            status="completed",
            completed_at=timezone.now(),
        )

        return report

    @classmethod
    def generate_expense_analysis(cls, user, days: int = 30) -> AutoGeneratedReport:
        """Gider analizi raporu"""
        end_date = timezone.now().date()
        start_date = end_date - timedelta(days=days)

        try:
            from accounting.models import Expense

            expenses = Expense.objects.filter(
                date__gte=start_date, date__lte=end_date, company__users=user
            )

            total_expense = expenses.aggregate(total=Sum("amount"))["total"] or 0

            # Kategorilere göre grupla
            by_category = (
                expenses.values("category")
                .annotate(total=Sum("amount"), count=Count("id"))
                .order_by("-total")
            )

            content = f"""
# Gider Analizi - Son {days} Gün

## 💸 Toplam Gider: {total_expense:,.2f} TL

## 📊 Kategorilere Göre Dağılım

"""
            for cat in by_category:
                percentage = (
                    (cat["total"] / total_expense * 100) if total_expense > 0 else 0
                )
                content += f"- **{cat['category']}:** {cat['total']:,.2f} TL ({percentage:.1f}%) - {cat['count']} işlem\n"

            insights = [
                f"En yüksek gider kategorisi: {by_category[0]['category'] if by_category else 'N/A'}",
                f"Günlük ortalama gider: {total_expense / days:,.2f} TL",
                f"Toplam {expenses.count()} gider kaydı",
            ]

            metrics = {
                "total_expense": float(total_expense),
                "expense_count": expenses.count(),
                "daily_average": float(total_expense / days) if days > 0 else 0,
                "categories": list(by_category),
            }

        except Exception as e:
            content = f"Rapor oluşturulamadı: {str(e)}"
            insights = []
            metrics = {}

        report = AutoGeneratedReport.objects.create(
            user=user,
            report_type="expense_analysis",
            title=f"Gider Analizi - Son {days} Gün",
            content=content,
            summary=f"Toplam gider: {total_expense:,.2f} TL",
            insights=insights,
            metrics=metrics,
            period_start=start_date,
            period_end=end_date,
            status="completed",
            completed_at=timezone.now(),
        )

        return report

    @classmethod
    def schedule_report(
        cls, user, report_type: str, frequency: str = "weekly"
    ) -> AutoGeneratedReport:
        """
        Zamanlanmış rapor oluştur

        Args:
            user: Kullanıcı
            report_type: Rapor tipi
            frequency: daily, weekly, monthly
        """
        # Sonraki çalışma zamanını hesapla
        now = timezone.now()
        if frequency == "daily":
            next_run = now + timedelta(days=1)
        elif frequency == "weekly":
            next_run = now + timedelta(weeks=1)
        elif frequency == "monthly":
            next_run = now + timedelta(days=30)
        else:
            next_run = now + timedelta(days=7)

        report = AutoGeneratedReport.objects.create(
            user=user,
            report_type=report_type,
            title=f"Zamanlanmış {report_type} - {frequency}",
            status="scheduled",
            is_scheduled=True,
            schedule_frequency=frequency,
            next_generation=next_run,
        )

        return report
