# Generated by Django 5.2 on 2025-04-08 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('virtual_company', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(choices=[('customer', 'Müşteri'), ('supplier', 'Tedarikçi'), ('employee', 'Çalışan'), ('other', 'Diğer')], max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('virtual_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='virtual_company.virtualcompany')),
            ],
            options={
                'verbose_name': 'Cari Hesap',
                'verbose_name_plural': 'Cari Hesaplar',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('number', models.CharField(max_length=20, unique=True)),
                ('date', models.DateField()),
                ('due_date', models.DateField()),
                ('type', models.CharField(choices=[('sales', 'Satış Faturası'), ('purchase', 'Alış Faturası')], max_length=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.account')),
                ('virtual_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='virtual_company.virtualcompany')),
            ],
            options={
                'verbose_name': 'Fatura',
                'verbose_name_plural': 'Faturalar',
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('product', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.invoice')),
                ('virtual_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='virtual_company.virtualcompany')),
            ],
            options={
                'verbose_name': 'Fatura Kalemi',
                'verbose_name_plural': 'Fatura Kalemleri',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('number', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.invoice')),
                ('virtual_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='virtual_company.virtualcompany')),
            ],
            options={
                'verbose_name': 'Yevmiye Kaydı',
                'verbose_name_plural': 'Yevmiye Kayıtları',
            },
        ),
        migrations.CreateModel(
            name='TransactionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('account_code', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.transaction')),
                ('virtual_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='virtual_company.virtualcompany')),
            ],
            options={
                'verbose_name': 'Yevmiye Kaydı Kalemi',
                'verbose_name_plural': 'Yevmiye Kaydı Kalemleri',
            },
        ),
    ]
