# Generated by Django 5.2.1 on 2025-05-23 09:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0002_banktransaction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_bankaccounts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Oluşturan Kullanıcı",
            ),
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Aktif mi?"),
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_bankaccounts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Güncelleyen Kullanıcı",
            ),
        ),
        migrations.AddField(
            model_name="banktransaction",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Aktif mi?"),
        ),
        migrations.AddField(
            model_name="company",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_companies",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Oluşturan Kullanıcı",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Aktif mi?"),
        ),
        migrations.AddField(
            model_name="company",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_companies",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Güncelleyen Kullanıcı",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_customers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Oluşturan Kullanıcı",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Aktif mi?"),
        ),
        migrations.AddField(
            model_name="customer",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_customers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Güncelleyen Kullanıcı",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_expenses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Oluşturan Kullanıcı",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Aktif mi?"),
        ),
        migrations.AddField(
            model_name="expense",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_expenses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Güncelleyen Kullanıcı",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_invoices",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Oluşturan Kullanıcı",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Aktif mi?"),
        ),
        migrations.AddField(
            model_name="invoice",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_invoices",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Güncelleyen Kullanıcı",
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Aktif mi?"),
        ),
        migrations.AddField(
            model_name="payment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_payments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Oluşturan Kullanıcı",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Aktif mi?"),
        ),
        migrations.AddField(
            model_name="payment",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_payments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Güncelleyen Kullanıcı",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_products",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Oluşturan Kullanıcı",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Aktif mi?"),
        ),
        migrations.AddField(
            model_name="product",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_products",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Güncelleyen Kullanıcı",
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_sales",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Oluşturan Kullanıcı",
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Aktif mi?"),
        ),
        migrations.AddField(
            model_name="sale",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_sales",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Güncelleyen Kullanıcı",
            ),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="iban",
            field=models.CharField(
                max_length=34,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Geçerli bir IBAN giriniz (TR ile başlamalıdır).",
                        regex="^TR\\d{2}[0-9A-Z]{1,30}$",
                    )
                ],
                verbose_name="IBAN",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="tax_number",
            field=models.CharField(
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Vergi numarası 10 haneli olmalıdır.", regex="^\\d{10}$"
                    )
                ],
                verbose_name="Vergi Numarası",
            ),
        ),
    ]
