# Generated by Django 5.1.8 on 2025-04-15 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0003_knowledgebase_account_e_archive_registered_and_more"),
        (
            "virtual_company",
            "0002_dailytask_product_alter_virtualcompany_options_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="edocument",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "E-Belge",
                "verbose_name_plural": "E-Belgeler",
            },
        ),
        migrations.RenameField(
            model_name="edocument",
            old_name="status_description",
            new_name="status_message",
        ),
        migrations.RemoveField(
            model_name="edocument",
            name="creation_date",
        ),
        migrations.RemoveField(
            model_name="edocument",
            name="pdf_url",
        ),
        migrations.RemoveField(
            model_name="edocument",
            name="response_date",
        ),
        migrations.AddField(
            model_name="account",
            name="currency",
            field=models.CharField(
                choices=[
                    ("TRY", "Türk Lirası"),
                    ("USD", "Amerikan Doları"),
                    ("EUR", "Euro"),
                    ("GBP", "İngiliz Sterlini"),
                ],
                default="TRY",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="bank",
            name="currency",
            field=models.CharField(
                choices=[
                    ("TRY", "Türk Lirası"),
                    ("USD", "Amerikan Doları"),
                    ("EUR", "Euro"),
                    ("GBP", "İngiliz Sterlini"),
                ],
                default="TRY",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="cashbox",
            name="currency",
            field=models.CharField(
                choices=[
                    ("TRY", "Türk Lirası"),
                    ("USD", "Amerikan Doları"),
                    ("EUR", "Euro"),
                    ("GBP", "İngiliz Sterlini"),
                ],
                default="TRY",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="chartofaccounts",
            name="currency",
            field=models.CharField(
                choices=[
                    ("TRY", "Türk Lirası"),
                    ("USD", "Amerikan Doları"),
                    ("EUR", "Euro"),
                    ("GBP", "İngiliz Sterlini"),
                ],
                default="TRY",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="dailytask",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Atanan Kişi",
            ),
        ),
        migrations.AddField(
            model_name="dailytask",
            name="due_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Son Tarih"),
        ),
        migrations.AddField(
            model_name="dailytask",
            name="e_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="accounting.edocument",
                verbose_name="İlgili E-Belge",
            ),
        ),
        migrations.AddField(
            model_name="dailytask",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="accounting.invoice",
                verbose_name="İlgili Fatura",
            ),
        ),
        migrations.AddField(
            model_name="dailytask",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Düşük"),
                    ("medium", "Orta"),
                    ("high", "Yüksek"),
                    ("urgent", "Acil"),
                ],
                default="medium",
                max_length=20,
                verbose_name="Öncelik",
            ),
        ),
        migrations.AddField(
            model_name="dailytask",
            name="reminder_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Hatırlatma Tarihi"
            ),
        ),
        migrations.AddField(
            model_name="dailytask",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Beklemede"),
                    ("in_progress", "Devam Ediyor"),
                    ("completed", "Tamamlandı"),
                    ("canceled", "İptal Edildi"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Durum",
            ),
        ),
        migrations.AddField(
            model_name="dailytask",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("invoice", "Fatura"),
                    ("tax", "Vergi"),
                    ("report", "Rapor"),
                    ("document", "Belge"),
                    ("other", "Diğer"),
                ],
                default="other",
                max_length=20,
                verbose_name="Görev Tipi",
            ),
        ),
        migrations.AddField(
            model_name="edocument",
            name="accepted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Onay Tarihi"
            ),
        ),
        migrations.AddField(
            model_name="edocument",
            name="currency",
            field=models.CharField(
                choices=[
                    ("TRY", "Türk Lirası"),
                    ("USD", "Amerikan Doları"),
                    ("EUR", "Euro"),
                    ("GBP", "İngiliz Sterlini"),
                ],
                default="TRY",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="edocument",
            name="last_retry_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Son Deneme Tarihi"
            ),
        ),
        migrations.AddField(
            model_name="edocument",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="Notlar"),
        ),
        migrations.AddField(
            model_name="edocument",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="e_documents/pdf/",
                verbose_name="PDF Dosyası",
            ),
        ),
        migrations.AddField(
            model_name="edocument",
            name="retry_count",
            field=models.IntegerField(default=0, verbose_name="Yeniden Deneme Sayısı"),
        ),
        migrations.AddField(
            model_name="edocument",
            name="sent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Gönderim Tarihi"
            ),
        ),
        migrations.AddField(
            model_name="edocument",
            name="target_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Hedef Adı"
            ),
        ),
        migrations.AddField(
            model_name="edocument",
            name="target_vkn_tckn",
            field=models.CharField(
                blank=True, max_length=11, null=True, verbose_name="Hedef VKN/TCKN"
            ),
        ),
        migrations.AddField(
            model_name="edocument",
            name="xml_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="e_documents/xml/",
                verbose_name="XML Dosyası",
            ),
        ),
        migrations.AddField(
            model_name="edocumentsettings",
            name="auto_archive",
            field=models.BooleanField(
                default=False,
                help_text="E-belgeler onaylandığında otomatik olarak arşivlensin",
                verbose_name="Otomatik Arşivleme",
            ),
        ),
        migrations.AddField(
            model_name="edocumentsettings",
            name="auto_send",
            field=models.BooleanField(
                default=False,
                help_text="E-belgeler oluşturulduğunda otomatik olarak gönderilsin",
                verbose_name="Otomatik Gönderim",
            ),
        ),
        migrations.AddField(
            model_name="edocumentsettings",
            name="currency",
            field=models.CharField(
                choices=[
                    ("TRY", "Türk Lirası"),
                    ("USD", "Amerikan Doları"),
                    ("EUR", "Euro"),
                    ("GBP", "İngiliz Sterlini"),
                ],
                default="TRY",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="edocumentsettings",
            name="notification_email",
            field=models.EmailField(
                blank=True,
                help_text="E-belge durumu değiştiğinde bildirim gönderilecek e-posta",
                max_length=254,
                null=True,
                verbose_name="Bildirim E-posta",
            ),
        ),
        migrations.AddField(
            model_name="edocumentsettings",
            name="retry_count",
            field=models.IntegerField(
                default=3,
                help_text="Başarısız e-belge işlemleri için yeniden deneme sayısı",
                verbose_name="Yeniden Deneme Sayısı",
            ),
        ),
        migrations.AddField(
            model_name="edocumentsettings",
            name="retry_interval",
            field=models.IntegerField(
                default=300,
                help_text="Başarısız e-belge işlemleri arasındaki bekleme süresi (saniye)",
                verbose_name="Yeniden Deneme Aralığı (sn)",
            ),
        ),
        migrations.AddField(
            model_name="edocumentsettings",
            name="service_url",
            field=models.URLField(blank=True, null=True, verbose_name="Servis URL"),
        ),
        migrations.AddField(
            model_name="edocumenttemplate",
            name="currency",
            field=models.CharField(
                choices=[
                    ("TRY", "Türk Lirası"),
                    ("USD", "Amerikan Doları"),
                    ("EUR", "Euro"),
                    ("GBP", "İngiliz Sterlini"),
                ],
                default="TRY",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="einvoicelog",
            name="currency",
            field=models.CharField(
                choices=[
                    ("TRY", "Türk Lirası"),
                    ("USD", "Amerikan Doları"),
                    ("EUR", "Euro"),
                    ("GBP", "İngiliz Sterlini"),
                ],
                default="TRY",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="einvoicesettings",
            name="auto_archive",
            field=models.BooleanField(default=False, verbose_name="Otomatik Arşivleme"),
        ),
        migrations.AddField(
            model_name="einvoicesettings",
            name="auto_send",
            field=models.BooleanField(default=False, verbose_name="Otomatik Gönderim"),
        ),
        migrations.AddField(
            model_name="einvoicesettings",
            name="currency",
            field=models.CharField(
                choices=[
                    ("TRY", "Türk Lirası"),
                    ("USD", "Amerikan Doları"),
                    ("EUR", "Euro"),
                    ("GBP", "İngiliz Sterlini"),
                ],
                default="TRY",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="einvoicesettings",
            name="integration_type",
            field=models.CharField(
                choices=[
                    ("GIB", "GİB"),
                    ("EFATURA", "E-Fatura"),
                    ("EFINANS", "E-Finans"),
                    ("TEFATURA", "Türk E-Fatura"),
                    ("CUSTOM", "Özel Entegrasyon"),
                ],
                default="GIB",
                max_length=20,
                verbose_name="Entegrasyon Tipi",
            ),
        ),
        migrations.AddField(
            model_name="einvoicesettings",
            name="notification_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Bildirim E-posta"
            ),
        ),
        migrations.AddField(
            model_name="einvoicesettings",
            name="retry_count",
            field=models.IntegerField(default=3, verbose_name="Yeniden Deneme Sayısı"),
        ),
        migrations.AddField(
            model_name="einvoicesettings",
            name="retry_interval",
            field=models.IntegerField(
                default=300, verbose_name="Yeniden Deneme Aralığı (sn)"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="currency",
            field=models.CharField(
                choices=[
                    ("TRY", "Türk Lirası"),
                    ("USD", "Amerikan Doları"),
                    ("EUR", "Euro"),
                    ("GBP", "İngiliz Sterlini"),
                ],
                default="TRY",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="exchange_rate",
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="invoiceline",
            name="currency",
            field=models.CharField(default="TRY", max_length=3),
        ),
        migrations.AddField(
            model_name="knowledgebaserelateditem",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="knowledge_resources",
                to="accounting.dailytask",
                verbose_name="Görev",
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="currency",
            field=models.CharField(default="TRY", max_length=3),
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="currency",
            field=models.CharField(
                choices=[
                    ("TRY", "Türk Lirası"),
                    ("USD", "Amerikan Doları"),
                    ("EUR", "Euro"),
                    ("GBP", "İngiliz Sterlini"),
                ],
                default="TRY",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="currency",
            field=models.CharField(
                choices=[
                    ("TRY", "Türk Lirası"),
                    ("USD", "Amerikan Doları"),
                    ("EUR", "Euro"),
                    ("GBP", "İngiliz Sterlini"),
                ],
                default="TRY",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="transactionline",
            name="currency",
            field=models.CharField(
                choices=[
                    ("TRY", "Türk Lirası"),
                    ("USD", "Amerikan Doları"),
                    ("EUR", "Euro"),
                    ("GBP", "İngiliz Sterlini"),
                ],
                default="TRY",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="edocument",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Oluşturma Tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="edocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("EINVOICE", "E-Fatura"),
                    ("EARCHIVE", "E-Arşiv Fatura"),
                    ("EDISPATCH", "E-İrsaliye"),
                    ("ERECEIPT", "E-Makbuz"),
                ],
                max_length=15,
                verbose_name="Belge Türü",
            ),
        ),
        migrations.AlterField(
            model_name="edocument",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Taslak"),
                    ("PENDING", "Beklemede"),
                    ("SENT", "Gönderildi"),
                    ("DELIVERED", "Teslim Edildi"),
                    ("ACCEPTED", "Onaylandı"),
                    ("REJECTED", "Reddedildi"),
                    ("CANCELED", "İptal Edildi"),
                    ("ERROR", "Hata"),
                ],
                default="DRAFT",
                max_length=15,
                verbose_name="Durum",
            ),
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("TRY", "Türk Lirası"),
                            ("USD", "Amerikan Doları"),
                            ("EUR", "Euro"),
                            ("GBP", "İngiliz Sterlini"),
                        ],
                        default="TRY",
                        max_length=3,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Bütçe Adı")),
                ("start_date", models.DateField(verbose_name="Başlangıç Tarihi")),
                ("end_date", models.DateField(verbose_name="Bitiş Tarihi")),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Toplam Tutar"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Açıklama"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Taslak"),
                            ("active", "Aktif"),
                            ("completed", "Tamamlandı"),
                            ("cancelled", "İptal Edildi"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "virtual_company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="virtual_company.virtualcompany",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bütçe",
                "verbose_name_plural": "Bütçeler",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="BudgetCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("TRY", "Türk Lirası"),
                            ("USD", "Amerikan Doları"),
                            ("EUR", "Euro"),
                            ("GBP", "İngiliz Sterlini"),
                        ],
                        default="TRY",
                        max_length=3,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Kategori Adı")),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Kategori Kodu"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Açıklama"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="accounting.budgetcategory",
                        verbose_name="Üst Kategori",
                    ),
                ),
                (
                    "virtual_company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="virtual_company.virtualcompany",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bütçe Kategorisi",
                "verbose_name_plural": "Bütçe Kategorileri",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="BudgetLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("TRY", "Türk Lirası"),
                            ("USD", "Amerikan Doları"),
                            ("EUR", "Euro"),
                            ("GBP", "İngiliz Sterlini"),
                        ],
                        default="TRY",
                        max_length=3,
                    ),
                ),
                (
                    "planned_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Planlanan Tutar"
                    ),
                ),
                (
                    "actual_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Gerçekleşen Tutar",
                    ),
                ),
                (
                    "variance",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="Fark"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notlar"),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounting.chartofaccounts",
                    ),
                ),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="accounting.budget",
                    ),
                ),
                (
                    "virtual_company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="virtual_company.virtualcompany",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bütçe Kalemi",
                "verbose_name_plural": "Bütçe Kalemleri",
                "ordering": ["account__code"],
            },
        ),
        migrations.CreateModel(
            name="CashFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("TRY", "Türk Lirası"),
                            ("USD", "Amerikan Doları"),
                            ("EUR", "Euro"),
                            ("GBP", "İngiliz Sterlini"),
                        ],
                        default="TRY",
                        max_length=3,
                    ),
                ),
                ("date", models.DateField(verbose_name="Tarih")),
                (
                    "type",
                    models.CharField(
                        choices=[("inflow", "Giriş"), ("outflow", "Çıkış")],
                        max_length=20,
                        verbose_name="Tip",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Tutar"
                    ),
                ),
                ("category", models.CharField(max_length=50, verbose_name="Kategori")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Açıklama"),
                ),
                (
                    "is_recurring",
                    models.BooleanField(default=False, verbose_name="Tekrarlayan mı?"),
                ),
                (
                    "recurrence_period",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("daily", "Günlük"),
                            ("weekly", "Haftalık"),
                            ("monthly", "Aylık"),
                            ("yearly", "Yıllık"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Tekrarlama Periyodu",
                    ),
                ),
                (
                    "virtual_company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="virtual_company.virtualcompany",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nakit Akışı",
                "verbose_name_plural": "Nakit Akışları",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("TRY", "Türk Lirası"),
                            ("USD", "Amerikan Doları"),
                            ("EUR", "Euro"),
                            ("GBP", "İngiliz Sterlini"),
                        ],
                        default="TRY",
                        max_length=3,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=3, unique=True, verbose_name="Para Birimi Kodu"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Para Birimi Adı"),
                ),
                ("symbol", models.CharField(max_length=5, verbose_name="Sembol")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Varsayılan mı?"),
                ),
                (
                    "decimal_places",
                    models.IntegerField(default=2, verbose_name="Ondalık Basamak"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Açıklama"),
                ),
                (
                    "virtual_company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="virtual_company.virtualcompany",
                    ),
                ),
            ],
            options={
                "verbose_name": "Para Birimi",
                "verbose_name_plural": "Para Birimleri",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="TaskCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("TRY", "Türk Lirası"),
                            ("USD", "Amerikan Doları"),
                            ("EUR", "Euro"),
                            ("GBP", "İngiliz Sterlini"),
                        ],
                        default="TRY",
                        max_length=3,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Kategori Adı")),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Kategori Kodu"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Açıklama"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="accounting.taskcategory",
                        verbose_name="Üst Kategori",
                    ),
                ),
                (
                    "virtual_company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="virtual_company.virtualcompany",
                    ),
                ),
            ],
            options={
                "verbose_name": "Görev Kategorisi",
                "verbose_name_plural": "Görev Kategorileri",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="TaskCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("TRY", "Türk Lirası"),
                            ("USD", "Amerikan Doları"),
                            ("EUR", "Euro"),
                            ("GBP", "İngiliz Sterlini"),
                        ],
                        default="TRY",
                        max_length=3,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Tamamlanma Tarihi"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notlar"),
                ),
                (
                    "points_earned",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Kazanılan Puanlar"
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completions",
                        to="accounting.dailytask",
                        verbose_name="Görev",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_completions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
                (
                    "virtual_company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="virtual_company.virtualcompany",
                    ),
                ),
            ],
            options={
                "verbose_name": "Görev Tamamlama",
                "verbose_name_plural": "Görev Tamamlamaları",
                "ordering": ["-completed_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("TRY", "Türk Lirası"),
                            ("USD", "Amerikan Doları"),
                            ("EUR", "Euro"),
                            ("GBP", "İngiliz Sterlini"),
                        ],
                        default="TRY",
                        max_length=3,
                    ),
                ),
                ("content", models.TextField(verbose_name="İçerik")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="accounting.dailytask",
                        verbose_name="Görev",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_notes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
                (
                    "virtual_company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="virtual_company.virtualcompany",
                    ),
                ),
            ],
            options={
                "verbose_name": "Görev Notu",
                "verbose_name_plural": "Görev Notları",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Tax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("TRY", "Türk Lirası"),
                            ("USD", "Amerikan Doları"),
                            ("EUR", "Euro"),
                            ("GBP", "İngiliz Sterlini"),
                        ],
                        default="TRY",
                        max_length=3,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Vergi Adı")),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Vergi Kodu"
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Vergi Oranı (%)"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("kdv", "KDV"),
                            ("otv", "ÖTV"),
                            ("damga", "Damga Vergisi"),
                            ("diger", "Diğer"),
                        ],
                        max_length=20,
                        verbose_name="Vergi Türü",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Açıklama"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                (
                    "virtual_company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="virtual_company.virtualcompany",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vergi",
                "verbose_name_plural": "Vergiler",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("date", models.DateField(verbose_name="Tarih")),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="Kur"
                    ),
                ),
                ("source", models.CharField(max_length=50, verbose_name="Kaynak")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exchange_rates",
                        to="accounting.currency",
                        verbose_name="Para Birimi",
                    ),
                ),
                (
                    "virtual_company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="virtual_company.virtualcompany",
                    ),
                ),
            ],
            options={
                "verbose_name": "Döviz Kuru",
                "verbose_name_plural": "Döviz Kurları",
                "ordering": ["-date", "currency"],
                "unique_together": {("currency", "date")},
            },
        ),
    ]
