# Generated by Django 4.2.23 on 2025-09-01 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0008_auditlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanningScenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Senaryo Adı")),
                ("start_date", models.DateField(verbose_name="Başlangıç Tarihi")),
                ("end_date", models.DateField(verbose_name="Bitiş Tarihi")),
                (
                    "revenue_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        max_digits=6,
                        verbose_name="Gelir Çarpanı",
                    ),
                ),
                (
                    "expense_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        max_digits=6,
                        verbose_name="Gider Çarpanı",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notlar"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planning_scenarios",
                        to="accounting.company",
                        verbose_name="Şirket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Planlama Senaryosu",
                "verbose_name_plural": "Planlama Senaryoları",
                "ordering": ["-created_at"],
            },
        ),
    ]
