# Generated by Django 5.2.6 on 2025-09-29 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0009_planningscenario"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("base_currency", models.CharField(max_length=3, verbose_name="Baz PB")),
                ("quote_currency", models.CharField(max_length=3, verbose_name="Karşı PB")),
                ("date", models.DateField()),
                ("rate", models.DecimalField(decimal_places=8, max_digits=18, verbose_name="Kur")),
                ("source", models.CharField(blank=True, max_length=50, null=True, verbose_name="Kaynak")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Kur",
                "verbose_name_plural": "Kurlar",
                "ordering": ["-date", "base_currency", "quote_currency"],
                "unique_together": {("base_currency", "quote_currency", "date")},
            },
        ),
        migrations.CreateModel(
            name="GLAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=20, verbose_name="Hesap Kodu")),
                ("name", models.CharField(max_length=255, verbose_name="Hesap Adı")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ASSET", "Varlık"),
                            ("LIAB", "Yükümlülük"),
                            ("EQUITY", "Özkaynak"),
                            ("INCOME", "Gelir"),
                            ("EXPENSE", "Gider"),
                            ("OFFBS", "Nazım"),
                        ],
                        max_length=32,
                        verbose_name="Kategori",
                    ),
                ),
                ("is_leaf", models.BooleanField(default=True, verbose_name="Alt Hesap Yok")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif mi?")),
                ("currency", models.CharField(default="TRY", max_length=3, verbose_name="Defter Para Birimi")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gl_accounts",
                        to="accounting.company",
                        verbose_name="Şirket",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="accounting.glaccount",
                        verbose_name="Üst Hesap",
                    ),
                ),
            ],
            options={
                "verbose_name": "GL Hesap",
                "verbose_name_plural": "GL Hesaplar",
                "ordering": ["code"],
                "unique_together": {("company", "code")},
            },
        ),
        migrations.CreateModel(
            name="GLJournalEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("number", models.CharField(max_length=30, verbose_name="Fiş No")),
                ("date", models.DateField(verbose_name="Tarih")),
                ("description", models.CharField(blank=True, max_length=255, null=True, verbose_name="Açıklama")),
                ("source_type", models.CharField(blank=True, max_length=30, null=True, verbose_name="Kaynak Türü")),
                ("source_id", models.CharField(blank=True, max_length=50, null=True, verbose_name="Kaynak ID")),
                ("currency", models.CharField(default="TRY", max_length=3, verbose_name="Fiş Para Birimi")),
                (
                    "total_debit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name="Toplam Borç"),
                ),
                (
                    "total_credit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name="Toplam Alacak"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("posted_at", models.DateTimeField(blank=True, null=True, verbose_name="Mizan Onay Zamanı")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_entries",
                        to="accounting.company",
                        verbose_name="Şirket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yevmiye Fişi",
                "verbose_name_plural": "Yevmiye Fişleri",
                "ordering": ["-date", "-id"],
                "unique_together": {("company", "number")},
            },
        ),
        migrations.CreateModel(
            name="GLJournalLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.CharField(blank=True, max_length=255, null=True, verbose_name="Açıklama")),
                ("debit", models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name="Borç")),
                ("credit", models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name="Alacak")),
                ("currency", models.CharField(default="TRY", max_length=3, verbose_name="Satır PB")),
                ("fx_rate", models.DecimalField(decimal_places=8, default=1, max_digits=18, verbose_name="Kur")),
                (
                    "amount_base",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name="Tutar (Baz PB)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journal_lines",
                        to="accounting.glaccount",
                        verbose_name="Hesap",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="accounting.gljournalentry",
                        verbose_name="Fiş",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yevmiye Satırı",
                "verbose_name_plural": "Yevmiye Satırları",
                "ordering": ["id"],
            },
        ),
    ]
