# Generated by Django 5.2.1 on 2025-10-08 17:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0010_exchangerate_glaccount_gljournalentry_gljournalline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="kdv_rate",
            field=models.DecimalField(
                choices=[(Decimal("0.01"), "%1"), (Decimal("0.10"), "%10"), (Decimal("0.20"), "%20")],
                decimal_places=2,
                default=Decimal("0.20"),
                max_digits=4,
                verbose_name="KDV Oranı",
            ),
        ),
    ]
