# Generated by Django 5.2.7 on 2025-10-21 16:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0002_add_performance_indexes"),
        ("accounting", "0013_alter_edefter_options_alter_edefter_created_at_and_more"),
    ]

    operations = []
