# Generated by Django 5.2.7 on 2025-10-22 21:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0014_merge_20251021_1953"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="banktransaction",
            name="acc_banktxn_date_idx",
        ),
        migrations.RemoveIndex(
            model_name="banktransaction",
            name="acc_banktxn_account_date_idx",
        ),
        migrations.RemoveIndex(
            model_name="company",
            name="acc_company_is_active_idx",
        ),
        migrations.RemoveIndex(
            model_name="company",
            name="acc_company_active_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="company",
            name="acc_company_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="customer",
            name="acc_customer_tax_number_idx",
        ),
        migrations.RemoveIndex(
            model_name="customer",
            name="acc_customer_company_active_idx",
        ),
        migrations.RemoveIndex(
            model_name="customer",
            name="acc_customer_company_email_idx",
        ),
        migrations.RemoveIndex(
            model_name="customer",
            name="acc_customer_email_idx",
        ),
        migrations.RemoveIndex(
            model_name="edefter",
            name="acc_edefter_period_idx",
        ),
        migrations.RemoveIndex(
            model_name="edefter",
            name="acc_edefter_year_month_idx",
        ),
        migrations.RemoveIndex(
            model_name="expense",
            name="acc_expense_date_idx",
        ),
        migrations.RemoveIndex(
            model_name="expense",
            name="acc_expense_company_date_idx",
        ),
        migrations.RemoveIndex(
            model_name="invoice",
            name="acc_invoice_issue_date_idx",
        ),
        migrations.RemoveIndex(
            model_name="invoice",
            name="acc_invoice_company_date_idx",
        ),
        migrations.RemoveIndex(
            model_name="invoice",
            name="acc_invoice_customer_date_idx",
        ),
        migrations.RemoveIndex(
            model_name="payment",
            name="acc_payment_date_idx",
        ),
        migrations.RemoveIndex(
            model_name="payment",
            name="acc_payment_company_date_idx",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="acc_product_company_active_idx",
        ),
        migrations.RemoveIndex(
            model_name="sale",
            name="acc_sale_date_idx",
        ),
        migrations.RemoveIndex(
            model_name="sale",
            name="acc_sale_company_date_idx",
        ),
    ]
