# Generated by Django 4.2.25 on 2025-11-02 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounting", "0015_remove_banktransaction_acc_banktxn_date_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountingAudit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "audit_type",
                    models.CharField(
                        choices=[
                            ("internal", "İç Denetim"),
                            ("external", "Dış Denetim"),
                            ("tax", "Vergi Denetimi"),
                            ("compliance", "Uyumluluk Denetimi"),
                            ("financial_statement", "Mali Tablo Denetimi"),
                            ("operational", "Operasyonel Denetim"),
                        ],
                        max_length=30,
                        verbose_name="Denetim Tipi",
                    ),
                ),
                ("audit_name", models.CharField(max_length=200, verbose_name="Denetim Adı")),
                ("fiscal_year", models.IntegerField(verbose_name="Mali Yıl")),
                ("fiscal_period", models.CharField(blank=True, max_length=10, verbose_name="Dönem")),
                ("planned_start", models.DateField(verbose_name="Planlanan Başlangıç")),
                ("planned_end", models.DateField(verbose_name="Planlanan Bitiş")),
                ("actual_start", models.DateField(blank=True, null=True, verbose_name="Gerçekleşen Başlangıç")),
                ("actual_end", models.DateField(blank=True, null=True, verbose_name="Gerçekleşen Bitiş")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planlanıyor"),
                            ("in_progress", "Devam Ediyor"),
                            ("fieldwork", "Saha Çalışması"),
                            ("reporting", "Raporlama"),
                            ("completed", "Tamamlandı"),
                            ("suspended", "Askıya Alındı"),
                        ],
                        default="planning",
                        max_length=20,
                    ),
                ),
                (
                    "audit_opinion",
                    models.CharField(
                        choices=[
                            ("unqualified", "Olumlu Görüş"),
                            ("qualified", "Şartlı Olumlu Görüş"),
                            ("adverse", "Olumsuz Görüş"),
                            ("disclaimer", "Görüş Bildirmekten Kaçınma"),
                            ("pending", "Henüz Belirlenmedi"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Denetim Görüşü",
                    ),
                ),
                ("overall_score", models.IntegerField(blank=True, null=True, verbose_name="Genel Skor (0-100)")),
                ("executive_summary", models.TextField(blank=True, verbose_name="Yönetici Özeti")),
                ("detailed_findings", models.TextField(blank=True, verbose_name="Detaylı Bulgular")),
                ("recommendations", models.JSONField(blank=True, default=list, verbose_name="Öneriler")),
                (
                    "audit_report",
                    models.FileField(blank=True, null=True, upload_to="audit_reports/", verbose_name="Denetim Raporu"),
                ),
                (
                    "working_papers",
                    models.FileField(
                        blank=True, null=True, upload_to="audit_workpapers/", verbose_name="Çalışma Kağıtları"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "audit_team",
                    models.ManyToManyField(
                        blank=True,
                        related_name="audit_participations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Denetim Ekibi",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounting_audits",
                        to="accounting.company",
                        verbose_name="Denetlenen Şirket",
                    ),
                ),
                (
                    "lead_auditor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="led_audits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Baş Denetçi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Muhasebe Denetimi",
                "verbose_name_plural": "Muhasebe Denetimleri",
                "ordering": ["-fiscal_year", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CostCenter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=20, verbose_name="Maliyet Merkezi Kodu")),
                ("name", models.CharField(max_length=200, verbose_name="Maliyet Merkezi Adı")),
                (
                    "center_type",
                    models.CharField(
                        choices=[
                            ("department", "Departman"),
                            ("project", "Proje"),
                            ("product", "Ürün"),
                            ("service", "Hizmet"),
                            ("location", "Lokasyon"),
                            ("custom", "Özel"),
                        ],
                        max_length=20,
                        verbose_name="Tip",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "budget_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name="Bütçe"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounting_cost_centers",
                        to="accounting.company",
                        verbose_name="Şirket",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_cost_centers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Sorumlu",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sub_centers",
                        to="accounting.costcenter",
                        verbose_name="Üst Maliyet Merkezi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Maliyet Merkezi",
                "verbose_name_plural": "Maliyet Merkezleri",
                "ordering": ["code"],
                "unique_together": {("company", "code")},
            },
        ),
        migrations.CreateModel(
            name="CostVarianceAnalysis",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("analysis_period", models.CharField(max_length=20, verbose_name="Analiz Dönemi")),
                ("budgeted_amount", models.DecimalField(decimal_places=2, max_digits=15, verbose_name="Bütçelenen")),
                ("actual_amount", models.DecimalField(decimal_places=2, max_digits=15, verbose_name="Gerçekleşen")),
                (
                    "variance_amount",
                    models.DecimalField(decimal_places=2, max_digits=15, verbose_name="Varyans Tutarı"),
                ),
                ("variance_percentage", models.DecimalField(decimal_places=2, max_digits=5, verbose_name="Varyans %")),
                ("variance_type", models.CharField(max_length=20, verbose_name="Varyans Tipi")),
                ("cause_analysis", models.TextField(blank=True, verbose_name="Sebep Analizi")),
                ("corrective_actions", models.JSONField(blank=True, default=list, verbose_name="Düzeltici Aksiyonlar")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analyzed_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "cost_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variance_analyses",
                        to="accounting.costcenter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Varyans Analizi",
                "verbose_name_plural": "Varyans Analizleri",
                "ordering": ["-analysis_period"],
            },
        ),
        migrations.CreateModel(
            name="CostReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("monthly", "Aylık Maliyet Raporu"),
                            ("quarterly", "Çeyreklik Maliyet Raporu"),
                            ("project_cost", "Proje Maliyet Raporu"),
                            ("product_cost", "Ürün Maliyet Raporu"),
                            ("variance", "Varyans Analizi"),
                            ("profitability", "Karlılık Analizi"),
                        ],
                        max_length=30,
                        verbose_name="Rapor Tipi",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Rapor Başlığı")),
                ("period_start", models.DateField(verbose_name="Başlangıç Tarihi")),
                ("period_end", models.DateField(verbose_name="Bitiş Tarihi")),
                (
                    "total_costs",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name="Toplam Maliyetler"),
                ),
                (
                    "budgeted_costs",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True, verbose_name="Bütçelenen Maliyetler"
                    ),
                ),
                (
                    "variance",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name="Varyans"),
                ),
                (
                    "variance_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True, verbose_name="Varyans %"
                    ),
                ),
                ("cost_breakdown", models.JSONField(blank=True, default=dict, verbose_name="Maliyet Dağılımı")),
                ("center_analysis", models.JSONField(blank=True, default=list, verbose_name="Merkez Bazlı Analiz")),
                ("recommendations", models.JSONField(blank=True, default=list, verbose_name="Öneriler")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_reports",
                        to="accounting.company",
                        verbose_name="Şirket",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Maliyet Raporu",
                "verbose_name_plural": "Maliyet Raporları",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CostAllocation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("allocation_date", models.DateField(verbose_name="Dağıtım Tarihi")),
                (
                    "allocation_method",
                    models.CharField(
                        choices=[
                            ("direct", "Direkt Dağıtım"),
                            ("proportional", "Oransal Dağıtım"),
                            ("activity_based", "Faaliyet Bazlı"),
                            ("manual", "Manuel Dağıtım"),
                        ],
                        default="direct",
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15, verbose_name="Tutar")),
                (
                    "percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True, verbose_name="Dağıtım Yüzdesi"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "allocated_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_allocations",
                        to="accounting.company",
                        verbose_name="Şirket",
                    ),
                ),
                (
                    "cost_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="accounting.costcenter",
                        verbose_name="Maliyet Merkezi",
                    ),
                ),
                (
                    "source_expense",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cost_allocations",
                        to="accounting.expense",
                    ),
                ),
                (
                    "source_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cost_allocations",
                        to="accounting.banktransaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Maliyet Dağıtımı",
                "verbose_name_plural": "Maliyet Dağıtımları",
                "ordering": ["-allocation_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditFinding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("finding_number", models.CharField(max_length=20, verbose_name="Bulgu No")),
                (
                    "finding_type",
                    models.CharField(
                        choices=[
                            ("error", "Hata"),
                            ("irregularity", "Usulsüzlük"),
                            ("weakness", "Zayıflık"),
                            ("noncompliance", "Uyumsuzluk"),
                            ("risk", "Risk"),
                            ("observation", "Gözlem"),
                        ],
                        max_length=20,
                        verbose_name="Bulgu Tipi",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[("low", "Düşük"), ("medium", "Orta"), ("high", "Yüksek"), ("critical", "Kritik")],
                        default="medium",
                        max_length=20,
                        verbose_name="Önem Derecesi",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Bulgu Başlığı")),
                ("description", models.TextField(verbose_name="Bulgu Açıklaması")),
                ("criteria", models.TextField(verbose_name="Denetim Kriteri/Standardı")),
                ("condition", models.TextField(verbose_name="Mevcut Durum")),
                ("cause", models.TextField(blank=True, verbose_name="Sebep")),
                ("effect", models.TextField(blank=True, verbose_name="Etki")),
                (
                    "financial_impact",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True, verbose_name="Mali Etki"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Açık"),
                            ("in_remediation", "Düzeltiliyor"),
                            ("resolved", "Çözüldü"),
                            ("accepted", "Kabul Edildi"),
                            ("disputed", "İtiraz Edildi"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("corrective_action", models.TextField(blank=True, verbose_name="Düzeltici Aksiyon")),
                ("target_resolution_date", models.DateField(blank=True, null=True, verbose_name="Hedef Çözüm Tarihi")),
                (
                    "actual_resolution_date",
                    models.DateField(blank=True, null=True, verbose_name="Gerçekleşen Çözüm Tarihi"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "audit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="accounting.accountingaudit",
                        verbose_name="Denetim",
                    ),
                ),
                (
                    "identified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="identified_findings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounting.glaccount",
                        verbose_name="İlgili Hesap",
                    ),
                ),
                (
                    "related_expense",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounting.expense",
                        verbose_name="İlgili Gider",
                    ),
                ),
                (
                    "related_invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounting.invoice",
                        verbose_name="İlgili Fatura",
                    ),
                ),
                (
                    "responsible_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responsible_findings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Sorumlu Kişi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Denetim Bulgusu",
                "verbose_name_plural": "Denetim Bulguları",
                "ordering": ["-severity", "-created_at"],
                "unique_together": {("audit", "finding_number")},
            },
        ),
        migrations.CreateModel(
            name="AuditEvidence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "evidence_type",
                    models.CharField(
                        choices=[
                            ("document", "Doküman"),
                            ("screenshot", "Ekran Görüntüsü"),
                            ("report", "Rapor"),
                            ("email", "E-posta"),
                            ("database_query", "Veritabanı Sorgusu"),
                            ("interview", "Görüşme Notu"),
                            ("photo", "Fotoğraf"),
                            ("other", "Diğer"),
                        ],
                        max_length=20,
                        verbose_name="Kanıt Tipi",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Kanıt Başlığı")),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="audit_evidence/", verbose_name="Kanıt Dosyası"),
                ),
                ("source", models.CharField(blank=True, max_length=200, verbose_name="Kaynak")),
                ("collection_date", models.DateField(verbose_name="Toplama Tarihi")),
                ("reliability_score", models.IntegerField(default=5, verbose_name="Güvenilirlik (1-10)")),
                ("notes", models.TextField(blank=True, verbose_name="Notlar")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "collected_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collected_evidence",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "finding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidences",
                        to="accounting.auditfinding",
                        verbose_name="Bulgu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Denetim Kanıtı",
                "verbose_name_plural": "Denetim Kanıtları",
                "ordering": ["-collection_date"],
            },
        ),
        migrations.AddIndex(
            model_name="accountingaudit",
            index=models.Index(fields=["company", "fiscal_year"], name="accounting__company_190b15_idx"),
        ),
        migrations.AddIndex(
            model_name="accountingaudit",
            index=models.Index(fields=["status", "audit_type"], name="accounting__status_d02e77_idx"),
        ),
    ]
