# Generated by Django 5.2.7 on 2025-11-07 15:24

from django.db import migrations, models
from django.utils.text import slugify


def populate_company_slugs(apps, schema_editor):
    Company = apps.get_model("accounting", "Company")

    def generate_unique_slug(instance, base_value):
        base_slug = slugify(base_value) or "sirket"
        base_slug = base_slug[:200]
        slug_candidate = base_slug
        counter = 2
        while (
            Company.objects.filter(slug=slug_candidate).exclude(pk=instance.pk).exists()
        ):
            slug_candidate = f"{base_slug}-{counter}"[:255]
            counter += 1
        return slug_candidate

    for company in Company.objects.all():
        if company.slug:
            continue
        base_value = company.name or company.trade_name or f"company-{company.pk}"
        company.slug = generate_unique_slug(company, base_value)
        company.save(update_fields=["slug"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0016_accountingaudit_costcenter_costvarianceanalysis_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="slug",
            field=models.SlugField(
                blank=True,
                max_length=255,
                unique=True,
                null=True,
                verbose_name="SEO Adresi",
            ),
        ),
        migrations.RunPython(populate_company_slugs, noop),
    ]
