# Generated by Django 5.2.8 on 2025-12-15 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0017_company_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bankaccount",
            options={
                "verbose_name": "Muhasebe Banka Hesabı",
                "verbose_name_plural": "Muhasebe Banka Hesapları",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "verbose_name": "Muhasebe Ürünü",
                "verbose_name_plural": "Muhasebe Ürünleri",
            },
        ),
    ]
