# Generated by Django 4.2.25 on 2025-11-02 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("advisors", "0002_taxpayerprofile_company"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsultationSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("initial", "İlk Görüşme"),
                            ("regular", "Rutin Danışmanlık"),
                            ("urgent", "Acil Danışmanlık"),
                            ("review", "İnceleme/Review"),
                            ("planning", "Planlama"),
                            ("training", "Eğitim"),
                        ],
                        default="regular",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Planlandı"),
                            ("in_progress", "Devam Ediyor"),
                            ("completed", "Tamamlandı"),
                            ("cancelled", "İptal Edildi"),
                            ("rescheduled", "Ertelendi"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("scheduled_date", models.DateField(verbose_name="Planlanan Tarih")),
                ("scheduled_time", models.TimeField(verbose_name="Planlanan Saat")),
                (
                    "duration_minutes",
                    models.IntegerField(default=60, verbose_name="Süre (dakika)"),
                ),
                ("actual_start", models.DateTimeField(blank=True, null=True)),
                ("actual_end", models.DateTimeField(blank=True, null=True)),
                ("agenda", models.TextField(blank=True, verbose_name="Gündem")),
                ("notes", models.TextField(blank=True, verbose_name="Görüşme Notları")),
                (
                    "action_items",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Aksiyonlar"
                    ),
                ),
                ("follow_up_required", models.BooleanField(default=False)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("billable", models.BooleanField(default=True)),
                (
                    "billing_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("invoice_generated", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "advisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="advisors.advisorprofile",
                    ),
                ),
                (
                    "taxpayer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="advisors.taxpayerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Danışmanlık Oturumu",
                "verbose_name_plural": "Danışmanlık Oturumları",
                "ordering": ["-scheduled_date", "-scheduled_time"],
            },
        ),
        migrations.CreateModel(
            name="ClientDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("contract", "Sözleşme"),
                            ("tax_return", "Beyanname"),
                            ("financial_statement", "Mali Tablo"),
                            ("invoice", "Fatura"),
                            ("receipt", "Fiş/Makbuz"),
                            ("correspondence", "Yazışma"),
                            ("report", "Rapor"),
                            ("certificate", "Sertifika"),
                            ("other", "Diğer"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Başlık")),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "file",
                    models.FileField(
                        upload_to="client_documents/", verbose_name="Dosya"
                    ),
                ),
                (
                    "file_size",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Dosya Boyutu (bytes)"
                    ),
                ),
                (
                    "document_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Belge Tarihi"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Etiketler"
                    ),
                ),
                ("is_confidential", models.BooleanField(default=True)),
                ("access_log", models.JSONField(blank=True, default=list)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "taxpayer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="advisors.taxpayerprofile",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to="advisors.advisorprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Müşteri Dokümanı",
                "verbose_name_plural": "Müşteri Dokümanları",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ClientContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("monthly_retainer", "Aylık Sabit Ücret"),
                            ("annual", "Yıllık Sözleşme"),
                            ("project", "Proje Bazlı"),
                            ("hourly", "Saatlik"),
                        ],
                        max_length=20,
                    ),
                ),
                ("contract_number", models.CharField(max_length=50, unique=True)),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Sözleşme Başlığı"),
                ),
                ("scope_of_work", models.TextField(verbose_name="İş Kapsamı")),
                (
                    "terms_and_conditions",
                    models.TextField(verbose_name="Şartlar ve Koşullar"),
                ),
                (
                    "contract_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Sözleşme Bedeli"
                    ),
                ),
                (
                    "payment_terms",
                    models.CharField(max_length=100, verbose_name="Ödeme Koşulları"),
                ),
                ("start_date", models.DateField(verbose_name="Başlangıç Tarihi")),
                ("end_date", models.DateField(verbose_name="Bitiş Tarihi")),
                (
                    "renewal_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Yenileme Tarihi"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Taslak"),
                            ("pending_signature", "İmza Bekliyor"),
                            ("active", "Aktif"),
                            ("expired", "Süresi Doldu"),
                            ("terminated", "Feshedildi"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "contract_file",
                    models.FileField(
                        blank=True, null=True, upload_to="advisor_contracts/"
                    ),
                ),
                (
                    "signed_contract",
                    models.FileField(
                        blank=True, null=True, upload_to="advisor_contracts/signed/"
                    ),
                ),
                ("auto_renew", models.BooleanField(default=False)),
                (
                    "renewal_notice_days",
                    models.IntegerField(
                        default=30, verbose_name="Yenileme Bildirimi (gün)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "advisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="advisors.advisorprofile",
                    ),
                ),
                (
                    "taxpayer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="advisors.taxpayerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Müşteri Sözleşmesi",
                "verbose_name_plural": "Müşteri Sözleşmeleri",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdvisorTimeTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Tarih")),
                ("start_time", models.TimeField(verbose_name="Başlangıç")),
                ("end_time", models.TimeField(verbose_name="Bitiş")),
                ("duration_minutes", models.IntegerField(verbose_name="Süre (dakika)")),
                ("task_description", models.TextField(verbose_name="Yapılan İş")),
                (
                    "service_category",
                    models.CharField(max_length=50, verbose_name="Hizmet Kategorisi"),
                ),
                ("billable", models.BooleanField(default=True)),
                (
                    "hourly_rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Saatlik Ücret"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Toplam Tutar"
                    ),
                ),
                ("invoiced", models.BooleanField(default=False)),
                ("invoice_reference", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "advisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_entries",
                        to="advisors.advisorprofile",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="time_entries",
                        to="advisors.consultationsession",
                    ),
                ),
                (
                    "taxpayer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_entries",
                        to="advisors.taxpayerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zaman Kaydı",
                "verbose_name_plural": "Zaman Kayıtları",
                "ordering": ["-date", "-start_time"],
            },
        ),
        migrations.CreateModel(
            name="AdvisorTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("tax_filing", "Vergi Beyanı"),
                            ("report_preparation", "Rapor Hazırlama"),
                            ("document_review", "Doküman İnceleme"),
                            ("client_meeting", "Müşteri Görüşmesi"),
                            ("follow_up", "Takip"),
                            ("research", "Araştırma"),
                            ("admin", "İdari İş"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Görev Başlığı"),
                ),
                ("description", models.TextField(verbose_name="Açıklama")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Düşük"),
                            ("medium", "Orta"),
                            ("high", "Yüksek"),
                            ("urgent", "Acil"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateField(verbose_name="Termin Tarihi")),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("completion_notes", models.TextField(blank=True)),
                ("reminder_sent", models.BooleanField(default=False)),
                ("reminder_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "advisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="advisors.advisorprofile",
                    ),
                ),
                (
                    "taxpayer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advisor_tasks",
                        to="advisors.taxpayerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Danışman Görevi",
                "verbose_name_plural": "Danışman Görevleri",
                "ordering": ["due_date", "-priority"],
            },
        ),
        migrations.CreateModel(
            name="AdvisorService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("tax_consulting", "Vergi Danışmanlığı"),
                            ("financial_advisory", "Mali Müşavirlik"),
                            ("audit", "Bağımsız Denetim"),
                            ("accounting", "Muhasebe Hizmetleri"),
                            ("payroll", "Bordro Hizmetleri"),
                            ("compliance", "Uyumluluk Danışmanlığı"),
                            ("business_consulting", "İş Danışmanlığı"),
                            ("legal", "Hukuki Danışmanlık"),
                        ],
                        max_length=30,
                        verbose_name="Hizmet Tipi",
                    ),
                ),
                (
                    "service_name",
                    models.CharField(max_length=200, verbose_name="Hizmet Adı"),
                ),
                ("description", models.TextField(verbose_name="Açıklama")),
                (
                    "pricing_model",
                    models.CharField(
                        choices=[
                            ("hourly", "Saatlik"),
                            ("monthly", "Aylık Sabit"),
                            ("per_transaction", "İşlem Başı"),
                            ("project_based", "Proje Bazlı"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Fiyat"
                    ),
                ),
                ("currency", models.CharField(default="TRY", max_length=3)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "advisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="advisors.advisorprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Danışman Hizmeti",
                "verbose_name_plural": "Danışman Hizmetleri",
                "ordering": ["service_type", "service_name"],
            },
        ),
        migrations.CreateModel(
            name="AdvisorReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("tax_analysis", "Vergi Analizi"),
                            ("financial_review", "Mali İnceleme"),
                            ("compliance_check", "Uyumluluk Kontrolü"),
                            ("business_valuation", "İşletme Değerleme"),
                            ("budget_planning", "Bütçe Planlama"),
                            ("audit_report", "Denetim Raporu"),
                            ("monthly_summary", "Aylık Özet"),
                            ("custom", "Özel Rapor"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Rapor Başlığı"),
                ),
                ("executive_summary", models.TextField(verbose_name="Yönetici Özeti")),
                ("detailed_content", models.TextField(verbose_name="Detaylı İçerik")),
                (
                    "findings",
                    models.JSONField(blank=True, default=list, verbose_name="Bulgular"),
                ),
                (
                    "recommendations",
                    models.JSONField(blank=True, default=list, verbose_name="Öneriler"),
                ),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                (
                    "report_file",
                    models.FileField(
                        blank=True, null=True, upload_to="advisor_reports/"
                    ),
                ),
                ("attachments", models.JSONField(blank=True, default=list)),
                ("is_approved", models.BooleanField(default=False)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "advisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="advisors.advisorprofile",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_advisor_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "taxpayer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advisor_reports",
                        to="advisors.taxpayerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Danışman Raporu",
                "verbose_name_plural": "Danışman Raporları",
                "ordering": ["-created_at"],
            },
        ),
    ]
