# Generated by Django 5.2.8 on 2025-11-14 16:18

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advisors", "0003_consultationsession_clientdocument_clientcontract_and_more"),
        ("education", "0013_studentprofile_studentassignment_studentprogress"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsultantProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("pending", "Onay Bekliyor"),
                            ("under_review", "İnceleniyor"),
                            ("approved", "Onaylandı"),
                            ("rejected", "Reddedildi"),
                            ("suspended", "Askıya Alındı"),
                            ("banned", "Yasaklandı"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Onay Durumu",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Onay Tarihi"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Red Nedeni"),
                ),
                (
                    "diploma_document",
                    models.FileField(
                        help_text="Üniversite diploma veya mezuniyet belgesi (Zorunlu)",
                        upload_to="consultant_documents/diplomas/",
                        verbose_name="Diploma/Mezuniyet Belgesi",
                    ),
                ),
                (
                    "graduation_document",
                    models.FileField(
                        help_text="Mezuniyet belgesi/transkript (Zorunlu)",
                        upload_to="consultant_documents/graduation/",
                        verbose_name="Mezuniyet Belgesi",
                    ),
                ),
                (
                    "diploma_verified",
                    models.BooleanField(
                        default=False, verbose_name="Diploma Doğrulandı"
                    ),
                ),
                (
                    "graduation_verified",
                    models.BooleanField(
                        default=False, verbose_name="Mezuniyet Doğrulandı"
                    ),
                ),
                (
                    "documents_verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Belge Doğrulama Tarihi"
                    ),
                ),
                (
                    "blockchain_contract_address",
                    models.CharField(
                        blank=True,
                        help_text="Platform ile mali müşavir arasındaki blockchain anlaşma adresi",
                        max_length=200,
                        verbose_name="Blockchain Sözleşme Adresi",
                    ),
                ),
                (
                    "blockchain_transaction_hash",
                    models.CharField(
                        blank=True,
                        help_text="Anlaşmanın blockchain üzerindeki işlem hash'i",
                        max_length=200,
                        verbose_name="Blockchain İşlem Hash",
                    ),
                ),
                (
                    "blockchain_contract_created_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Blockchain Anlaşma Tarihi"
                    ),
                ),
                (
                    "blockchain_contract_terms",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Blockchain'e kaydedilen anlaşma şartları",
                        verbose_name="Anlaşma Şartları",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(max_length=200, verbose_name="Görünür İsim"),
                ),
                ("bio", models.TextField(verbose_name="Biyografi")),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="consultant_photos/",
                        verbose_name="Profil Fotoğrafı",
                    ),
                ),
                (
                    "office_address",
                    models.TextField(blank=True, verbose_name="Ofis Adresi"),
                ),
                ("city", models.CharField(max_length=100, verbose_name="Şehir")),
                ("phone", models.CharField(max_length=20, verbose_name="Telefon")),
                ("website", models.URLField(blank=True, verbose_name="Website")),
                (
                    "specializations",
                    models.JSONField(default=list, verbose_name="Uzmanlık Alanları"),
                ),
                (
                    "languages",
                    models.JSONField(default=list, verbose_name="Konuşulan Diller"),
                ),
                (
                    "years_of_experience",
                    models.IntegerField(default=0, verbose_name="Deneyim (Yıl)"),
                ),
                ("education", models.JSONField(default=list, verbose_name="Eğitim")),
                (
                    "certifications",
                    models.JSONField(default=list, verbose_name="Sertifikalar"),
                ),
                (
                    "availability_status",
                    models.CharField(
                        choices=[
                            ("available", "Müsait"),
                            ("busy", "Meşgul"),
                            ("on_vacation", "Tatilde"),
                            ("limited", "Sınırlı Müsaitlik"),
                        ],
                        default="available",
                        max_length=20,
                        verbose_name="Müsaitlik Durumu",
                    ),
                ),
                (
                    "working_hours",
                    models.JSONField(
                        default=dict,
                        help_text="Haftanın günleri ve saatler",
                        verbose_name="Çalışma Saatleri",
                    ),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Saatlik Ücret",
                    ),
                ),
                ("currency", models.CharField(default="TRY", max_length=3)),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("15.00"),
                        help_text="FinAsis platform komisyonu",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Komisyon Oranı (%)",
                    ),
                ),
                (
                    "total_consultations",
                    models.IntegerField(default=0, verbose_name="Toplam Danışmanlık"),
                ),
                (
                    "completed_consultations",
                    models.IntegerField(
                        default=0, verbose_name="Tamamlanan Danışmanlık"
                    ),
                ),
                (
                    "total_earnings",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Toplam Kazanç",
                    ),
                ),
                (
                    "average_rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=3,
                        verbose_name="Ortalama Puan",
                    ),
                ),
                (
                    "total_reviews",
                    models.IntegerField(default=0, verbose_name="Toplam Değerlendirme"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Öne Çıkan"),
                ),
                (
                    "featured_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Öne Çıkma Süresi"
                    ),
                ),
                (
                    "accepts_new_clients",
                    models.BooleanField(
                        default=True, verbose_name="Yeni Müşteri Kabul Ediyor"
                    ),
                ),
                (
                    "instant_booking",
                    models.BooleanField(
                        default=False,
                        help_text="Müşteriler onay beklemeden randevu alabilir",
                        verbose_name="Anında Rezervasyon",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "advisor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketplace_profile",
                        to="advisors.advisorprofile",
                        verbose_name="Danışman Profili",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_consultants",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Onaylayan",
                    ),
                ),
                (
                    "documents_verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_consultant_documents_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Belgeleri Doğrulayan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mali Müşavir Profili (Marketplace)",
                "verbose_name_plural": "Mali Müşavir Profilleri (Marketplace)",
                "ordering": ["-is_featured", "-average_rating", "display_name"],
            },
        ),
        migrations.CreateModel(
            name="ConsultantPayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Tutar"
                    ),
                ),
                ("currency", models.CharField(default="TRY", max_length=3)),
                ("period_start", models.DateField(verbose_name="Dönem Başlangıç")),
                ("period_end", models.DateField(verbose_name="Dönem Bitiş")),
                (
                    "included_payments",
                    models.JSONField(
                        default=list,
                        help_text="ConsultationPayment ID'leri",
                        verbose_name="Dahil Edilen Ödemeler",
                    ),
                ),
                ("bank_name", models.CharField(max_length=100, verbose_name="Banka")),
                (
                    "account_holder",
                    models.CharField(max_length=200, verbose_name="Hesap Sahibi"),
                ),
                ("iban", models.CharField(max_length=34, verbose_name="IBAN")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Bekliyor"),
                            ("processing", "İşleniyor"),
                            ("completed", "Tamamlandı"),
                            ("failed", "Başarısız"),
                            ("cancelled", "İptal Edildi"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("transaction_reference", models.CharField(blank=True, max_length=200)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "consultant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payouts",
                        to="advisors.consultantprofile",
                        verbose_name="Mali Müşavir",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mali Müşavir Ödemesi",
                "verbose_name_plural": "Mali Müşavir Ödemeleri",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConsultantDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("id_card", "Kimlik"),
                            ("diploma", "Diploma"),
                            ("certificate", "Sertifika"),
                            ("license", "Lisans/Ruhsat"),
                            ("chamber_registration", "Oda Kayıt Belgesi"),
                            ("tax_certificate", "Vergi Levhası"),
                            ("other", "Diğer"),
                        ],
                        max_length=30,
                        verbose_name="Belge Tipi",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Başlık")),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "file",
                    models.FileField(
                        upload_to="consultant_documents/", verbose_name="Dosya"
                    ),
                ),
                ("file_size", models.IntegerField(blank=True, null=True)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Beklemede"),
                            ("verified", "Doğrulandı"),
                            ("rejected", "Reddedildi"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Doğrulama Durumu",
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "issue_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Düzenlenme Tarihi"
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Geçerlilik Tarihi"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_consultant_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "consultant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="advisors.consultantprofile",
                        verbose_name="Mali Müşavir",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mali Müşavir Belgesi",
                "verbose_name_plural": "Mali Müşavir Belgeleri",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ConsultantContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Sözleşme No"
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("one_time", "Tek Seferlik"),
                            ("monthly", "Aylık"),
                            ("quarterly", "Üç Aylık"),
                            ("annual", "Yıllık"),
                            ("project", "Proje Bazlı"),
                        ],
                        max_length=20,
                        verbose_name="Sözleşme Tipi",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Başlık")),
                ("scope_of_work", models.TextField(verbose_name="İş Kapsamı")),
                (
                    "terms_and_conditions",
                    models.TextField(verbose_name="Şartlar ve Koşullar"),
                ),
                (
                    "deliverables",
                    models.JSONField(default=list, verbose_name="Teslim Edilecekler"),
                ),
                (
                    "contract_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Sözleşme Bedeli"
                    ),
                ),
                ("payment_terms", models.TextField(verbose_name="Ödeme Koşulları")),
                (
                    "payment_schedule",
                    models.JSONField(default=list, verbose_name="Ödeme Planı"),
                ),
                ("start_date", models.DateField(verbose_name="Başlangıç Tarihi")),
                ("end_date", models.DateField(verbose_name="Bitiş Tarihi")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Taslak"),
                            ("sent", "Gönderildi"),
                            ("signed", "İmzalandı"),
                            ("active", "Aktif"),
                            ("completed", "Tamamlandı"),
                            ("terminated", "Feshedildi"),
                            ("expired", "Süresi Doldu"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("client_signed_at", models.DateTimeField(blank=True, null=True)),
                ("consultant_signed_at", models.DateTimeField(blank=True, null=True)),
                ("client_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("consultant_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "contract_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="consultant_contracts/",
                        verbose_name="Sözleşme Belgesi",
                    ),
                ),
                (
                    "signed_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="consultant_contracts/signed/",
                        verbose_name="İmzalı Sözleşme",
                    ),
                ),
                ("attachments", models.JSONField(default=list, verbose_name="Ekler")),
                (
                    "auto_renew",
                    models.BooleanField(
                        default=False, verbose_name="Otomatik Yenileme"
                    ),
                ),
                ("renewal_notice_days", models.IntegerField(default=30)),
                ("termination_reason", models.TextField(blank=True)),
                ("terminated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultant_contracts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Müşteri",
                    ),
                ),
                (
                    "terminated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="terminated_consultant_contracts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "consultant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_contracts",
                        to="advisors.consultantprofile",
                        verbose_name="Mali Müşavir",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mali Müşavir Sözleşmesi",
                "verbose_name_plural": "Mali Müşavir Sözleşmeleri",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConsultantAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Pazartesi"),
                            (1, "Salı"),
                            (2, "Çarşamba"),
                            (3, "Perşembe"),
                            (4, "Cuma"),
                            (5, "Cumartesi"),
                            (6, "Pazar"),
                        ],
                        verbose_name="Gün",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="Başlangıç Saati")),
                ("end_time", models.TimeField(verbose_name="Bitiş Saati")),
                (
                    "specific_date",
                    models.DateField(
                        blank=True,
                        help_text="Belirli bir tarih için (opsiyonel)",
                        null=True,
                        verbose_name="Özel Tarih",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="Müsait"),
                ),
                (
                    "is_recurring",
                    models.BooleanField(
                        default=True,
                        help_text="Her hafta tekrarlanır",
                        verbose_name="Tekrarlı",
                    ),
                ),
                (
                    "consultant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_slots",
                        to="advisors.consultantprofile",
                        verbose_name="Mali Müşavir",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mali Müşavir Müsaitlik",
                "verbose_name_plural": "Mali Müşavir Müsaitlikleri",
                "ordering": ["consultant", "day_of_week", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="ConsultantService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Hizmet Başlığı"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("tax_consulting", "Vergi Danışmanlığı"),
                            ("accounting", "Muhasebe Hizmetleri"),
                            ("audit", "Denetim"),
                            ("financial_planning", "Mali Planlama"),
                            ("business_advisory", "İş Danışmanlığı"),
                            ("compliance", "Uyumluluk"),
                            ("payroll", "Bordrolama"),
                            ("bookkeeping", "Defter Tutma"),
                            ("tax_filing", "Vergi Beyanı"),
                            ("financial_analysis", "Mali Analiz"),
                        ],
                        max_length=30,
                        verbose_name="Kategori",
                    ),
                ),
                ("description", models.TextField(verbose_name="Açıklama")),
                (
                    "pricing_type",
                    models.CharField(
                        choices=[
                            ("hourly", "Saatlik"),
                            ("fixed", "Sabit Fiyat"),
                            ("monthly", "Aylık Paket"),
                            ("project", "Proje Bazlı"),
                        ],
                        max_length=20,
                        verbose_name="Fiyatlandırma Tipi",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Fiyat",
                    ),
                ),
                ("currency", models.CharField(default="TRY", max_length=3)),
                (
                    "duration_minutes",
                    models.IntegerField(
                        blank=True,
                        help_text="Saatlik hizmetler için",
                        null=True,
                        verbose_name="Süre (Dakika)",
                    ),
                ),
                (
                    "estimated_delivery_days",
                    models.IntegerField(
                        blank=True,
                        help_text="Proje bazlı hizmetler için",
                        null=True,
                        verbose_name="Tahmini Teslim (Gün)",
                    ),
                ),
                (
                    "includes",
                    models.JSONField(default=list, verbose_name="Dahil Olanlar"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "total_orders",
                    models.IntegerField(default=0, verbose_name="Toplam Sipariş"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "consultant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="advisors.consultantprofile",
                        verbose_name="Mali Müşavir",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mali Müşavir Hizmeti",
                "verbose_name_plural": "Mali Müşavir Hizmetleri",
                "ordering": ["consultant", "category", "title"],
            },
        ),
        migrations.CreateModel(
            name="ConsultationBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Randevu No"
                    ),
                ),
                (
                    "meeting_type",
                    models.CharField(
                        choices=[
                            ("online", "Online Görüşme"),
                            ("in_person", "Yüz Yüze"),
                            ("phone", "Telefon"),
                        ],
                        default="online",
                        max_length=20,
                    ),
                ),
                (
                    "video_provider",
                    models.CharField(
                        choices=[
                            ("finasis", "FinAsis (Dahili)"),
                            ("jitsi", "Jitsi"),
                            ("zoom", "Zoom"),
                            ("google_meet", "Google Meet"),
                        ],
                        default="finasis",
                        max_length=30,
                        verbose_name="Video Sağlayıcısı",
                    ),
                ),
                ("scheduled_date", models.DateField(verbose_name="Randevu Tarihi")),
                ("scheduled_time", models.TimeField(verbose_name="Randevu Saati")),
                (
                    "duration_minutes",
                    models.IntegerField(default=60, verbose_name="Süre (Dakika)"),
                ),
                (
                    "timezone",
                    models.CharField(default="Europe/Istanbul", max_length=50),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Onay Bekliyor"),
                            ("confirmed", "Onaylandı"),
                            ("cancelled_by_client", "Müşteri İptal Etti"),
                            ("cancelled_by_consultant", "Mali Müşavir İptal Etti"),
                            ("completed", "Tamamlandı"),
                            ("no_show", "Katılmadı"),
                            ("rescheduled", "Ertelendi"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="Konu")),
                ("description", models.TextField(verbose_name="Detaylar")),
                (
                    "meeting_url",
                    models.URLField(blank=True, verbose_name="Görüşme Linki"),
                ),
                (
                    "meeting_id",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Görüşme ID"
                    ),
                ),
                ("meeting_password", models.CharField(blank=True, max_length=100)),
                (
                    "meeting_address",
                    models.TextField(blank=True, verbose_name="Görüşme Adresi"),
                ),
                ("actual_start_time", models.DateTimeField(blank=True, null=True)),
                ("actual_end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "consultant_notes",
                    models.TextField(blank=True, verbose_name="Mali Müşavir Notları"),
                ),
                (
                    "quoted_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Teklif Edilen Fiyat",
                    ),
                ),
                (
                    "final_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Nihai Fiyat",
                    ),
                ),
                (
                    "commission_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Komisyon Tutarı",
                    ),
                ),
                (
                    "consultant_earning",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Mali Müşavir Kazancı",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Ödeme Bekliyor"),
                            ("paid", "Ödendi"),
                            ("refunded", "İade Edildi"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("reminder_sent", models.BooleanField(default=False)),
                ("reminder_sent_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultant_bookings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Müşteri",
                    ),
                ),
                (
                    "consultant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="advisors.consultantprofile",
                        verbose_name="Mali Müşavir",
                    ),
                ),
                (
                    "education_meeting",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consultation_booking",
                        to="education.meeting",
                        verbose_name="FinAsis Toplantısı",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="advisors.consultantservice",
                        verbose_name="Hizmet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Danışmanlık Randevusu",
                "verbose_name_plural": "Danışmanlık Randevuları",
                "ordering": ["-scheduled_date", "-scheduled_time"],
            },
        ),
        migrations.CreateModel(
            name="ConsultantReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Puan",
                    ),
                ),
                (
                    "professionalism_rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Profesyonellik",
                    ),
                ),
                (
                    "communication_rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="İletişim",
                    ),
                ),
                (
                    "expertise_rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Uzmanlık",
                    ),
                ),
                (
                    "value_rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Fiyat/Performans",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Başlık")),
                ("comment", models.TextField(verbose_name="Yorum")),
                (
                    "consultant_response",
                    models.TextField(blank=True, verbose_name="Mali Müşavir Yanıtı"),
                ),
                (
                    "consultant_responded_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=True, verbose_name="Doğrulanmış"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Öne Çıkan"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Yayında"),
                ),
                (
                    "helpful_count",
                    models.IntegerField(default=0, verbose_name="Faydalı Sayısı"),
                ),
                (
                    "not_helpful_count",
                    models.IntegerField(default=0, verbose_name="Faydasız Sayısı"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultant_reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Müşteri",
                    ),
                ),
                (
                    "consultant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="advisors.consultantprofile",
                        verbose_name="Mali Müşavir",
                    ),
                ),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="advisors.consultationbooking",
                        verbose_name="Randevu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mali Müşavir Değerlendirmesi",
                "verbose_name_plural": "Mali Müşavir Değerlendirmeleri",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConsultationPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("booking", "Randevu Ödemesi"),
                            ("service", "Hizmet Ödemesi"),
                            ("package", "Paket Ödemesi"),
                        ],
                        default="booking",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("credit_card", "Kredi Kartı"),
                            ("debit_card", "Banka Kartı"),
                            ("bank_transfer", "Havale/EFT"),
                            ("wallet", "Cüzdan"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Tutar"
                    ),
                ),
                (
                    "commission",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Komisyon"
                    ),
                ),
                (
                    "consultant_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Mali Müşavir Tutarı",
                    ),
                ),
                ("currency", models.CharField(default="TRY", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Bekliyor"),
                            ("processing", "İşleniyor"),
                            ("completed", "Tamamlandı"),
                            ("failed", "Başarısız"),
                            ("refunded", "İade Edildi"),
                            ("partially_refunded", "Kısmi İade"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("gateway_name", models.CharField(blank=True, max_length=50)),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="İşlem ID"
                    ),
                ),
                ("gateway_response", models.JSONField(blank=True, default=dict)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "payout_to_consultant_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Mali Müşavire Ödeme Tarihi"
                    ),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="İade Tutarı",
                    ),
                ),
                ("refund_reason", models.TextField(blank=True)),
                ("refunded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="advisors.consultationbooking",
                        verbose_name="Randevu",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultation_payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Müşteri",
                    ),
                ),
                (
                    "consultant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_payments",
                        to="advisors.consultantprofile",
                        verbose_name="Mali Müşavir",
                    ),
                ),
            ],
            options={
                "verbose_name": "Danışmanlık Ödemesi",
                "verbose_name_plural": "Danışmanlık Ödemeleri",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="consultationbooking",
            index=models.Index(
                fields=["consultant", "scheduled_date", "status"],
                name="advisors_co_consult_9ad6c0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="consultationbooking",
            index=models.Index(
                fields=["client", "status"], name="advisors_co_client__d75d67_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consultationbooking",
            index=models.Index(
                fields=["booking_number"], name="advisors_co_booking_5783ed_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="consultantreview",
            unique_together={("booking", "client")},
        ),
    ]
