name: Deploy FinAsis

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: config.settings.production
    steps:
      - name: Kodu Checkout Et
        uses: actions/checkout@v4

      - name: Python Kurulumu
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Bağımlılıkları Yükle
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Testleri Çalıştır
        run: |
          python manage.py test

      - name: Docker Build
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/finasis:latest .

      - name: Docker Hub'a Push Et
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/finasis:latest

      - name: Sunucuya Deploy (SSH ile)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/finasis:latest
            docker stop finasis || true
            docker rm finasis || true
            docker run -d --name finasis -p 80:8000 --env-file /home/${{ secrets.SERVER_USER }}/.env ${{ secrets.DOCKERHUB_USERNAME }}/finasis:latest 