name: Test Sonuçları Bildirimi

on:
  workflow_run:
    workflows: ["Django Test CI"]
    types:
      - completed

jobs:
  slack-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Webhook URL Kontrolü
        id: check-webhook
        run: |
          if [[ -z "${{ secrets.SLACK_WEBHOOK }}" ]]; then
            echo "::warning::SLACK_WEBHOOK değişkeni ayarlanmamış. Slack bildirimi atlanacak."
            echo "has_webhook=false" >> $GITHUB_OUTPUT
          else
            echo "has_webhook=true" >> $GITHUB_OUTPUT
          fi
        
      - name: Slack Bildirimi
        if: steps.check-webhook.outputs.has_webhook == 'true'
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: geliştirme
          SLACK_TITLE: "Test Sonuçları"
          SLACK_MESSAGE: |
            ${{ github.workflow }} iş akışı ${{ github.event.workflow_run.conclusion }} durumunda tamamlandı.
            Commit: ${{ github.event.workflow_run.head_commit.message }}
            Kaynak Dalı: ${{ github.event.workflow_run.head_branch }}
            Kaynak: ${{ github.event.workflow_run.html_url }}
          SLACK_COLOR: ${{ github.event.workflow_run.conclusion == 'success' && 'good' || 'danger' }}
          SLACK_FOOTER: "FinAsis CI/CD Sistemi"
          SLACK_ICON_EMOJI: ":test_tube:" 