# Generated by Django 4.2.25 on 2025-11-02 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("integrator_gib", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GIBCertificate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="Sertifika Adı")),
                (
                    "certificate_type",
                    models.CharField(
                        choices=[("E_SIGNATURE", "E-İmza"), ("TAX_SEAL", "Mali Mühür")],
                        max_length=20,
                        verbose_name="Sertifika Tipi",
                    ),
                ),
                ("serial_number", models.CharField(max_length=100, unique=True, verbose_name="Seri Numarası")),
                ("alias", models.CharField(max_length=200, verbose_name="Alias")),
                ("certificate_file", models.FileField(upload_to="gib_certificates/", verbose_name="Sertifika Dosyası")),
                ("password_hash", models.CharField(blank=True, max_length=255, verbose_name="Şifre Hash")),
                ("valid_from", models.DateTimeField(verbose_name="Geçerlilik Başlangıcı")),
                ("valid_until", models.DateTimeField(verbose_name="Geçerlilik Bitişi")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("last_used_at", models.DateTimeField(blank=True, null=True, verbose_name="Son Kullanım")),
                ("usage_count", models.IntegerField(default=0, verbose_name="Kullanım Sayısı")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "GİB Sertifikası",
                "verbose_name_plural": "GİB Sertifikaları",
                "ordering": ["-valid_until"],
            },
        ),
        migrations.CreateModel(
            name="GIBSubmissionLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("submission_id", models.CharField(max_length=100, unique=True, verbose_name="Gönderim ID")),
                ("declaration_code", models.CharField(max_length=50, verbose_name="Beyan Kodu")),
                ("period", models.CharField(max_length=20, verbose_name="Dönem")),
                ("taxpayer_vkn", models.CharField(max_length=20, verbose_name="VKN/TCKN")),
                ("request_payload", models.JSONField(default=dict, verbose_name="İstek Verisi")),
                ("request_xml", models.TextField(blank=True, verbose_name="İstek XML")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Beklemede"),
                            ("SENT", "Gönderildi"),
                            ("ACCEPTED", "Kabul Edildi"),
                            ("REJECTED", "Reddedildi"),
                            ("ERROR", "Hata"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                ("response_data", models.JSONField(blank=True, default=dict, verbose_name="Yanıt Verisi")),
                ("response_xml", models.TextField(blank=True, verbose_name="Yanıt XML")),
                ("gib_reference_number", models.CharField(blank=True, max_length=100, verbose_name="GİB Referans No")),
                ("gib_tracking_id", models.CharField(blank=True, max_length=100, verbose_name="GİB Takip No")),
                ("error_code", models.CharField(blank=True, max_length=50, verbose_name="Hata Kodu")),
                ("error_message", models.TextField(blank=True, verbose_name="Hata Mesajı")),
                ("submitted_at", models.DateTimeField(auto_now_add=True, verbose_name="Gönderim Zamanı")),
                ("processed_at", models.DateTimeField(blank=True, null=True, verbose_name="İşlenme Zamanı")),
                (
                    "integrator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="integrator_gib.integratorconfig",
                        verbose_name="Entegratör",
                    ),
                ),
            ],
            options={
                "verbose_name": "GİB Gönderim Logu",
                "verbose_name_plural": "GİB Gönderim Logları",
                "ordering": ["-submitted_at"],
            },
        ),
    ]
